import type { BuilderIntent } from './types.js';

export interface BuilderLegacyComposer {
  readonly portfolio: (desc: string) => string;
  readonly referenceSocial: (desc: string) => string;
  readonly socialBlog: (desc: string) => string;
  readonly storefront: (desc: string) => string;
}

function buildReactViteTsApp(options: {
  packageName: string;
  title: string;
  appTsx: string;
  stylesCss: string;
}): string {
  return [
    '```json title="package.json"',
    JSON.stringify({
      name: options.packageName,
      private: true,
      version: '0.0.0',
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc -b && vite build',
        preview: 'vite preview',
      },
      dependencies: {
        react: '^18.3.1',
        'react-dom': '^18.3.1',
      },
      devDependencies: {
        '@types/react': '^18.3.1',
        '@types/react-dom': '^18.3.1',
        '@vitejs/plugin-react': '^4.3.1',
        typescript: '^5.5.3',
        vite: '^5.4.10',
      },
    }, null, 2),
    '```',
    '',
    '```html title="index.html"',
    '<!doctype html>',
    '<html lang="en">',
    '  <head>',
    '    <meta charset="UTF-8" />',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `    <title>${options.title}</title>`,
    '    <script type="module" src="/src/main.tsx"></script>',
    '  </head>',
    '  <body>',
    '    <div id="root"></div>',
    '  </body>',
    '</html>',
    '```',
    '',
    '```tsx title="src/main.tsx"',
    "import { StrictMode } from 'react';",
    "import { createRoot } from 'react-dom/client';",
    "import App from './App.tsx';",
    "import './styles.css';",
    '',
    "createRoot(document.getElementById('root')!).render(",
    '  <StrictMode>',
    '    <App />',
    '  </StrictMode>,',
    ');',
    '```',
    '',
    '```tsx title="src/App.tsx"',
    options.appTsx,
    '```',
    '',
    '```css title="src/styles.css"',
    options.stylesCss,
    '```',
    '',
    '```json title="tsconfig.json"',
    JSON.stringify({
      compilerOptions: {
        target: 'ES2020',
        lib: ['ES2020', 'DOM', 'DOM.Iterable'],
        module: 'ESNext',
        moduleResolution: 'bundler',
        jsx: 'react-jsx',
        strict: true,
        skipLibCheck: true,
      },
      include: ['src'],
    }, null, 2),
    '```',
  ].join('\n');
}

function generateTrainingTrackerApp(intent: BuilderIntent): string {
  const heroLabel = intent.audience === 'personal' ? 'Personal training tracker' : 'Training tracker';
  const heroLead = intent.audience === 'personal'
    ? 'A private workout app focused on weekly structure, session completion, and progress you can use for yourself without admin clutter.'
    : 'A focused training app for planning sessions, tracking weekly load, and keeping momentum visible.';

  const appTsx = [
    "import { useMemo, useState } from 'react';",
    '',
    "type Intensity = 'Recovery' | 'Build' | 'Peak';",
    '',
    'type Session = {',
    '  id: number;',
    '  day: string;',
    '  title: string;',
    '  focus: string;',
    '  duration: number;',
    '  intensity: Intensity;',
    '  completed: boolean;',
    '};',
    '',
    'const initialPlan: Session[] = [',
    "  { id: 1, day: 'Mon', title: 'Lower body strength', focus: 'Front squat + split squat + carries', duration: 64, intensity: 'Build', completed: true },",
    "  { id: 2, day: 'Tue', title: 'Zone 2 run', focus: 'Steady aerobic base with nasal breathing pace', duration: 38, intensity: 'Recovery', completed: true },",
    "  { id: 3, day: 'Thu', title: 'Upper body push-pull', focus: 'Bench, row, press, and shoulder health work', duration: 58, intensity: 'Build', completed: false },",
    "  { id: 4, day: 'Sat', title: 'Hill repeat session', focus: 'Short uphill efforts with long walk-back recovery', duration: 46, intensity: 'Peak', completed: false },",
    '];',
    '',
    'const progressNotes = [',
    "  { label: 'Consistency', value: '11 days', note: 'current streak' },",
    "  { label: 'Weekly load', value: '206 min', note: 'planned volume' },",
    "  { label: 'PR watch', value: 'Front squat +5 kg', note: 'last two weeks' },",
    '];',
    '',
    'const recoveryChecklist = [',
    "  'Sleep target: 8 hours before the hill session',",
    "  'Prepare next-day workout clothes tonight',",
    "  'Keep Friday mobility easy instead of adding more volume',",
    '];',
    '',
    'export default function App() {',
    '  const [plan, setPlan] = useState(initialPlan);',
    "  const [selectedFilter, setSelectedFilter] = useState<'All' | Intensity>('All');",
    '',
    '  const completedCount = useMemo(() => plan.filter((session) => session.completed).length, [plan]);',
    '  const visiblePlan = useMemo(() => (',
    "    selectedFilter === 'All' ? plan : plan.filter((session) => session.intensity === selectedFilter)",
    '  ), [plan, selectedFilter]);',
    '  const nextSession = useMemo(() => plan.find((session) => !session.completed) ?? plan[plan.length - 1], [plan]);',
    '',
    '  function toggleSession(id: number) {',
    '    setPlan((current) => current.map((session) => (',
    '      session.id === id',
    '        ? { ...session, completed: !session.completed }',
    '        : session',
    '    )));',
    '  }',
    '',
    '  return (',
    '    <main className="tracker-shell">',
    '      <section className="hero-card">',
    '        <div>',
    `          <p className="eyebrow">${heroLabel}</p>`,
    "          <h1>Train with structure, not guesswork.</h1>",
    `          <p className="lede">${heroLead}</p>`,
    '          <div className="hero-pills">',
    '            <span>Plan the week</span>',
    '            <span>Log sessions</span>',
    '            <span>Review progress</span>',
    '          </div>',
    '        </div>',
    '        <aside className="hero-note">',
    "          <span>Next session</span>",
    '          <strong>{nextSession.title}</strong>',
    '          <p>{nextSession.focus}</p>',
    '          <small>{nextSession.day} • {nextSession.duration} min • {nextSession.intensity}</small>',
    '        </aside>',
    '      </section>',
    '',
    '      <section className="metric-grid">',
    '        {progressNotes.map((item) => (',
    '          <article key={item.label} className="metric-card">',
    '            <span>{item.label}</span>',
    '            <strong>{item.value}</strong>',
    '            <small>{item.note}</small>',
    '          </article>',
    '        ))}',
    '      </section>',
    '',
    '      <section className="content-grid">',
    '        <section className="card">',
    '          <div className="section-head">',
    '            <div>',
    '              <p className="eyebrow">Weekly plan</p>',
    '              <h2>{completedCount}/{plan.length} sessions done</h2>',
    '            </div>',
    '            <div className="filter-row">',
    "              {(['All', 'Recovery', 'Build', 'Peak'] as const).map((filter) => (",
    '                <button',
    '                  key={filter}',
    '                  type="button"',
    '                  className={selectedFilter === filter ? "chip active" : "chip"}',
    '                  onClick={() => setSelectedFilter(filter)}',
    '                >',
    '                  {filter}',
    '                </button>',
    '              ))}',
    '            </div>',
    '          </div>',
    '          <div className="session-list">',
    '            {visiblePlan.map((session) => (',
    '              <button key={session.id} type="button" className={session.completed ? "session-card is-complete" : "session-card"} onClick={() => toggleSession(session.id)}>',
    '                <div>',
    '                  <span className="session-day">{session.day}</span>',
    '                  <strong>{session.title}</strong>',
    '                  <p>{session.focus}</p>',
    '                </div>',
    '                <div className="session-meta">',
    '                  <span>{session.duration} min</span>',
    '                  <span>{session.intensity}</span>',
    '                  <span>{session.completed ? "Done" : "Tap to log"}</span>',
    '                </div>',
    '              </button>',
    '            ))}',
    '          </div>',
    '        </section>',
    '',
    '        <section className="card side-stack">',
    '          <div>',
    '            <p className="eyebrow">Recovery cues</p>',
    '            <h2>Keep the hard day hard.</h2>',
    '          </div>',
    '          <ul className="checklist">',
    '            {recoveryChecklist.map((item) => (',
    '              <li key={item}>{item}</li>',
    '            ))}',
    '          </ul>',
    '          <div className="progress-panel">',
    '            <span>Momentum</span>',
    '            <strong>78%</strong>',
    '            <p>Your plan is on pace if you complete the Thursday lift before 20:00.</p>',
    '          </div>',
    '        </section>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
  ].join('\n');

  const stylesCss = [
    ":root { color: #f8fafc; background: #090b12; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }",
    '* { box-sizing: border-box; }',
    'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top, rgba(56,189,248,0.18), transparent 24%), radial-gradient(circle at 86% 10%, rgba(34,197,94,0.16), transparent 18%), #090b12; }',
    'button { font: inherit; }',
    '.tracker-shell { width: min(1160px, calc(100% - 32px)); margin: 0 auto; padding: 28px 0 72px; }',
    '.hero-card, .metric-card, .card { border-radius: 28px; border: 1px solid rgba(148,163,184,0.16); background: rgba(9,11,18,0.8); box-shadow: 0 24px 80px rgba(0,0,0,0.26); backdrop-filter: blur(18px); }',
    '.hero-card { display: grid; grid-template-columns: minmax(0, 1.1fr) 320px; gap: 22px; padding: 28px; }',
    '.eyebrow { margin: 0 0 12px; color: #67e8f9; font-size: 12px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; }',
    'h1, h2, p { margin: 0; }',
    'h1 { font-size: clamp(3rem, 7vw, 5rem); line-height: 0.94; letter-spacing: -0.06em; max-width: 10ch; }',
    '.lede { margin-top: 18px; max-width: 58ch; color: #cbd5e1; font-size: 18px; line-height: 1.75; }',
    '.hero-pills, .filter-row { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 22px; }',
    '.hero-pills span, .chip { padding: 10px 14px; border-radius: 999px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); color: #dbe4ef; }',
    '.chip { cursor: pointer; transition: transform 0.18s ease, border-color 0.18s ease; }',
    '.chip.active { border-color: rgba(34,197,94,0.65); color: #bbf7d0; }',
    '.hero-note { padding: 24px; border-radius: 24px; background: linear-gradient(180deg, rgba(12,18,32,0.94), rgba(9,11,18,0.94)); display: grid; gap: 10px; align-content: end; }',
    '.hero-note span, .hero-note small { color: #94a3b8; text-transform: uppercase; letter-spacing: 0.08em; font-size: 12px; }',
    '.hero-note strong { font-size: 30px; letter-spacing: -0.05em; }',
    '.hero-note p { color: #dbe4ef; line-height: 1.7; }',
    '.metric-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; margin-top: 20px; }',
    '.metric-card { padding: 20px; display: grid; gap: 8px; }',
    '.metric-card span, .metric-card small { color: #94a3b8; }',
    '.metric-card strong { font-size: 32px; letter-spacing: -0.05em; }',
    '.content-grid { display: grid; grid-template-columns: minmax(0, 1.2fr) 340px; gap: 18px; margin-top: 20px; }',
    '.card { padding: 24px; }',
    '.section-head { display: flex; justify-content: space-between; gap: 18px; align-items: flex-start; }',
    '.session-list { display: grid; gap: 12px; margin-top: 20px; }',
    '.session-card { border: 1px solid rgba(148,163,184,0.14); border-radius: 22px; background: rgba(15,23,42,0.72); padding: 18px; color: inherit; text-align: left; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 16px; cursor: pointer; transition: transform 0.18s ease, border-color 0.18s ease; }',
    '.session-card:hover, .chip:hover { transform: translateY(-2px); }',
    '.session-card.is-complete { border-color: rgba(34,197,94,0.45); background: rgba(20,83,45,0.26); }',
    '.session-day { display: inline-block; margin-bottom: 10px; color: #86efac; font-size: 12px; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.session-card strong { font-size: 22px; letter-spacing: -0.04em; }',
    '.session-card p { margin-top: 8px; color: #cbd5e1; line-height: 1.7; }',
    '.session-meta { display: grid; gap: 8px; justify-items: end; color: #cbd5e1; font-size: 13px; }',
    '.side-stack { display: grid; gap: 18px; align-content: start; }',
    '.checklist { margin: 0; padding-left: 18px; display: grid; gap: 12px; color: #dbe4ef; }',
    '.checklist li { line-height: 1.6; }',
    '.progress-panel { border-radius: 22px; padding: 18px; background: linear-gradient(135deg, rgba(34,197,94,0.24), rgba(56,189,248,0.2)); border: 1px solid rgba(148,163,184,0.18); display: grid; gap: 8px; }',
    '.progress-panel span { color: #dcfce7; font-size: 12px; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.progress-panel strong { font-size: 38px; letter-spacing: -0.06em; }',
    '.progress-panel p { color: #e2e8f0; line-height: 1.7; }',
    '@media (max-width: 960px) { .hero-card, .content-grid { grid-template-columns: 1fr; } .metric-grid { grid-template-columns: 1fr; } }',
    '@media (max-width: 720px) { .tracker-shell { width: min(100%, calc(100% - 20px)); padding-top: 18px; } .hero-card, .card { padding: 20px; } .section-head, .session-card { grid-template-columns: 1fr; } .session-meta { justify-items: start; } }',
  ].join('\n');

  return buildReactViteTsApp({
    packageName: 'summit-training-tracker',
    title: 'Summit Training Tracker',
    appTsx,
    stylesCss,
  });
}

function generateMatchingApp(): string {
  const appTsx = [
    "import { useMemo, useState } from 'react';",
    '',
    'type Profile = {',
    '  id: number;',
    '  name: string;',
    '  age: number;',
    '  city: string;',
    '  vibe: string;',
    '  blurb: string;',
    '  interests: string[];',
    '  gradient: string;',
    '};',
    '',
    'const profiles: Profile[] = [',
    "  { id: 1, name: 'Sana', age: 29, city: 'Oslo', vibe: 'Slow mornings, sharp humour, coastal weekends.', blurb: 'Product designer who likes winter sea dips, bookstore dates, and low-key city walks.', interests: ['Sea sauna', 'Film photos', 'Thai curry'], gradient: 'linear-gradient(135deg, #f97316, #fb7185)' },",
    "  { id: 2, name: 'Jonas', age: 31, city: 'Bergen', vibe: 'Trail runs, espresso, and good conversation.', blurb: 'Usually planning a cabin trip or a dinner party with too much olive oil and good bread.', interests: ['Trail running', 'Espresso bars', 'Cabin trips'], gradient: 'linear-gradient(135deg, #38bdf8, #818cf8)' },",
    "  { id: 3, name: 'Maja', age: 27, city: 'Trondheim', vibe: 'Warm energy with a calm social battery.', blurb: 'Works in publishing, loves live music, and picks restaurants based on lighting almost as much as food.', interests: ['Live sets', 'Late dinners', 'Bookshops'], gradient: 'linear-gradient(135deg, #22c55e, #14b8a6)' },",
    '];',
    '',
    'const openers = [',
    "  'Ask about their ideal slow Sunday.',",
    "  'Swap favourite low-key Oslo spots.',",
    "  'Start with travel or trail plans, not small talk.',",
    '];',
    '',
    'export default function App() {',
    '  const [index, setIndex] = useState(0);',
    '  const [matches, setMatches] = useState<Profile[]>([]);',
    "  const [filter, setFilter] = useState<'Nearby' | 'New' | 'Matches'>('Nearby');",
    '',
    '  const currentProfile = profiles[index] ?? null;',
    '  const remaining = Math.max(profiles.length - index, 0);',
    '  const topMatch = useMemo(() => matches[0] ?? null, [matches]);',
    '',
    "  function swipe(action: 'pass' | 'like') {",
    '    if (!currentProfile) return;',
    '    if (action === "like" && !matches.some((profile) => profile.id === currentProfile.id)) {',
    '      setMatches((current) => [currentProfile, ...current]);',
    '    }',
    '    setIndex((current) => current + 1);',
    '  }',
    '',
    '  return (',
    '    <main className="matching-shell">',
    '      <section className="hero-card">',
    '        <div>',
    '          <p className="eyebrow">Matching app archetype</p>',
    '          <h1>Browse profiles, match quickly, and move into real conversation.</h1>',
    '          <p className="lede">A swipe-based product shell with a profile deck, match queue, and chat-ready follow-up prompts instead of a generic landing page.</p>',
    '          <div className="hero-pills">',
    '            <span>Profile deck</span>',
    '            <span>Swipe actions</span>',
    '            <span>Matches + chat</span>',
    '          </div>',
    '        </div>',
    '        <aside className="hero-note">',
    '          <span>Queue state</span>',
    '          <strong>{remaining} profiles left</strong>',
    '          <p>{topMatch ? `Latest match: ${topMatch.name} from ${topMatch.city}` : "Like someone to start the match queue."}</p>',
    '        </aside>',
    '      </section>',
    '',
    '      <section className="content-grid">',
    '        <section className="deck-card">',
    '          <div className="deck-head">',
    '            <div>',
    '              <p className="eyebrow">Swipe queue</p>',
    '              <h2>{filter}</h2>',
    '            </div>',
    '            <div className="filter-row">',
    "              {(['Nearby', 'New', 'Matches'] as const).map((label) => (",
    '                <button key={label} type="button" className={filter === label ? "chip active" : "chip"} onClick={() => setFilter(label)}>{label}</button>',
    '              ))}',
    '            </div>',
    '          </div>',
    '',
    '          {currentProfile ? (',
    '            <article className="profile-card">',
    '              <div className="profile-visual" style={{ background: currentProfile.gradient }} />',
    '              <div className="profile-copy">',
    '                <div>',
    '                  <h3>{currentProfile.name}, {currentProfile.age}</h3>',
    '                  <span>{currentProfile.city}</span>',
    '                </div>',
    '                <p className="profile-vibe">{currentProfile.vibe}</p>',
    '                <p>{currentProfile.blurb}</p>',
    '                <div className="tag-row">',
    '                  {currentProfile.interests.map((interest) => (',
    '                    <span key={interest}>{interest}</span>',
    '                  ))}',
    '                </div>',
    '                <div className="action-row">',
    '                  <button type="button" className="secondary" onClick={() => swipe("pass")}>Pass</button>',
    '                  <button type="button" className="primary" onClick={() => swipe("like")}>Like</button>',
    '                </div>',
    '              </div>',
    '            </article>',
    '          ) : (',
    '            <article className="profile-card profile-empty">',
    '              <h3>You reached the end of the deck.</h3>',
    '              <p>Reset the queue or move into matches and chat as the next feature slice.</p>',
    '            </article>',
    '          )}',
    '        </section>',
    '',
    '        <aside className="side-stack">',
    '          <section className="card">',
    '            <p className="eyebrow">Matches</p>',
    '            <h2>{matches.length} active</h2>',
    '            <div className="match-list">',
    '              {matches.length > 0 ? matches.map((profile) => (',
    '                <div key={profile.id} className="match-card">',
    '                  <strong>{profile.name}</strong>',
    '                  <span>{profile.city}</span>',
    '                </div>',
    '              )) : <p className="empty-copy">Your next like should appear here immediately.</p>}',
    '            </div>',
    '          </section>',
    '',
    '          <section className="card">',
    '            <p className="eyebrow">Conversation starters</p>',
    '            <ul className="opener-list">',
    '              {openers.map((item) => (',
    '                <li key={item}>{item}</li>',
    '              ))}',
    '            </ul>',
    '          </section>',
    '        </aside>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
  ].join('\n');

  const stylesCss = [
    ":root { color: #f8fafc; background: #090b12; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }",
    '* { box-sizing: border-box; }',
    'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top, rgba(244,114,182,0.18), transparent 24%), radial-gradient(circle at 82% 14%, rgba(96,165,250,0.16), transparent 18%), #090b12; }',
    'button { font: inherit; }',
    '.matching-shell { width: min(1160px, calc(100% - 32px)); margin: 0 auto; padding: 28px 0 72px; }',
    '.hero-card, .deck-card, .card, .profile-card { border-radius: 28px; border: 1px solid rgba(148,163,184,0.16); background: rgba(9,11,18,0.8); box-shadow: 0 24px 80px rgba(0,0,0,0.26); backdrop-filter: blur(18px); }',
    '.hero-card { display: grid; grid-template-columns: minmax(0, 1.1fr) 300px; gap: 22px; padding: 28px; }',
    '.eyebrow { margin: 0 0 12px; color: #f9a8d4; font-size: 12px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; }',
    'h1, h2, h3, p { margin: 0; }',
    'h1 { font-size: clamp(3rem, 7vw, 5rem); line-height: 0.94; letter-spacing: -0.06em; max-width: 10ch; }',
    '.lede { margin-top: 18px; max-width: 56ch; color: #cbd5e1; font-size: 18px; line-height: 1.75; }',
    '.hero-pills, .filter-row, .tag-row, .action-row { display: flex; flex-wrap: wrap; gap: 10px; }',
    '.hero-pills { margin-top: 22px; }',
    '.hero-pills span, .chip, .tag-row span { padding: 10px 14px; border-radius: 999px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); color: #dbe4ef; }',
    '.chip { cursor: pointer; }',
    '.chip.active { border-color: rgba(244,114,182,0.55); color: #fbcfe8; }',
    '.hero-note { padding: 22px; border-radius: 24px; background: linear-gradient(180deg, rgba(17,24,39,0.92), rgba(9,11,18,0.94)); display: grid; gap: 10px; align-content: end; }',
    '.hero-note span { color: #94a3b8; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.hero-note strong { font-size: 32px; letter-spacing: -0.05em; }',
    '.hero-note p { color: #dbe4ef; line-height: 1.7; }',
    '.content-grid { display: grid; grid-template-columns: minmax(0, 1.08fr) 320px; gap: 18px; margin-top: 20px; }',
    '.deck-card, .card { padding: 24px; }',
    '.deck-head { display: flex; justify-content: space-between; gap: 18px; align-items: flex-start; margin-bottom: 18px; }',
    '.profile-card { overflow: hidden; }',
    '.profile-visual { min-height: 320px; }',
    '.profile-copy { padding: 22px; display: grid; gap: 14px; }',
    '.profile-copy h3 { font-size: 34px; letter-spacing: -0.05em; }',
    '.profile-copy > div span { color: #94a3b8; }',
    '.profile-vibe { color: #fbcfe8; font-weight: 600; line-height: 1.7; }',
    '.profile-copy p { color: #dbe4ef; line-height: 1.7; }',
    '.action-row { margin-top: 6px; }',
    '.primary, .secondary { border-radius: 999px; padding: 14px 20px; cursor: pointer; transition: transform 0.18s ease, box-shadow 0.18s ease; }',
    '.primary { border: none; background: linear-gradient(135deg, #f472b6, #fb7185); color: white; font-weight: 700; box-shadow: 0 18px 40px rgba(244,114,182,0.26); }',
    '.secondary { border: 1px solid rgba(148,163,184,0.18); background: rgba(15,23,42,0.72); color: #e2e8f0; }',
    '.primary:hover, .secondary:hover, .chip:hover { transform: translateY(-2px); }',
    '.side-stack { display: grid; gap: 18px; }',
    '.match-list { display: grid; gap: 12px; margin-top: 16px; }',
    '.match-card { border-radius: 20px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); padding: 16px; display: grid; gap: 6px; }',
    '.match-card span, .empty-copy { color: #94a3b8; }',
    '.opener-list { margin: 16px 0 0; padding-left: 18px; display: grid; gap: 12px; color: #dbe4ef; }',
    '.profile-empty { padding: 28px; display: grid; gap: 12px; }',
    '.profile-empty p { color: #cbd5e1; line-height: 1.7; }',
    '@media (max-width: 960px) { .hero-card, .content-grid { grid-template-columns: 1fr; } }',
    '@media (max-width: 720px) { .matching-shell { width: min(100%, calc(100% - 20px)); padding-top: 18px; } .hero-card, .deck-card, .card { padding: 20px; } .deck-head { flex-direction: column; } }',
  ].join('\n');

  return buildReactViteTsApp({
    packageName: 'north-match',
    title: 'North Match',
    appTsx,
    stylesCss,
  });
}

function generateDashboardWorkspaceApp(): string {
  const appTsx = [
    "import { useMemo, useState } from 'react';",
    '',
    "type Range = '7d' | '30d' | '90d';",
    '',
    'type QueueItem = {',
    '  id: number;',
    '  customer: string;',
    '  status: string;',
    '  value: string;',
    '  owner: string;',
    '};',
    '',
    'const metricsByRange: Record<Range, Array<{ label: string; value: string; note: string }>> = {',
    "  '7d': [",
    "    { label: 'Revenue', value: '$48.2k', note: '+8.4% vs prior week' },",
    "    { label: 'Approval queue', value: '18', note: '5 need action today' },",
    "    { label: 'Resolution time', value: '2.8h', note: 'median first response' },",
    "  ],",
    "  '30d': [",
    "    { label: 'Revenue', value: '$186k', note: '+12.1% vs prior month' },",
    "    { label: 'Approval queue', value: '64', note: '14 need action today' },",
    "    { label: 'Resolution time', value: '3.2h', note: 'median first response' },",
    "  ],",
    "  '90d': [",
    "    { label: 'Revenue', value: '$542k', note: '+18.9% vs prior quarter' },",
    "    { label: 'Approval queue', value: '141', note: '31 need action today' },",
    "    { label: 'Resolution time', value: '3.6h', note: 'median first response' },",
    "  ],",
    '};',
    '',
    'const pipeline = [',
    "  { label: 'Qualified', value: 42, accent: '#38bdf8' },",
    "  { label: 'Review', value: 28, accent: '#a78bfa' },",
    "  { label: 'Approved', value: 17, accent: '#22c55e' },",
    "  { label: 'Escalated', value: 6, accent: '#f97316' },",
    '];',
    '',
    'const queue: QueueItem[] = [',
    "  { id: 1, customer: 'Northwind Travel', status: 'Needs review', value: '$8.4k', owner: 'Mila' },",
    "  { id: 2, customer: 'Fjord Health', status: 'Waiting on docs', value: '$14.2k', owner: 'Jon' },",
    "  { id: 3, customer: 'Studio Forma', status: 'Ready to approve', value: '$5.6k', owner: 'Ari' },",
    "  { id: 4, customer: 'Atlas Ops', status: 'Escalated', value: '$11.3k', owner: 'Sana' },",
    '];',
    '',
    'const activity = [',
    "  'Activity: Mila approved Northwind Travel for contract review.',",
    "  'Activity: Jon requested missing documents from Fjord Health.',",
    "  'Activity: Sana escalated Atlas Ops to the incident owner lane.',",
    '];',
    '',
    'export default function App() {',
    "  const [range, setRange] = useState<Range>('30d');",
    '  const activeMetrics = useMemo(() => metricsByRange[range], [range]);',
    '',
    '  return (',
    '    <main className="dashboard-shell">',
    '      <section className="hero-card">',
    '        <div>',
    '          <p className="eyebrow">Dashboard archetype</p>',
    '          <h1>Operational clarity with KPIs, queue state, and decision lanes.</h1>',
    '          <p className="lede">A composed dashboard shell for analytics-heavy or ops-heavy apps, with metrics first, a real review queue, live activity, and visible ownership instead of empty chart wallpaper.</p>',
    '          <div className="range-row">',
    "            {(['7d', '30d', '90d'] as const).map((option) => (",
    '              <button key={option} type="button" className={range === option ? "chip active" : "chip"} onClick={() => setRange(option)}>{option}</button>',
    '            ))}',
    '          </div>',
    '        </div>',
    '        <aside className="hero-note">',
    '          <span>Operator view</span>',
    '          <strong>{queue.length} live items</strong>',
    '          <p>Use this base for admin dashboards, internal tools, analytics surfaces, or approval workflows.</p>',
    '        </aside>',
    '      </section>',
    '',
    '      <section className="metric-grid">',
    '        {activeMetrics.map((metric) => (',
    '          <article key={metric.label} className="metric-card">',
    '            <span>{metric.label}</span>',
    '            <strong>{metric.value}</strong>',
    '            <small>{metric.note}</small>',
    '          </article>',
    '        ))}',
    '      </section>',
    '',
    '      <section className="content-grid">',
    '        <section className="card">',
    '          <div className="section-head">',
    '            <div>',
    '              <p className="eyebrow">Pipeline</p>',
    '              <h2>Current flow</h2>',
    '            </div>',
    '            <span>4 stages</span>',
    '          </div>',
    '          <div className="pipeline-grid">',
    '            {pipeline.map((item) => (',
    '              <article key={item.label} className="pipeline-card">',
    '                <div className="pipeline-bar" style={{ background: item.accent, width: `${Math.max(item.value * 2, 22)}px` }} />',
    '                <strong>{item.value}</strong>',
    '                <span>{item.label}</span>',
    '              </article>',
    '            ))}',
    '          </div>',
    '        </section>',
    '',
    '        <section className="card">',
    '          <div className="section-head">',
    '            <div>',
    '              <p className="eyebrow">Review queue</p>',
    '              <h2>Approvals and follow-up</h2>',
    '            </div>',
    '          </div>',
    '          <div className="queue-list">',
    '            {queue.map((item) => (',
    '              <article key={item.id} className="queue-card">',
    '                <div>',
    '                  <strong>{item.customer}</strong>',
    '                  <p>{item.status}</p>',
    '                </div>',
    '                <div className="queue-meta">',
    '                  <span>{item.value}</span>',
    '                  <small>{item.owner}</small>',
    '                </div>',
    '              </article>',
    '            ))}',
    '          </div>',
    '        </section>',
    '',
    '        <aside className="card note-stack">',
    '          <p className="eyebrow">Live Activity</p>',
    '          <ul className="note-list">',
    '            {activity.map((note) => (',
    '              <li key={note}>{note}</li>',
    '            ))}',
    '          </ul>',
    '        </aside>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
  ].join('\n');

  const stylesCss = [
    ":root { color: #f8fafc; background: #090b12; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }",
    '* { box-sizing: border-box; }',
    'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top, rgba(56,189,248,0.18), transparent 24%), radial-gradient(circle at 82% 14%, rgba(167,139,250,0.16), transparent 18%), #090b12; }',
    'button { font: inherit; }',
    '.dashboard-shell { width: min(1180px, calc(100% - 32px)); margin: 0 auto; padding: 28px 0 72px; }',
    '.hero-card, .metric-card, .card { border-radius: 28px; border: 1px solid rgba(148,163,184,0.16); background: rgba(9,11,18,0.8); box-shadow: 0 24px 80px rgba(0,0,0,0.26); backdrop-filter: blur(18px); }',
    '.hero-card { display: grid; grid-template-columns: minmax(0, 1.1fr) 300px; gap: 22px; padding: 28px; }',
    '.eyebrow { margin: 0 0 12px; color: #67e8f9; font-size: 12px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; }',
    'h1, h2, p, ul { margin: 0; padding: 0; }',
    'h1 { font-size: clamp(3rem, 7vw, 5rem); line-height: 0.94; letter-spacing: -0.06em; max-width: 11ch; }',
    '.lede { margin-top: 18px; max-width: 58ch; color: #cbd5e1; font-size: 18px; line-height: 1.75; }',
    '.range-row { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 22px; }',
    '.chip { padding: 10px 14px; border-radius: 999px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); color: #dbe4ef; cursor: pointer; transition: transform 0.18s ease, border-color 0.18s ease; }',
    '.chip.active { border-color: rgba(56,189,248,0.7); color: #bae6fd; }',
    '.chip:hover { transform: translateY(-2px); }',
    '.hero-note { padding: 22px; border-radius: 24px; background: linear-gradient(180deg, rgba(17,24,39,0.92), rgba(9,11,18,0.94)); display: grid; gap: 10px; align-content: end; }',
    '.hero-note span { color: #94a3b8; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.hero-note strong { font-size: 32px; letter-spacing: -0.05em; }',
    '.hero-note p { color: #dbe4ef; line-height: 1.7; }',
    '.metric-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 18px; margin-top: 20px; }',
    '.metric-card { padding: 20px; display: grid; gap: 8px; }',
    '.metric-card span, .metric-card small { color: #94a3b8; }',
    '.metric-card strong { font-size: 32px; letter-spacing: -0.05em; }',
    '.content-grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) 280px; gap: 18px; margin-top: 20px; }',
    '.card { padding: 24px; }',
    '.section-head { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; margin-bottom: 18px; }',
    '.section-head span { color: #94a3b8; }',
    '.pipeline-grid { display: grid; gap: 12px; }',
    '.pipeline-card { border-radius: 22px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); padding: 18px; display: grid; gap: 10px; }',
    '.pipeline-bar { height: 10px; border-radius: 999px; }',
    '.pipeline-card strong { font-size: 28px; letter-spacing: -0.04em; }',
    '.pipeline-card span, .queue-card p, .queue-meta small, .note-list { color: #cbd5e1; }',
    '.queue-list { display: grid; gap: 12px; }',
    '.queue-card { border-radius: 22px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); padding: 18px; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 16px; }',
    '.queue-card strong { font-size: 20px; letter-spacing: -0.04em; }',
    '.queue-card p { margin-top: 8px; line-height: 1.7; }',
    '.queue-meta { display: grid; gap: 8px; justify-items: end; }',
    '.queue-meta span { font-size: 18px; font-weight: 700; }',
    '.note-stack { align-content: start; }',
    '.note-list { padding-left: 18px; display: grid; gap: 12px; line-height: 1.7; }',
    '@media (max-width: 1040px) { .hero-card, .content-grid, .metric-grid { grid-template-columns: 1fr; } }',
    '@media (max-width: 720px) { .dashboard-shell { width: min(100%, calc(100% - 20px)); padding-top: 18px; } .hero-card, .card { padding: 20px; } .queue-card { grid-template-columns: 1fr; } .queue-meta { justify-items: start; } }',
  ].join('\n');

  return buildReactViteTsApp({
    packageName: 'ops-lens-dashboard',
    title: 'Ops Lens Dashboard',
    appTsx,
    stylesCss,
  });
}

function generateBookingApp(intent: BuilderIntent): string {
  const heroLabel = intent.audience === 'personal' ? 'Personal booking planner' : 'Booking app archetype';
  const heroLead = intent.audience === 'personal'
    ? 'A personal scheduling surface for appointments, calendar blocks, and client follow-up without the weight of a full CRM.'
    : 'A booking-first app shell for consultations, appointments, and time-slot management.';

  const appTsx = [
    "import { useMemo, useState } from 'react';",
    '',
    'type Appointment = {',
    '  id: number;',
    '  client: string;',
    '  slot: string;',
    '  service: string;',
    '  status: string;',
    '};',
    '',
    'const weeklySlots = [',
    "  { day: 'Mon', open: '09:00-16:00', note: 'Consult calls + follow-up' },",
    "  { day: 'Tue', open: '10:00-18:00', note: 'On-site sessions' },",
    "  { day: 'Thu', open: '08:30-15:30', note: 'Remote booking blocks' },",
    "  { day: 'Fri', open: '11:00-17:00', note: 'Short intro appointments' },",
    '];',
    '',
    'const appointments: Appointment[] = [',
    "  { id: 1, client: 'North Studio', slot: 'Tue 10:30', service: 'Discovery call', status: 'Confirmed' },",
    "  { id: 2, client: 'Lina Berg', slot: 'Thu 09:00', service: 'Portfolio review', status: 'Needs reminder' },",
    "  { id: 3, client: 'Atlas Retreat', slot: 'Fri 13:15', service: 'Planning session', status: 'Deposit pending' },",
    '];',
    '',
    'const checklist = [',
    "  'Show next available slots clearly before adding deeper settings.',",
    "  'Keep appointment status and client context close together.',",
    "  'This is the right base before payments, reminders, or calendar sync.',",
    '];',
    '',
    'export default function App() {',
    "  const [selectedDay, setSelectedDay] = useState(weeklySlots[0]?.day ?? 'Mon');",
    '  const selectedSchedule = useMemo(() => weeklySlots.find((slot) => slot.day === selectedDay) ?? weeklySlots[0], [selectedDay]);',
    '',
    '  return (',
    '    <main className="booking-shell">',
    '      <section className="hero-card">',
    '        <div>',
    `          <p className="eyebrow">${heroLabel}</p>`,
    '          <h1>Let people book time without losing the shape of your week.</h1>',
    `          <p className="lede">${heroLead}</p>`,
    '          <div className="day-row">',
    '            {weeklySlots.map((slot) => (',
    '              <button key={slot.day} type="button" className={selectedDay === slot.day ? "chip active" : "chip"} onClick={() => setSelectedDay(slot.day)}>{slot.day}</button>',
    '            ))}',
    '          </div>',
    '        </div>',
    '        <aside className="hero-note">',
    '          <span>Selected schedule</span>',
    '          <strong>{selectedSchedule.day}</strong>',
    '          <p>{selectedSchedule.open}</p>',
    '          <small>{selectedSchedule.note}</small>',
    '        </aside>',
    '      </section>',
    '',
    '      <section className="content-grid">',
    '        <section className="card">',
    '          <div className="section-head">',
    '            <div>',
    '              <p className="eyebrow">Availability</p>',
    '              <h2>Weekly open blocks</h2>',
    '            </div>',
    '          </div>',
    '          <div className="slot-list">',
    '            {weeklySlots.map((slot) => (',
    '              <article key={slot.day} className={selectedDay === slot.day ? "slot-card is-active" : "slot-card"}>',
    '                <div>',
    '                  <strong>{slot.day}</strong>',
    '                  <p>{slot.note}</p>',
    '                </div>',
    '                <span>{slot.open}</span>',
    '              </article>',
    '            ))}',
    '          </div>',
    '        </section>',
    '',
    '        <section className="card">',
    '          <div className="section-head">',
    '            <div>',
    '              <p className="eyebrow">Appointments</p>',
    '              <h2>Upcoming bookings</h2>',
    '            </div>',
    '          </div>',
    '          <div className="appointment-list">',
    '            {appointments.map((appointment) => (',
    '              <article key={appointment.id} className="appointment-card">',
    '                <div>',
    '                  <strong>{appointment.client}</strong>',
    '                  <p>{appointment.service}</p>',
    '                </div>',
    '                <div className="appointment-meta">',
    '                  <span>{appointment.slot}</span>',
    '                  <small>{appointment.status}</small>',
    '                </div>',
    '              </article>',
    '            ))}',
    '          </div>',
    '        </section>',
    '',
    '        <aside className="card note-stack">',
    '          <p className="eyebrow">Build notes</p>',
    '          <ul className="note-list">',
    '            {checklist.map((item) => (',
    '              <li key={item}>{item}</li>',
    '            ))}',
    '          </ul>',
    '          <div className="cta-panel">',
    '            <span>Next slice</span>',
    '            <strong>Add reminders + intake form</strong>',
    '          </div>',
    '        </aside>',
    '      </section>',
    '    </main>',
    '  );',
    '}',
  ].join('\n');

  const stylesCss = [
    ":root { color: #f8fafc; background: #090b12; font-family: Inter, ui-sans-serif, system-ui, sans-serif; }",
    '* { box-sizing: border-box; }',
    'body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top, rgba(34,197,94,0.16), transparent 24%), radial-gradient(circle at 82% 14%, rgba(250,204,21,0.14), transparent 18%), #090b12; }',
    'button { font: inherit; }',
    '.booking-shell { width: min(1160px, calc(100% - 32px)); margin: 0 auto; padding: 28px 0 72px; }',
    '.hero-card, .card { border-radius: 28px; border: 1px solid rgba(148,163,184,0.16); background: rgba(9,11,18,0.8); box-shadow: 0 24px 80px rgba(0,0,0,0.26); backdrop-filter: blur(18px); }',
    '.hero-card { display: grid; grid-template-columns: minmax(0, 1.1fr) 300px; gap: 22px; padding: 28px; }',
    '.eyebrow { margin: 0 0 12px; color: #86efac; font-size: 12px; font-weight: 800; letter-spacing: 0.12em; text-transform: uppercase; }',
    'h1, h2, p, ul { margin: 0; padding: 0; }',
    'h1 { font-size: clamp(3rem, 7vw, 5rem); line-height: 0.94; letter-spacing: -0.06em; max-width: 11ch; }',
    '.lede { margin-top: 18px; max-width: 58ch; color: #cbd5e1; font-size: 18px; line-height: 1.75; }',
    '.day-row { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 22px; }',
    '.chip { padding: 10px 14px; border-radius: 999px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); color: #dbe4ef; cursor: pointer; transition: transform 0.18s ease, border-color 0.18s ease; }',
    '.chip.active { border-color: rgba(34,197,94,0.7); color: #dcfce7; }',
    '.chip:hover { transform: translateY(-2px); }',
    '.hero-note { padding: 22px; border-radius: 24px; background: linear-gradient(180deg, rgba(17,24,39,0.92), rgba(9,11,18,0.94)); display: grid; gap: 10px; align-content: end; }',
    '.hero-note span, .hero-note small { color: #94a3b8; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.hero-note strong { font-size: 32px; letter-spacing: -0.05em; }',
    '.hero-note p { color: #dbe4ef; line-height: 1.7; }',
    '.content-grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr) 280px; gap: 18px; margin-top: 20px; }',
    '.card { padding: 24px; }',
    '.section-head { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; margin-bottom: 18px; }',
    '.slot-list, .appointment-list { display: grid; gap: 12px; }',
    '.slot-card, .appointment-card { border-radius: 22px; border: 1px solid rgba(148,163,184,0.14); background: rgba(15,23,42,0.72); padding: 18px; display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 16px; }',
    '.slot-card.is-active { border-color: rgba(34,197,94,0.6); box-shadow: 0 18px 48px rgba(34,197,94,0.12); }',
    '.slot-card strong, .appointment-card strong { font-size: 20px; letter-spacing: -0.04em; }',
    '.slot-card p, .appointment-card p, .note-list { color: #cbd5e1; line-height: 1.7; }',
    '.slot-card span, .appointment-meta span { font-size: 16px; font-weight: 700; }',
    '.appointment-meta { display: grid; gap: 8px; justify-items: end; }',
    '.appointment-meta small { color: #94a3b8; }',
    '.note-stack { align-content: start; }',
    '.note-list { padding-left: 18px; display: grid; gap: 12px; }',
    '.cta-panel { margin-top: 18px; border-radius: 22px; padding: 18px; background: linear-gradient(135deg, rgba(34,197,94,0.2), rgba(250,204,21,0.16)); border: 1px solid rgba(148,163,184,0.18); display: grid; gap: 8px; }',
    '.cta-panel span { color: #dcfce7; font-size: 12px; font-weight: 800; letter-spacing: 0.08em; text-transform: uppercase; }',
    '.cta-panel strong { font-size: 24px; letter-spacing: -0.04em; }',
    '@media (max-width: 1040px) { .hero-card, .content-grid { grid-template-columns: 1fr; } }',
    '@media (max-width: 720px) { .booking-shell { width: min(100%, calc(100% - 20px)); padding-top: 18px; } .hero-card, .card { padding: 20px; } .slot-card, .appointment-card { grid-template-columns: 1fr; } .appointment-meta { justify-items: start; } }',
  ].join('\n');

  return buildReactViteTsApp({
    packageName: 'booked-calendar',
    title: 'Booked Calendar',
    appTsx,
    stylesCss,
  });
}

export function composeBuilderApp(intent: BuilderIntent, legacy: BuilderLegacyComposer): string | null {
  switch (intent.archetype) {
    case 'portfolio':
      return legacy.portfolio(intent.cleanedPrompt);
    case 'storefront':
      return legacy.storefront(intent.cleanedPrompt);
    case 'social-feed':
      return intent.referenceBrand || intent.isCloneRequest
        ? legacy.referenceSocial(intent.cleanedPrompt)
        : legacy.socialBlog(intent.cleanedPrompt);
    case 'dashboard':
      return generateDashboardWorkspaceApp();
    case 'tracker':
      return generateTrainingTrackerApp(intent);
    case 'matching':
      return generateMatchingApp();
    case 'booking':
      return generateBookingApp(intent);
    default:
      return null;
  }
}
