/**
 * Shared scaffold UI — ambient motion, kinetic headlines, scroll reveals.
 * Used by quick-start sandbox templates and stack basic tiers.
 */

export interface ScaffoldAccent {
  /** Tailwind color name, e.g. violet, emerald, blue */
  name: string;
  /** Hex for canvas / gradients */
  hex: string;
}

/** Extra CSS appended to template index.css / globals.css */
export const SCAFFOLD_MOTION_CSS = [
  `@keyframes mesh-drift {`,
  `  0%, 100% { transform: translate(0, 0) scale(1); }`,
  `  33% { transform: translate(2%, -1.5%) scale(1.03); }`,
  `  66% { transform: translate(-1.5%, 2%) scale(0.98); }`,
  `}`,
  `@keyframes kinetic-in {`,
  `  0% { opacity: 0; transform: translateY(0.6em) rotateX(12deg); filter: blur(6px); }`,
  `  100% { opacity: 1; transform: translateY(0) rotateX(0); filter: blur(0); }`,
  `}`,
  `@keyframes kinetic-out {`,
  `  0% { opacity: 1; transform: translateY(0) rotateX(0); filter: blur(0); }`,
  `  100% { opacity: 0; transform: translateY(-0.5em) rotateX(-10deg); filter: blur(4px); }`,
  `}`,
  `@keyframes float-soft {`,
  `  0%, 100% { transform: translateY(0); }`,
  `  50% { transform: translateY(-6px); }`,
  `}`,
  `@keyframes shimmer-pulse {`,
  `  0%, 100% { color: #c4b5fd; text-shadow: 0 0 20px rgba(167,139,250,0.35); }`,
  `  50% { color: #f0abfc; text-shadow: 0 0 28px rgba(240,171,252,0.55); }`,
  `}`,
  `@keyframes reveal-up {`,
  `  from { opacity: 0; transform: translateY(16px); }`,
  `  to { opacity: 1; transform: translateY(0); }`,
  `}`,
  `.scaffold-mesh {`,
  `  pointer-events: none; position: fixed; inset: 0; z-index: 0; overflow: hidden;`,
  `}`,
  `.scaffold-mesh__orb {`,
  `  position: absolute; border-radius: 9999px; filter: blur(80px); opacity: 0.45;`,
  `  animation: mesh-drift 18s ease-in-out infinite;`,
  `}`,
  `.scaffold-mesh__orb--a { width: 42vmin; height: 42vmin; top: -8%; left: -6%; animation-delay: 0s; }`,
  `.scaffold-mesh__orb--b { width: 36vmin; height: 36vmin; bottom: -10%; right: -4%; animation-delay: -6s; }`,
  `.scaffold-mesh__orb--c { width: 28vmin; height: 28vmin; top: 40%; left: 55%; animation-delay: -12s; opacity: 0.28; }`,
  `.kinetic-slot {`,
  `  display: inline-block; position: relative; min-width: 6ch; text-align: left; perspective: 400px;`,
  `}`,
  `.kinetic-word {`,
  `  display: inline-block; white-space: nowrap; opacity: 1;`,
  `  animation: kinetic-in 0.55s cubic-bezier(0.16, 1, 0.3, 1) forwards;`,
  `}`,
  `.kinetic-word--out { animation: kinetic-out 0.35s cubic-bezier(0.4, 0, 1, 1) forwards; }`,
  `.scroll-reveal { opacity: 0; transform: translateY(14px); transition: opacity 0.6s cubic-bezier(0.16,1,0.3,1), transform 0.6s cubic-bezier(0.16,1,0.3,1); }`,
  `.scroll-reveal.is-visible { opacity: 1; transform: translateY(0); }`,
  `.shimmer-text {`,
  `  display: inline-block;`,
  `  color: #c4b5fd;`,
  `  animation: shimmer-pulse 3s ease-in-out infinite;`,
  `}`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  .scaffold-mesh__orb, .shimmer-text { animation: none !important; }`,
  `  .kinetic-word, .kinetic-word--out { animation: none !important; opacity: 1 !important; filter: none !important; transform: none !important; }`,
  `  .scroll-reveal { opacity: 1; transform: none; transition: none; }`,
  `}`,
  ``,
].join('\n');

export function generateAmbientMeshComponent(): string {
  return [
    `/** Subtle animated gradient mesh — loops quietly behind app chrome */`,
    `export function AmbientMesh({ accent = '#8b5cf6' }: { accent?: string }) {`,
    `  return (`,
    `    <div className="scaffold-mesh" aria-hidden="true">`,
    `      <div className="scaffold-mesh__orb scaffold-mesh__orb--a" style={{ background: accent }} />`,
    `      <div className="scaffold-mesh__orb scaffold-mesh__orb--b" style={{ background: accent, opacity: 0.35 }} />`,
    `      <div className="scaffold-mesh__orb scaffold-mesh__orb--c" style={{ background: accent }} />`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join('\n');
}

export function generateKineticHeadlineComponent(): string {
  return [
    `import { useEffect, useState } from 'react';`,
    ``,
    `interface Props {`,
    `  words: string[];`,
    `  intervalMs?: number;`,
    `  className?: string;`,
    `}`,
    ``,
    `/** Rotating headline word with enter/exit motion */`,
    `export function KineticHeadline({ words, intervalMs = 2800, className = '' }: Props) {`,
    `  const [index, setIndex] = useState(0);`,
    `  const [leaving, setLeaving] = useState(false);`,
    ``,
    `  useEffect(() => {`,
    `    if (words.length <= 1) return;`,
    `    const id = window.setInterval(() => {`,
    `      setLeaving(true);`,
    `      window.setTimeout(() => {`,
    `        setIndex(i => (i + 1) % words.length);`,
    `        setLeaving(false);`,
    `      }, 320);`,
    `    }, intervalMs);`,
    `    return () => window.clearInterval(id);`,
    `  }, [words, intervalMs]);`,
    ``,
    `  return (`,
    `    <span className="kinetic-slot">`,
    `      <span key={words[index]} className={\`\${leaving ? 'kinetic-word kinetic-word--out' : 'kinetic-word'} \${className}\`.trim()}>`,
    `        {words[index]}`,
    `      </span>`,
    `    </span>`,
    `  );`,
    `}`,
    ``,
  ].join('\n');
}

export function generateScrollRevealHook(): string {
  return [
    `import { useEffect, useRef } from 'react';`,
    ``,
    `/** Adds .is-visible when element enters viewport — never leaves content permanently hidden */`,
    `export function useScrollReveal<T extends HTMLElement>(threshold = 0.08) {`,
    `  const ref = useRef<T | null>(null);`,
    ``,
    `  useEffect(() => {`,
    `    const el = ref.current;`,
    `    if (!el) return;`,
    `    el.classList.add('scroll-reveal');`,
    `    const show = () => el.classList.add('is-visible');`,
    `    const obs = new IntersectionObserver(`,
    `      ([entry]) => { if (entry?.isIntersecting) { show(); obs.disconnect(); } },`,
    `      { threshold, rootMargin: '0px 0px -4% 0px' },`,
    `    );`,
    `    obs.observe(el);`,
    `    const rect = el.getBoundingClientRect();`,
    `    if (rect.top < window.innerHeight * 0.95 && rect.bottom > 0) show();`,
    `    const fallback = window.setTimeout(show, 900);`,
    `    return () => { obs.disconnect(); window.clearTimeout(fallback); };`,
    `  }, [threshold]);`,
    ``,
    `  return ref;`,
    `}`,
    ``,
  ].join('\n');
}

/** Component files injected into stack basic tiers */
export function getScaffoldUiFiles(accent: ScaffoldAccent): { path: string; content: string }[] {
  return [
    { path: 'src/components/AmbientMesh.tsx', content: generateAmbientMeshComponent() },
    { path: 'src/components/KineticHeadline.tsx', content: generateKineticHeadlineComponent() },
    { path: 'src/hooks/useScrollReveal.ts', content: generateScrollRevealHook() },
    {
      path: 'src/lib/scaffold-accent.ts',
      content: `export const SCAFFOLD_ACCENT = '${accent.hex}';\nexport const SCAFFOLD_ACCENT_NAME = '${accent.name}';\n`,
    },
  ];
}

export function appendScaffoldMotionCss(css: string): string {
  if (css.includes('mesh-drift')) return css;
  return `${css.trimEnd()}\n\n/* ── Scaffold motion system ── */\n${SCAFFOLD_MOTION_CSS}`;
}

/* ── Quick Start: React + Vite launch pad ── */

export function generateReactViteLaunchCss(): string {
  return appendScaffoldMotionCss([
    `@import "tailwindcss";`,
    ``,
    `@theme inline {`,
    `  --font-sans: "Segoe UI", system-ui, -apple-system, sans-serif;`,
    `  --color-accent: oklch(0.62 0.24 292);`,
    `}`,
    ``,
    `@layer base {`,
    `  *, *::before, *::after { box-sizing: border-box; }`,
    `  html { -webkit-font-smoothing: antialiased; scroll-behavior: smooth; }`,
    `  body {`,
    `    margin: 0;`,
    `    background: oklch(0.13 0.01 280);`,
    `    color: oklch(0.96 0.01 280);`,
    `    font-family: var(--font-sans);`,
    `  }`,
    `}`,
    ``,
  ].join('\n'));
}

export function generateReactViteLaunchApp(): string {
  return [
    `import { useState } from 'react';`,
    `import { motion } from 'framer-motion';`,
    `import { Sparkles, ArrowRight, Layers, Zap, MessageSquare, Copy, Check } from 'lucide-react';`,
    `import { AmbientMesh } from './components/AmbientMesh.js';`,
    `import { KineticHeadline } from './components/KineticHeadline.js';`,
    `import { useScrollReveal } from './hooks/useScrollReveal.js';`,
    ``,
    `const BUILD_WORDS = ['SaaS dashboards', 'brand clones', 'portfolios', 'internal tools', 'landing pages', 'games'];`,
    ``,
    `const EXAMPLE_PROMPTS = [`,
    `  'Build a dark analytics dashboard like Amplitude with sidebar nav',`,
    `  'Clone Spotify — album grid, player bar, emerald accent',`,
    `  'Tinder-style swipe cards with match animations and gradients',`,
    `];`,
    ``,
    `const STEPS = [`,
    `  { icon: Sparkles, title: 'Describe the product', body: 'Use VeggaAI chat on the left — name the niche, competitors, and must-have screens.' },`,
    `  { icon: Layers, title: 'Builder council ships it', body: 'Architect → coder → stylist → reviewer replace this shell with real React + Tailwind.' },`,
    `  { icon: Zap, title: 'Live preview updates', body: 'Every builder turn refreshes this pane with runnable code you can iterate on.' },`,
    `];`,
    ``,
    `const CHIPS = ['React 19', 'Vite 8', 'Tailwind v4', 'TypeScript 6', 'Motion-ready'];`,
    ``,
    `function sendPromptToVai(prompt: string) {`,
    `  if (typeof window !== 'undefined' && window.parent !== window) {`,
    `    window.parent.postMessage({ type: 'vai-sandbox-action', action: 'prefill-chat', prompt }, '*');`,
    `  }`,
    `  if (navigator.clipboard?.writeText) void navigator.clipboard.writeText(prompt);`,
    `}`,
    ``,
    `export function App() {`,
    `  const stepsRef = useScrollReveal<HTMLDivElement>();`,
    `  const [sentPrompt, setSentPrompt] = useState<string | null>(null);`,
    ``,
    `  const tryExample = (prompt: string) => {`,
    `    sendPromptToVai(prompt);`,
    `    setSentPrompt(prompt);`,
    `    window.setTimeout(() => setSentPrompt(null), 4000);`,
    `  };`,
    ``,
    `  return (`,
    `    <div className="relative min-h-screen overflow-x-hidden">`,
    `      <AmbientMesh accent="#8b5cf6" />`,
    `      <div className="relative z-10 mx-auto flex min-h-screen max-w-3xl flex-col px-6 py-10 sm:py-14">`,
    `        <header className="mb-10 flex items-center justify-between">`,
    `          <div className="flex items-center gap-2.5">`,
    `            <motion.div`,
    `              className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-500/15 ring-1 ring-violet-400/25"`,
    `              animate={{ rotate: [0, 3, -3, 0] }}`,
    `              transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }}`,
    `            >`,
    `              <Sparkles className="h-4 w-4 text-violet-300" />`,
    `            </motion.div>`,
    `            <span className="text-sm font-semibold tracking-tight text-zinc-200">Vai App</span>`,
    `          </div>`,
    `          <span className="rounded-full border border-zinc-800/80 bg-zinc-900/60 px-3 py-1 text-[10px] font-medium uppercase tracking-widest text-zinc-500">`,
    `            Preview shell · chat is on the left`,
    `          </span>`,
    `        </header>`,
    ``,
    `        <div className="flex flex-1 flex-col justify-center pb-8">`,
    `          <motion.p`,
    `            initial={{ opacity: 0, y: 8 }}`,
    `            animate={{ opacity: 1, y: 0 }}`,
    `            transition={{ duration: 0.5 }}`,
    `            className="mb-4 text-xs font-medium uppercase tracking-[0.2em] text-violet-400/90"`,
    `          >`,
    `            Your canvas is live — 2026-ready`,
    `          </motion.p>`,
    `          <h1 className="max-w-xl text-4xl font-semibold leading-[1.08] tracking-tight text-zinc-50 sm:text-5xl">`,
    `            Build{' '}`,
    `            <KineticHeadline words={BUILD_WORDS} className="font-semibold text-violet-300" />`,
    `            {' '}in chat`,
    `          </h1>`,
    `          <motion.p`,
    `            initial={{ opacity: 0, y: 10 }}`,
    `            animate={{ opacity: 1, y: 0 }}`,
    `            transition={{ delay: 0.15, duration: 0.5 }}`,
    `            className="mt-5 max-w-lg text-base leading-relaxed text-zinc-400"`,
    `          >`,
    `            This pane is only the live preview. Type in the <strong className="font-medium text-zinc-200">VeggaAI chat on the left</strong>, switch to <strong className="font-medium text-violet-300">Builder</strong> mode, and Vai replaces this shell with your real app.`,
    `          </motion.p>`,
    `          <motion.div`,
    `            initial={{ opacity: 0, y: 12 }}`,
    `            animate={{ opacity: 1, y: 0 }}`,
    `            transition={{ delay: 0.25, duration: 0.5 }}`,
    `            className="mt-8 flex flex-wrap gap-2"`,
    `          >`,
    `            {CHIPS.map((c, i) => (`,
    `              <span key={c} className="rounded-lg border border-zinc-800/90 bg-zinc-900/50 px-2.5 py-1 text-[11px] text-zinc-400"`,
    `                style={{ animation: \`reveal-up 0.5s \${0.3 + i * 0.06}s forwards\` }}>`,
    `                {c}`,
    `              </span>`,
    `            ))}`,
    `          </motion.div>`,
    ``,
    `          <motion.div`,
    `            initial={{ opacity: 0, y: 12 }}`,
    `            animate={{ opacity: 1, y: 0 }}`,
    `            transition={{ delay: 0.35, duration: 0.5 }}`,
    `            className="mt-8 rounded-2xl border border-violet-500/25 bg-violet-500/5 p-4 backdrop-blur-sm"`,
    `          >`,
    `            <div className="mb-3 flex items-center gap-2 text-sm font-medium text-violet-200">`,
    `              <MessageSquare className="h-4 w-4 text-violet-400" />`,
    `              Try an example — sends text to the chat panel`,
    `            </div>`,
    `            <div className="flex flex-col gap-2">`,
    `              {EXAMPLE_PROMPTS.map((prompt) => (`,
    `                <button`,
    `                  key={prompt}`,
    `                  type="button"`,
    `                  onClick={() => tryExample(prompt)}`,
    `                  className="group flex w-full items-start gap-2 rounded-xl border border-zinc-800/80 bg-zinc-950/60 px-3 py-2.5 text-left text-sm text-zinc-300 transition-colors hover:border-violet-500/40 hover:bg-zinc-900/80 hover:text-zinc-100"`,
    `                >`,
    `                  {sentPrompt === prompt ? (`,
    `                    <Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-400" />`,
    `                  ) : (`,
    `                    <Copy className="mt-0.5 h-4 w-4 shrink-0 text-zinc-600 group-hover:text-violet-400" />`,
    `                  )}`,
    `                  <span>{prompt}</span>`,
    `                </button>`,
    `              ))}`,
    `            </div>`,
    `            {sentPrompt && (`,
    `              <p className="mt-3 text-xs text-emerald-400/90">Sent to VeggaAI chat — switch to Builder mode and press Enter.</p>`,
    `            )}`,
    `          </motion.div>`,
    ``,
    `          <motion.div`,
    `            initial={{ opacity: 0 }}`,
    `            animate={{ opacity: 1 }}`,
    `            transition={{ delay: 0.45 }}`,
    `            className="mt-6 inline-flex items-center gap-2 text-sm text-zinc-500"`,
    `          >`,
    `            <ArrowRight className="h-4 w-4 rotate-180 text-violet-400/60" />`,
    `            <span>Chat panel is on the left — this preview updates when Builder runs</span>`,
    `          </motion.div>`,
    `        </div>`,
    ``,
    `        <div ref={stepsRef} className="grid gap-3 border-t border-zinc-800/70 pt-8 sm:grid-cols-3">`,
    `          {STEPS.map(({ icon: Icon, title, body }, i) => (`,
    `            <div key={title} className="rounded-2xl border border-zinc-800/60 bg-zinc-950/40 p-4 backdrop-blur-sm"`,
    `              style={{ transitionDelay: \`\${i * 80}ms\` }}>`,
    `              <Icon className="mb-2 h-4 w-4 text-violet-400/80" />`,
    `              <p className="text-sm font-medium text-zinc-200">{title}</p>`,
    `              <p className="mt-1 text-xs leading-relaxed text-zinc-500">{body}</p>`,
    `            </div>`,
    `          ))}`,
    `        </div>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join('\n');
}

export function getReactViteScaffoldExtraFiles(): { path: string; content: string }[] {
  return [
    ...getScaffoldUiFiles({ name: 'violet', hex: '#8b5cf6' }),
  ];
}

/* ── Quick Start: Next.js launch pad ── */

export function generateNextLaunchPage(): string {
  return [
    `'use client';`,
    ``,
    `import { motion } from 'framer-motion';`,
    `import { Sparkles, Server, Globe, ArrowDown, Database } from 'lucide-react';`,
    `import { AmbientMesh } from '@/components/AmbientMesh';`,
    `import { KineticHeadline } from '@/components/KineticHeadline';`,
    `import { useScrollReveal } from '@/hooks/useScrollReveal';`,
    ``,
    `const ROUTES = [`,
    `  { label: 'App Router pages', desc: 'Server & client components with file-based routing' },`,
    `  { label: 'API routes', desc: 'REST handlers colocated with your frontend' },`,
    `  { label: 'Edge-ready', desc: 'Deploy to Vercel or iterate locally in the sandbox' },`,
    `];`,
    ``,
    `export default function Page() {`,
    `  const stackRef = useScrollReveal<HTMLDivElement>();`,
    ``,
    `  return (`,
    `    <div className="relative min-h-screen overflow-hidden">`,
    `      <AmbientMesh accent="#6366f1" />`,
    `      <main className="relative z-10 mx-auto flex min-h-screen max-w-3xl flex-col px-6 py-12">`,
    `        <header className="mb-12 flex items-center gap-3">`,
    `          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/15 ring-1 ring-indigo-400/20">`,
    `            <span className="text-lg font-bold text-indigo-300">▲</span>`,
    `          </div>`,
    `          <div>`,
    `            <p className="text-sm font-semibold text-zinc-100">Inkwell on Next.js 16</p>`,
    `            <p className="text-xs text-zinc-500">Notes studio · API routes · chat-ready</p>`,
    `          </div>`,
    `        </header>`,
    ``,
    `        <section className="flex flex-1 flex-col justify-center">`,
    `          <motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="mb-3 text-xs font-medium uppercase tracking-[0.18em] text-indigo-400">`,
    `            Ship full-stack products`,
    `          </motion.p>`,
    `          <h1 className="text-4xl font-semibold tracking-tight text-zinc-50 sm:text-5xl">`,
    `            Ship{' '}`,
    `            <KineticHeadline words={['notes apps', 'SaaS dashboards', 'auth flows', 'marketplaces']} className="text-indigo-300" />`,
    `          </h1>`,
    `          <p className="mt-5 max-w-xl text-base leading-relaxed text-zinc-400">`,
    `            App Router pages, layouts, and route handlers are ready. Describe your product in VeggaAI chat — Builder grows this into Inkwell-style notes, CRMs, or full SaaS without breaking compile gates.`,
    `          </p>`,
    `          <div className="mt-8 flex flex-wrap gap-3 text-xs text-zinc-500">`,
    `            <span className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900/50 px-3 py-1.5"><Server className="h-3.5 w-3.5" /> API routes</span>`,
    `            <span className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900/50 px-3 py-1.5"><Globe className="h-3.5 w-3.5" /> App Router</span>`,
    `            <span className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-800 bg-zinc-900/50 px-3 py-1.5"><Database className="h-3.5 w-3.5" /> Ready for data</span>`,
    `          </div>`,
    `        </section>`,
    ``,
    `        <section ref={stackRef} className="mt-auto space-y-3 border-t border-zinc-800/70 pt-10 pb-4">`,
    `          <p className="mb-4 flex items-center gap-2 text-xs text-zinc-500">`,
    `            <Sparkles className="h-3.5 w-3.5 text-indigo-400" /> What this stack gives you`,
    `          </p>`,
    `          {ROUTES.map((r, i) => (`,
    `            <div key={r.label} className="flex gap-3 rounded-xl border border-zinc-800/60 bg-zinc-950/50 p-4"`,
    `              style={{ animation: \`reveal-up 0.55s \${0.1 + i * 0.08}s both\` }}>`,
    `              <ArrowDown className="mt-0.5 h-4 w-4 shrink-0 rotate-[-90deg] text-indigo-400/60" />`,
    `              <div>`,
    `                <p className="text-sm font-medium text-zinc-200">{r.label}</p>`,
    `                <p className="text-xs text-zinc-500">{r.desc}</p>`,
    `              </div>`,
    `            </div>`,
    `          ))}`,
    `        </section>`,
    `      </main>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join('\n');
}

export function generateNextGlobalsCss(): string {
  return appendScaffoldMotionCss([
    `@import "tailwindcss";`,
    ``,
    `@layer base {`,
    `  *, *::before, *::after { box-sizing: border-box; }`,
    `  html { -webkit-font-smoothing: antialiased; scroll-behavior: smooth; }`,
    `  body {`,
    `    margin: 0;`,
    `    background: oklch(0.13 0.01 270);`,
    `    color: oklch(0.96 0.01 270);`,
    `    font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;`,
    `  }`,
    `}`,
    ``,
  ].join('\n'));
}
