const NORMALIZATION_RULES: ReadonlyArray<readonly [RegExp, string]> = [
  [/\bwhats\b/gi, 'what is'],
  [/\bwats\b/gi, 'what is'],
  [/\bwaht\b/gi, 'what'],
  [/\bwhta\b/gi, 'what'],
  [/\bhwo\b/gi, 'how'],
  [/\bhoww\b/gi, 'how'],
  [/\bwyh\b/gi, 'why'],
  [/\bcna\b/gi, 'can'],
  [/\bcan\s+u\b/gi, 'can you'],
  [/\balsi\b/gi, 'also'],
  [/\bpls\b/gi, 'please'],
  [/\bplz\b/gi, 'please'],
  [/\bplis\b/gi, 'please'],
  [/\bseamles\b/gi, 'seamless'],
  [/\bseamlesly\b/gi, 'seamlessly'],
  [/\bneatles\b/gi, 'neatly'],
  [/\bitterate\b/gi, 'iterate'],
  [/\bitterating\b/gi, 'iterating'],
  [/\bitteration\b/gi, 'iteration'],
  [/\bupgaades\b/gi, 'upgrades'],
  [/\bupgades\b/gi, 'upgrades'],
  [/\baps\b/gi, 'apps'],
  [/\brepliceate\b/gi, 'replicate'],
  [/\bwebstie\b/gi, 'website'],
  [/\bwebiste\b/gi, 'website'],
  [/\bscrenshot\b/gi, 'screenshot'],
  [/\bsceenshot\b/gi, 'screenshot'],
  [/\btwiter\b/gi, 'twitter'],
  [/\btwitterr\b/gi, 'twitter'],
  [/\bcloen\b/gi, 'clone'],
  [/\bexsplain\b/gi, 'explain'],
  [/\bexplian\b/gi, 'explain'],
  [/\bexpalin\b/gi, 'explain'],
  [/\bexpain\b/gi, 'explain'],
  [/\bexplaine\b/gi, 'explain'],
  [/\bexplane\b/gi, 'explain'],
  [/\bdesribe\b/gi, 'describe'],
  [/\bdescrbie\b/gi, 'describe'],
  [/\bdefintion\b/gi, 'definition'],
  [/\bcomparision\b/gi, 'comparison'],
  [/\bcomparsion\b/gi, 'comparison'],
  [/\bcompair\b/gi, 'compare'],
  [/\bcomapre\b/gi, 'compare'],
  [/\breccomend\b/gi, 'recommend'],
  [/\bdiffernce\b/gi, 'difference'],
  [/\bundrestand\b/gi, 'understand'],
  [/\bunderstad\b/gi, 'understand'],
  [/\bhvaa\b/gi, 'hva'],
  [/\bhvae\b/gi, 'hva'],
  [/\bvha\b/gi, 'hva'],
  [/\bka\s+(?:er|e)\b/gi, 'hva er'],
  [/\bkva\s+er\b/gi, 'hva er'],
  [/\bhvodan\b/gi, 'hvordan'],
  [/\bhvordna\b/gi, 'hvordan'],
  [/\bhvoran\b/gi, 'hvordan'],
  [/\bkordan\b/gi, 'hvordan'],
  [/\bkossen\b/gi, 'hvordan'],
  [/\bforkalr\b/gi, 'forklar'],
  [/\bfoklar\b/gi, 'forklar'],
  [/\bforklr\b/gi, 'forklar'],
  [/\bforklare\b/gi, 'forklar'],
  [/\bfunke\b/gi, 'fungerer'],
  [/\bfunker\b/gi, 'fungerer'],
  [/\bpyhton\b/gi, 'python'],
  [/\bphyton\b/gi, 'python'],
  [/\btypescirpt\b/gi, 'typescript'],
  [/\btypsecript\b/gi, 'typescript'],
  [/\btypscript\b/gi, 'typescript'],
  [/\btypecript\b/gi, 'typescript'],
  [/\bjavascripts\b/gi, 'javascript'],
  [/\bjavascritp\b/gi, 'javascript'],
  [/\bjavscript\b/gi, 'javascript'],
  [/\bjavascipt\b/gi, 'javascript'],
  [/\bdockre\b/gi, 'docker'],
  [/\bdokcer\b/gi, 'docker'],
  [/\bwebsokcet\b/gi, 'websocket'],
  [/\bwebscoket\b/gi, 'websocket'],
  [/\bwebsockett\b/gi, 'websocket'],
  [/\bdatabse\b/gi, 'database'],
  [/\bdatabaes\b/gi, 'database'],
  [/\brecusrion\b/gi, 'recursion'],
  [/\brecusion\b/gi, 'recursion'],
  [/\blatancy\b/gi, 'latency'],
  [/\blatecny\b/gi, 'latency'],
  [/\bqeue\b/gi, 'queue'],
  [/\bprsima\b/gi, 'prisma'],
  [/\bpostgress\b/gi, 'postgres'],
  [/\bpostrges\b/gi, 'postgres'],
  [/\brecat\b/gi, 'react'],
  [/\breactt\b/gi, 'react'],
  [/\bnextj\b/gi, 'nextjs'],
  [/\bnxtjs\b/gi, 'nextjs'],
  [/\bmeanng\b/gi, 'meaning'],
  [/\bmeanig\b/gi, 'meaning'],
  [/\bprograming\b/gi, 'programming'],
  [/\bprgramming\b/gi, 'programming'],
];

export function normalizeInputForUnderstanding(input: string): string {
  const trimmed = input.trim();
  if (trimmed.length === 0) return input;
  if (/```/.test(trimmed)) return input;

  let normalized = trimmed;
  for (const [pattern, replacement] of NORMALIZATION_RULES) {
    normalized = normalized.replace(pattern, replacement);
  }

  return normalized.replace(/\s+/g, ' ').trim();
}