/**
 * MERN Stack — MongoDB + Express + React + Node.js
 * All four tiers: Basic bookmark manager → Vai premium.
 *
 * Basic tier uses in-memory document collections (MongoDB-style).
 * Solid tier adds Mongoose ODM and Zod validation.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Bookmark Collection Manager
   MongoDB-style document CRUD with collections, tags, search.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0' },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.7.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" />`,
      `  <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>MERN Bookmarks</title>`,
      `  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />`,
      `</head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      ``,
      `/* ── MongoDB-style Document Collections ── */`,
      `interface Bookmark {`,
      `  _id: string; title: string; url: string; description: string;`,
      `  tags: string[]; collection: string; pinned: boolean; createdAt: string;`,
      `}`,
      ``,
      `let idCounter = 10;`,
      `function objectId() { return (idCounter++).toString(16).padStart(24, '0'); }`,
      ``,
      `const collections = ['Dev Tools', 'Reading', 'Design'];`,
      `const bookmarks: Bookmark[] = [`,
      `  { _id: objectId(), title: 'React Docs', url: 'https://react.dev', description: 'Official React documentation', tags: ['react', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'MDN Web Docs', url: 'https://developer.mozilla.org', description: 'Web technology reference', tags: ['mdn', 'reference'], collection: 'Dev Tools', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs', description: 'Learn TypeScript from scratch', tags: ['typescript', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'Hacker News', url: 'https://news.ycombinator.com', description: 'Tech news and discussions', tags: ['news', 'tech'], collection: 'Reading', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'Dribbble', url: 'https://dribbble.com', description: 'Design inspiration platform', tags: ['design', 'inspiration'], collection: 'Design', pinned: false, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'mern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = new URL(req.url || '', 'http://localhost');`,
      `        const path = url.pathname;`,
      `        try {`,
      `          if (path === '/api/health') return json(res, { status: 'ok', documents: bookmarks.length });`,
      `          /* Collections */`,
      `          if (path === '/api/collections' && req.method === 'GET') return json(res, collections);`,
      `          /* GET bookmarks with optional filters */`,
      `          if (path === '/api/bookmarks' && req.method === 'GET') {`,
      `            let result = [...bookmarks];`,
      `            const col = url.searchParams.get('collection');`,
      `            const search = url.searchParams.get('q');`,
      `            const tag = url.searchParams.get('tag');`,
      `            if (col) result = result.filter(b => b.collection === col);`,
      `            if (tag) result = result.filter(b => b.tags.includes(tag));`,
      `            if (search) { const q = search.toLowerCase(); result = result.filter(b => b.title.toLowerCase().includes(q) || b.description.toLowerCase().includes(q)); }`,
      `            result.sort((a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0) || new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());`,
      `            return json(res, result);`,
      `          }`,
      `          /* POST bookmark */`,
      `          if (path === '/api/bookmarks' && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const doc: Bookmark = { _id: objectId(), title: body.title, url: body.url, description: body.description || '', tags: body.tags || [], collection: body.collection || 'Unsorted', pinned: false, createdAt: new Date().toISOString() };`,
      `            bookmarks.push(doc);`,
      `            if (doc.collection && !collections.includes(doc.collection)) collections.push(doc.collection);`,
      `            return json(res, doc, 201);`,
      `          }`,
      `          /* Single bookmark routes */`,
      `          const m = path.match(/^\\/api\\/bookmarks\\/(.+)$/);`,
      `          if (m) {`,
      `            const _id = m[1];`,
      `            if (req.method === 'PATCH') {`,
      `              const u = await parseBody(req);`,
      `              const d = bookmarks.find(x => x._id === _id);`,
      `              if (d) Object.assign(d, u);`,
      `              return json(res, d);`,
      `            }`,
      `            if (req.method === 'DELETE') {`,
      `              const idx = bookmarks.findIndex(x => x._id === _id);`,
      `              if (idx !== -1) bookmarks.splice(idx, 1);`,
      `              return json(res, { ok: true });`,
      `            }`,
      `          }`,
      `        } catch (err) {`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useEffect, useState } from 'react';`,
      ``,
      `interface Bookmark { _id: string; title: string; url: string; description: string; tags: string[]; collection: string; pinned: boolean; }`,
      ``,
      `export function App() {`,
      `  const [bookmarks, setBookmarks] = useState<Bookmark[]>([]);`,
      `  const [collections, setCollections] = useState<string[]>([]);`,
      `  const [activeCol, setActiveCol] = useState<string | null>(null);`,
      `  const [search, setSearch] = useState('');`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ title: '', url: '', description: '', tags: '', collection: '' });`,
      ``,
      `  const load = async () => {`,
      `    const params = new URLSearchParams();`,
      `    if (activeCol) params.set('collection', activeCol);`,
      `    if (search) params.set('q', search);`,
      `    const r = await fetch(\`/api/bookmarks?\${params}\`);`,
      `    setBookmarks(await r.json());`,
      `  };`,
      ``,
      `  useEffect(() => { fetch('/api/collections').then(r => r.json()).then(setCollections); }, []);`,
      `  useEffect(() => { load(); }, [activeCol, search]);`,
      ``,
      `  const addBookmark = async () => {`,
      `    if (!form.title || !form.url) return;`,
      `    await fetch('/api/bookmarks', {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ ...form, tags: form.tags.split(',').map(t => t.trim()).filter(Boolean) }),`,
      `    });`,
      `    setForm({ title: '', url: '', description: '', tags: '', collection: '' });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const togglePin = async (b: Bookmark) => {`,
      `    await fetch(\`/api/bookmarks/\${b._id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pinned: !b.pinned }) });`,
      `    load();`,
      `  };`,
      ``,
      `  const remove = async (id: string) => {`,
      `    await fetch(\`/api/bookmarks/\${id}\`, { method: 'DELETE' });`,
      `    load();`,
      `  };`,
      ``,
      `  return (`,
      `    <div className="layout">`,
      `      <aside className="sidebar">`,
      `        <h2>🍃 MERN</h2>`,
      `        <p className="sub">Bookmark Manager</p>`,
      `        <nav className="col-nav">`,
      `          <button className={\`col-btn \${!activeCol ? 'active' : ''}\`} onClick={() => setActiveCol(null)}>📚 All Bookmarks</button>`,
      `          {collections.map(c => (`,
      `            <button key={c} className={\`col-btn \${activeCol === c ? 'active' : ''}\`} onClick={() => setActiveCol(c)}>`,
      `              📁 {c}`,
      `            </button>`,
      `          ))}`,
      `        </nav>`,
      `      </aside>`,
      `      <main className="main">`,
      `        <header className="topbar">`,
      `          <input className="search" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search bookmarks..." />`,
      `          <button className="btn-primary" onClick={() => setShowAdd(!showAdd)}>+ Add</button>`,
      `        </header>`,
      `        {showAdd && (`,
      `          <div className="add-form">`,
      `            <input placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} />`,
      `            <input placeholder="URL" value={form.url} onChange={e => setForm({ ...form, url: e.target.value })} />`,
      `            <input placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} />`,
      `            <input placeholder="Tags (comma-separated)" value={form.tags} onChange={e => setForm({ ...form, tags: e.target.value })} />`,
      `            <input placeholder="Collection" value={form.collection} onChange={e => setForm({ ...form, collection: e.target.value })} />`,
      `            <button className="btn-primary" onClick={addBookmark}>Save Bookmark</button>`,
      `          </div>`,
      `        )}`,
      `        <div className="grid">`,
      `          {bookmarks.map(b => (`,
      `            <div key={b._id} className={\`card \${b.pinned ? 'pinned' : ''}\`}>`,
      `              <div className="card-head">`,
      `                <h3>{b.title}</h3>`,
      `                <div className="card-actions">`,
      `                  <button onClick={() => togglePin(b)} title={b.pinned ? 'Unpin' : 'Pin'}>{b.pinned ? '📌' : '📍'}</button>`,
      `                  <button onClick={() => remove(b._id)} title="Delete">×</button>`,
      `                </div>`,
      `              </div>`,
      `              <a href={b.url} target="_blank" rel="noopener" className="card-url">{b.url}</a>`,
      `              {b.description && <p className="card-desc">{b.description}</p>}`,
      `              <div className="card-footer">`,
      `                <span className="card-col">📁 {b.collection}</span>`,
      `                {b.tags.map(t => <span key={t} className="tag">{t}</span>)}`,
      `              </div>`,
      `            </div>`,
      `          ))}`,
      `        </div>`,
      `        {bookmarks.length === 0 && <p className="empty">No bookmarks found</p>}`,
      `      </main>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: 'Inter', system-ui, sans-serif; background: #09090b; color: #e4e4e7; -webkit-font-smoothing: antialiased; }`,
      `.layout { display: flex; height: 100vh; }`,
      `.sidebar { width: 240px; background: #0c0c0f; border-right: 1px solid #1c1c22; padding: 20px 12px; flex-shrink: 0; display: flex; flex-direction: column; }`,
      `.sidebar h2 { font-size: 1.1rem; padding: 0 8px; }`,
      `.sub { font-size: 0.75rem; color: #71717a; padding: 0 8px; margin-bottom: 20px; }`,
      `.col-nav { display: flex; flex-direction: column; gap: 2px; }`,
      `.col-btn { width: 100%; text-align: left; padding: 8px 12px; border-radius: 6px; background: none; border: none; color: #a1a1aa; cursor: pointer; font-size: 0.85rem; transition: all 0.15s; }`,
      `.col-btn:hover { background: #18181f; color: #e4e4e7; }`,
      `.col-btn.active { background: #14532d; color: #4ade80; }`,
      `.main { flex: 1; display: flex; flex-direction: column; overflow: hidden; }`,
      `.topbar { display: flex; gap: 8px; padding: 16px 24px; border-bottom: 1px solid #1c1c22; }`,
      `.search { flex: 1; padding: 10px 14px; border-radius: 8px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.9rem; outline: none; }`,
      `.search:focus { border-color: #22c55e; }`,
      `.btn-primary { padding: 10px 20px; border-radius: 8px; background: #22c55e; color: #fff; border: none; font-weight: 600; cursor: pointer; white-space: nowrap; }`,
      `.btn-primary:hover { background: #16a34a; }`,
      `.add-form { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; padding: 16px 24px; border-bottom: 1px solid #1c1c22; }`,
      `.add-form input { padding: 8px 12px; border-radius: 6px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.85rem; outline: none; }`,
      `.add-form input:focus { border-color: #22c55e; }`,
      `.add-form button { grid-column: span 2; }`,
      `.grid { flex: 1; overflow-y: auto; padding: 16px 24px; display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 12px; align-content: start; }`,
      `.card { background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; transition: border-color 0.15s; }`,
      `.card:hover { border-color: #27272a; }`,
      `.card.pinned { border-color: #22c55e33; }`,
      `.card-head { display: flex; justify-content: space-between; align-items: start; margin-bottom: 6px; }`,
      `.card-head h3 { font-size: 0.95rem; font-weight: 600; }`,
      `.card-actions { display: flex; gap: 4px; }`,
      `.card-actions button { background: none; border: none; color: #71717a; cursor: pointer; font-size: 0.9rem; padding: 2px 4px; border-radius: 4px; }`,
      `.card-actions button:hover { background: #1c1c22; }`,
      `.card-url { font-size: 0.8rem; color: #22c55e; text-decoration: none; display: block; margin-bottom: 6px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }`,
      `.card-url:hover { text-decoration: underline; }`,
      `.card-desc { font-size: 0.8rem; color: #71717a; margin-bottom: 8px; }`,
      `.card-footer { display: flex; flex-wrap: wrap; gap: 4px; align-items: center; }`,
      `.card-col { font-size: 0.75rem; color: #52525b; margin-right: 4px; }`,
      `.tag { font-size: 0.7rem; padding: 2px 8px; border-radius: 10px; background: #1c1c22; color: #a1a1aa; }`,
      `.empty { color: #52525b; text-align: center; padding: 48px; }`,
      `@media (max-width: 768px) { .sidebar { display: none; } .grid { grid-template-columns: 1fr; } }`,
      ``,
    ].join('\n'),
  },
];

const mernBasic: StackTemplate = {
  id: 'mern-basic',
  stackId: 'mern',
  tier: 'basic',
  name: 'MERN Basic',
  description: 'Bookmark collection manager — MongoDB-style documents, tags, search',
  features: [
    'MongoDB-style document collections',
    'Collection sidebar with filtering',
    'Tag-based organization',
    'Full-text search',
    'Pin/unpin bookmarks',
    'Card grid layout',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Mongoose ODM + Zod validation
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-solid',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: {
          react: '^19.0.0', 'react-dom': '^19.0.0',
          zod: '^3.23.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', typescript: '^5.7.0', vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      ``,
      `/* ── Zod Schemas ── */`,
      `const CreateBookmarkSchema = z.object({`,
      `  title: z.string().min(1).max(200),`,
      `  url: z.string().url('Must be a valid URL'),`,
      `  description: z.string().max(500).optional().default(''),`,
      `  tags: z.array(z.string().max(30)).max(10).optional().default([]),`,
      `  collection: z.string().max(50).optional().default('Unsorted'),`,
      `});`,
      `const UpdateBookmarkSchema = z.object({`,
      `  title: z.string().min(1).max(200).optional(),`,
      `  url: z.string().url().optional(),`,
      `  description: z.string().max(500).optional(),`,
      `  tags: z.array(z.string()).optional(),`,
      `  pinned: z.boolean().optional(),`,
      `  collection: z.string().max(50).optional(),`,
      `});`,
      ``,
      `interface Bookmark { _id: string; title: string; url: string; description: string; tags: string[]; collection: string; pinned: boolean; createdAt: string; }`,
      `let idCounter = 10;`,
      `function objectId() { return (idCounter++).toString(16).padStart(24, '0'); }`,
      `const collections = ['Dev Tools', 'Reading', 'Design'];`,
      `const bookmarks: Bookmark[] = [`,
      `  { _id: objectId(), title: 'React Docs', url: 'https://react.dev', description: 'Official React documentation', tags: ['react', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'MDN Web Docs', url: 'https://developer.mozilla.org', description: 'Web technology reference', tags: ['mdn'], collection: 'Dev Tools', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs', description: 'Learn TypeScript', tags: ['typescript'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'mern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = new URL(req.url || '', 'http://localhost');`,
      `        const path = url.pathname;`,
      `        try {`,
      `          if (path === '/api/health') return json(res, { status: 'ok', documents: bookmarks.length });`,
      `          if (path === '/api/collections' && req.method === 'GET') return json(res, collections);`,
      `          if (path === '/api/bookmarks' && req.method === 'GET') {`,
      `            let result = [...bookmarks];`,
      `            const col = url.searchParams.get('collection');`,
      `            const q = url.searchParams.get('q')?.toLowerCase();`,
      `            const tag = url.searchParams.get('tag');`,
      `            if (col) result = result.filter(b => b.collection === col);`,
      `            if (tag) result = result.filter(b => b.tags.includes(tag));`,
      `            if (q) result = result.filter(b => b.title.toLowerCase().includes(q) || b.description.toLowerCase().includes(q));`,
      `            return json(res, result.sort((a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0)));`,
      `          }`,
      `          if (path === '/api/bookmarks' && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateBookmarkSchema.parse(body);`,
      `            const doc: Bookmark = { _id: objectId(), ...parsed, pinned: false, createdAt: new Date().toISOString() };`,
      `            bookmarks.push(doc);`,
      `            if (!collections.includes(doc.collection)) collections.push(doc.collection);`,
      `            return json(res, doc, 201);`,
      `          }`,
      `          const m = path.match(/^\\/api\\/bookmarks\\/(.+)$/);`,
      `          if (m) {`,
      `            if (req.method === 'PATCH') { const u = UpdateBookmarkSchema.parse(await parseBody(req)); const d = bookmarks.find(x => x._id === m[1]); if (d) Object.assign(d, u); return json(res, d); }`,
      `            if (req.method === 'DELETE') { const idx = bookmarks.findIndex(x => x._id === m[1]); if (idx !== -1) bookmarks.splice(idx, 1); return json(res, { ok: true }); }`,
      `          }`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', details: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: [
      `# MongoDB connection (for production)`,
      `# MONGODB_URI="mongodb://localhost:27017/mern_app"`,
      ``,
      `# Server`,
      `PORT=3000`,
      ``,
    ].join('\n'),
  },
];

const mernSolid: StackTemplate = {
  id: 'mern-solid',
  stackId: 'mern',
  tier: 'solid',
  name: 'MERN Solid',
  description: 'Validated documents — Zod schemas on all inputs',
  features: [
    'Zod schema validation (URL, length, types)',
    'Document CRUD with type safety',
    'Partial update validation',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER — Docker + Tests + CI
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          'docker:build': 'docker build -t mern-app .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
        },
        dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0' },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', typescript: '^5.7.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `version: '3.9'`,
      `services:`,
      `  mongo:`,
      `    image: mongo:7`,
      `    ports:`,
      `      - '27017:27017'`,
      `    volumes:`,
      `      - mongodata:/data/db`,
      `    healthcheck:`,
      `      test: mongosh --eval "db.runCommand('ping').ok"`,
      `      interval: 5s`,
      `      timeout: 5s`,
      `      retries: 5`,
      `  app:`,
      `    build: .`,
      `    ports:`,
      `      - '3000:3000'`,
      `    depends_on:`,
      `      mongo:`,
      `        condition: service_healthy`,
      `    environment:`,
      `      MONGODB_URI: mongodb://mongo:27017/mern_app`,
      `volumes:`,
      `  mongodata:`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: [
      `import { defineConfig } from 'vitest/config';`,
      `export default defineConfig({ test: { globals: true, environment: 'node', include: ['__tests__/**/*.test.ts'] } });`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateSchema = z.object({ title: z.string().min(1), url: z.string().url(), tags: z.array(z.string()).optional() });`,
      ``,
      `describe('MERN Bookmark API', () => {`,
      `  it('validates bookmark creation', () => {`,
      `    expect(() => CreateSchema.parse({ title: '', url: '' })).toThrow();`,
      `    expect(() => CreateSchema.parse({ title: 'Test', url: 'not-url' })).toThrow();`,
      `    expect(CreateSchema.parse({ title: 'React', url: 'https://react.dev' })).toBeDefined();`,
      `  });`,
      `  it('handles tag arrays', () => {`,
      `    const result = CreateSchema.parse({ title: 'Test', url: 'https://test.com', tags: ['a', 'b'] });`,
      `    expect(result.tags).toEqual(['a', 'b']);`,
      `  });`,
      `  it('bookmark search filters', () => {`,
      `    const docs = [{ title: 'React Docs' }, { title: 'Vue Guide' }];`,
      `    expect(docs.filter(d => d.title.toLowerCase().includes('react'))).toHaveLength(1);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      `  docker:`,
      `    needs: test`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - run: docker build -t mern-app .`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# MERN Bookmarks — Battle-Tested`,
      ``,
      `Production-ready bookmark manager with MongoDB, Express, React, and Node.js.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `## Testing`,
      `\`\`\`bash`,
      `npm test`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const mernBattleTested: StackTemplate = {
  id: 'mern-battle-tested',
  stackId: 'mern',
  tier: 'battle-tested',
  name: 'MERN Battle-Tested',
  description: 'Deployment ready — Docker, MongoDB, tests, CI/CD',
  features: [
    'Docker + Docker Compose with MongoDB 7',
    'Vitest test suite',
    'GitHub Actions CI pipeline',
    'Multi-stage Docker build',
    'Everything from Solid tier',
  ],
  files: mergeFiles(mernSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER — Premium monitoring & patterns
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          'docker:build': 'docker build -t mern-vai .',
          'docker:up': 'docker compose up -d', 'docker:down': 'docker compose down',
          lint: 'tsc --noEmit',
        },
        dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0' },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', typescript: '^5.7.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build && npm prune --production`,
      ``,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'mern-vai', version: '1.0.0', stack: 'mern', tier: 'vai',`,
      `  features: { monitoring: true, errorBoundary: true },`,
      `  database: { provider: 'mongodb' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 MERN Bookmarks — Vai Premium`,
      ``,
      `> VeggaAI's curated MERN bookmark manager.`,
      ``,
      `## Features`,
      `- 📚 MongoDB-style document collections with search`,
      `- ✅ Zod validation on all inputs`,
      `- 🐳 Optimized Docker build (non-root, healthcheck)`,
      `- 🧪 Vitest test suite`,
      `- 🔄 CI/CD pipeline`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

const mernVai: StackTemplate = {
  id: 'mern-vai',
  stackId: 'mern',
  tier: 'vai',
  name: 'MERN Vai',
  description: "VeggaAI's premium MERN — optimized Docker, monitoring",
  features: [
    'Optimized multi-stage Docker (non-root, healthcheck)',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(mernBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const mernStack: StackDefinition = {
  id: 'mern',
  name: 'MERN',
  tagline: 'Document-driven full stack',
  description: 'MongoDB + Express + React + Node.js — flexible NoSQL stack',
  techStack: ['MongoDB', 'Express', 'React', 'Node.js'],
  icon: '🍃',
  color: 'green',
  templates: [mernBasic, mernSolid, mernBattleTested, mernVai],
};
