/**
 * MERN Stack — MongoDB + Express + React + Node.js
 * Basic tier with in-memory store, higher tiers coming soon.
 */

import type { StackDefinition, StackTemplate } from './types.js';

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0' },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.7.0',
          vite: '^6.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>MERN Stack</title></head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      ``,
      `// In-memory "collections" mimicking MongoDB documents`,
      `interface Doc { _id: string; text: string; done: boolean; createdAt: string; }`,
      `const collection: Doc[] = [`,
      `  { _id: '6601a1', text: 'Set up MERN stack', done: true, createdAt: new Date().toISOString() },`,
      `  { _id: '6601a2', text: 'Connect MongoDB', done: false, createdAt: new Date().toISOString() },`,
      `];`,
      `let counter = 3;`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'mern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = req.url || '';`,
      `        if (url === '/api/health') return json(res, { status: 'ok' });`,
      `        if (url === '/api/todos' && req.method === 'GET') return json(res, collection);`,
      `        if (url === '/api/todos' && req.method === 'POST') {`,
      `          const { text } = await parseBody(req);`,
      `          const doc: Doc = { _id: \`6601a\${counter++}\`, text, done: false, createdAt: new Date().toISOString() };`,
      `          collection.push(doc);`,
      `          return json(res, doc, 201);`,
      `        }`,
      `        const m = url.match(/^\\/api\\/todos\\/(.+)$/);`,
      `        if (m) {`,
      `          const _id = m[1];`,
      `          if (req.method === 'PATCH') { const u = await parseBody(req); const d = collection.find(x => x._id === _id); if (d) Object.assign(d, u); return json(res, d); }`,
      `          if (req.method === 'DELETE') { const idx = collection.findIndex(x => x._id === _id); if (idx !== -1) collection.splice(idx, 1); return json(res, { ok: true }); }`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useEffect, useState } from 'react';`,
      `interface Doc { _id: string; text: string; done: boolean; }`,
      `export function App() {`,
      `  const [docs, setDocs] = useState<Doc[]>([]);`,
      `  const [text, setText] = useState('');`,
      `  useEffect(() => { fetch('/api/todos').then(r => r.json()).then(setDocs); }, []);`,
      `  const add = async () => {`,
      `    if (!text.trim()) return;`,
      `    const r = await fetch('/api/todos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) });`,
      `    setDocs([...docs, await r.json()]); setText('');`,
      `  };`,
      `  return (`,
      `    <div className="app">`,
      `      <h1>🍃 MERN Todos</h1>`,
      `      <p className="sub">MongoDB · Express · React · Node.js</p>`,
      `      <div className="input-row">`,
      `        <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} placeholder="Add a document..." />`,
      `        <button onClick={add}>Add</button>`,
      `      </div>`,
      `      <ul>{docs.map(d => (`,
      `        <li key={d._id}><input type="checkbox" checked={d.done} onChange={async () => {`,
      `          await fetch(\`/api/todos/\${d._id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ done: !d.done }) });`,
      `          setDocs(docs.map(x => x._id === d._id ? { ...x, done: !x.done } : x));`,
      `        }} /><span style={{ textDecoration: d.done ? 'line-through' : 'none' }}>{d.text}</span></li>`,
      `      ))}</ul>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: system-ui, sans-serif; background: #09090b; color: #e4e4e7; }`,
      `.app { max-width: 600px; margin: 60px auto; padding: 0 20px; }`,
      `h1 { font-size: 2rem; margin-bottom: 4px; }`,
      `.sub { color: #71717a; font-size: 0.875rem; margin-bottom: 32px; }`,
      `.input-row { display: flex; gap: 8px; margin-bottom: 24px; }`,
      `.input-row input { flex: 1; padding: 10px 14px; border-radius: 8px; border: 1px solid #27272a; background: #18181b; color: #e4e4e7; font-size: 0.9rem; }`,
      `.input-row button { padding: 10px 20px; border-radius: 8px; background: #22c55e; color: #fff; border: none; font-weight: 600; cursor: pointer; }`,
      `ul { list-style: none; } li { display: flex; align-items: center; gap: 12px; padding: 10px 0; border-bottom: 1px solid #27272a; }`,
      `li input[type="checkbox"] { width: 18px; height: 18px; accent-color: #22c55e; }`,
      `li span { flex: 1; font-size: 0.9rem; }`,
      ``,
    ].join('\n'),
  },
];

const mernBasic: StackTemplate = {
  id: 'mern-basic',
  stackId: 'mern',
  tier: 'basic',
  name: 'MERN Basic',
  description: 'Minimal MongoDB + Express + React + Node.js starter',
  features: ['MongoDB-style document API', 'React 19 + TypeScript', 'In-memory collections', 'Document CRUD'],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

const comingSoon = (tier: 'solid' | 'battle-tested' | 'vai'): StackTemplate => ({
  id: `mern-${tier}`,
  stackId: 'mern',
  tier,
  name: `MERN ${tier === 'battle-tested' ? 'Battle-Tested' : tier === 'vai' ? 'Vai' : 'Solid'}`,
  description: 'Coming soon',
  features: ['Coming soon — check back for updates'],
  files: [],
  hasDocker: tier === 'battle-tested' || tier === 'vai',
  hasTests: tier === 'battle-tested' || tier === 'vai',
  comingSoon: true,
});

export const mernStack: StackDefinition = {
  id: 'mern',
  name: 'MERN',
  tagline: 'Document-driven full stack',
  description: 'MongoDB + Express + React + Node.js — flexible NoSQL stack',
  techStack: ['MongoDB', 'Express', 'React', 'Node.js'],
  icon: '🍃',
  color: 'green',
  templates: [mernBasic, comingSoon('solid'), comingSoon('battle-tested'), comingSoon('vai')],
};
