/**
 * MERN Stack — MongoDB + Express + React + Node.js
 * All four tiers: Basic bookmark manager → Vai premium.
 *
 * Basic tier uses in-memory document collections (MongoDB-style).
 * Solid tier adds Mongoose ODM and Zod validation.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Bookmark Collection Manager
   MongoDB-style document CRUD with collections, tags, search.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: {
          react: '^19.2.0', 'react-dom': '^19.2.0',
          'lucide-react': '^0.513.0', clsx: '^2.1.1',
        },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^5.1.0',
          '@tailwindcss/vite': '^4.1.0',
          tailwindcss: '^4.1.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import tailwindcss from '@tailwindcss/vite';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), tailwindcss(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" />`,
      `  <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>MERN Bookmarks</title>`,
      `  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />`,
      `</head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      ``,
      `/* ── MongoDB-style Document Collections ── */`,
      `interface Bookmark {`,
      `  _id: string; title: string; url: string; description: string;`,
      `  tags: string[]; collection: string; pinned: boolean; createdAt: string;`,
      `}`,
      ``,
      `let idCounter = 10;`,
      `function objectId() { return (idCounter++).toString(16).padStart(24, '0'); }`,
      ``,
      `const collections = ['Dev Tools', 'Reading', 'Design'];`,
      `const bookmarks: Bookmark[] = [`,
      `  { _id: objectId(), title: 'React Docs', url: 'https://react.dev', description: 'Official React documentation', tags: ['react', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'MDN Web Docs', url: 'https://developer.mozilla.org', description: 'Web technology reference', tags: ['mdn', 'reference'], collection: 'Dev Tools', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs', description: 'Learn TypeScript from scratch', tags: ['typescript', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'Hacker News', url: 'https://news.ycombinator.com', description: 'Tech news and discussions', tags: ['news', 'tech'], collection: 'Reading', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'Dribbble', url: 'https://dribbble.com', description: 'Design inspiration platform', tags: ['design', 'inspiration'], collection: 'Design', pinned: false, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'mern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = new URL(req.url || '', 'http://localhost');`,
      `        const path = url.pathname;`,
      `        try {`,
      `          if (path === '/api/health') return json(res, { status: 'ok', documents: bookmarks.length });`,
      `          /* Collections */`,
      `          if (path === '/api/collections' && req.method === 'GET') return json(res, collections);`,
      `          /* GET bookmarks with optional filters */`,
      `          if (path === '/api/bookmarks' && req.method === 'GET') {`,
      `            let result = [...bookmarks];`,
      `            const col = url.searchParams.get('collection');`,
      `            const search = url.searchParams.get('q');`,
      `            const tag = url.searchParams.get('tag');`,
      `            if (col) result = result.filter(b => b.collection === col);`,
      `            if (tag) result = result.filter(b => b.tags.includes(tag));`,
      `            if (search) { const q = search.toLowerCase(); result = result.filter(b => b.title.toLowerCase().includes(q) || b.description.toLowerCase().includes(q)); }`,
      `            result.sort((a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0) || new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());`,
      `            return json(res, result);`,
      `          }`,
      `          /* POST bookmark */`,
      `          if (path === '/api/bookmarks' && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const doc: Bookmark = { _id: objectId(), title: body.title, url: body.url, description: body.description || '', tags: body.tags || [], collection: body.collection || 'Unsorted', pinned: false, createdAt: new Date().toISOString() };`,
      `            bookmarks.push(doc);`,
      `            if (doc.collection && !collections.includes(doc.collection)) collections.push(doc.collection);`,
      `            return json(res, doc, 201);`,
      `          }`,
      `          /* Single bookmark routes */`,
      `          const m = path.match(/^\\/api\\/bookmarks\\/(.+)$/);`,
      `          if (m) {`,
      `            const _id = m[1];`,
      `            if (req.method === 'PATCH') {`,
      `              const u = await parseBody(req);`,
      `              const d = bookmarks.find(x => x._id === _id);`,
      `              if (d) Object.assign(d, u);`,
      `              return json(res, d);`,
      `            }`,
      `            if (req.method === 'DELETE') {`,
      `              const idx = bookmarks.findIndex(x => x._id === _id);`,
      `              if (idx !== -1) bookmarks.splice(idx, 1);`,
      `              return json(res, { ok: true });`,
      `            }`,
      `          }`,
      `        } catch (err) {`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { Bookmark as BookmarkIcon, Folder, Plus, Trash2, Pin, PinOff, Search, Menu, X, Globe, Tag, ExternalLink } from 'lucide-react';`,
      `import clsx from 'clsx';`,
      ``,
      `interface BookmarkItem {`,
      `  _id: string; title: string; url: string; description: string;`,
      `  tags: string[]; collection: string; pinned: boolean; createdAt: string;`,
      `}`,
      ``,
      `export function App() {`,
      `  const [bookmarks, setBookmarks] = useState<BookmarkItem[]>([]);`,
      `  const [collections, setCollections] = useState<string[]>([]);`,
      `  const [activeCollection, setActiveCollection] = useState<string | null>(null);`,
      `  const [search, setSearch] = useState('');`,
      `  const [sidebarOpen, setSidebarOpen] = useState(window.innerWidth > 768);`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ title: '', url: '', description: '', tags: '', collection: '' });`,
      `  const [loading, setLoading] = useState(true);`,
      ``,
      `  const load = async () => {`,
      `    const params = new URLSearchParams();`,
      `    if (activeCollection) params.set('collection', activeCollection);`,
      `    if (search) params.set('search', search);`,
      `    const r = await fetch(\`/api/bookmarks?\${params}\`);`,
      `    const data = await r.json();`,
      `    setBookmarks(data.bookmarks ?? data);`,
      `    if (data.collections) setCollections(data.collections);`,
      `    setLoading(false);`,
      `  };`,
      ``,
      `  useEffect(() => { load(); }, [activeCollection, search]);`,
      ``,
      `  const addBookmark = async () => {`,
      `    if (!form.title.trim() || !form.url.trim()) return;`,
      `    await fetch('/api/bookmarks', {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ ...form, tags: form.tags.split(',').map(t => t.trim()).filter(Boolean) }),`,
      `    });`,
      `    setForm({ title: '', url: '', description: '', tags: '', collection: '' });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const togglePin = async (id: string, pinned: boolean) => {`,
      `    await fetch(\`/api/bookmarks/\${id}\`, {`,
      `      method: 'PATCH', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ pinned: !pinned }),`,
      `    });`,
      `    setBookmarks(prev => prev.map(b => b._id === id ? { ...b, pinned: !b.pinned } : b));`,
      `  };`,
      ``,
      `  const deleteBookmark = async (id: string) => {`,
      `    await fetch(\`/api/bookmarks/\${id}\`, { method: 'DELETE' });`,
      `    setBookmarks(prev => prev.filter(b => b._id !== id));`,
      `  };`,
      ``,
      `  const pinned = bookmarks.filter(b => b.pinned);`,
      `  const unpinned = bookmarks.filter(b => !b.pinned);`,
      ``,
      `  return (`,
      `    <div className="flex h-screen overflow-hidden bg-zinc-950 text-zinc-200 font-sans">`,
      `      {sidebarOpen && (`,
      `        <div className="fixed inset-0 z-40 bg-black/60 md:hidden" onClick={() => setSidebarOpen(false)} />`,
      `      )}`,
      ``,
      `      <aside className={clsx(`,
      `        'fixed inset-y-0 left-0 z-50 flex w-64 flex-col border-r border-zinc-800/80 bg-zinc-950 transition-transform duration-200 md:static md:translate-x-0',`,
      `        sidebarOpen ? 'translate-x-0 shadow-2xl' : '-translate-x-full'`,
      `      )}>`,
      `        <div className="flex items-center justify-between border-b border-zinc-800/80 px-4 py-4">`,
      `          <div className="flex items-center gap-2">`,
      `            <BookmarkIcon className="h-4 w-4 text-emerald-400" />`,
      `            <span className="text-sm font-semibold tracking-tight">Bookmarks</span>`,
      `          </div>`,
      `          <button onClick={() => setSidebarOpen(false)} className="rounded-md p-1 text-zinc-500 hover:bg-zinc-800 md:hidden">`,
      `            <X className="h-4 w-4" />`,
      `          </button>`,
      `        </div>`,
      ``,
      `        <nav className="flex-1 space-y-0.5 overflow-y-auto p-2">`,
      `          <button onClick={() => setActiveCollection(null)}`,
      `            className={clsx(`,
      `              'flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-left text-sm transition-colors',`,
      `              !activeCollection ? 'bg-emerald-500/10 text-emerald-400' : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-200'`,
      `            )}>`,
      `            <Globe className="h-4 w-4 shrink-0" />`,
      `            <span className="flex-1">All Bookmarks</span>`,
      `            <span className="text-xs text-zinc-600">{bookmarks.length}</span>`,
      `          </button>`,
      `          {collections.map(c => (`,
      `            <button key={c} onClick={() => { setActiveCollection(c); if (window.innerWidth <= 768) setSidebarOpen(false); }}`,
      `              className={clsx(`,
      `                'flex w-full items-center gap-2.5 rounded-lg px-3 py-2 text-left text-sm transition-colors',`,
      `                activeCollection === c ? 'bg-emerald-500/10 text-emerald-400' : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-200'`,
      `              )}>`,
      `              <Folder className="h-4 w-4 shrink-0" />`,
      `              <span className="flex-1 truncate">{c}</span>`,
      `            </button>`,
      `          ))}`,
      `        </nav>`,
      `      </aside>`,
      ``,
      `      <main className="flex min-w-0 flex-1 flex-col overflow-hidden">`,
      `        <header className="flex shrink-0 items-center gap-3 border-b border-zinc-800/80 px-6 py-3">`,
      `          <button onClick={() => setSidebarOpen(true)} className="rounded-md p-1.5 text-zinc-400 hover:bg-zinc-800 md:hidden">`,
      `            <Menu className="h-5 w-5" />`,
      `          </button>`,
      `          <div className="relative flex-1">`,
      `            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500" />`,
      `            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search bookmarks..."`,
      `              className="w-full rounded-lg border border-zinc-800 bg-zinc-900 py-2 pl-10 pr-4 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-emerald-500/50" />`,
      `          </div>`,
      `          <button onClick={() => setShowAdd(!showAdd)}`,
      `            className={clsx(`,
      `              'flex items-center gap-1.5 rounded-lg px-4 py-2 text-sm font-medium transition-colors',`,
      `              showAdd ? 'bg-zinc-800 text-zinc-300' : 'bg-emerald-600 text-white hover:bg-emerald-500'`,
      `            )}>`,
      `            {showAdd ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}`,
      `            {showAdd ? 'Cancel' : 'Add'}`,
      `          </button>`,
      `        </header>`,
      ``,
      `        {showAdd && (`,
      `          <div className="shrink-0 border-b border-zinc-800/80 bg-zinc-900/50 p-4">`,
      `            <div className="mx-auto grid max-w-2xl gap-3 sm:grid-cols-2">`,
      `              <input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="Title"`,
      `                className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-emerald-500/50" />`,
      `              <input value={form.url} onChange={e => setForm(f => ({ ...f, url: e.target.value }))} placeholder="https://..."`,
      `                className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-emerald-500/50" />`,
      `              <input value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="Description"`,
      `                className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-emerald-500/50 sm:col-span-2" />`,
      `              <input value={form.tags} onChange={e => setForm(f => ({ ...f, tags: e.target.value }))} placeholder="Tags (comma separated)"`,
      `                className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-emerald-500/50" />`,
      `              <div className="flex gap-2">`,
      `                <select value={form.collection} onChange={e => setForm(f => ({ ...f, collection: e.target.value }))}`,
      `                  className="flex-1 rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none focus:border-emerald-500/50">`,
      `                  <option value="">Collection...</option>`,
      `                  {collections.map(c => <option key={c} value={c}>{c}</option>)}`,
      `                </select>`,
      `                <button onClick={addBookmark}`,
      `                  className="rounded-md bg-emerald-600 px-4 py-2 text-sm font-medium text-white hover:bg-emerald-500">`,
      `                  Save`,
      `                </button>`,
      `              </div>`,
      `            </div>`,
      `          </div>`,
      `        )}`,
      ``,
      `        <div className="flex-1 overflow-y-auto p-6">`,
      `          {loading ? (`,
      `            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">`,
      `              {[...Array(6)].map((_, i) => (`,
      `                <div key={i} className="h-36 animate-pulse rounded-xl bg-zinc-900" />`,
      `              ))}`,
      `            </div>`,
      `          ) : bookmarks.length === 0 ? (`,
      `            <div className="flex flex-col items-center justify-center py-20">`,
      `              <BookmarkIcon className="mb-3 h-12 w-12 text-zinc-800" />`,
      `              <p className="text-sm text-zinc-500">{search ? 'No bookmarks match your search' : 'No bookmarks yet — add one!'}</p>`,
      `            </div>`,
      `          ) : (`,
      `            <div className="space-y-6">`,
      `              {pinned.length > 0 && (`,
      `                <div>`,
      `                  <h3 className="mb-3 flex items-center gap-1.5 text-xs font-medium uppercase tracking-wider text-zinc-500">`,
      `                    <Pin className="h-3 w-3" /> Pinned`,
      `                  </h3>`,
      `                  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">`,
      `                    {pinned.map(b => <Card key={b._id} bookmark={b} onPin={togglePin} onDelete={deleteBookmark} />)}`,
      `                  </div>`,
      `                </div>`,
      `              )}`,
      `              <div>`,
      `                {pinned.length > 0 && (`,
      `                  <h3 className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-500">All</h3>`,
      `                )}`,
      `                <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">`,
      `                  {unpinned.map(b => <Card key={b._id} bookmark={b} onPin={togglePin} onDelete={deleteBookmark} />)}`,
      `                </div>`,
      `              </div>`,
      `            </div>`,
      `          )}`,
      `        </div>`,
      `      </main>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
      `function Card({ bookmark: b, onPin, onDelete }: {`,
      `  bookmark: BookmarkItem;`,
      `  onPin: (id: string, pinned: boolean) => void;`,
      `  onDelete: (id: string) => void;`,
      `}) {`,
      `  return (`,
      `    <div className="group relative rounded-xl border border-zinc-800 bg-zinc-900 p-4 transition-colors hover:border-zinc-700">`,
      `      <div className="mb-2 flex items-start justify-between gap-2">`,
      `        <h4 className="text-sm font-medium leading-tight">{b.title}</h4>`,
      `        <div className="flex shrink-0 gap-1">`,
      `          <button onClick={() => onPin(b._id, b.pinned)}`,
      `            className="rounded p-1 text-zinc-600 transition-colors hover:bg-zinc-800 hover:text-emerald-400">`,
      `            {b.pinned ? <PinOff className="h-3.5 w-3.5" /> : <Pin className="h-3.5 w-3.5" />}`,
      `          </button>`,
      `          <button onClick={() => onDelete(b._id)}`,
      `            className="rounded p-1 text-zinc-600 transition-colors hover:bg-zinc-800 hover:text-red-400">`,
      `            <Trash2 className="h-3.5 w-3.5" />`,
      `          </button>`,
      `        </div>`,
      `      </div>`,
      `      <a href={b.url} target="_blank" rel="noopener noreferrer"`,
      `        className="mb-2 flex items-center gap-1 text-xs text-emerald-400/70 hover:text-emerald-400 truncate">`,
      `        <ExternalLink className="h-3 w-3 shrink-0" /> {b.url}`,
      `      </a>`,
      `      {b.description && <p className="mb-3 text-xs leading-relaxed text-zinc-500">{b.description}</p>}`,
      `      {b.tags.length > 0 && (`,
      `        <div className="flex flex-wrap gap-1">`,
      `          {b.tags.map(tag => (`,
      `            <span key={tag} className="inline-flex items-center gap-1 rounded-md bg-zinc-800 px-1.5 py-0.5 text-[10px] text-zinc-400">`,
      `              <Tag className="h-2.5 w-2.5" /> {tag}`,
      `            </span>`,
      `          ))}`,
      `        </div>`,
      `      )}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `@import "tailwindcss";`,
      ``,
      `@theme {`,
      `  --font-sans: 'Inter', system-ui, -apple-system, sans-serif;`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const mernBasic: StackTemplate = {
  id: 'mern-basic',
  stackId: 'mern',
  tier: 'basic',
  name: 'MERN Basic',
  description: 'Bookmark collection manager — MongoDB-style documents, tags, search',
  features: [
    'MongoDB-style document collections',
    'Collection sidebar with filtering',
    'Tag-based organization',
    'Full-text search',
    'Pin/unpin bookmarks',
    'Card grid layout',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Mongoose ODM + Zod validation
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-solid',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: {
          react: '^19.2.0', 'react-dom': '^19.2.0',
          zod: '^4.3.0',
          'lucide-react': '^0.513.0', clsx: '^2.1.1',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^5.1.0',
          '@tailwindcss/vite': '^4.1.0', tailwindcss: '^4.1.0',
          typescript: '^5.9.0', vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      ``,
      `/* ── Zod Schemas ── */`,
      `const CreateBookmarkSchema = z.object({`,
      `  title: z.string().min(1).max(200),`,
      `  url: z.string().url('Must be a valid URL'),`,
      `  description: z.string().max(500).optional().default(''),`,
      `  tags: z.array(z.string().max(30)).max(10).optional().default([]),`,
      `  collection: z.string().max(50).optional().default('Unsorted'),`,
      `});`,
      `const UpdateBookmarkSchema = z.object({`,
      `  title: z.string().min(1).max(200).optional(),`,
      `  url: z.string().url().optional(),`,
      `  description: z.string().max(500).optional(),`,
      `  tags: z.array(z.string()).optional(),`,
      `  pinned: z.boolean().optional(),`,
      `  collection: z.string().max(50).optional(),`,
      `});`,
      ``,
      `interface Bookmark { _id: string; title: string; url: string; description: string; tags: string[]; collection: string; pinned: boolean; createdAt: string; }`,
      `let idCounter = 10;`,
      `function objectId() { return (idCounter++).toString(16).padStart(24, '0'); }`,
      `const collections = ['Dev Tools', 'Reading', 'Design'];`,
      `const bookmarks: Bookmark[] = [`,
      `  { _id: objectId(), title: 'React Docs', url: 'https://react.dev', description: 'Official React documentation', tags: ['react', 'docs'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'MDN Web Docs', url: 'https://developer.mozilla.org', description: 'Web technology reference', tags: ['mdn'], collection: 'Dev Tools', pinned: false, createdAt: new Date().toISOString() },`,
      `  { _id: objectId(), title: 'TypeScript Handbook', url: 'https://www.typescriptlang.org/docs', description: 'Learn TypeScript', tags: ['typescript'], collection: 'Dev Tools', pinned: true, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'mern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = new URL(req.url || '', 'http://localhost');`,
      `        const path = url.pathname;`,
      `        try {`,
      `          if (path === '/api/health') return json(res, { status: 'ok', documents: bookmarks.length });`,
      `          if (path === '/api/collections' && req.method === 'GET') return json(res, collections);`,
      `          if (path === '/api/bookmarks' && req.method === 'GET') {`,
      `            let result = [...bookmarks];`,
      `            const col = url.searchParams.get('collection');`,
      `            const q = url.searchParams.get('q')?.toLowerCase();`,
      `            const tag = url.searchParams.get('tag');`,
      `            if (col) result = result.filter(b => b.collection === col);`,
      `            if (tag) result = result.filter(b => b.tags.includes(tag));`,
      `            if (q) result = result.filter(b => b.title.toLowerCase().includes(q) || b.description.toLowerCase().includes(q));`,
      `            return json(res, result.sort((a, b) => (b.pinned ? 1 : 0) - (a.pinned ? 1 : 0)));`,
      `          }`,
      `          if (path === '/api/bookmarks' && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateBookmarkSchema.parse(body);`,
      `            const doc: Bookmark = { _id: objectId(), ...parsed, pinned: false, createdAt: new Date().toISOString() };`,
      `            bookmarks.push(doc);`,
      `            if (!collections.includes(doc.collection)) collections.push(doc.collection);`,
      `            return json(res, doc, 201);`,
      `          }`,
      `          const m = path.match(/^\\/api\\/bookmarks\\/(.+)$/);`,
      `          if (m) {`,
      `            if (req.method === 'PATCH') { const u = UpdateBookmarkSchema.parse(await parseBody(req)); const d = bookmarks.find(x => x._id === m[1]); if (d) Object.assign(d, u); return json(res, d); }`,
      `            if (req.method === 'DELETE') { const idx = bookmarks.findIndex(x => x._id === m[1]); if (idx !== -1) bookmarks.splice(idx, 1); return json(res, { ok: true }); }`,
      `          }`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', details: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: [
      `# MongoDB connection (for production)`,
      `# MONGODB_URI="mongodb://localhost:27017/mern_app"`,
      ``,
      `# Server`,
      `PORT=3000`,
      ``,
    ].join('\n'),
  },
];

const mernSolid: StackTemplate = {
  id: 'mern-solid',
  stackId: 'mern',
  tier: 'solid',
  name: 'MERN Solid',
  description: 'Validated documents — Zod schemas on all inputs',
  features: [
    'Zod schema validation (URL, length, types)',
    'Document CRUD with type safety',
    'Partial update validation',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER — Docker + Tests + CI
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          'docker:build': 'docker build -t mern-app .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
        },
        dependencies: { react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0' },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^5.1.0', typescript: '^5.9.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `services:`,
      `  mongo:`,
      `    image: mongo:7`,
      `    ports:`,
      `      - '27017:27017'`,
      `    volumes:`,
      `      - mongodata:/data/db`,
      `    healthcheck:`,
      `      test: mongosh --eval "db.runCommand('ping').ok"`,
      `      interval: 5s`,
      `      timeout: 5s`,
      `      retries: 5`,
      `  app:`,
      `    build: .`,
      `    ports:`,
      `      - '3000:3000'`,
      `    depends_on:`,
      `      mongo:`,
      `        condition: service_healthy`,
      `    environment:`,
      `      MONGODB_URI: mongodb://mongo:27017/mern_app`,
      `volumes:`,
      `  mongodata:`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: [
      `import { defineConfig } from 'vitest/config';`,
      `export default defineConfig({ test: { globals: true, environment: 'node', include: ['__tests__/**/*.test.ts'] } });`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateSchema = z.object({ title: z.string().min(1), url: z.string().url(), tags: z.array(z.string()).optional() });`,
      ``,
      `describe('MERN Bookmark API', () => {`,
      `  it('validates bookmark creation', () => {`,
      `    expect(() => CreateSchema.parse({ title: '', url: '' })).toThrow();`,
      `    expect(() => CreateSchema.parse({ title: 'Test', url: 'not-url' })).toThrow();`,
      `    expect(CreateSchema.parse({ title: 'React', url: 'https://react.dev' })).toBeDefined();`,
      `  });`,
      `  it('handles tag arrays', () => {`,
      `    const result = CreateSchema.parse({ title: 'Test', url: 'https://test.com', tags: ['a', 'b'] });`,
      `    expect(result.tags).toEqual(['a', 'b']);`,
      `  });`,
      `  it('bookmark search filters', () => {`,
      `    const docs = [{ title: 'React Docs' }, { title: 'Vue Guide' }];`,
      `    expect(docs.filter(d => d.title.toLowerCase().includes('react'))).toHaveLength(1);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      `  docker:`,
      `    needs: test`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - run: docker build -t mern-app .`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# MERN Bookmarks — Battle-Tested`,
      ``,
      `Production-ready bookmark manager with MongoDB, Express, React, and Node.js.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `## Testing`,
      `\`\`\`bash`,
      `npm test`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const mernBattleTested: StackTemplate = {
  id: 'mern-battle-tested',
  stackId: 'mern',
  tier: 'battle-tested',
  name: 'MERN Battle-Tested',
  description: 'Deployment ready — Docker, MongoDB, tests, CI/CD',
  features: [
    'Docker + Docker Compose with MongoDB 7',
    'Vitest test suite',
    'GitHub Actions CI pipeline',
    'Multi-stage Docker build',
    'Everything from Solid tier',
  ],
  files: mergeFiles(mernSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER — Premium monitoring & patterns
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'mern-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          'docker:build': 'docker build -t mern-vai .',
          'docker:up': 'docker compose up -d', 'docker:down': 'docker compose down',
          lint: 'tsc --noEmit',
        },
        dependencies: { react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0' },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^5.1.0', typescript: '^5.9.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build && npm prune --production`,
      ``,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'mern-vai', version: '1.0.0', stack: 'mern', tier: 'vai',`,
      `  features: { monitoring: true, errorBoundary: true },`,
      `  database: { provider: 'mongodb' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 MERN Bookmarks — Vai Premium`,
      ``,
      `> VeggaAI's curated MERN bookmark manager.`,
      ``,
      `## Features`,
      `- 📚 MongoDB-style document collections with search`,
      `- ✅ Zod validation on all inputs`,
      `- 🐳 Optimized Docker build (non-root, healthcheck)`,
      `- 🧪 Vitest test suite`,
      `- 🔄 CI/CD pipeline`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

const mernVai: StackTemplate = {
  id: 'mern-vai',
  stackId: 'mern',
  tier: 'vai',
  name: 'MERN Vai',
  description: "VeggaAI's premium MERN — optimized Docker, monitoring",
  features: [
    'Optimized multi-stage Docker (non-root, healthcheck)',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(mernBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const mernStack: StackDefinition = {
  id: 'mern',
  name: 'MERN',
  tagline: 'Document-driven full stack',
  description: 'MongoDB + Express + React + Node.js — flexible NoSQL stack',
  techStack: ['MongoDB', 'Express', 'React', 'Node.js'],
  icon: '🍃',
  color: 'green',
  templates: [mernBasic, mernSolid, mernBattleTested, mernVai],
};
