/**
 * Next.js Full-Stack — App Router + API Routes + Server Components
 * All four tiers: Basic notes dashboard → Vai premium.
 *
 * Basic uses in-memory API routes. Solid adds Prisma + Zod.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Notes Dashboard with App Router
   Server Components + API Routes + client interactivity
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-fullstack',
        private: true,
        scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
        dependencies: { next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0', 'lucide-react': '^0.513.0', clsx: '^2.1.1' },
        devDependencies: { '@types/react': '^19.0.0', '@types/node': '^22.0.0', typescript: '^5.9.0', '@tailwindcss/postcss': '^4.1.0', tailwindcss: '^4.1.0', postcss: '^8.5.0' },
      },
      null,
      2,
    ),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', lib: ['dom', 'ES2022'], module: 'ESNext',
          moduleResolution: 'bundler', jsx: 'preserve', strict: true,
          esModuleInterop: true, skipLibCheck: true,
          plugins: [{ name: 'next' }], paths: { '@/*': ['./src/*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    ),
  },
  {
    path: 'postcss.config.mjs',
    content: [
      `export default {`,
      `  plugins: {`,
      `    '@tailwindcss/postcss': {},`,
      `  },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'next.config.ts',
    content: [
      `import type { NextConfig } from 'next';`,
      `const config: NextConfig = {};`,
      `export default config;`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/layout.tsx',
    content: [
      `import type { Metadata } from 'next';`,
      `import './globals.css';`,
      ``,
      `export const metadata: Metadata = { title: 'Next.js Notes', description: 'Built with Vai' };`,
      ``,
      `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
      `  return (`,
      `    <html lang="en">`,
      `      <head><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" /></head>`,
      `      <body>{children}</body>`,
      `    </html>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/globals.css',
    content: [
      `@import "tailwindcss";`,
      ``,
      `@theme {`,
      `  --font-sans: 'Inter', system-ui, -apple-system, sans-serif;`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/page.tsx',
    content: [
      `'use client';`,
      ``,
      `import { useState, useEffect } from 'react';`,
      `import { StickyNote, Search, Plus, Trash2, X, Tag, FileText, CalendarDays, Sparkles } from 'lucide-react';`,
      `import clsx from 'clsx';`,
      ``,
      `interface Note {`,
      `  id: number; title: string; content: string;`,
      `  category: string; createdAt: string;`,
      `}`,
      ``,
      `interface Stats { total: number; categories: number; today: number; }`,
      ``,
      `export default function NotesPage() {`,
      `  const [notes, setNotes] = useState<Note[]>([]);`,
      `  const [stats, setStats] = useState<Stats>({ total: 0, categories: 0, today: 0 });`,
      `  const [search, setSearch] = useState('');`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ title: '', content: '', category: '' });`,
      `  const [loading, setLoading] = useState(true);`,
      ``,
      `  const load = async () => {`,
      `    const params = search ? \`?search=\${encodeURIComponent(search)}\` : '';`,
      `    const [notesRes, statsRes] = await Promise.all([`,
      `      fetch(\`/api/notes\${params}\`),`,
      `      fetch('/api/notes?stats=true'),`,
      `    ]);`,
      `    setNotes(await notesRes.json());`,
      `    const s = await statsRes.json();`,
      `    setStats({ total: s.total ?? 0, categories: s.categories ?? 0, today: s.today ?? 0 });`,
      `    setLoading(false);`,
      `  };`,
      ``,
      `  useEffect(() => { load(); }, [search]);`,
      ``,
      `  const addNote = async () => {`,
      `    if (!form.title.trim()) return;`,
      `    await fetch('/api/notes', {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify(form),`,
      `    });`,
      `    setForm({ title: '', content: '', category: '' });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const deleteNote = async (id: number) => {`,
      `    await fetch(\`/api/notes/\${id}\`, { method: 'DELETE' });`,
      `    setNotes(prev => prev.filter(n => n.id !== id));`,
      `    setStats(s => ({ ...s, total: s.total - 1 }));`,
      `  };`,
      ``,
      `  const CATEGORIES = ['Work', 'Personal', 'Ideas', 'Learning'];`,
      `  const categoryColors: Record<string, string> = {`,
      `    Work: 'bg-blue-500/15 text-blue-400',`,
      `    Personal: 'bg-emerald-500/15 text-emerald-400',`,
      `    Ideas: 'bg-amber-500/15 text-amber-400',`,
      `    Learning: 'bg-violet-500/15 text-violet-400',`,
      `  };`,
      ``,
      `  return (`,
      `    <div className="mx-auto min-h-screen max-w-5xl px-6 py-10 font-sans">`,
      `      <div className="mb-8">`,
      `        <h1 className="text-2xl font-bold tracking-tight">Notes</h1>`,
      `        <p className="mt-1 text-sm text-zinc-500">Capture ideas, track progress, stay organized</p>`,
      `      </div>`,
      ``,
      `      <div className="mb-6 grid grid-cols-3 gap-3">`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-2 text-xs text-zinc-500">`,
      `            <FileText className="h-3.5 w-3.5" /> Total`,
      `          </div>`,
      `          <p className="mt-1 text-2xl font-bold text-violet-400">{stats.total}</p>`,
      `        </div>`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-2 text-xs text-zinc-500">`,
      `            <Tag className="h-3.5 w-3.5" /> Categories`,
      `          </div>`,
      `          <p className="mt-1 text-2xl font-bold text-emerald-400">{stats.categories}</p>`,
      `        </div>`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-2 text-xs text-zinc-500">`,
      `            <CalendarDays className="h-3.5 w-3.5" /> Today`,
      `          </div>`,
      `          <p className="mt-1 text-2xl font-bold text-amber-400">{stats.today}</p>`,
      `        </div>`,
      `      </div>`,
      ``,
      `      <div className="mb-4 flex gap-2">`,
      `        <div className="relative flex-1">`,
      `          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-500" />`,
      `          <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search notes..."`,
      `            className="w-full rounded-lg border border-zinc-800 bg-zinc-900 py-2.5 pl-10 pr-4 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-violet-500/50" />`,
      `        </div>`,
      `        <button onClick={() => setShowAdd(!showAdd)}`,
      `          className={clsx(`,
      `            'flex items-center gap-1.5 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors',`,
      `            showAdd ? 'bg-zinc-800 text-zinc-300' : 'bg-violet-600 text-white hover:bg-violet-500'`,
      `          )}>`,
      `          {showAdd ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}`,
      `          {showAdd ? 'Cancel' : 'New Note'}`,
      `        </button>`,
      `      </div>`,
      ``,
      `      {showAdd && (`,
      `        <div className="mb-6 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">`,
      `          <div className="grid gap-3 sm:grid-cols-2">`,
      `            <input value={form.title} onChange={e => setForm(f => ({ ...f, title: e.target.value }))} placeholder="Title"`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-violet-500/50" />`,
      `            <select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none focus:border-violet-500/50">`,
      `              <option value="">Category...</option>`,
      `              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}`,
      `            </select>`,
      `            <textarea value={form.content} onChange={e => setForm(f => ({ ...f, content: e.target.value }))}`,
      `              placeholder="Write your note..." rows={3}`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-violet-500/50 sm:col-span-2" />`,
      `          </div>`,
      `          <div className="mt-3 flex justify-end">`,
      `            <button onClick={addNote} className="rounded-md bg-violet-600 px-4 py-2 text-sm font-medium text-white hover:bg-violet-500">`,
      `              Save Note`,
      `            </button>`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      ``,
      `      {loading ? (`,
      `        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">`,
      `          {[...Array(6)].map((_, i) => <div key={i} className="h-40 animate-pulse rounded-xl bg-zinc-900" />)}`,
      `        </div>`,
      `      ) : notes.length === 0 ? (`,
      `        <div className="flex flex-col items-center justify-center py-20">`,
      `          <Sparkles className="mb-3 h-12 w-12 text-zinc-800" />`,
      `          <p className="text-sm text-zinc-500">{search ? 'No notes match your search' : 'No notes yet — create one!'}</p>`,
      `        </div>`,
      `      ) : (`,
      `        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">`,
      `          {notes.map(n => (`,
      `            <div key={n.id} className="group rounded-xl border border-zinc-800 bg-zinc-900 p-4 transition-colors hover:border-zinc-700">`,
      `              <div className="mb-2 flex items-start justify-between">`,
      `                <div className="flex items-center gap-2">`,
      `                  {n.category && (`,
      `                    <span className={clsx('rounded-md px-2 py-0.5 text-[10px] font-medium', categoryColors[n.category] ?? 'bg-zinc-800 text-zinc-400')}>`,
      `                      {n.category}`,
      `                    </span>`,
      `                  )}`,
      `                </div>`,
      `                <button onClick={() => deleteNote(n.id)}`,
      `                  className="rounded p-1 text-zinc-600 opacity-0 transition-all hover:bg-zinc-800 hover:text-red-400 group-hover:opacity-100">`,
      `                  <Trash2 className="h-3.5 w-3.5" />`,
      `                </button>`,
      `              </div>`,
      `              <h3 className="mb-1 text-sm font-medium">{n.title}</h3>`,
      `              <p className="text-xs leading-relaxed text-zinc-500 line-clamp-3">{n.content}</p>`,
      `              <p className="mt-3 text-[10px] text-zinc-600">{new Date(n.createdAt).toLocaleDateString()}</p>`,
      `            </div>`,
      `          ))}`,
      `        </div>`,
      `      )}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `interface Note { id: number; title: string; body: string; category: string; createdAt: string; }`,
      ``,
      `const notes: Note[] = [`,
      `  { id: 1, title: 'Getting Started with Next.js', body: 'App Router provides a new way to build applications using React Server Components. It supports layouts, nested routing, and more.', category: 'Framework', createdAt: new Date().toISOString() },`,
      `  { id: 2, title: 'API Routes are powerful', body: 'Create RESTful API endpoints directly in your Next.js app using route handlers. Supports GET, POST, PUT, DELETE, and more.', category: 'Backend', createdAt: new Date().toISOString() },`,
      `  { id: 3, title: 'Server Components', body: 'React Server Components render on the server, reducing client-side JavaScript and improving performance.', category: 'Framework', createdAt: new Date().toISOString() },`,
      `  { id: 4, title: 'TypeScript everywhere', body: 'Next.js has first-class TypeScript support with automatic type checking in API routes and page components.', category: 'DX', createdAt: new Date().toISOString() },`,
      `];`,
      `let nextId = 5;`,
      ``,
      `export async function GET(request: Request) {`,
      `  const { searchParams } = new URL(request.url);`,
      `  const q = searchParams.get('q')?.toLowerCase();`,
      `  let result = [...notes];`,
      `  if (q) result = result.filter(n => n.title.toLowerCase().includes(q) || n.body.toLowerCase().includes(q));`,
      `  return NextResponse.json(result);`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const body = await request.json();`,
      `  const note: Note = { id: nextId++, title: body.title, body: body.body || '', category: body.category || 'General', createdAt: new Date().toISOString() };`,
      `  notes.push(note);`,
      `  return NextResponse.json(note, { status: 201 });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/[id]/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `// Note: shares state with parent route in dev mode`,
      `export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  const body = await request.json();`,
      `  return NextResponse.json({ id: parseInt(id), ...body });`,
      `}`,
      ``,
      `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  return NextResponse.json({ ok: true, deleted: id });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/health/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `export async function GET() {`,
      `  return NextResponse.json({ status: 'ok', framework: 'next.js', timestamp: new Date().toISOString() });`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const nextjsBasic: StackTemplate = {
  id: 'nextjs-basic',
  stackId: 'nextjs',
  tier: 'basic',
  name: 'Next.js Basic',
  description: 'Notes dashboard — App Router, API Routes, stats cards, search',
  features: [
    'Next.js 16 App Router',
    'API Route handlers (GET, POST, DELETE)',
    'Notes grid with categories',
    'Dashboard stats cards',
    'Full-text search',
    'TypeScript + Server Components',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Prisma + Zod + Server Actions
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-solid',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
          'lucide-react': '^0.513.0', clsx: '^2.1.1',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0',
          '@tailwindcss/postcss': '^4.1.0', tailwindcss: '^4.1.0', postcss: '^8.5.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client { provider = "prisma-client-js" }`,
      `datasource db { provider = "sqlite"; url = "file:./dev.db" }`,
      ``,
      `model Note {`,
      `  id        Int      @id @default(autoincrement())`,
      `  title     String`,
      `  body      String   @default("")`,
      `  category  String   @default("General")`,
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const CreateNoteSchema = z.object({ title: z.string().min(1).max(200), body: z.string().max(5000).optional(), category: z.string().max(50).optional() });`,
      ``,
      `export async function GET(request: Request) {`,
      `  const { searchParams } = new URL(request.url);`,
      `  const q = searchParams.get('q');`,
      `  const notes = await prisma.note.findMany({`,
      `    where: q ? { OR: [{ title: { contains: q } }, { body: { contains: q } }] } : undefined,`,
      `    orderBy: { createdAt: 'desc' },`,
      `  });`,
      `  return NextResponse.json(notes);`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  try {`,
      `    const body = await request.json();`,
      `    const parsed = CreateNoteSchema.parse(body);`,
      `    const note = await prisma.note.create({ data: { title: parsed.title, body: parsed.body || '', category: parsed.category || 'General' } });`,
      `    return NextResponse.json(note, { status: 201 });`,
      `  } catch (err) {`,
      `    if (err instanceof z.ZodError) return NextResponse.json({ error: 'Validation failed', details: err.issues }, { status: 400 });`,
      `    return NextResponse.json({ error: (err as Error).message }, { status: 500 });`,
      `  }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/[id]/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const UpdateNoteSchema = z.object({ title: z.string().min(1).max(200).optional(), body: z.string().max(5000).optional(), category: z.string().max(50).optional() });`,
      ``,
      `export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  const body = await request.json();`,
      `  const parsed = UpdateNoteSchema.parse(body);`,
      `  const note = await prisma.note.update({ where: { id: parseInt(id) }, data: parsed });`,
      `  return NextResponse.json(note);`,
      `}`,
      ``,
      `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  await prisma.note.delete({ where: { id: parseInt(id) } });`,
      `  return NextResponse.json({ ok: true });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# Switch to PostgreSQL for production\n# DATABASE_URL="postgresql://..."\nDATABASE_URL="file:./prisma/dev.db"\n`,
  },
];

const nextjsSolid: StackTemplate = {
  id: 'nextjs-solid',
  stackId: 'nextjs',
  tier: 'solid',
  name: 'Next.js Solid',
  description: 'Production patterns — Prisma ORM + Zod validation',
  features: [
    'Prisma ORM with auto-migration',
    'Zod schema validation',
    'Type-safe API routes',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client { provider = "prisma-client-js" }`,
      `datasource db { provider = "postgresql"; url = env("DATABASE_URL") }`,
      ``,
      `model Note {`,
      `  id        Int      @id @default(autoincrement())`,
      `  title     String`,
      `  body      String   @default("")`,
      `  category  String   @default("General")`,
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# PostgreSQL (used by docker-compose)\nDATABASE_URL="postgresql://nextjs:nextjs_secret@localhost:5432/nextjs_app"\n`,
  },
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-battle-tested',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t nextjs-app .',
          'docker:up': 'docker compose up -d',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/.next ./.next`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["npm", "start"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: nextjs_app`,
      `      POSTGRES_USER: nextjs`,
      `      POSTGRES_PASSWORD: nextjs_secret`,
      `    ports: ['5432:5432']`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U nextjs']`,
      `      interval: 5s`,
      `  app:`,
      `    build: .`,
      `    ports: ['3000:3000']`,
      `    depends_on:`,
      `      db: { condition: service_healthy }`,
      `    environment:`,
      `      DATABASE_URL: postgresql://nextjs:nextjs_secret@db:5432/nextjs_app`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: `import { defineConfig } from 'vitest/config';\nexport default defineConfig({ test: { globals: true, include: ['__tests__/**/*.test.ts'] } });\n`,
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const NoteSchema = z.object({ title: z.string().min(1).max(200), body: z.string().optional(), category: z.string().optional() });`,
      ``,
      `describe('Next.js Notes API', () => {`,
      `  it('validates note creation', () => {`,
      `    expect(() => NoteSchema.parse({ title: '' })).toThrow();`,
      `    expect(NoteSchema.parse({ title: 'Test' })).toHaveProperty('title', 'Test');`,
      `  });`,
      `  it('search filters notes', () => {`,
      `    const notes = [{ title: 'React Guide' }, { title: 'Vue Guide' }];`,
      `    expect(notes.filter(n => n.title.includes('React'))).toHaveLength(1);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# Next.js Notes — Battle-Tested`,
      ``,
      `Production-ready notes dashboard with Next.js 16, Prisma, and Docker.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const nextjsBattleTested: StackTemplate = {
  id: 'nextjs-battle-tested',
  stackId: 'nextjs',
  tier: 'battle-tested',
  name: 'Next.js Battle-Tested',
  description: 'Deployment ready — Docker, tests, CI/CD',
  features: [
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite',
    'GitHub Actions CI',
    'Multi-stage Docker build',
    'Everything from Solid tier',
  ],
  files: mergeFiles(nextjsSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-vai',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t nextjs-vai .',
          'docker:up': 'docker compose up -d',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/.next ./.next`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["npm", "start"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'nextjs-vai', version: '1.0.0', stack: 'nextjs', tier: 'vai',`,
      `  features: { serverComponents: true, edgeReady: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 Next.js Notes — Vai Premium`,
      ``,
      `> VeggaAI's curated Next.js notes dashboard.`,
      ``,
      `## Features`,
      `- ▲ Next.js 16 App Router + Server Components`,
      `- 📝 Notes dashboard with stats, search, categories`,
      `- 🗄️ Prisma ORM + Zod validation`,
      `- 🐳 Optimized Docker (non-root, healthcheck)`,
      `- 🧪 Vitest + CI/CD`,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

const nextjsVai: StackTemplate = {
  id: 'nextjs-vai',
  stackId: 'nextjs',
  tier: 'vai',
  name: 'Next.js Vai',
  description: "VeggaAI's premium Next.js — optimized Docker, monitoring",
  features: [
    'Optimized Docker (non-root, healthcheck)',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(nextjsBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const nextjsStack: StackDefinition = {
  id: 'nextjs',
  name: 'Next.js',
  tagline: 'The React framework for the web',
  description: 'Next.js 16 with App Router, API routes, and Server Components',
  techStack: ['Next.js', 'React', 'TypeScript', 'Vercel'],
  icon: '▲',
  color: 'zinc',
  templates: [nextjsBasic, nextjsSolid, nextjsBattleTested, nextjsVai],
};
