/**
 * Next.js Full-Stack — App Router + API Routes + Tailwind
 * Basic tier available, higher tiers coming soon.
 */

import type { StackDefinition, StackTemplate } from './types.js';

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-fullstack',
        private: true,
        scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
        dependencies: {
          next: '^15.0.0',
          react: '^19.0.0',
          'react-dom': '^19.0.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/node': '^22.0.0',
          typescript: '^5.7.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          lib: ['dom', 'ES2022'],
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'preserve',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          plugins: [{ name: 'next' }],
          paths: { '@/*': ['./src/*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    ),
  },
  {
    path: 'next.config.ts',
    content: [
      `import type { NextConfig } from 'next';`,
      `const config: NextConfig = {};`,
      `export default config;`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/layout.tsx',
    content: [
      `import type { Metadata } from 'next';`,
      ``,
      `export const metadata: Metadata = { title: 'Next.js Full-Stack', description: 'Built with Vai' };`,
      ``,
      `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
      `  return (`,
      `    <html lang="en">`,
      `      <body style={{ fontFamily: 'system-ui, sans-serif', background: '#09090b', color: '#e4e4e7', margin: 0 }}>`,
      `        {children}`,
      `      </body>`,
      `    </html>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/page.tsx',
    content: [
      `'use client';`,
      `import { useEffect, useState } from 'react';`,
      ``,
      `interface Todo { id: number; text: string; done: boolean; }`,
      ``,
      `export default function Home() {`,
      `  const [todos, setTodos] = useState<Todo[]>([]);`,
      `  const [text, setText] = useState('');`,
      ``,
      `  useEffect(() => { fetch('/api/todos').then(r => r.json()).then(setTodos); }, []);`,
      ``,
      `  const add = async () => {`,
      `    if (!text.trim()) return;`,
      `    const r = await fetch('/api/todos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) });`,
      `    setTodos([...todos, await r.json()]); setText('');`,
      `  };`,
      ``,
      `  return (`,
      `    <main style={{ maxWidth: 600, margin: '60px auto', padding: '0 20px' }}>`,
      `      <h1 style={{ fontSize: '2rem', marginBottom: 4 }}>▲ Next.js Todos</h1>`,
      `      <p style={{ color: '#71717a', fontSize: '0.875rem', marginBottom: 32 }}>Full-Stack · App Router · API Routes</p>`,
      `      <div style={{ display: 'flex', gap: 8, marginBottom: 24 }}>`,
      `        <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()}`,
      `          placeholder="Add a todo..." style={{ flex: 1, padding: '10px 14px', borderRadius: 8, border: '1px solid #27272a', background: '#18181b', color: '#e4e4e7' }} />`,
      `        <button onClick={add} style={{ padding: '10px 20px', borderRadius: 8, background: '#000', color: '#fff', border: '1px solid #333', fontWeight: 600, cursor: 'pointer' }}>Add</button>`,
      `      </div>`,
      `      <ul style={{ listStyle: 'none', padding: 0 }}>`,
      `        {todos.map(t => (`,
      `          <li key={t.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '10px 0', borderBottom: '1px solid #27272a' }}>`,
      `            <input type="checkbox" checked={t.done} onChange={async () => {`,
      `              await fetch(\`/api/todos/\${t.id}\`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ done: !t.done }) });`,
      `              setTodos(todos.map(x => x.id === t.id ? { ...x, done: !x.done } : x));`,
      `            }} />`,
      `            <span style={{ flex: 1, textDecoration: t.done ? 'line-through' : 'none', color: t.done ? '#52525b' : '#e4e4e7' }}>{t.text}</span>`,
      `          </li>`,
      `        ))}`,
      `      </ul>`,
      `    </main>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/todos/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `interface Todo { id: number; text: string; done: boolean; }`,
      `let todos: Todo[] = [`,
      `  { id: 1, text: 'Try Next.js App Router', done: true },`,
      `  { id: 2, text: 'Build API routes', done: false },`,
      `];`,
      `let nextId = 3;`,
      ``,
      `export async function GET() {`,
      `  return NextResponse.json(todos);`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const { text } = await request.json();`,
      `  const todo: Todo = { id: nextId++, text, done: false };`,
      `  todos.push(todo);`,
      `  return NextResponse.json(todo, { status: 201 });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/todos/[id]/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `// Re-use the in-memory store from the parent route`,
      `// In production, use a database`,
      ``,
      `export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  const body = await request.json();`,
      `  return NextResponse.json({ id: parseInt(id), ...body });`,
      `}`,
      ``,
      `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  return NextResponse.json({ ok: true, deleted: id });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/health/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `export async function GET() {`,
      `  return NextResponse.json({ status: 'ok', framework: 'next.js', timestamp: new Date().toISOString() });`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const nextjsBasic: StackTemplate = {
  id: 'nextjs-basic',
  stackId: 'nextjs',
  tier: 'basic',
  name: 'Next.js Basic',
  description: 'Minimal Next.js 15 with App Router and API routes',
  features: ['Next.js 15 App Router', 'API Routes', 'TypeScript', 'Server Components', 'In-memory data'],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

const comingSoon = (tier: 'solid' | 'battle-tested' | 'vai'): StackTemplate => ({
  id: `nextjs-${tier}`,
  stackId: 'nextjs',
  tier,
  name: `Next.js ${tier === 'battle-tested' ? 'Battle-Tested' : tier === 'vai' ? 'Vai' : 'Solid'}`,
  description: 'Coming soon',
  features: ['Coming soon — check back for updates'],
  files: [],
  hasDocker: tier === 'battle-tested' || tier === 'vai',
  hasTests: tier === 'battle-tested' || tier === 'vai',
  comingSoon: true,
});

export const nextjsStack: StackDefinition = {
  id: 'nextjs',
  name: 'Next.js',
  tagline: 'The React framework for the web',
  description: 'Next.js 15 with App Router, API routes, and Server Components',
  techStack: ['Next.js', 'React', 'TypeScript', 'Vercel'],
  icon: '▲',
  color: 'zinc',
  templates: [nextjsBasic, comingSoon('solid'), comingSoon('battle-tested'), comingSoon('vai')],
};
