/**
 * Next.js Full-Stack — App Router + API Routes + Server Components
 * All four tiers: Basic notes dashboard → Vai premium.
 *
 * Basic uses in-memory API routes. Solid adds Prisma + Zod.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Notes Dashboard with App Router
   Server Components + API Routes + client interactivity
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-fullstack',
        private: true,
        scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
        dependencies: { next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0' },
        devDependencies: { '@types/react': '^19.0.0', '@types/node': '^22.0.0', typescript: '^5.9.0' },
      },
      null,
      2,
    ),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', lib: ['dom', 'ES2022'], module: 'ESNext',
          moduleResolution: 'bundler', jsx: 'preserve', strict: true,
          esModuleInterop: true, skipLibCheck: true,
          plugins: [{ name: 'next' }], paths: { '@/*': ['./src/*'] },
        },
        include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
        exclude: ['node_modules'],
      },
      null,
      2,
    ),
  },
  {
    path: 'next.config.ts',
    content: [
      `import type { NextConfig } from 'next';`,
      `const config: NextConfig = {};`,
      `export default config;`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/layout.tsx',
    content: [
      `import type { Metadata } from 'next';`,
      `import './globals.css';`,
      ``,
      `export const metadata: Metadata = { title: 'Next.js Notes', description: 'Built with Vai' };`,
      ``,
      `export default function RootLayout({ children }: { children: React.ReactNode }) {`,
      `  return (`,
      `    <html lang="en">`,
      `      <head><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" /></head>`,
      `      <body>{children}</body>`,
      `    </html>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/globals.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: 'Inter', system-ui, sans-serif; background: #09090b; color: #e4e4e7; -webkit-font-smoothing: antialiased; }`,
      `a { color: inherit; text-decoration: none; }`,
      ``,
      `/* Layout */`,
      `.dashboard { max-width: 1000px; margin: 0 auto; padding: 40px 24px; }`,
      `.header { margin-bottom: 32px; }`,
      `.header h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 4px; }`,
      `.header p { color: #71717a; font-size: 0.875rem; }`,
      ``,
      `/* Stats row */`,
      `.stats { display: flex; gap: 12px; margin-bottom: 24px; }`,
      `.stat-card { flex: 1; background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; }`,
      `.stat-card .label { font-size: 0.75rem; color: #71717a; text-transform: uppercase; letter-spacing: 0.05em; }`,
      `.stat-card .value { font-size: 1.5rem; font-weight: 700; margin-top: 4px; }`,
      `.stat-card .value.blue { color: #60a5fa; }`,
      `.stat-card .value.green { color: #4ade80; }`,
      `.stat-card .value.amber { color: #fbbf24; }`,
      ``,
      `/* Toolbar */`,
      `.toolbar { display: flex; gap: 8px; margin-bottom: 16px; }`,
      `.toolbar input { flex: 1; padding: 10px 14px; border-radius: 8px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.9rem; outline: none; }`,
      `.toolbar input:focus { border-color: #3b82f6; }`,
      `.btn { padding: 10px 20px; border-radius: 8px; background: #18181b; color: #e4e4e7; border: 1px solid #27272a; font-weight: 500; cursor: pointer; white-space: nowrap; transition: all 0.15s; }`,
      `.btn:hover { background: #27272a; }`,
      `.btn-primary { background: #2563eb; color: #fff; border-color: #2563eb; }`,
      `.btn-primary:hover { background: #1d4ed8; }`,
      ``,
      `/* Notes grid */`,
      `.notes-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 12px; }`,
      `.note-card { background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; transition: border-color 0.15s; cursor: default; }`,
      `.note-card:hover { border-color: #27272a; }`,
      `.note-card .title { font-size: 0.95rem; font-weight: 600; margin-bottom: 6px; }`,
      `.note-card .body { font-size: 0.85rem; color: #a1a1aa; line-height: 1.5; margin-bottom: 10px; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }`,
      `.note-card .meta { display: flex; justify-content: space-between; align-items: center; }`,
      `.note-card .date { font-size: 0.75rem; color: #52525b; }`,
      `.note-card .category { font-size: 0.7rem; padding: 2px 8px; border-radius: 10px; background: #1c1c22; color: #a1a1aa; }`,
      `.note-actions { display: flex; gap: 4px; margin-top: 8px; }`,
      `.note-actions button { background: none; border: none; color: #52525b; cursor: pointer; font-size: 0.8rem; padding: 4px 8px; border-radius: 4px; }`,
      `.note-actions button:hover { background: #1c1c22; color: #e4e4e7; }`,
      `.note-actions button.del:hover { color: #ef4444; }`,
      ``,
      `/* Add form */`,
      `.add-form { background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; margin-bottom: 16px; display: grid; gap: 8px; }`,
      `.add-form input, .add-form textarea { padding: 10px 12px; border-radius: 6px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-family: inherit; font-size: 0.85rem; outline: none; resize: vertical; }`,
      `.add-form input:focus, .add-form textarea:focus { border-color: #3b82f6; }`,
      `.add-form .row { display: flex; gap: 8px; }`,
      ``,
      `.empty { color: #52525b; text-align: center; padding: 48px; }`,
      ``,
      `@media (max-width: 640px) {`,
      `  .stats { flex-direction: column; }`,
      `  .notes-grid { grid-template-columns: 1fr; }`,
      `  .toolbar { flex-direction: column; }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/page.tsx',
    content: [
      `'use client';`,
      `import { useEffect, useState } from 'react';`,
      ``,
      `interface Note { id: number; title: string; body: string; category: string; createdAt: string; }`,
      ``,
      `export default function Home() {`,
      `  const [notes, setNotes] = useState<Note[]>([]);`,
      `  const [search, setSearch] = useState('');`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ title: '', body: '', category: '' });`,
      ``,
      `  const load = async () => {`,
      `    const params = search ? \`?q=\${encodeURIComponent(search)}\` : '';`,
      `    const r = await fetch(\`/api/notes\${params}\`);`,
      `    setNotes(await r.json());`,
      `  };`,
      ``,
      `  useEffect(() => { load(); }, [search]);`,
      ``,
      `  const addNote = async () => {`,
      `    if (!form.title) return;`,
      `    await fetch('/api/notes', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) });`,
      `    setForm({ title: '', body: '', category: '' });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const remove = async (id: number) => {`,
      `    await fetch(\`/api/notes/\${id}\`, { method: 'DELETE' });`,
      `    load();`,
      `  };`,
      ``,
      `  const total = notes.length;`,
      `  const categories = [...new Set(notes.map(n => n.category))].length;`,
      `  const today = notes.filter(n => new Date(n.createdAt).toDateString() === new Date().toDateString()).length;`,
      ``,
      `  return (`,
      `    <div className="dashboard">`,
      `      <header className="header">`,
      `        <h1>▲ Notes Dashboard</h1>`,
      `        <p>Next.js 16 · App Router · API Routes · TypeScript</p>`,
      `      </header>`,
      ``,
      `      <div className="stats">`,
      `        <div className="stat-card"><span className="label">Total Notes</span><div className="value blue">{total}</div></div>`,
      `        <div className="stat-card"><span className="label">Categories</span><div className="value green">{categories}</div></div>`,
      `        <div className="stat-card"><span className="label">Today</span><div className="value amber">{today}</div></div>`,
      `      </div>`,
      ``,
      `      <div className="toolbar">`,
      `        <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search notes..." />`,
      `        <button className={\`btn \${showAdd ? '' : 'btn-primary'}\`} onClick={() => setShowAdd(!showAdd)}>`,
      `          {showAdd ? 'Cancel' : '+ New Note'}`,
      `        </button>`,
      `      </div>`,
      ``,
      `      {showAdd && (`,
      `        <div className="add-form">`,
      `          <input placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} />`,
      `          <textarea placeholder="Write your note..." rows={3} value={form.body} onChange={e => setForm({ ...form, body: e.target.value })} />`,
      `          <div className="row">`,
      `            <input placeholder="Category (optional)" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} style={{ flex: 1 }} />`,
      `            <button className="btn btn-primary" onClick={addNote}>Save</button>`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      ``,
      `      <div className="notes-grid">`,
      `        {notes.map(n => (`,
      `          <div key={n.id} className="note-card">`,
      `            <div className="title">{n.title}</div>`,
      `            {n.body && <div className="body">{n.body}</div>}`,
      `            <div className="meta">`,
      `              <span className="date">{new Date(n.createdAt).toLocaleDateString()}</span>`,
      `              {n.category && <span className="category">{n.category}</span>}`,
      `            </div>`,
      `            <div className="note-actions">`,
      `              <button className="del" onClick={() => remove(n.id)}>Delete</button>`,
      `            </div>`,
      `          </div>`,
      `        ))}`,
      `      </div>`,
      `      {notes.length === 0 && <p className="empty">No notes yet — create one above!</p>}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `interface Note { id: number; title: string; body: string; category: string; createdAt: string; }`,
      ``,
      `const notes: Note[] = [`,
      `  { id: 1, title: 'Getting Started with Next.js', body: 'App Router provides a new way to build applications using React Server Components. It supports layouts, nested routing, and more.', category: 'Framework', createdAt: new Date().toISOString() },`,
      `  { id: 2, title: 'API Routes are powerful', body: 'Create RESTful API endpoints directly in your Next.js app using route handlers. Supports GET, POST, PUT, DELETE, and more.', category: 'Backend', createdAt: new Date().toISOString() },`,
      `  { id: 3, title: 'Server Components', body: 'React Server Components render on the server, reducing client-side JavaScript and improving performance.', category: 'Framework', createdAt: new Date().toISOString() },`,
      `  { id: 4, title: 'TypeScript everywhere', body: 'Next.js has first-class TypeScript support with automatic type checking in API routes and page components.', category: 'DX', createdAt: new Date().toISOString() },`,
      `];`,
      `let nextId = 5;`,
      ``,
      `export async function GET(request: Request) {`,
      `  const { searchParams } = new URL(request.url);`,
      `  const q = searchParams.get('q')?.toLowerCase();`,
      `  let result = [...notes];`,
      `  if (q) result = result.filter(n => n.title.toLowerCase().includes(q) || n.body.toLowerCase().includes(q));`,
      `  return NextResponse.json(result);`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  const body = await request.json();`,
      `  const note: Note = { id: nextId++, title: body.title, body: body.body || '', category: body.category || 'General', createdAt: new Date().toISOString() };`,
      `  notes.push(note);`,
      `  return NextResponse.json(note, { status: 201 });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/[id]/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      ``,
      `// Note: shares state with parent route in dev mode`,
      `export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  const body = await request.json();`,
      `  return NextResponse.json({ id: parseInt(id), ...body });`,
      `}`,
      ``,
      `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  return NextResponse.json({ ok: true, deleted: id });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/health/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `export async function GET() {`,
      `  return NextResponse.json({ status: 'ok', framework: 'next.js', timestamp: new Date().toISOString() });`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const nextjsBasic: StackTemplate = {
  id: 'nextjs-basic',
  stackId: 'nextjs',
  tier: 'basic',
  name: 'Next.js Basic',
  description: 'Notes dashboard — App Router, API Routes, stats cards, search',
  features: [
    'Next.js 16 App Router',
    'API Route handlers (GET, POST, DELETE)',
    'Notes grid with categories',
    'Dashboard stats cards',
    'Full-text search',
    'TypeScript + Server Components',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Prisma + Zod + Server Actions
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-solid',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client { provider = "prisma-client-js" }`,
      `datasource db { provider = "sqlite"; url = "file:./dev.db" }`,
      ``,
      `model Note {`,
      `  id        Int      @id @default(autoincrement())`,
      `  title     String`,
      `  body      String   @default("")`,
      `  category  String   @default("General")`,
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const CreateNoteSchema = z.object({ title: z.string().min(1).max(200), body: z.string().max(5000).optional(), category: z.string().max(50).optional() });`,
      ``,
      `export async function GET(request: Request) {`,
      `  const { searchParams } = new URL(request.url);`,
      `  const q = searchParams.get('q');`,
      `  const notes = await prisma.note.findMany({`,
      `    where: q ? { OR: [{ title: { contains: q } }, { body: { contains: q } }] } : undefined,`,
      `    orderBy: { createdAt: 'desc' },`,
      `  });`,
      `  return NextResponse.json(notes);`,
      `}`,
      ``,
      `export async function POST(request: Request) {`,
      `  try {`,
      `    const body = await request.json();`,
      `    const parsed = CreateNoteSchema.parse(body);`,
      `    const note = await prisma.note.create({ data: { title: parsed.title, body: parsed.body || '', category: parsed.category || 'General' } });`,
      `    return NextResponse.json(note, { status: 201 });`,
      `  } catch (err) {`,
      `    if (err instanceof z.ZodError) return NextResponse.json({ error: 'Validation failed', details: err.issues }, { status: 400 });`,
      `    return NextResponse.json({ error: (err as Error).message }, { status: 500 });`,
      `  }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/app/api/notes/[id]/route.ts',
    content: [
      `import { NextResponse } from 'next/server';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const UpdateNoteSchema = z.object({ title: z.string().min(1).max(200).optional(), body: z.string().max(5000).optional(), category: z.string().max(50).optional() });`,
      ``,
      `export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  const body = await request.json();`,
      `  const parsed = UpdateNoteSchema.parse(body);`,
      `  const note = await prisma.note.update({ where: { id: parseInt(id) }, data: parsed });`,
      `  return NextResponse.json(note);`,
      `}`,
      ``,
      `export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) {`,
      `  const { id } = await params;`,
      `  await prisma.note.delete({ where: { id: parseInt(id) } });`,
      `  return NextResponse.json({ ok: true });`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# Switch to PostgreSQL for production\n# DATABASE_URL="postgresql://..."\nDATABASE_URL="file:./prisma/dev.db"\n`,
  },
];

const nextjsSolid: StackTemplate = {
  id: 'nextjs-solid',
  stackId: 'nextjs',
  tier: 'solid',
  name: 'Next.js Solid',
  description: 'Production patterns — Prisma ORM + Zod validation',
  features: [
    'Prisma ORM with auto-migration',
    'Zod schema validation',
    'Type-safe API routes',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-battle-tested',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t nextjs-app .',
          'docker:up': 'docker compose up -d',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/.next ./.next`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["npm", "start"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `version: '3.9'`,
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: nextjs_app`,
      `      POSTGRES_USER: nextjs`,
      `      POSTGRES_PASSWORD: nextjs_secret`,
      `    ports: ['5432:5432']`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U nextjs']`,
      `      interval: 5s`,
      `  app:`,
      `    build: .`,
      `    ports: ['3000:3000']`,
      `    depends_on:`,
      `      db: { condition: service_healthy }`,
      `    environment:`,
      `      DATABASE_URL: postgresql://nextjs:nextjs_secret@db:5432/nextjs_app`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: `import { defineConfig } from 'vitest/config';\nexport default defineConfig({ test: { globals: true, include: ['__tests__/**/*.test.ts'] } });\n`,
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const NoteSchema = z.object({ title: z.string().min(1).max(200), body: z.string().optional(), category: z.string().optional() });`,
      ``,
      `describe('Next.js Notes API', () => {`,
      `  it('validates note creation', () => {`,
      `    expect(() => NoteSchema.parse({ title: '' })).toThrow();`,
      `    expect(NoteSchema.parse({ title: 'Test' })).toHaveProperty('title', 'Test');`,
      `  });`,
      `  it('search filters notes', () => {`,
      `    const notes = [{ title: 'React Guide' }, { title: 'Vue Guide' }];`,
      `    expect(notes.filter(n => n.title.includes('React'))).toHaveLength(1);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# Next.js Notes — Battle-Tested`,
      ``,
      `Production-ready notes dashboard with Next.js 16, Prisma, and Docker.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const nextjsBattleTested: StackTemplate = {
  id: 'nextjs-battle-tested',
  stackId: 'nextjs',
  tier: 'battle-tested',
  name: 'Next.js Battle-Tested',
  description: 'Deployment ready — Docker, tests, CI/CD',
  features: [
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite',
    'GitHub Actions CI',
    'Multi-stage Docker build',
    'Everything from Solid tier',
  ],
  files: mergeFiles(nextjsSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'nextjs-vai',
        private: true,
        scripts: {
          dev: 'next dev', build: 'next build', start: 'next start',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t nextjs-vai .',
          'docker:up': 'docker compose up -d',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          next: '^16.1.0', react: '^19.2.0', 'react-dom': '^19.2.0',
          '@prisma/client': '^7.4.0', zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/node': '^22.0.0',
          prisma: '^7.4.0', typescript: '^5.9.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/.next ./.next`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["npm", "start"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'nextjs-vai', version: '1.0.0', stack: 'nextjs', tier: 'vai',`,
      `  features: { serverComponents: true, edgeReady: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 Next.js Notes — Vai Premium`,
      ``,
      `> VeggaAI's curated Next.js notes dashboard.`,
      ``,
      `## Features`,
      `- ▲ Next.js 16 App Router + Server Components`,
      `- 📝 Notes dashboard with stats, search, categories`,
      `- 🗄️ Prisma ORM + Zod validation`,
      `- 🐳 Optimized Docker (non-root, healthcheck)`,
      `- 🧪 Vitest + CI/CD`,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

const nextjsVai: StackTemplate = {
  id: 'nextjs-vai',
  stackId: 'nextjs',
  tier: 'vai',
  name: 'Next.js Vai',
  description: "VeggaAI's premium Next.js — optimized Docker, monitoring",
  features: [
    'Optimized Docker (non-root, healthcheck)',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(nextjsBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const nextjsStack: StackDefinition = {
  id: 'nextjs',
  name: 'Next.js',
  tagline: 'The React framework for the web',
  description: 'Next.js 16 with App Router, API routes, and Server Components',
  techStack: ['Next.js', 'React', 'TypeScript', 'Vercel'],
  icon: '▲',
  color: 'zinc',
  templates: [nextjsBasic, nextjsSolid, nextjsBattleTested, nextjsVai],
};
