/**
 * PERN Stack — PostgreSQL + Express + React + Node.js
 * All four tiers from basic board task manager to Vai premium.
 *
 * Dev approach: Vite serves frontend, custom Vite plugin provides API routes.
 * This keeps the sandbox single-port and works with `npm run dev -- --port X`.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Board Task Manager with Framer Motion drag-to-reorder
   Features: Multiple boards, sidebar navigation, edit/view mode toggle,
   drag-to-reorder with Framer Motion, responsive design, position ordering.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-basic',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({`,
      `  plugins: [react(), apiPlugin()],`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'react-jsx',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          outDir: 'dist',
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" />`,
      `  <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>PERN Board</title>`,
      `  <link rel="preconnect" href="https://fonts.googleapis.com" />`,
      `  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />`,
      `</head>`,
      `<body>`,
      `  <div id="root"></div>`,
      `  <script type="module" src="/src/main.tsx"></script>`,
      `</body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      ``,
      `/* ── Data Models ── */`,
      `interface Board { id: number; name: string; icon: string; createdAt: string; }`,
      `interface Todo {`,
      `  id: number; boardId: number; title: string; done: boolean;`,
      `  position: number; createdAt: string;`,
      `}`,
      ``,
      `const ICONS = ['📁', '🏠', '☀️', '🎯', '📚', '💡', '🚀', '🎨', '🔥', '⭐'];`,
      `let boardSeq = 4;`,
      `let todoSeq = 10;`,
      ``,
      `const boards: Board[] = [`,
      `  { id: 1, name: 'Work', icon: '💼', createdAt: new Date().toISOString() },`,
      `  { id: 2, name: 'Personal', icon: '🏠', createdAt: new Date().toISOString() },`,
      `  { id: 3, name: 'Today', icon: '☀️', createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `const todos: Todo[] = [`,
      `  { id: 1, boardId: 1, title: 'Set up project structure', done: true, position: 0, createdAt: new Date().toISOString() },`,
      `  { id: 2, boardId: 1, title: 'Design the database schema', done: true, position: 1, createdAt: new Date().toISOString() },`,
      `  { id: 3, boardId: 1, title: 'Build REST API endpoints', done: false, position: 2, createdAt: new Date().toISOString() },`,
      `  { id: 4, boardId: 1, title: 'Connect React frontend', done: false, position: 3, createdAt: new Date().toISOString() },`,
      `  { id: 5, boardId: 1, title: 'Add drag-to-reorder feature', done: false, position: 4, createdAt: new Date().toISOString() },`,
      `  { id: 6, boardId: 2, title: 'Grocery shopping', done: false, position: 0, createdAt: new Date().toISOString() },`,
      `  { id: 7, boardId: 2, title: 'Read "Designing Data-Intensive Apps"', done: false, position: 1, createdAt: new Date().toISOString() },`,
      `  { id: 8, boardId: 2, title: 'Call dentist for appointment', done: true, position: 2, createdAt: new Date().toISOString() },`,
      `  { id: 9, boardId: 3, title: 'Morning standup at 9am', done: true, position: 0, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `/* ── Helpers ── */`,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<Record<string, unknown>> {`,
      `  return new Promise((resolve) => {`,
      `    let body = '';`,
      `    req.on('data', (c: Buffer) => (body += c.toString()));`,
      `    req.on('end', () => resolve(body ? JSON.parse(body) : {}));`,
      `  });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'pern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = req.url || '';`,
      `        try {`,
      `          /* Health */`,
      `          if (url === '/api/health') {`,
      `            return json(res, { status: 'ok', boards: boards.length, todos: todos.length, uptime: process.uptime() });`,
      `          }`,
      `          /* GET /api/boards */`,
      `          if (url === '/api/boards' && req.method === 'GET') return json(res, boards);`,
      `          /* POST /api/boards */`,
      `          if (url === '/api/boards' && req.method === 'POST') {`,
      `            const { name, icon } = await parseBody(req);`,
      `            const board: Board = {`,
      `              id: boardSeq++, name: name as string,`,
      `              icon: (icon as string) || ICONS[Math.floor(Math.random() * ICONS.length)],`,
      `              createdAt: new Date().toISOString(),`,
      `            };`,
      `            boards.push(board);`,
      `            return json(res, board, 201);`,
      `          }`,
      `          /* Board-specific routes */`,
      `          const boardMatch = url.match(/^\\/api\\/boards\\/(\\d+)$/);`,
      `          if (boardMatch) {`,
      `            const bid = parseInt(boardMatch[1]);`,
      `            if (req.method === 'DELETE') {`,
      `              const idx = boards.findIndex(b => b.id === bid);`,
      `              if (idx !== -1) boards.splice(idx, 1);`,
      `              for (let i = todos.length - 1; i >= 0; i--) { if (todos[i].boardId === bid) todos.splice(i, 1); }`,
      `              return json(res, { ok: true });`,
      `            }`,
      `          }`,
      `          /* GET /api/boards/:id/todos */`,
      `          const todosMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/todos$/);`,
      `          if (todosMatch && req.method === 'GET') {`,
      `            const bid = parseInt(todosMatch[1]);`,
      `            return json(res, todos.filter(t => t.boardId === bid).sort((a, b) => a.position - b.position));`,
      `          }`,
      `          /* POST /api/boards/:id/todos */`,
      `          if (todosMatch && req.method === 'POST') {`,
      `            const bid = parseInt(todosMatch[1]);`,
      `            const { title } = await parseBody(req);`,
      `            const boardTodos = todos.filter(t => t.boardId === bid);`,
      `            const maxPos = boardTodos.length ? Math.max(...boardTodos.map(t => t.position)) : -1;`,
      `            const todo: Todo = { id: todoSeq++, boardId: bid, title: title as string, done: false, position: maxPos + 1, createdAt: new Date().toISOString() };`,
      `            todos.push(todo);`,
      `            return json(res, todo, 201);`,
      `          }`,
      `          /* PUT /api/boards/:id/reorder */`,
      `          const reorderMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/reorder$/);`,
      `          if (reorderMatch && req.method === 'PUT') {`,
      `            const { todoIds } = await parseBody(req);`,
      `            (todoIds as number[]).forEach((id, i) => { const t = todos.find(x => x.id === id); if (t) t.position = i; });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          /* PATCH /api/todos/:id */`,
      `          const todoMatch = url.match(/^\\/api\\/todos\\/(\\d+)$/);`,
      `          if (todoMatch && req.method === 'PATCH') {`,
      `            const id = parseInt(todoMatch[1]);`,
      `            const updates = await parseBody(req);`,
      `            const todo = todos.find(t => t.id === id);`,
      `            if (todo) Object.assign(todo, updates);`,
      `            return json(res, todo);`,
      `          }`,
      `          /* DELETE /api/todos/:id */`,
      `          if (todoMatch && req.method === 'DELETE') {`,
      `            const id = parseInt(todoMatch[1]);`,
      `            const idx = todos.findIndex(t => t.id === id);`,
      `            if (idx !== -1) todos.splice(idx, 1);`,
      `            return json(res, { ok: true });`,
      `          }`,
      `        } catch (err) {`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: [
      `import { createRoot } from 'react-dom/client';`,
      `import { App } from './App';`,
      `import './index.css';`,
      ``,
      `createRoot(document.getElementById('root')!).render(<App />);`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { Reorder, AnimatePresence, motion } from 'framer-motion';`,
      ``,
      `interface Board { id: number; name: string; icon: string; }`,
      `interface Todo { id: number; boardId: number; title: string; done: boolean; position: number; }`,
      ``,
      `export function App() {`,
      `  const [boards, setBoards] = useState<Board[]>([]);`,
      `  const [todos, setTodos] = useState<Todo[]>([]);`,
      `  const [activeBoard, setActiveBoard] = useState<number | null>(null);`,
      `  const [editMode, setEditMode] = useState(false);`,
      `  const [sidebarOpen, setSidebarOpen] = useState(window.innerWidth > 768);`,
      `  const [newTodo, setNewTodo] = useState('');`,
      `  const [newBoard, setNewBoard] = useState('');`,
      `  const [loading, setLoading] = useState(true);`,
      ``,
      `  useEffect(() => {`,
      `    fetch('/api/boards').then(r => r.json()).then((data: Board[]) => {`,
      `      setBoards(data);`,
      `      if (data.length) setActiveBoard(data[0].id);`,
      `      setLoading(false);`,
      `    });`,
      `  }, []);`,
      ``,
      `  useEffect(() => {`,
      `    if (!activeBoard) return;`,
      `    fetch(\`/api/boards/\${activeBoard}/todos\`).then(r => r.json()).then(setTodos);`,
      `  }, [activeBoard]);`,
      ``,
      `  const addTodo = async () => {`,
      `    if (!newTodo.trim() || !activeBoard) return;`,
      `    const r = await fetch(\`/api/boards/\${activeBoard}/todos\`, {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ title: newTodo }),`,
      `    });`,
      `    const created = await r.json();`,
      `    setTodos(prev => [...prev, created]);`,
      `    setNewTodo('');`,
      `  };`,
      ``,
      `  const toggleTodo = async (id: number) => {`,
      `    const t = todos.find(x => x.id === id)!;`,
      `    await fetch(\`/api/todos/\${id}\`, {`,
      `      method: 'PATCH', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ done: !t.done }),`,
      `    });`,
      `    setTodos(prev => prev.map(x => x.id === id ? { ...x, done: !x.done } : x));`,
      `  };`,
      ``,
      `  const deleteTodo = async (id: number) => {`,
      `    await fetch(\`/api/todos/\${id}\`, { method: 'DELETE' });`,
      `    setTodos(prev => prev.filter(x => x.id !== id));`,
      `  };`,
      ``,
      `  const handleReorder = (newOrder: Todo[]) => {`,
      `    setTodos(newOrder);`,
      `    if (activeBoard) {`,
      `      fetch(\`/api/boards/\${activeBoard}/reorder\`, {`,
      `        method: 'PUT', headers: { 'Content-Type': 'application/json' },`,
      `        body: JSON.stringify({ todoIds: newOrder.map(t => t.id) }),`,
      `      });`,
      `    }`,
      `  };`,
      ``,
      `  const addBoard = async () => {`,
      `    if (!newBoard.trim()) return;`,
      `    const r = await fetch('/api/boards', {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ name: newBoard }),`,
      `    });`,
      `    const board = await r.json();`,
      `    setBoards(prev => [...prev, board]);`,
      `    setActiveBoard(board.id);`,
      `    setNewBoard('');`,
      `  };`,
      ``,
      `  const deleteBoard = async (id: number) => {`,
      `    await fetch(\`/api/boards/\${id}\`, { method: 'DELETE' });`,
      `    const remaining = boards.filter(b => b.id !== id);`,
      `    setBoards(remaining);`,
      `    if (activeBoard === id) setActiveBoard(remaining[0]?.id ?? null);`,
      `  };`,
      ``,
      `  const active = boards.find(b => b.id === activeBoard);`,
      `  const doneCount = todos.filter(t => t.done).length;`,
      `  const pct = todos.length ? Math.round((doneCount / todos.length) * 100) : 0;`,
      ``,
      `  return (`,
      `    <div className="layout">`,
      `      {sidebarOpen && <div className="overlay" onClick={() => setSidebarOpen(false)} />}`,
      ``,
      `      {/* ── Sidebar ── */}`,
      `      <aside className={\`sidebar \${sidebarOpen ? 'open' : ''}\`}>`,
      `        <div className="sb-head">`,
      `          <h2>📋 Boards</h2>`,
      `          <button className="icon-btn" onClick={() => setSidebarOpen(false)} title="Close sidebar">✕</button>`,
      `        </div>`,
      `        <nav className="board-nav">`,
      `          {boards.map(b => (`,
      `            <button key={b.id} className={\`board-btn \${b.id === activeBoard ? 'active' : ''}\`}`,
      `              onClick={() => { setActiveBoard(b.id); if (innerWidth <= 768) setSidebarOpen(false); }}>`,
      `              <span className="board-icon">{b.icon}</span>`,
      `              <span className="board-name">{b.name}</span>`,
      `              <span className="board-del" onClick={e => { e.stopPropagation(); deleteBoard(b.id); }}>×</span>`,
      `            </button>`,
      `          ))}`,
      `        </nav>`,
      `        <div className="sb-foot">`,
      `          <div className="sb-input">`,
      `            <input value={newBoard} onChange={e => setNewBoard(e.target.value)}`,
      `              onKeyDown={e => e.key === 'Enter' && addBoard()} placeholder="New board..." />`,
      `            <button onClick={addBoard}>+</button>`,
      `          </div>`,
      `        </div>`,
      `      </aside>`,
      ``,
      `      {/* ── Main ── */}`,
      `      <main className="main">`,
      `        <header className="topbar">`,
      `          <button className="icon-btn menu-btn" onClick={() => setSidebarOpen(true)}>☰</button>`,
      `          <div className="topbar-info">`,
      `            <h1>{active ? \`\${active.icon} \${active.name}\` : 'Select a board'}</h1>`,
      `            {todos.length > 0 && (`,
      `              <div className="progress-row">`,
      `                <div className="progress-bar"><div className="progress-fill" style={{ width: \`\${pct}%\` }} /></div>`,
      `                <span className="progress-text">{doneCount}/{todos.length}</span>`,
      `              </div>`,
      `            )}`,
      `          </div>`,
      `          <label className="mode-toggle" title={editMode ? 'Drag to reorder enabled' : 'Toggle edit mode to reorder'}>`,
      `            <input type="checkbox" checked={editMode} onChange={() => setEditMode(!editMode)} />`,
      `            <span className="toggle-track"><span className="toggle-thumb" /></span>`,
      `            <span className="toggle-label">{editMode ? '✏️ Edit' : '👁 View'}</span>`,
      `          </label>`,
      `        </header>`,
      ``,
      `        <div className="add-row">`,
      `          <input value={newTodo} onChange={e => setNewTodo(e.target.value)}`,
      `            onKeyDown={e => e.key === 'Enter' && addTodo()} placeholder="What needs to be done?" />`,
      `          <button onClick={addTodo} className="btn-primary">Add Task</button>`,
      `        </div>`,
      ``,
      `        <div className="todo-area">`,
      `          {loading ? (`,
      `            <p className="empty">Loading...</p>`,
      `          ) : !activeBoard ? (`,
      `            <div className="empty-state">`,
      `              <span className="empty-icon">📋</span>`,
      `              <p>Create a board to get started</p>`,
      `            </div>`,
      `          ) : todos.length === 0 ? (`,
      `            <div className="empty-state">`,
      `              <span className="empty-icon">✨</span>`,
      `              <p>No tasks yet — add one above!</p>`,
      `            </div>`,
      `          ) : editMode ? (`,
      `            <Reorder.Group axis="y" values={todos} onReorder={handleReorder} className="todo-list">`,
      `              {todos.map(t => (`,
      `                <Reorder.Item key={t.id} value={t} className={\`todo-item \${t.done ? 'done' : ''}\`}`,
      `                  whileDrag={{ scale: 1.02, boxShadow: '0 8px 24px rgba(59,130,246,0.15)', cursor: 'grabbing' }}>`,
      `                  <span className="grip">⠿</span>`,
      `                  <input type="checkbox" checked={t.done} onChange={() => toggleTodo(t.id)} />`,
      `                  <span className="todo-text">{t.title}</span>`,
      `                  <button className="btn-del" onClick={() => deleteTodo(t.id)}>×</button>`,
      `                </Reorder.Item>`,
      `              ))}`,
      `            </Reorder.Group>`,
      `          ) : (`,
      `            <ul className="todo-list">`,
      `              <AnimatePresence mode="popLayout">`,
      `                {todos.map(t => (`,
      `                  <motion.li key={t.id} className={\`todo-item \${t.done ? 'done' : ''}\`}`,
      `                    initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}`,
      `                    exit={{ opacity: 0, x: -80 }} layout>`,
      `                    <input type="checkbox" checked={t.done} onChange={() => toggleTodo(t.id)} />`,
      `                    <span className="todo-text">{t.title}</span>`,
      `                    <button className="btn-del" onClick={() => deleteTodo(t.id)}>×</button>`,
      `                  </motion.li>`,
      `                ))}`,
      `              </AnimatePresence>`,
      `            </ul>`,
      `          )}`,
      `        </div>`,
      `      </main>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: 'Inter', system-ui, -apple-system, sans-serif; background: #09090b; color: #e4e4e7; -webkit-font-smoothing: antialiased; }`,
      ``,
      `/* ── Layout ── */`,
      `.layout { display: flex; height: 100vh; overflow: hidden; }`,
      `.overlay { display: none; }`,
      ``,
      `/* ── Sidebar ── */`,
      `.sidebar { width: 280px; background: #0c0c0f; border-right: 1px solid #1c1c22; display: flex; flex-direction: column; flex-shrink: 0; z-index: 50; }`,
      `.sb-head { display: flex; align-items: center; justify-content: space-between; padding: 20px 16px; border-bottom: 1px solid #1c1c22; }`,
      `.sb-head h2 { font-size: 1rem; font-weight: 600; }`,
      `.board-nav { flex: 1; overflow-y: auto; padding: 8px; display: flex; flex-direction: column; gap: 2px; }`,
      `.board-btn { width: 100%; display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 8px; background: transparent; border: none; color: #a1a1aa; cursor: pointer; font-size: 0.875rem; text-align: left; transition: all 0.15s; }`,
      `.board-btn:hover { background: #18181f; color: #e4e4e7; }`,
      `.board-btn.active { background: #172554; color: #60a5fa; }`,
      `.board-icon { font-size: 1.1rem; flex-shrink: 0; }`,
      `.board-name { flex: 1; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }`,
      `.board-del { display: none; color: #71717a; font-size: 1rem; padding: 2px 4px; border-radius: 4px; }`,
      `.board-btn:hover .board-del { display: block; }`,
      `.board-del:hover { color: #ef4444; background: #1c1c22; }`,
      `.sb-foot { padding: 12px; border-top: 1px solid #1c1c22; }`,
      `.sb-input { display: flex; gap: 6px; }`,
      `.sb-input input { flex: 1; padding: 8px 10px; border-radius: 6px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.8rem; outline: none; }`,
      `.sb-input input:focus { border-color: #3b82f6; }`,
      `.sb-input button { padding: 8px 12px; border-radius: 6px; background: #1e293b; color: #60a5fa; border: none; cursor: pointer; font-weight: 600; font-size: 0.9rem; }`,
      `.sb-input button:hover { background: #1e3a5f; }`,
      ``,
      `/* ── Main ── */`,
      `.main { flex: 1; display: flex; flex-direction: column; overflow: hidden; min-width: 0; }`,
      `.topbar { display: flex; align-items: center; gap: 12px; padding: 16px 24px; border-bottom: 1px solid #1c1c22; flex-shrink: 0; }`,
      `.topbar h1 { font-size: 1.25rem; font-weight: 600; }`,
      `.topbar-info { flex: 1; min-width: 0; }`,
      `.menu-btn { display: none; }`,
      ``,
      `/* Progress bar */`,
      `.progress-row { display: flex; align-items: center; gap: 8px; margin-top: 6px; }`,
      `.progress-bar { flex: 1; max-width: 120px; height: 4px; background: #27272a; border-radius: 2px; overflow: hidden; }`,
      `.progress-fill { height: 100%; background: #3b82f6; border-radius: 2px; transition: width 0.3s ease; }`,
      `.progress-text { font-size: 0.75rem; color: #71717a; }`,
      ``,
      `/* Mode toggle */`,
      `.mode-toggle { display: flex; align-items: center; gap: 8px; cursor: pointer; -webkit-user-select: none; user-select: none; flex-shrink: 0; }`,
      `.mode-toggle input { display: none; }`,
      `.toggle-track { width: 36px; height: 20px; background: #27272a; border-radius: 10px; position: relative; transition: background 0.2s; flex-shrink: 0; }`,
      `.mode-toggle input:checked + .toggle-track { background: #2563eb; }`,
      `.toggle-thumb { width: 16px; height: 16px; background: #e4e4e7; border-radius: 50%; position: absolute; top: 2px; left: 2px; transition: transform 0.2s; }`,
      `.mode-toggle input:checked + .toggle-track .toggle-thumb { transform: translateX(16px); }`,
      `.toggle-label { font-size: 0.8rem; color: #a1a1aa; white-space: nowrap; }`,
      ``,
      `/* Add row */`,
      `.add-row { display: flex; gap: 8px; padding: 16px 24px; flex-shrink: 0; }`,
      `.add-row input { flex: 1; padding: 10px 14px; border-radius: 8px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.9rem; outline: none; transition: border-color 0.15s; }`,
      `.add-row input:focus { border-color: #3b82f6; }`,
      `.btn-primary { padding: 10px 20px; border-radius: 8px; background: #3b82f6; color: #fff; border: none; font-weight: 600; cursor: pointer; transition: background 0.15s; white-space: nowrap; }`,
      `.btn-primary:hover { background: #2563eb; }`,
      ``,
      `/* Todo list */`,
      `.todo-area { flex: 1; overflow-y: auto; padding: 0 24px 24px; }`,
      `.todo-list { list-style: none; padding: 0; display: flex; flex-direction: column; gap: 4px; }`,
      `.todo-item { display: flex; align-items: center; gap: 12px; padding: 12px 14px; border-radius: 10px; background: #111115; border: 1px solid #1c1c22; transition: border-color 0.15s, background 0.15s; }`,
      `.todo-item:hover { border-color: #27272a; background: #141418; }`,
      `.todo-item.done { opacity: 0.6; }`,
      `.todo-item.done .todo-text { text-decoration: line-through; color: #52525b; }`,
      `.todo-item input[type="checkbox"] { width: 18px; height: 18px; accent-color: #3b82f6; flex-shrink: 0; cursor: pointer; }`,
      `.todo-text { flex: 1; font-size: 0.9rem; line-height: 1.4; }`,
      `.grip { color: #3f3f46; cursor: grab; user-select: none; font-size: 1rem; flex-shrink: 0; }`,
      `.grip:active { cursor: grabbing; }`,
      `.btn-del { background: none; border: none; color: #52525b; cursor: pointer; font-size: 1.2rem; padding: 4px 8px; opacity: 0; transition: all 0.15s; border-radius: 4px; }`,
      `.todo-item:hover .btn-del { opacity: 1; }`,
      `.btn-del:hover { color: #ef4444; background: #1c1c22; }`,
      ``,
      `/* Icon button */`,
      `.icon-btn { background: none; border: none; color: #71717a; cursor: pointer; font-size: 1.1rem; padding: 4px 8px; border-radius: 6px; transition: all 0.15s; }`,
      `.icon-btn:hover { background: #1c1c22; color: #e4e4e7; }`,
      ``,
      `/* Empty state */`,
      `.empty-state { text-align: center; padding: 60px 24px; }`,
      `.empty-icon { font-size: 3rem; display: block; margin-bottom: 12px; }`,
      `.empty-state p { color: #52525b; font-size: 0.9rem; }`,
      ``,
      `/* ── Responsive ── */`,
      `@media (max-width: 768px) {`,
      `  .sidebar { position: fixed; top: 0; left: 0; height: 100vh; transform: translateX(-100%); transition: transform 0.25s ease; box-shadow: 4px 0 24px rgba(0,0,0,0.5); }`,
      `  .sidebar.open { transform: translateX(0); }`,
      `  .overlay { display: block; position: fixed; inset: 0; background: rgba(0,0,0,0.6); z-index: 40; }`,
      `  .menu-btn { display: flex; }`,
      `  .topbar { padding: 12px 16px; }`,
      `  .add-row { padding: 12px 16px; }`,
      `  .todo-area { padding: 0 16px 16px; }`,
      `  .sb-head button { display: flex; }`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const pernBasic: StackTemplate = {
  id: 'pern-basic',
  stackId: 'pern',
  tier: 'basic',
  name: 'PERN Basic',
  description: 'Board task manager — multiple boards, drag-to-reorder, responsive sidebar',
  features: [
    'Multiple boards with sidebar navigation',
    'Drag-to-reorder with Framer Motion',
    'Edit/View mode toggle',
    'Responsive design (mobile sidebar drawer)',
    'Progress tracking per board',
    'In-memory data store (swap to PostgreSQL)',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Prisma ORM + Zod validation + Auth scaffolding
   Adds: real database, input validation, user model
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-solid',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `// PERN Solid — Prisma schema`,
      `// Switch provider to "postgresql" and update url for production`,
      `generator client {`,
      `  provider = "prisma-client-js"`,
      `}`,
      ``,
      `datasource db {`,
      `  provider = "sqlite"`,
      `  url      = "file:./dev.db"`,
      `}`,
      ``,
      `model User {`,
      `  id        Int      @id @default(autoincrement())`,
      `  email     String   @unique`,
      `  name      String?`,
      `  password  String`,
      `  boards    Board[]`,
      `  createdAt DateTime @default(now())`,
      `}`,
      ``,
      `model Board {`,
      `  id        Int      @id @default(autoincrement())`,
      `  name      String`,
      `  icon      String   @default("📁")`,
      `  userId    Int`,
      `  user      User     @relation(fields: [userId], references: [id])`,
      `  todos     Todo[]`,
      `  createdAt DateTime @default(now())`,
      `}`,
      ``,
      `model Todo {`,
      `  id        Int      @id @default(autoincrement())`,
      `  title     String`,
      `  done      Boolean  @default(false)`,
      `  position  Int      @default(0)`,
      `  boardId   Int`,
      `  board     Board    @relation(fields: [boardId], references: [id], onDelete: Cascade)`,
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      `const UpdateTodoSchema = z.object({ title: z.string().min(1).max(500).optional(), done: z.boolean().optional() });`,
      `const ReorderSchema = z.object({ todoIds: z.array(z.number()) });`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<Record<string, unknown>> {`,
      `  return new Promise((resolve) => {`,
      `    let body = '';`,
      `    req.on('data', (c: Buffer) => (body += c.toString()));`,
      `    req.on('end', () => resolve(body ? JSON.parse(body) : {}));`,
      `  });`,
      `}`,
      ``,
      `async function ensureUser() {`,
      `  let user = await prisma.user.findFirst();`,
      `  if (!user) user = await prisma.user.create({ data: { email: 'demo@pern.dev', name: 'Demo', password: 'demo' } });`,
      `  return user;`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'pern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = req.url || '';`,
      `        try {`,
      `          if (url === '/api/health') {`,
      `            const [boardCount, todoCount] = await Promise.all([prisma.board.count(), prisma.todo.count()]);`,
      `            return json(res, { status: 'ok', boards: boardCount, todos: todoCount, uptime: process.uptime() });`,
      `          }`,
      `          if (url === '/api/boards' && req.method === 'GET') {`,
      `            const user = await ensureUser();`,
      `            const boards = await prisma.board.findMany({ where: { userId: user.id }, orderBy: { createdAt: 'asc' } });`,
      `            return json(res, boards);`,
      `          }`,
      `          if (url === '/api/boards' && req.method === 'POST') {`,
      `            const user = await ensureUser();`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateBoardSchema.parse(body);`,
      `            const board = await prisma.board.create({ data: { name: parsed.name, icon: parsed.icon || '📁', userId: user.id } });`,
      `            return json(res, board, 201);`,
      `          }`,
      `          const boardMatch = url.match(/^\\/api\\/boards\\/(\\d+)$/);`,
      `          if (boardMatch && req.method === 'DELETE') {`,
      `            await prisma.board.delete({ where: { id: parseInt(boardMatch[1]) } });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          const todosMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/todos$/);`,
      `          if (todosMatch && req.method === 'GET') {`,
      `            const todos = await prisma.todo.findMany({ where: { boardId: parseInt(todosMatch[1]) }, orderBy: { position: 'asc' } });`,
      `            return json(res, todos);`,
      `          }`,
      `          if (todosMatch && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateTodoSchema.parse(body);`,
      `            const maxPos = await prisma.todo.aggregate({ where: { boardId: parseInt(todosMatch[1]) }, _max: { position: true } });`,
      `            const todo = await prisma.todo.create({ data: { title: parsed.title, boardId: parseInt(todosMatch[1]), position: (maxPos._max.position ?? -1) + 1 } });`,
      `            return json(res, todo, 201);`,
      `          }`,
      `          const reorderMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/reorder$/);`,
      `          if (reorderMatch && req.method === 'PUT') {`,
      `            const body = await parseBody(req);`,
      `            const { todoIds } = ReorderSchema.parse(body);`,
      `            await prisma.$transaction(todoIds.map((id, i) => prisma.todo.update({ where: { id }, data: { position: i } })));`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          const todoMatch = url.match(/^\\/api\\/todos\\/(\\d+)$/);`,
      `          if (todoMatch && req.method === 'PATCH') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = UpdateTodoSchema.parse(body);`,
      `            const todo = await prisma.todo.update({ where: { id: parseInt(todoMatch[1]) }, data: parsed });`,
      `            return json(res, todo);`,
      `          }`,
      `          if (todoMatch && req.method === 'DELETE') {`,
      `            await prisma.todo.delete({ where: { id: parseInt(todoMatch[1]) } });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', details: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/validation.ts',
    content: [
      `import { z } from 'zod';`,
      ``,
      `export const CreateBoardSchema = z.object({`,
      `  name: z.string().min(1, 'Board name is required').max(100),`,
      `  icon: z.string().max(4).optional(),`,
      `});`,
      ``,
      `export const CreateTodoSchema = z.object({`,
      `  title: z.string().min(1, 'Todo title is required').max(500),`,
      `});`,
      ``,
      `export const UpdateTodoSchema = z.object({`,
      `  title: z.string().min(1).max(500).optional(),`,
      `  done: z.boolean().optional(),`,
      `});`,
      ``,
      `export const ReorderSchema = z.object({`,
      `  todoIds: z.array(z.number().int()),`,
      `});`,
      ``,
      `export const CreateUserSchema = z.object({`,
      `  email: z.string().email('Invalid email'),`,
      `  name: z.string().min(1).max(100).optional(),`,
      `  password: z.string().min(8, 'Password must be at least 8 characters'),`,
      `});`,
      ``,
      `export type CreateBoardInput = z.infer<typeof CreateBoardSchema>;`,
      `export type CreateTodoInput = z.infer<typeof CreateTodoSchema>;`,
      `export type UpdateTodoInput = z.infer<typeof UpdateTodoSchema>;`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: [
      `# Database — switch to PostgreSQL for production`,
      `# DATABASE_URL="postgresql://user:pass@localhost:5432/pern_app"`,
      `DATABASE_URL="file:./prisma/dev.db"`,
      ``,
      `# Auth`,
      `JWT_SECRET="change-me-in-production"`,
      ``,
      `# Server`,
      `PORT=3000`,
      ``,
    ].join('\n'),
  },
];

const pernSolid: StackTemplate = {
  id: 'pern-solid',
  stackId: 'pern',
  tier: 'solid',
  name: 'PERN Solid',
  description: 'Production patterns — Prisma ORM, Zod validation, user model',
  features: [
    'Prisma ORM with Board + Todo + User models',
    'Zod schema validation on all inputs',
    'Cascading deletes (Board → Todos)',
    'Transaction-based reordering',
    'Auth scaffolding with User model',
    'Auto-migration on install',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER — Docker, Tests, CI/CD
   Adds: Dockerfile, docker-compose, Vitest, GitHub Actions
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
          'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
          'docker:build': 'docker build -t pern-app .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
          vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `COPY prisma ./prisma/`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `version: '3.9'`,
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: pern_app`,
      `      POSTGRES_USER: pern`,
      `      POSTGRES_PASSWORD: pern_secret`,
      `    ports:`,
      `      - '5432:5432'`,
      `    volumes:`,
      `      - pgdata:/var/lib/postgresql/data`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U pern']`,
      `      interval: 5s`,
      `      timeout: 5s`,
      `      retries: 5`,
      ``,
      `  app:`,
      `    build: .`,
      `    ports:`,
      `      - '3000:3000'`,
      `    depends_on:`,
      `      db:`,
      `        condition: service_healthy`,
      `    environment:`,
      `      DATABASE_URL: postgresql://pern:pern_secret@db:5432/pern_app`,
      `      NODE_ENV: production`,
      ``,
      `volumes:`,
      `  pgdata:`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: [
      `import { defineConfig } from 'vitest/config';`,
      ``,
      `export default defineConfig({`,
      `  test: {`,
      `    globals: true,`,
      `    environment: 'node',`,
      `    include: ['__tests__/**/*.test.ts'],`,
      `  },`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      `const ReorderSchema = z.object({ todoIds: z.array(z.number()) });`,
      ``,
      `describe('PERN Board API — Validation', () => {`,
      `  it('validates board creation', () => {`,
      `    expect(() => CreateBoardSchema.parse({ name: '' })).toThrow();`,
      `    expect(() => CreateBoardSchema.parse({ name: 'Work' })).not.toThrow();`,
      `    expect(CreateBoardSchema.parse({ name: 'Work', icon: '💼' })).toEqual({ name: 'Work', icon: '💼' });`,
      `  });`,
      ``,
      `  it('validates todo creation', () => {`,
      `    expect(() => CreateTodoSchema.parse({ title: '' })).toThrow();`,
      `    expect(() => CreateTodoSchema.parse({ title: 'a'.repeat(501) })).toThrow();`,
      `    expect(CreateTodoSchema.parse({ title: 'Build feature' })).toEqual({ title: 'Build feature' });`,
      `  });`,
      ``,
      `  it('validates reorder payload', () => {`,
      `    expect(() => ReorderSchema.parse({ todoIds: 'not-array' })).toThrow();`,
      `    expect(ReorderSchema.parse({ todoIds: [1, 2, 3] })).toEqual({ todoIds: [1, 2, 3] });`,
      `  });`,
      `});`,
      ``,
      `describe('Board data model', () => {`,
      `  it('boards contain todos with positions', () => {`,
      `    const board = { id: 1, name: 'Work', icon: '💼' };`,
      `    const todos = [`,
      `      { id: 1, boardId: 1, title: 'Task A', done: false, position: 0 },`,
      `      { id: 2, boardId: 1, title: 'Task B', done: true, position: 1 },`,
      `    ];`,
      `    expect(todos.filter(t => t.boardId === board.id)).toHaveLength(2);`,
      `    expect(todos.filter(t => t.done)).toHaveLength(1);`,
      `  });`,
      ``,
      `  it('reorder updates positions correctly', () => {`,
      `    const todos = [`,
      `      { id: 1, position: 0 },`,
      `      { id: 2, position: 1 },`,
      `      { id: 3, position: 2 },`,
      `    ];`,
      `    const newOrder = [3, 1, 2];`,
      `    newOrder.forEach((id, i) => {`,
      `      const t = todos.find(x => x.id === id)!;`,
      `      t.position = i;`,
      `    });`,
      `    expect(todos.find(t => t.id === 3)!.position).toBe(0);`,
      `    expect(todos.find(t => t.id === 1)!.position).toBe(1);`,
      `    expect(todos.find(t => t.id === 2)!.position).toBe(2);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with:`,
      `          node-version: 22`,
      `          cache: npm`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
      `  docker:`,
      `    needs: test`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - run: docker build -t pern-app .`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# PERN Stack — Battle-Tested`,
      ``,
      `Production-ready board task manager with PostgreSQL, Express, React, and Node.js.`,
      ``,
      `## Features`,
      `- 📋 Multiple boards with sidebar navigation`,
      `- ✨ Drag-to-reorder with Framer Motion`,
      `- 🗄️ Prisma ORM with SQLite (swappable to PostgreSQL)`,
      `- ✅ Zod validation on all inputs`,
      `- 🐳 Docker + Docker Compose`,
      `- 🧪 Vitest test suite`,
      `- 🔄 GitHub Actions CI/CD`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install`,
      `npm run dev`,
      `\`\`\``,
      ``,
      `## Docker (Production)`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `## Testing`,
      `\`\`\`bash`,
      `npm test           # Run once`,
      `npm run test:watch  # Watch mode`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const pernBattleTested: StackTemplate = {
  id: 'pern-battle-tested',
  stackId: 'pern',
  tier: 'battle-tested',
  name: 'PERN Battle-Tested',
  description: 'Deployment ready — Docker, tests, CI/CD pipeline',
  features: [
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite (validation + data model)',
    'GitHub Actions CI pipeline',
    'Multi-stage Docker build',
    'Production-ready Dockerfile',
    'Everything from Solid tier',
  ],
  files: mergeFiles(pernSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER — VeggaAI Premium: monitoring, error boundaries, hooks
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
          'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
          'docker:build': 'docker build -t pern-vai .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
          vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Multi-Stage Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci --ignore-scripts && npx prisma generate`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      `RUN npm prune --production`,
      ``,
      `FROM node:22-alpine AS runner`,
      `WORKDIR /app`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/monitor.ts',
    content: [
      `/**`,
      ` * VeggaAI Performance Monitor — lightweight request tracing.`,
      ` */`,
      `interface RequestMetric {`,
      `  path: string; method: string; status: number; duration: number; timestamp: number;`,
      `}`,
      ``,
      `const metrics: RequestMetric[] = [];`,
      `const MAX_METRICS = 1000;`,
      ``,
      `export function recordMetric(metric: RequestMetric) {`,
      `  metrics.push(metric);`,
      `  if (metrics.length > MAX_METRICS) metrics.shift();`,
      `}`,
      ``,
      `export function getMetricsSummary() {`,
      `  const last5m = metrics.filter(m => m.timestamp > Date.now() - 5 * 60 * 1000);`,
      `  const avgDuration = last5m.length ? last5m.reduce((s, m) => s + m.duration, 0) / last5m.length : 0;`,
      `  const errorRate = last5m.length ? last5m.filter(m => m.status >= 400).length / last5m.length : 0;`,
      `  return {`,
      `    totalRequests: metrics.length,`,
      `    last5min: last5m.length,`,
      `    avgResponseMs: Math.round(avgDuration * 100) / 100,`,
      `    errorRate: Math.round(errorRate * 10000) / 100,`,
      `    uptime: process.uptime(),`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/ErrorBoundary.tsx',
    content: [
      `import { Component, type ReactNode, type ErrorInfo } from 'react';`,
      ``,
      `interface Props { children: ReactNode; fallback?: ReactNode; }`,
      `interface State { hasError: boolean; error: Error | null; }`,
      ``,
      `export class ErrorBoundary extends Component<Props, State> {`,
      `  state: State = { hasError: false, error: null };`,
      `  static getDerivedStateFromError(error: Error): State { return { hasError: true, error }; }`,
      `  componentDidCatch(error: Error, info: ErrorInfo) { console.error('[Vai ErrorBoundary]', error, info.componentStack); }`,
      `  render() {`,
      `    if (this.state.hasError) {`,
      `      return this.props.fallback ?? (`,
      `        <div style={{ padding: 40, textAlign: 'center', color: '#ef4444' }}>`,
      `          <h2>Something went wrong</h2>`,
      `          <pre style={{ fontSize: '0.8rem', color: '#71717a', marginTop: 8 }}>{this.state.error?.message}</pre>`,
      `          <button onClick={() => this.setState({ hasError: false, error: null })}`,
      `            style={{ marginTop: 16, padding: '8px 16px', borderRadius: 8, background: '#27272a', color: '#e4e4e7', border: 'none', cursor: 'pointer' }}>`,
      `            Try Again`,
      `          </button>`,
      `        </div>`,
      `      );`,
      `    }`,
      `    return this.props.children;`,
      `  }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/hooks/useApi.ts',
    content: [
      `import { useState, useCallback } from 'react';`,
      ``,
      `interface UseApiOptions<T> { onSuccess?: (data: T) => void; onError?: (error: Error) => void; }`,
      ``,
      `export function useApi<T>(url: string, options?: UseApiOptions<T>) {`,
      `  const [data, setData] = useState<T | null>(null);`,
      `  const [loading, setLoading] = useState(false);`,
      `  const [error, setError] = useState<Error | null>(null);`,
      ``,
      `  const execute = useCallback(async (init?: RequestInit) => {`,
      `    setLoading(true); setError(null);`,
      `    try {`,
      `      const res = await fetch(url, init);`,
      `      if (!res.ok) throw new Error(\`HTTP \${res.status}\`);`,
      `      const json = await res.json();`,
      `      setData(json); options?.onSuccess?.(json);`,
      `      return json as T;`,
      `    } catch (err) {`,
      `      const e = err instanceof Error ? err : new Error(String(err));`,
      `      setError(e); options?.onError?.(e); throw e;`,
      `    } finally { setLoading(false); }`,
      `  }, [url]);`,
      ``,
      `  return { data, loading, error, execute };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      ``,
      `describe('PERN Vai — Validation', () => {`,
      `  it('validates board creation', () => {`,
      `    expect(() => CreateBoardSchema.parse({ name: '' })).toThrow();`,
      `    expect(CreateBoardSchema.parse({ name: 'Work', icon: '💼' })).toEqual({ name: 'Work', icon: '💼' });`,
      `  });`,
      ``,
      `  it('validates todo creation', () => {`,
      `    expect(() => CreateTodoSchema.parse({ title: '' })).toThrow();`,
      `    expect(() => CreateTodoSchema.parse({ title: 'a'.repeat(501) })).toThrow();`,
      `    expect(CreateTodoSchema.parse({ title: 'Valid' })).toEqual({ title: 'Valid' });`,
      `  });`,
      `});`,
      ``,
      `describe('Vai — Data Model', () => {`,
      `  it('board contains todos with positions', () => {`,
      `    const todos = [{ id: 1, pos: 0 }, { id: 2, pos: 1 }, { id: 3, pos: 2 }];`,
      `    expect(todos.sort((a, b) => a.pos - b.pos).map(t => t.id)).toEqual([1, 2, 3]);`,
      `  });`,
      ``,
      `  it('reorder respects new positions', () => {`,
      `    const todos = [{ id: 1, pos: 0 }, { id: 2, pos: 1 }, { id: 3, pos: 2 }];`,
      `    [3, 1, 2].forEach((id, i) => { todos.find(t => t.id === id)!.pos = i; });`,
      `    expect(todos.sort((a, b) => a.pos - b.pos).map(t => t.id)).toEqual([3, 1, 2]);`,
      `  });`,
      ``,
      `  it('monitors track metrics', () => {`,
      `    const m: { path: string; duration: number }[] = [];`,
      `    m.push({ path: '/api/boards', duration: 12 });`,
      `    m.push({ path: '/api/todos', duration: 8 });`,
      `    const avg = m.reduce((s, x) => s + x.duration, 0) / m.length;`,
      `    expect(avg).toBe(10);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'pern-vai',`,
      `  version: '1.0.0',`,
      `  stack: 'pern',`,
      `  tier: 'vai',`,
      `  features: { monitoring: true, errorBoundary: true, typeContract: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 PERN Board — Vai Premium`,
      ``,
      `> VeggaAI's curated PERN board task manager.`,
      ``,
      `## Features`,
      `- 📋 Multiple boards with sidebar navigation`,
      `- ✨ Drag-to-reorder with Framer Motion`,
      `- 🗄️ Prisma ORM (SQLite dev / PostgreSQL prod)`,
      `- ✅ Zod validation on all inputs`,
      `- 📊 Performance monitoring middleware`,
      `- 🛡️ React ErrorBoundary component`,
      `- 🎣 Type-safe \`useApi\` hook`,
      `- 🐳 Optimized multi-stage Docker build`,
      `- 🧪 Vitest test suite`,
      `- 🔄 GitHub Actions CI/CD`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install`,
      `npm run dev`,
      `\`\`\``,
      ``,
      `## Production`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `---`,
      `*Built with VeggaAI — Local-first AI that learns from you.*`,
      ``,
    ].join('\n'),
  },
];

const pernVai: StackTemplate = {
  id: 'pern-vai',
  stackId: 'pern',
  tier: 'vai',
  name: 'PERN Vai',
  description: "VeggaAI's premium PERN — monitoring, error boundaries, optimized Docker",
  features: [
    'Multi-stage Docker (non-root, healthcheck)',
    'Performance monitoring middleware',
    'React ErrorBoundary component',
    'Type-safe useApi hook',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(pernBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT PERN STACK DEFINITION
   ================================================================ */

export const pernStack: StackDefinition = {
  id: 'pern',
  name: 'PERN',
  tagline: 'The classic full-stack combo',
  description: 'PostgreSQL + Express + React + Node.js — battle-proven stack for production apps',
  techStack: ['PostgreSQL', 'Express', 'React', 'Node.js'],
  icon: '🐘',
  color: 'blue',
  templates: [pernBasic, pernSolid, pernBattleTested, pernVai],
};
