/**
 * PERN Stack — PostgreSQL + Express + React + Node.js
 * All four tiers from basic board task manager to Vai premium.
 *
 * Dev approach: Vite serves frontend, custom Vite plugin provides API routes.
 * This keeps the sandbox single-port and works with `npm run dev -- --port X`.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Board Task Manager with Framer Motion drag-to-reorder
   Features: Multiple boards, sidebar navigation, edit/view mode toggle,
   drag-to-reorder with Framer Motion, responsive design, position ordering.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-basic',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          'lucide-react': '^0.513.0',
          clsx: '^2.1.1',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          '@tailwindcss/vite': '^4.1.0',
          tailwindcss: '^4.1.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import tailwindcss from '@tailwindcss/vite';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({`,
      `  plugins: [react(), tailwindcss(), apiPlugin()],`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022',
          module: 'ESNext',
          moduleResolution: 'bundler',
          jsx: 'react-jsx',
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          forceConsistentCasingInFileNames: true,
          outDir: 'dist',
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" />`,
      `  <meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>PERN Board</title>`,
      `  <link rel="preconnect" href="https://fonts.googleapis.com" />`,
      `  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />`,
      `</head>`,
      `<body>`,
      `  <div id="root"></div>`,
      `  <script type="module" src="/src/main.tsx"></script>`,
      `</body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      ``,
      `/* ── Data Models ── */`,
      `interface Board { id: number; name: string; icon: string; createdAt: string; }`,
      `interface Todo {`,
      `  id: number; boardId: number; title: string; done: boolean;`,
      `  position: number; createdAt: string;`,
      `}`,
      ``,
      `const ICONS = ['📁', '🏠', '☀️', '🎯', '📚', '💡', '🚀', '🎨', '🔥', '⭐'];`,
      `let boardSeq = 4;`,
      `let todoSeq = 10;`,
      ``,
      `const boards: Board[] = [`,
      `  { id: 1, name: 'Work', icon: '💼', createdAt: new Date().toISOString() },`,
      `  { id: 2, name: 'Personal', icon: '🏠', createdAt: new Date().toISOString() },`,
      `  { id: 3, name: 'Today', icon: '☀️', createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `const todos: Todo[] = [`,
      `  { id: 1, boardId: 1, title: 'Set up project structure', done: true, position: 0, createdAt: new Date().toISOString() },`,
      `  { id: 2, boardId: 1, title: 'Design the database schema', done: true, position: 1, createdAt: new Date().toISOString() },`,
      `  { id: 3, boardId: 1, title: 'Build REST API endpoints', done: false, position: 2, createdAt: new Date().toISOString() },`,
      `  { id: 4, boardId: 1, title: 'Connect React frontend', done: false, position: 3, createdAt: new Date().toISOString() },`,
      `  { id: 5, boardId: 1, title: 'Add drag-to-reorder feature', done: false, position: 4, createdAt: new Date().toISOString() },`,
      `  { id: 6, boardId: 2, title: 'Grocery shopping', done: false, position: 0, createdAt: new Date().toISOString() },`,
      `  { id: 7, boardId: 2, title: 'Read "Designing Data-Intensive Apps"', done: false, position: 1, createdAt: new Date().toISOString() },`,
      `  { id: 8, boardId: 2, title: 'Call dentist for appointment', done: true, position: 2, createdAt: new Date().toISOString() },`,
      `  { id: 9, boardId: 3, title: 'Morning standup at 9am', done: true, position: 0, createdAt: new Date().toISOString() },`,
      `];`,
      ``,
      `/* ── Helpers ── */`,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<Record<string, unknown>> {`,
      `  return new Promise((resolve) => {`,
      `    let body = '';`,
      `    req.on('data', (c: Buffer) => (body += c.toString()));`,
      `    req.on('end', () => resolve(body ? JSON.parse(body) : {}));`,
      `  });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'pern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = req.url || '';`,
      `        try {`,
      `          /* Health */`,
      `          if (url === '/api/health') {`,
      `            return json(res, { status: 'ok', boards: boards.length, todos: todos.length, uptime: process.uptime() });`,
      `          }`,
      `          /* GET /api/boards */`,
      `          if (url === '/api/boards' && req.method === 'GET') return json(res, boards);`,
      `          /* POST /api/boards */`,
      `          if (url === '/api/boards' && req.method === 'POST') {`,
      `            const { name, icon } = await parseBody(req);`,
      `            const board: Board = {`,
      `              id: boardSeq++, name: name as string,`,
      `              icon: (icon as string) || ICONS[Math.floor(Math.random() * ICONS.length)],`,
      `              createdAt: new Date().toISOString(),`,
      `            };`,
      `            boards.push(board);`,
      `            return json(res, board, 201);`,
      `          }`,
      `          /* Board-specific routes */`,
      `          const boardMatch = url.match(/^\\/api\\/boards\\/(\\d+)$/);`,
      `          if (boardMatch) {`,
      `            const bid = parseInt(boardMatch[1]);`,
      `            if (req.method === 'DELETE') {`,
      `              const idx = boards.findIndex(b => b.id === bid);`,
      `              if (idx !== -1) boards.splice(idx, 1);`,
      `              for (let i = todos.length - 1; i >= 0; i--) { if (todos[i].boardId === bid) todos.splice(i, 1); }`,
      `              return json(res, { ok: true });`,
      `            }`,
      `          }`,
      `          /* GET /api/boards/:id/todos */`,
      `          const todosMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/todos$/);`,
      `          if (todosMatch && req.method === 'GET') {`,
      `            const bid = parseInt(todosMatch[1]);`,
      `            return json(res, todos.filter(t => t.boardId === bid).sort((a, b) => a.position - b.position));`,
      `          }`,
      `          /* POST /api/boards/:id/todos */`,
      `          if (todosMatch && req.method === 'POST') {`,
      `            const bid = parseInt(todosMatch[1]);`,
      `            const { title } = await parseBody(req);`,
      `            const boardTodos = todos.filter(t => t.boardId === bid);`,
      `            const maxPos = boardTodos.length ? Math.max(...boardTodos.map(t => t.position)) : -1;`,
      `            const todo: Todo = { id: todoSeq++, boardId: bid, title: title as string, done: false, position: maxPos + 1, createdAt: new Date().toISOString() };`,
      `            todos.push(todo);`,
      `            return json(res, todo, 201);`,
      `          }`,
      `          /* PUT /api/boards/:id/reorder */`,
      `          const reorderMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/reorder$/);`,
      `          if (reorderMatch && req.method === 'PUT') {`,
      `            const { todoIds } = await parseBody(req);`,
      `            (todoIds as number[]).forEach((id, i) => { const t = todos.find(x => x.id === id); if (t) t.position = i; });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          /* PATCH /api/todos/:id */`,
      `          const todoMatch = url.match(/^\\/api\\/todos\\/(\\d+)$/);`,
      `          if (todoMatch && req.method === 'PATCH') {`,
      `            const id = parseInt(todoMatch[1]);`,
      `            const updates = await parseBody(req);`,
      `            const todo = todos.find(t => t.id === id);`,
      `            if (todo) Object.assign(todo, updates);`,
      `            return json(res, todo);`,
      `          }`,
      `          /* DELETE /api/todos/:id */`,
      `          if (todoMatch && req.method === 'DELETE') {`,
      `            const id = parseInt(todoMatch[1]);`,
      `            const idx = todos.findIndex(t => t.id === id);`,
      `            if (idx !== -1) todos.splice(idx, 1);`,
      `            return json(res, { ok: true });`,
      `          }`,
      `        } catch (err) {`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: [
      `import { createRoot } from 'react-dom/client';`,
      `import { App } from './App';`,
      `import './index.css';`,
      ``,
      `createRoot(document.getElementById('root')!).render(<App />);`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { Reorder, AnimatePresence, motion } from 'framer-motion';`,
      `import { LayoutGrid, Plus, Trash2, GripVertical, Menu, X, Pencil, Eye, CheckCircle2, Circle, Sparkles } from 'lucide-react';`,
      `import clsx from 'clsx';`,
      ``,
      `interface Board { id: number; name: string; icon: string; }`,
      `interface Todo { id: number; boardId: number; title: string; done: boolean; position: number; }`,
      ``,
      `export function App() {`,
      `  const [boards, setBoards] = useState<Board[]>([]);`,
      `  const [todos, setTodos] = useState<Todo[]>([]);`,
      `  const [activeBoard, setActiveBoard] = useState<number | null>(null);`,
      `  const [editMode, setEditMode] = useState(false);`,
      `  const [sidebarOpen, setSidebarOpen] = useState(window.innerWidth > 768);`,
      `  const [newTodo, setNewTodo] = useState('');`,
      `  const [newBoard, setNewBoard] = useState('');`,
      `  const [loading, setLoading] = useState(true);`,
      ``,
      `  useEffect(() => {`,
      `    fetch('/api/boards').then(r => r.json()).then((data: Board[]) => {`,
      `      setBoards(data);`,
      `      if (data.length) setActiveBoard(data[0].id);`,
      `      setLoading(false);`,
      `    });`,
      `  }, []);`,
      ``,
      `  useEffect(() => {`,
      `    if (!activeBoard) return;`,
      `    fetch(\`/api/boards/\${activeBoard}/todos\`).then(r => r.json()).then(setTodos);`,
      `  }, [activeBoard]);`,
      ``,
      `  const addTodo = async () => {`,
      `    if (!newTodo.trim() || !activeBoard) return;`,
      `    const r = await fetch(\`/api/boards/\${activeBoard}/todos\`, {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ title: newTodo }),`,
      `    });`,
      `    const created = await r.json();`,
      `    setTodos(prev => [...prev, created]);`,
      `    setNewTodo('');`,
      `  };`,
      ``,
      `  const toggleTodo = async (id: number) => {`,
      `    const t = todos.find(x => x.id === id)!;`,
      `    await fetch(\`/api/todos/\${id}\`, {`,
      `      method: 'PATCH', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ done: !t.done }),`,
      `    });`,
      `    setTodos(prev => prev.map(x => x.id === id ? { ...x, done: !x.done } : x));`,
      `  };`,
      ``,
      `  const deleteTodo = async (id: number) => {`,
      `    await fetch(\`/api/todos/\${id}\`, { method: 'DELETE' });`,
      `    setTodos(prev => prev.filter(x => x.id !== id));`,
      `  };`,
      ``,
      `  const handleReorder = (newOrder: Todo[]) => {`,
      `    setTodos(newOrder);`,
      `    if (activeBoard) {`,
      `      fetch(\`/api/boards/\${activeBoard}/reorder\`, {`,
      `        method: 'PUT', headers: { 'Content-Type': 'application/json' },`,
      `        body: JSON.stringify({ todoIds: newOrder.map(t => t.id) }),`,
      `      });`,
      `    }`,
      `  };`,
      ``,
      `  const addBoard = async () => {`,
      `    if (!newBoard.trim()) return;`,
      `    const r = await fetch('/api/boards', {`,
      `      method: 'POST', headers: { 'Content-Type': 'application/json' },`,
      `      body: JSON.stringify({ name: newBoard }),`,
      `    });`,
      `    const board = await r.json();`,
      `    setBoards(prev => [...prev, board]);`,
      `    setActiveBoard(board.id);`,
      `    setNewBoard('');`,
      `  };`,
      ``,
      `  const deleteBoard = async (id: number) => {`,
      `    await fetch(\`/api/boards/\${id}\`, { method: 'DELETE' });`,
      `    const remaining = boards.filter(b => b.id !== id);`,
      `    setBoards(remaining);`,
      `    if (activeBoard === id) setActiveBoard(remaining[0]?.id ?? null);`,
      `  };`,
      ``,
      `  const active = boards.find(b => b.id === activeBoard);`,
      `  const doneCount = todos.filter(t => t.done).length;`,
      `  const pct = todos.length ? Math.round((doneCount / todos.length) * 100) : 0;`,
      ``,
      `  return (`,
      `    <div className="flex h-screen overflow-hidden bg-zinc-950 text-zinc-200 font-sans">`,
      `      {sidebarOpen && (`,
      `        <div className="fixed inset-0 z-40 bg-black/60 md:hidden" onClick={() => setSidebarOpen(false)} />`,
      `      )}`,
      ``,
      `      <aside className={clsx(`,
      `        'fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-zinc-800/80 bg-zinc-950 transition-transform duration-200 md:static md:translate-x-0',`,
      `        sidebarOpen ? 'translate-x-0 shadow-2xl' : '-translate-x-full'`,
      `      )}>`,
      `        <div className="flex items-center justify-between border-b border-zinc-800/80 px-4 py-4">`,
      `          <div className="flex items-center gap-2">`,
      `            <LayoutGrid className="h-4 w-4 text-blue-400" />`,
      `            <span className="text-sm font-semibold tracking-tight">Boards</span>`,
      `          </div>`,
      `          <button onClick={() => setSidebarOpen(false)} className="rounded-md p-1 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-300 md:hidden">`,
      `            <X className="h-4 w-4" />`,
      `          </button>`,
      `        </div>`,
      ``,
      `        <nav className="flex-1 space-y-0.5 overflow-y-auto p-2">`,
      `          {boards.map(b => (`,
      `            <button key={b.id} onClick={() => { setActiveBoard(b.id); if (window.innerWidth <= 768) setSidebarOpen(false); }}`,
      `              className={clsx(`,
      `                'group flex w-full items-center gap-2.5 rounded-lg px-3 py-2.5 text-left text-sm transition-colors',`,
      `                b.id === activeBoard`,
      `                  ? 'bg-blue-500/10 text-blue-400'`,
      `                  : 'text-zinc-400 hover:bg-zinc-800/60 hover:text-zinc-200'`,
      `              )}>`,
      `              <span className="shrink-0 text-base">{b.icon}</span>`,
      `              <span className="flex-1 truncate">{b.name}</span>`,
      `              <span onClick={e => { e.stopPropagation(); deleteBoard(b.id); }}`,
      `                className="hidden rounded p-0.5 text-zinc-600 hover:bg-zinc-700 hover:text-red-400 group-hover:block">`,
      `                <Trash2 className="h-3.5 w-3.5" />`,
      `              </span>`,
      `            </button>`,
      `          ))}`,
      `        </nav>`,
      ``,
      `        <div className="border-t border-zinc-800/80 p-3">`,
      `          <div className="flex gap-1.5">`,
      `            <input value={newBoard} onChange={e => setNewBoard(e.target.value)}`,
      `              onKeyDown={e => e.key === 'Enter' && addBoard()}`,
      `              placeholder="New board..."`,
      `              className="flex-1 rounded-md border border-zinc-800 bg-zinc-900 px-2.5 py-1.5 text-xs text-zinc-200 placeholder-zinc-600 outline-none focus:border-blue-500/50" />`,
      `            <button onClick={addBoard} className="rounded-md bg-blue-500/15 px-2.5 py-1.5 text-blue-400 transition-colors hover:bg-blue-500/25">`,
      `              <Plus className="h-3.5 w-3.5" />`,
      `            </button>`,
      `          </div>`,
      `        </div>`,
      `      </aside>`,
      ``,
      `      <main className="flex min-w-0 flex-1 flex-col overflow-hidden">`,
      `        <header className="flex shrink-0 items-center gap-3 border-b border-zinc-800/80 px-6 py-3.5">`,
      `          <button onClick={() => setSidebarOpen(true)} className="rounded-md p-1.5 text-zinc-400 hover:bg-zinc-800 hover:text-zinc-200 md:hidden">`,
      `            <Menu className="h-5 w-5" />`,
      `          </button>`,
      `          <div className="min-w-0 flex-1">`,
      `            <h1 className="truncate text-lg font-semibold tracking-tight">`,
      `              {active ? \`\${active.icon} \${active.name}\` : 'Select a board'}`,
      `            </h1>`,
      `            {todos.length > 0 && (`,
      `              <div className="mt-1 flex items-center gap-2">`,
      `                <div className="h-1 w-28 overflow-hidden rounded-full bg-zinc-800">`,
      `                  <div className="h-full rounded-full bg-blue-500 transition-all duration-300" style={{ width: \`\${pct}%\` }} />`,
      `                </div>`,
      `                <span className="text-xs text-zinc-500">{doneCount}/{todos.length}</span>`,
      `              </div>`,
      `            )}`,
      `          </div>`,
      `          <button onClick={() => setEditMode(!editMode)} className={clsx(`,
      `            'flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors',`,
      `            editMode ? 'bg-blue-500/15 text-blue-400' : 'bg-zinc-800/60 text-zinc-400 hover:text-zinc-200'`,
      `          )}>`,
      `            {editMode ? <><Pencil className="h-3 w-3" /> Edit</> : <><Eye className="h-3 w-3" /> View</>}`,
      `          </button>`,
      `        </header>`,
      ``,
      `        <div className="flex shrink-0 gap-2 px-6 py-3">`,
      `          <input value={newTodo} onChange={e => setNewTodo(e.target.value)}`,
      `            onKeyDown={e => e.key === 'Enter' && addTodo()}`,
      `            placeholder="What needs to be done?"`,
      `            className="flex-1 rounded-lg border border-zinc-800 bg-zinc-900 px-4 py-2.5 text-sm text-zinc-200 placeholder-zinc-600 outline-none transition-colors focus:border-blue-500/50" />`,
      `          <button onClick={addTodo}`,
      `            className="flex shrink-0 items-center gap-1.5 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-blue-500">`,
      `            <Plus className="h-4 w-4" /> Add`,
      `          </button>`,
      `        </div>`,
      ``,
      `        <div className="flex-1 overflow-y-auto px-6 pb-6">`,
      `          {loading ? (`,
      `            <div className="space-y-2 pt-4">`,
      `              {[...Array(4)].map((_, i) => (`,
      `                <div key={i} className="h-12 animate-pulse rounded-xl bg-zinc-900" />`,
      `              ))}`,
      `            </div>`,
      `          ) : !activeBoard ? (`,
      `            <div className="flex flex-col items-center justify-center py-20 text-center">`,
      `              <LayoutGrid className="mb-3 h-12 w-12 text-zinc-800" />`,
      `              <p className="text-sm text-zinc-500">Create a board to get started</p>`,
      `            </div>`,
      `          ) : todos.length === 0 ? (`,
      `            <div className="flex flex-col items-center justify-center py-20 text-center">`,
      `              <Sparkles className="mb-3 h-12 w-12 text-zinc-800" />`,
      `              <p className="text-sm text-zinc-500">No tasks yet — add one above!</p>`,
      `            </div>`,
      `          ) : editMode ? (`,
      `            <Reorder.Group axis="y" values={todos} onReorder={handleReorder} className="space-y-1">`,
      `              {todos.map(t => (`,
      `                <Reorder.Item key={t.id} value={t}`,
      `                  whileDrag={{ scale: 1.02, boxShadow: '0 8px 24px rgba(59,130,246,0.12)' }}`,
      `                  className={clsx(`,
      `                    'group flex items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-900 px-3.5 py-3 transition-colors hover:border-zinc-700',`,
      `                    t.done && 'opacity-50'`,
      `                  )}>`,
      `                  <GripVertical className="h-4 w-4 shrink-0 cursor-grab text-zinc-600 active:cursor-grabbing" />`,
      `                  <button onClick={() => toggleTodo(t.id)} className="shrink-0">`,
      `                    {t.done ? <CheckCircle2 className="h-5 w-5 text-blue-400" /> : <Circle className="h-5 w-5 text-zinc-600" />}`,
      `                  </button>`,
      `                  <span className={clsx('flex-1 text-sm', t.done && 'text-zinc-600 line-through')}>{t.title}</span>`,
      `                  <button onClick={() => deleteTodo(t.id)}`,
      `                    className="rounded p-1 text-zinc-600 opacity-0 transition-all hover:bg-zinc-800 hover:text-red-400 group-hover:opacity-100">`,
      `                    <Trash2 className="h-3.5 w-3.5" />`,
      `                  </button>`,
      `                </Reorder.Item>`,
      `              ))}`,
      `            </Reorder.Group>`,
      `          ) : (`,
      `            <ul className="space-y-1 list-none">`,
      `              <AnimatePresence mode="popLayout">`,
      `                {todos.map(t => (`,
      `                  <motion.li key={t.id}`,
      `                    initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}`,
      `                    exit={{ opacity: 0, x: -80 }} layout`,
      `                    className={clsx(`,
      `                      'group flex items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-900 px-3.5 py-3 transition-colors hover:border-zinc-700',`,
      `                      t.done && 'opacity-50'`,
      `                    )}>`,
      `                    <button onClick={() => toggleTodo(t.id)} className="shrink-0">`,
      `                      {t.done ? <CheckCircle2 className="h-5 w-5 text-blue-400" /> : <Circle className="h-5 w-5 text-zinc-600 hover:text-zinc-400" />}`,
      `                    </button>`,
      `                    <span className={clsx('flex-1 text-sm', t.done && 'text-zinc-600 line-through')}>{t.title}</span>`,
      `                    <button onClick={() => deleteTodo(t.id)}`,
      `                      className="rounded p-1 text-zinc-600 opacity-0 transition-all hover:bg-zinc-800 hover:text-red-400 group-hover:opacity-100">`,
      `                      <Trash2 className="h-3.5 w-3.5" />`,
      `                    </button>`,
      `                  </motion.li>`,
      `                ))}`,
      `              </AnimatePresence>`,
      `            </ul>`,
      `          )}`,
      `        </div>`,
      `      </main>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `@import "tailwindcss";`,
      ``,
      `@theme {`,
      `  --font-sans: 'Inter', system-ui, -apple-system, sans-serif;`,
      `}`,
      ``,
    ].join('\n'),
  },
];

const pernBasic: StackTemplate = {
  id: 'pern-basic',
  stackId: 'pern',
  tier: 'basic',
  name: 'PERN Basic',
  description: 'Board task manager — multiple boards, drag-to-reorder, responsive sidebar',
  features: [
    'Multiple boards with sidebar navigation',
    'Drag-to-reorder with Framer Motion',
    'Edit/View mode toggle',
    'Responsive design (mobile sidebar drawer)',
    'Progress tracking per board',
    'In-memory data store (swap to PostgreSQL)',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Prisma ORM + Zod validation + Auth scaffolding
   Adds: real database, input validation, user model
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-solid',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          'lucide-react': '^0.513.0',
          clsx: '^2.1.1',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          '@tailwindcss/vite': '^4.1.0',
          tailwindcss: '^4.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `// PERN Solid — Prisma schema`,
      `// Switch provider to "postgresql" and update url for production`,
      `generator client {`,
      `  provider = "prisma-client-js"`,
      `}`,
      ``,
      `datasource db {`,
      `  provider = "sqlite"`,
      `  url      = "file:./dev.db"`,
      `}`,
      ``,
      `model User {`,
      `  id        Int      @id @default(autoincrement())`,
      `  email     String   @unique`,
      `  name      String?`,
      `  password  String`,
      `  boards    Board[]`,
      `  createdAt DateTime @default(now())`,
      `}`,
      ``,
      `model Board {`,
      `  id        Int      @id @default(autoincrement())`,
      `  name      String`,
      `  icon      String   @default("📁")`,
      `  userId    Int`,
      `  user      User     @relation(fields: [userId], references: [id])`,
      `  todos     Todo[]`,
      `  createdAt DateTime @default(now())`,
      `}`,
      ``,
      `model Todo {`,
      `  id        Int      @id @default(autoincrement())`,
      `  title     String`,
      `  done      Boolean  @default(false)`,
      `  position  Int      @default(0)`,
      `  boardId   Int`,
      `  board     Board    @relation(fields: [boardId], references: [id], onDelete: Cascade)`,
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { z } from 'zod';`,
      ``,
      `const prisma = new PrismaClient();`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      `const UpdateTodoSchema = z.object({ title: z.string().min(1).max(500).optional(), done: z.boolean().optional() });`,
      `const ReorderSchema = z.object({ todoIds: z.array(z.number()) });`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status;`,
      `  res.setHeader('Content-Type', 'application/json');`,
      `  res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<Record<string, unknown>> {`,
      `  return new Promise((resolve) => {`,
      `    let body = '';`,
      `    req.on('data', (c: Buffer) => (body += c.toString()));`,
      `    req.on('end', () => resolve(body ? JSON.parse(body) : {}));`,
      `  });`,
      `}`,
      ``,
      `async function ensureUser() {`,
      `  let user = await prisma.user.findFirst();`,
      `  if (!user) user = await prisma.user.create({ data: { email: 'demo@pern.dev', name: 'Demo', password: 'demo' } });`,
      `  return user;`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 'pern-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = req.url || '';`,
      `        try {`,
      `          if (url === '/api/health') {`,
      `            const [boardCount, todoCount] = await Promise.all([prisma.board.count(), prisma.todo.count()]);`,
      `            return json(res, { status: 'ok', boards: boardCount, todos: todoCount, uptime: process.uptime() });`,
      `          }`,
      `          if (url === '/api/boards' && req.method === 'GET') {`,
      `            const user = await ensureUser();`,
      `            const boards = await prisma.board.findMany({ where: { userId: user.id }, orderBy: { createdAt: 'asc' } });`,
      `            return json(res, boards);`,
      `          }`,
      `          if (url === '/api/boards' && req.method === 'POST') {`,
      `            const user = await ensureUser();`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateBoardSchema.parse(body);`,
      `            const board = await prisma.board.create({ data: { name: parsed.name, icon: parsed.icon || '📁', userId: user.id } });`,
      `            return json(res, board, 201);`,
      `          }`,
      `          const boardMatch = url.match(/^\\/api\\/boards\\/(\\d+)$/);`,
      `          if (boardMatch && req.method === 'DELETE') {`,
      `            await prisma.board.delete({ where: { id: parseInt(boardMatch[1]) } });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          const todosMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/todos$/);`,
      `          if (todosMatch && req.method === 'GET') {`,
      `            const todos = await prisma.todo.findMany({ where: { boardId: parseInt(todosMatch[1]) }, orderBy: { position: 'asc' } });`,
      `            return json(res, todos);`,
      `          }`,
      `          if (todosMatch && req.method === 'POST') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = CreateTodoSchema.parse(body);`,
      `            const maxPos = await prisma.todo.aggregate({ where: { boardId: parseInt(todosMatch[1]) }, _max: { position: true } });`,
      `            const todo = await prisma.todo.create({ data: { title: parsed.title, boardId: parseInt(todosMatch[1]), position: (maxPos._max.position ?? -1) + 1 } });`,
      `            return json(res, todo, 201);`,
      `          }`,
      `          const reorderMatch = url.match(/^\\/api\\/boards\\/(\\d+)\\/reorder$/);`,
      `          if (reorderMatch && req.method === 'PUT') {`,
      `            const body = await parseBody(req);`,
      `            const { todoIds } = ReorderSchema.parse(body);`,
      `            await prisma.$transaction(todoIds.map((id, i) => prisma.todo.update({ where: { id }, data: { position: i } })));`,
      `            return json(res, { ok: true });`,
      `          }`,
      `          const todoMatch = url.match(/^\\/api\\/todos\\/(\\d+)$/);`,
      `          if (todoMatch && req.method === 'PATCH') {`,
      `            const body = await parseBody(req);`,
      `            const parsed = UpdateTodoSchema.parse(body);`,
      `            const todo = await prisma.todo.update({ where: { id: parseInt(todoMatch[1]) }, data: parsed });`,
      `            return json(res, todo);`,
      `          }`,
      `          if (todoMatch && req.method === 'DELETE') {`,
      `            await prisma.todo.delete({ where: { id: parseInt(todoMatch[1]) } });`,
      `            return json(res, { ok: true });`,
      `          }`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', details: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `        next();`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/validation.ts',
    content: [
      `import { z } from 'zod';`,
      ``,
      `export const CreateBoardSchema = z.object({`,
      `  name: z.string().min(1, 'Board name is required').max(100),`,
      `  icon: z.string().max(4).optional(),`,
      `});`,
      ``,
      `export const CreateTodoSchema = z.object({`,
      `  title: z.string().min(1, 'Todo title is required').max(500),`,
      `});`,
      ``,
      `export const UpdateTodoSchema = z.object({`,
      `  title: z.string().min(1).max(500).optional(),`,
      `  done: z.boolean().optional(),`,
      `});`,
      ``,
      `export const ReorderSchema = z.object({`,
      `  todoIds: z.array(z.number().int()),`,
      `});`,
      ``,
      `export const CreateUserSchema = z.object({`,
      `  email: z.string().email('Invalid email'),`,
      `  name: z.string().min(1).max(100).optional(),`,
      `  password: z.string().min(8, 'Password must be at least 8 characters'),`,
      `});`,
      ``,
      `export type CreateBoardInput = z.infer<typeof CreateBoardSchema>;`,
      `export type CreateTodoInput = z.infer<typeof CreateTodoSchema>;`,
      `export type UpdateTodoInput = z.infer<typeof UpdateTodoSchema>;`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: [
      `# Database — switch to PostgreSQL for production`,
      `# DATABASE_URL="postgresql://user:pass@localhost:5432/pern_app"`,
      `DATABASE_URL="file:./prisma/dev.db"`,
      ``,
      `# Auth`,
      `JWT_SECRET="change-me-in-production"`,
      ``,
      `# Server`,
      `PORT=3000`,
      ``,
    ].join('\n'),
  },
];

const pernSolid: StackTemplate = {
  id: 'pern-solid',
  stackId: 'pern',
  tier: 'solid',
  name: 'PERN Solid',
  description: 'Production patterns — Prisma ORM, Zod validation, user model',
  features: [
    'Prisma ORM with Board + Todo + User models',
    'Zod schema validation on all inputs',
    'Cascading deletes (Board → Todos)',
    'Transaction-based reordering',
    'Auth scaffolding with User model',
    'Auto-migration on install',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER — Docker, Tests, CI/CD
   Adds: Dockerfile, docker-compose, Vitest, GitHub Actions
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
          'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
          'docker:build': 'docker build -t pern-app .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
          vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json ./`,
      `COPY prisma ./prisma/`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      ``,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: pern_app`,
      `      POSTGRES_USER: pern`,
      `      POSTGRES_PASSWORD: pern_secret`,
      `    ports:`,
      `      - '5432:5432'`,
      `    volumes:`,
      `      - pgdata:/var/lib/postgresql/data`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U pern']`,
      `      interval: 5s`,
      `      timeout: 5s`,
      `      retries: 5`,
      ``,
      `  app:`,
      `    build: .`,
      `    ports:`,
      `      - '3000:3000'`,
      `    depends_on:`,
      `      db:`,
      `        condition: service_healthy`,
      `    environment:`,
      `      DATABASE_URL: postgresql://pern:pern_secret@db:5432/pern_app`,
      `      NODE_ENV: production`,
      ``,
      `volumes:`,
      `  pgdata:`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: [
      `import { defineConfig } from 'vitest/config';`,
      ``,
      `export default defineConfig({`,
      `  test: {`,
      `    globals: true,`,
      `    environment: 'node',`,
      `    include: ['__tests__/**/*.test.ts'],`,
      `  },`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      `const ReorderSchema = z.object({ todoIds: z.array(z.number()) });`,
      ``,
      `describe('PERN Board API — Validation', () => {`,
      `  it('validates board creation', () => {`,
      `    expect(() => CreateBoardSchema.parse({ name: '' })).toThrow();`,
      `    expect(() => CreateBoardSchema.parse({ name: 'Work' })).not.toThrow();`,
      `    expect(CreateBoardSchema.parse({ name: 'Work', icon: '💼' })).toEqual({ name: 'Work', icon: '💼' });`,
      `  });`,
      ``,
      `  it('validates todo creation', () => {`,
      `    expect(() => CreateTodoSchema.parse({ title: '' })).toThrow();`,
      `    expect(() => CreateTodoSchema.parse({ title: 'a'.repeat(501) })).toThrow();`,
      `    expect(CreateTodoSchema.parse({ title: 'Build feature' })).toEqual({ title: 'Build feature' });`,
      `  });`,
      ``,
      `  it('validates reorder payload', () => {`,
      `    expect(() => ReorderSchema.parse({ todoIds: 'not-array' })).toThrow();`,
      `    expect(ReorderSchema.parse({ todoIds: [1, 2, 3] })).toEqual({ todoIds: [1, 2, 3] });`,
      `  });`,
      `});`,
      ``,
      `describe('Board data model', () => {`,
      `  it('boards contain todos with positions', () => {`,
      `    const board = { id: 1, name: 'Work', icon: '💼' };`,
      `    const todos = [`,
      `      { id: 1, boardId: 1, title: 'Task A', done: false, position: 0 },`,
      `      { id: 2, boardId: 1, title: 'Task B', done: true, position: 1 },`,
      `    ];`,
      `    expect(todos.filter(t => t.boardId === board.id)).toHaveLength(2);`,
      `    expect(todos.filter(t => t.done)).toHaveLength(1);`,
      `  });`,
      ``,
      `  it('reorder updates positions correctly', () => {`,
      `    const todos = [`,
      `      { id: 1, position: 0 },`,
      `      { id: 2, position: 1 },`,
      `      { id: 3, position: 2 },`,
      `    ];`,
      `    const newOrder = [3, 1, 2];`,
      `    newOrder.forEach((id, i) => {`,
      `      const t = todos.find(x => x.id === id)!;`,
      `      t.position = i;`,
      `    });`,
      `    expect(todos.find(t => t.id === 3)!.position).toBe(0);`,
      `    expect(todos.find(t => t.id === 1)!.position).toBe(1);`,
      `    expect(todos.find(t => t.id === 2)!.position).toBe(2);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with:`,
      `          node-version: 22`,
      `          cache: npm`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
      `  docker:`,
      `    needs: test`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - run: docker build -t pern-app .`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# PERN Stack — Battle-Tested`,
      ``,
      `Production-ready board task manager with PostgreSQL, Express, React, and Node.js.`,
      ``,
      `## Features`,
      `- 📋 Multiple boards with sidebar navigation`,
      `- ✨ Drag-to-reorder with Framer Motion`,
      `- 🗄️ Prisma ORM with SQLite (swappable to PostgreSQL)`,
      `- ✅ Zod validation on all inputs`,
      `- 🐳 Docker + Docker Compose`,
      `- 🧪 Vitest test suite`,
      `- 🔄 GitHub Actions CI/CD`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install`,
      `npm run dev`,
      `\`\`\``,
      ``,
      `## Docker (Production)`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `## Testing`,
      `\`\`\`bash`,
      `npm test           # Run once`,
      `npm run test:watch  # Watch mode`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const pernBattleTested: StackTemplate = {
  id: 'pern-battle-tested',
  stackId: 'pern',
  tier: 'battle-tested',
  name: 'PERN Battle-Tested',
  description: 'Deployment ready — Docker, tests, CI/CD pipeline',
  features: [
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite (validation + data model)',
    'GitHub Actions CI pipeline',
    'Multi-stage Docker build',
    'Production-ready Dockerfile',
    'Everything from Solid tier',
  ],
  files: mergeFiles(pernSolid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER — VeggaAI Premium: monitoring, error boundaries, hooks
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 'pern-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          preview: 'vite preview',
          test: 'vitest run',
          'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
          'docker:build': 'docker build -t pern-vai .',
          'docker:up': 'docker compose up -d',
          'docker:down': 'docker compose down',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          react: '^19.2.0',
          'react-dom': '^19.2.0',
          'framer-motion': '^12.34.0',
          '@prisma/client': '^7.4.0',
          zod: '^4.3.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0',
          '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0',
          prisma: '^7.4.0',
          typescript: '^5.9.0',
          vite: '^7.3.0',
          vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `# ── VeggaAI Optimized Multi-Stage Build ──`,
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci --ignore-scripts && npx prisma generate`,
      ``,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build`,
      `RUN npm prune --production`,
      ``,
      `FROM node:22-alpine AS runner`,
      `WORKDIR /app`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `ENV NODE_ENV=production`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/monitor.ts',
    content: [
      `/**`,
      ` * VeggaAI Performance Monitor — lightweight request tracing.`,
      ` */`,
      `interface RequestMetric {`,
      `  path: string; method: string; status: number; duration: number; timestamp: number;`,
      `}`,
      ``,
      `const metrics: RequestMetric[] = [];`,
      `const MAX_METRICS = 1000;`,
      ``,
      `export function recordMetric(metric: RequestMetric) {`,
      `  metrics.push(metric);`,
      `  if (metrics.length > MAX_METRICS) metrics.shift();`,
      `}`,
      ``,
      `export function getMetricsSummary() {`,
      `  const last5m = metrics.filter(m => m.timestamp > Date.now() - 5 * 60 * 1000);`,
      `  const avgDuration = last5m.length ? last5m.reduce((s, m) => s + m.duration, 0) / last5m.length : 0;`,
      `  const errorRate = last5m.length ? last5m.filter(m => m.status >= 400).length / last5m.length : 0;`,
      `  return {`,
      `    totalRequests: metrics.length,`,
      `    last5min: last5m.length,`,
      `    avgResponseMs: Math.round(avgDuration * 100) / 100,`,
      `    errorRate: Math.round(errorRate * 10000) / 100,`,
      `    uptime: process.uptime(),`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/ErrorBoundary.tsx',
    content: [
      `import { Component, type ReactNode, type ErrorInfo } from 'react';`,
      ``,
      `interface Props { children: ReactNode; fallback?: ReactNode; }`,
      `interface State { hasError: boolean; error: Error | null; }`,
      ``,
      `export class ErrorBoundary extends Component<Props, State> {`,
      `  state: State = { hasError: false, error: null };`,
      `  static getDerivedStateFromError(error: Error): State { return { hasError: true, error }; }`,
      `  componentDidCatch(error: Error, info: ErrorInfo) { console.error('[Vai ErrorBoundary]', error, info.componentStack); }`,
      `  render() {`,
      `    if (this.state.hasError) {`,
      `      return this.props.fallback ?? (`,
      `        <div style={{ padding: 40, textAlign: 'center', color: '#ef4444' }}>`,
      `          <h2>Something went wrong</h2>`,
      `          <pre style={{ fontSize: '0.8rem', color: '#71717a', marginTop: 8 }}>{this.state.error?.message}</pre>`,
      `          <button onClick={() => this.setState({ hasError: false, error: null })}`,
      `            style={{ marginTop: 16, padding: '8px 16px', borderRadius: 8, background: '#27272a', color: '#e4e4e7', border: 'none', cursor: 'pointer' }}>`,
      `            Try Again`,
      `          </button>`,
      `        </div>`,
      `      );`,
      `    }`,
      `    return this.props.children;`,
      `  }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/hooks/useApi.ts',
    content: [
      `import { useState, useCallback } from 'react';`,
      ``,
      `interface UseApiOptions<T> { onSuccess?: (data: T) => void; onError?: (error: Error) => void; }`,
      ``,
      `export function useApi<T>(url: string, options?: UseApiOptions<T>) {`,
      `  const [data, setData] = useState<T | null>(null);`,
      `  const [loading, setLoading] = useState(false);`,
      `  const [error, setError] = useState<Error | null>(null);`,
      ``,
      `  const execute = useCallback(async (init?: RequestInit) => {`,
      `    setLoading(true); setError(null);`,
      `    try {`,
      `      const res = await fetch(url, init);`,
      `      if (!res.ok) throw new Error(\`HTTP \${res.status}\`);`,
      `      const json = await res.json();`,
      `      setData(json); options?.onSuccess?.(json);`,
      `      return json as T;`,
      `    } catch (err) {`,
      `      const e = err instanceof Error ? err : new Error(String(err));`,
      `      setError(e); options?.onError?.(e); throw e;`,
      `    } finally { setLoading(false); }`,
      `  }, [url]);`,
      ``,
      `  return { data, loading, error, execute };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CreateBoardSchema = z.object({ name: z.string().min(1).max(100), icon: z.string().max(4).optional() });`,
      `const CreateTodoSchema = z.object({ title: z.string().min(1).max(500) });`,
      ``,
      `describe('PERN Vai — Validation', () => {`,
      `  it('validates board creation', () => {`,
      `    expect(() => CreateBoardSchema.parse({ name: '' })).toThrow();`,
      `    expect(CreateBoardSchema.parse({ name: 'Work', icon: '💼' })).toEqual({ name: 'Work', icon: '💼' });`,
      `  });`,
      ``,
      `  it('validates todo creation', () => {`,
      `    expect(() => CreateTodoSchema.parse({ title: '' })).toThrow();`,
      `    expect(() => CreateTodoSchema.parse({ title: 'a'.repeat(501) })).toThrow();`,
      `    expect(CreateTodoSchema.parse({ title: 'Valid' })).toEqual({ title: 'Valid' });`,
      `  });`,
      `});`,
      ``,
      `describe('Vai — Data Model', () => {`,
      `  it('board contains todos with positions', () => {`,
      `    const todos = [{ id: 1, pos: 0 }, { id: 2, pos: 1 }, { id: 3, pos: 2 }];`,
      `    expect(todos.sort((a, b) => a.pos - b.pos).map(t => t.id)).toEqual([1, 2, 3]);`,
      `  });`,
      ``,
      `  it('reorder respects new positions', () => {`,
      `    const todos = [{ id: 1, pos: 0 }, { id: 2, pos: 1 }, { id: 3, pos: 2 }];`,
      `    [3, 1, 2].forEach((id, i) => { todos.find(t => t.id === id)!.pos = i; });`,
      `    expect(todos.sort((a, b) => a.pos - b.pos).map(t => t.id)).toEqual([3, 1, 2]);`,
      `  });`,
      ``,
      `  it('monitors track metrics', () => {`,
      `    const m: { path: string; duration: number }[] = [];`,
      `    m.push({ path: '/api/boards', duration: 12 });`,
      `    m.push({ path: '/api/todos', duration: 8 });`,
      `    const avg = m.reduce((s, x) => s + x.duration, 0) / m.length;`,
      `    expect(avg).toBe(10);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 'pern-vai',`,
      `  version: '1.0.0',`,
      `  stack: 'pern',`,
      `  tier: 'vai',`,
      `  features: { monitoring: true, errorBoundary: true, typeContract: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 PERN Board — Vai Premium`,
      ``,
      `> VeggaAI's curated PERN board task manager.`,
      ``,
      `## Features`,
      `- 📋 Multiple boards with sidebar navigation`,
      `- ✨ Drag-to-reorder with Framer Motion`,
      `- 🗄️ Prisma ORM (SQLite dev / PostgreSQL prod)`,
      `- ✅ Zod validation on all inputs`,
      `- 📊 Performance monitoring middleware`,
      `- 🛡️ React ErrorBoundary component`,
      `- 🎣 Type-safe \`useApi\` hook`,
      `- 🐳 Optimized multi-stage Docker build`,
      `- 🧪 Vitest test suite`,
      `- 🔄 GitHub Actions CI/CD`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install`,
      `npm run dev`,
      `\`\`\``,
      ``,
      `## Production`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
      `---`,
      `*Built with VeggaAI — Local-first AI that learns from you.*`,
      ``,
    ].join('\n'),
  },
];

const pernVai: StackTemplate = {
  id: 'pern-vai',
  stackId: 'pern',
  tier: 'vai',
  name: 'PERN Vai',
  description: "VeggaAI's premium PERN — monitoring, error boundaries, optimized Docker",
  features: [
    'Multi-stage Docker (non-root, healthcheck)',
    'Performance monitoring middleware',
    'React ErrorBoundary component',
    'Type-safe useApi hook',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(pernBattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT PERN STACK DEFINITION
   ================================================================ */

export const pernStack: StackDefinition = {
  id: 'pern',
  name: 'PERN',
  tagline: 'The classic full-stack combo',
  description: 'PostgreSQL + Express + React + Node.js — battle-proven stack for production apps',
  techStack: ['PostgreSQL', 'Express', 'React', 'Node.js'],
  icon: '🐘',
  color: 'blue',
  templates: [pernBasic, pernSolid, pernBattleTested, pernVai],
};
