/**
 * T3 Stack — tRPC + Zod + React + TypeScript
 * All four tiers: Basic expense tracker → Vai premium.
 *
 * Showcases end-to-end type safety with tRPC-like procedure system.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';
import {
  getT3EnvVars,
  buildSetupScript,
  generateT3DemoSequence,
  generateAuthContext,
  generateAuthPage,
  generateUserMenu,
  generateMessagePanel,
  generateProfileCard,
  generateSocialFeed,
  generateNotificationPanel,
  generateGenericSolidShell,
  generateGenericBattleTestedShell,
  generateGenericVaiShell,
  generateAdminDashboard,
  type DomainShellConfig,
} from './shared-setup.js';

/* ================================================================
   BASIC TIER — Expense Tracker with tRPC-like Procedures
   End-to-end type-safe, Zod-validated, category-grouped expenses.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0', 'framer-motion': '^12.34.0', 'lucide-react': '^0.513.0', clsx: '^2.1.1', 'tailwind-merge': '^3.2.0' },
        devDependencies: {
          '@types/react': '^19.2.0', '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0', typescript: '^5.9.0', vite: '^7.3.0',
          '@tailwindcss/vite': '^4.1.0', tailwindcss: '^4.1.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import tailwindcss from '@tailwindcss/vite';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), tailwindcss(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>T3 Expenses</title>`,
      `</head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      ``,
      `/* ── Data ── */`,
      `interface Expense { id: number; description: string; amount: number; category: string; date: string; }`,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      `let nextId = 8;`,
      `const expenses: Expense[] = [`,
      `  { id: 1, description: 'Grocery run', amount: 67.42, category: 'Food', date: '2025-01-15' },`,
      `  { id: 2, description: 'Uber to office', amount: 12.50, category: 'Transport', date: '2025-01-15' },`,
      `  { id: 3, description: 'Netflix subscription', amount: 15.99, category: 'Entertainment', date: '2025-01-14' },`,
      `  { id: 4, description: 'Electric bill', amount: 89.00, category: 'Bills', date: '2025-01-13' },`,
      `  { id: 5, description: 'Coffee beans', amount: 18.50, category: 'Food', date: '2025-01-13' },`,
      `  { id: 6, description: 'New headphones', amount: 79.99, category: 'Shopping', date: '2025-01-12' },`,
      `  { id: 7, description: 'Gym membership', amount: 45.00, category: 'Health', date: '2025-01-10' },`,
      `];`,
      ``,
      `/* ── Zod Schemas ── */`,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive().max(999999),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      `const UpdateExpense = z.object({`,
      `  description: z.string().min(1).max(200).optional(),`,
      `  amount: z.number().positive().optional(),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]).optional(),`,
      `}).partial();`,
      ``,
      `/* ── tRPC-like Type-Safe Procedures ── */`,
      `const procedures: Record<string, (input: unknown) => Promise<unknown>> = {`,
      `  'expense.list': async () => expenses.sort((a, b) => b.date.localeCompare(a.date)),`,
      `  'expense.create': async (input) => {`,
      `    const data = CreateExpense.parse(input);`,
      `    const exp: Expense = { id: nextId++, ...data };`,
      `    expenses.push(exp);`,
      `    return exp;`,
      `  },`,
      `  'expense.update': async (input) => {`,
      `    const { id, ...updates } = z.object({ id: z.number() }).merge(UpdateExpense).parse(input);`,
      `    const exp = expenses.find(e => e.id === id);`,
      `    if (exp) Object.assign(exp, updates);`,
      `    return exp;`,
      `  },`,
      `  'expense.delete': async (input) => {`,
      `    const { id } = z.object({ id: z.number() }).parse(input);`,
      `    const idx = expenses.findIndex(e => e.id === id);`,
      `    if (idx !== -1) expenses.splice(idx, 1);`,
      `    return { ok: true };`,
      `  },`,
      `  'expense.summary': async () => {`,
      `    const total = expenses.reduce((s, e) => s + e.amount, 0);`,
      `    const byCategory: Record<string, number> = {};`,
      `    expenses.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    return { total, count: expenses.length, byCategory, categories: CATEGORIES };`,
      `  },`,
      `};`,
      ``,
      `/* ── Plugin ── */`,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 't3-api',`,
      `    apply: 'serve',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        if (req.url === '/api/health') return json(res, { status: 'ok' });`,
      `        const m = req.url?.match(/^\\/api\\/trpc\\/(.+)$/);`,
      `        if (!m) return next();`,
      `        const proc = procedures[m[1]];`,
      `        if (!proc) return json(res, { error: 'Procedure not found' }, 404);`,
      `        try {`,
      `          const input = req.method === 'POST' ? await parseBody(req) : {};`,
      `          return json(res, { result: await proc(input) });`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', issues: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/trpc.ts',
    content: [
      `// Type-safe tRPC-like client`,
      `export async function trpc<T>(procedure: string, input?: unknown): Promise<T> {`,
      `  const res = await fetch(\`/api/trpc/\${procedure}\`, input !== undefined`,
      `    ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }`,
      `    : {});`,
      `  const data = await res.json();`,
      `  if (data.error) throw new Error(typeof data.error === 'string' ? data.error : 'Procedure failed');`,
      `  return data.result;`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useState, useEffect, useRef, useCallback } from 'react';`,
      `import { AnimatePresence, motion } from 'framer-motion';`,
      `import { DollarSign, Plus, Trash2, X, TrendingUp, Receipt, Tag, Calendar, Sparkles, Pencil, Check } from 'lucide-react';`,
      `import clsx from 'clsx';`,
      `import { trpc } from './trpc';`,
      ``,
      `interface Expense { id: number; description: string; amount: number; category: string; date: string; }`,
      `interface Summary { total: number; count: number; byCategory: Record<string, number>; }`,
      ``,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      `const categoryColors: Record<string, string> = {`,
      `  Food: 'bg-orange-500/15 text-orange-400 border-orange-500/20',`,
      `  Transport: 'bg-blue-500/15 text-blue-400 border-blue-500/20',`,
      `  Entertainment: 'bg-pink-500/15 text-pink-400 border-pink-500/20',`,
      `  Bills: 'bg-red-500/15 text-red-400 border-red-500/20',`,
      `  Shopping: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20',`,
      `  Health: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/20',`,
      `  Other: 'bg-zinc-500/15 text-zinc-400 border-zinc-500/20',`,
      `};`,
      `const barColors: Record<string, string> = {`,
      `  Food: 'bg-orange-500', Transport: 'bg-blue-500', Entertainment: 'bg-pink-500',`,
      `  Bills: 'bg-red-500', Shopping: 'bg-emerald-500', Health: 'bg-cyan-500', Other: 'bg-zinc-500',`,
      `};`,
      ``,
      `/* ── ExpenseRow: inline edit, long-press, hover tips ── */`,
      `function ExpenseRow({ expense: e, onDelete, onUpdate }: {`,
      `  expense: Expense; onDelete: (id: number) => void;`,
      `  onUpdate: (id: number, data: Partial<Expense>) => void;`,
      `}) {`,
      `  const [editing, setEditing] = useState(false);`,
      `  const [desc, setDesc] = useState(e.description);`,
      `  const [amount, setAmount] = useState(String(e.amount));`,
      `  const inputRef = useRef<HTMLInputElement>(null);`,
      `  const longPressRef = useRef<ReturnType<typeof setTimeout> | null>(null);`,
      `  const didLongPress = useRef(false);`,
      `  const startPos = useRef({ x: 0, y: 0 });`,
      ``,
      `  useEffect(() => { setDesc(e.description); setAmount(String(e.amount)); }, [e.description, e.amount]);`,
      `  useEffect(() => { if (editing) inputRef.current?.focus(); }, [editing]);`,
      ``,
      `  const startEdit = useCallback(() => { setDesc(e.description); setAmount(String(e.amount)); setEditing(true); }, [e.description, e.amount]);`,
      `  const save = () => {`,
      `    const d = desc.trim(), a = parseFloat(amount);`,
      `    if (d && !isNaN(a) && a > 0 && (d !== e.description || a !== e.amount))`,
      `      onUpdate(e.id, { description: d, amount: a });`,
      `    setEditing(false);`,
      `  };`,
      `  const cancel = () => { setDesc(e.description); setAmount(String(e.amount)); setEditing(false); };`,
      ``,
      `  const onDown = (ev: React.PointerEvent) => {`,
      `    startPos.current = { x: ev.clientX, y: ev.clientY }; didLongPress.current = false;`,
      `    longPressRef.current = setTimeout(() => {`,
      `      didLongPress.current = true; try { navigator.vibrate?.(50); } catch {} startEdit();`,
      `    }, 500);`,
      `  };`,
      `  const onMove = (ev: React.PointerEvent) => {`,
      `    if (!longPressRef.current) return;`,
      `    if (Math.abs(ev.clientX - startPos.current.x) > 5 || Math.abs(ev.clientY - startPos.current.y) > 5) {`,
      `      clearTimeout(longPressRef.current); longPressRef.current = null;`,
      `    }`,
      `  };`,
      `  const onCancel = () => { if (longPressRef.current) clearTimeout(longPressRef.current); didLongPress.current = false; };`,
      ``,
      `  if (editing) return (`,
      `    <div className="flex flex-wrap items-center gap-2 rounded-xl border border-purple-500/30 bg-zinc-900/80 px-4 py-2.5 backdrop-blur-sm">`,
      `      <input ref={inputRef} value={desc} onChange={ev => setDesc(ev.target.value)} placeholder="Description"`,
      `        onKeyDown={ev => { if (ev.key === 'Enter') save(); if (ev.key === 'Escape') cancel(); }}`,
      `        className="min-w-0 flex-1 bg-transparent text-sm text-zinc-200 outline-none" />`,
      `      <input type="number" step="0.01" value={amount} onChange={ev => setAmount(ev.target.value)}`,
      `        onKeyDown={ev => { if (ev.key === 'Enter') save(); if (ev.key === 'Escape') cancel(); }}`,
      `        className="w-24 bg-transparent text-right text-sm font-semibold text-zinc-200 outline-none" />`,
      `      <button onClick={save} title="Save" className="rounded-md p-1.5 text-green-400 hover:bg-zinc-800 active:scale-95"><Check className="h-4 w-4" /></button>`,
      `      <button onClick={cancel} title="Cancel" className="rounded-md p-1.5 text-zinc-500 hover:bg-zinc-800 active:scale-95"><X className="h-4 w-4" /></button>`,
      `    </div>`,
      `  );`,
      ``,
      `  return (`,
      `    <div className="group flex items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 transition-colors hover:border-zinc-700"`,
      `      onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onCancel} onPointerLeave={onCancel}>`,
      `      <span className={clsx('shrink-0 rounded-md border px-2 py-0.5 text-[10px] font-medium', categoryColors[e.category] ?? 'bg-zinc-800 text-zinc-400 border-zinc-700')}>`,
      `        {e.category}`,
      `      </span>`,
      `      <span className="flex-1 truncate text-sm select-none touch-manipulation">{e.description}</span>`,
      `      <span className="text-xs text-zinc-500 hidden sm:inline">{e.date}</span>`,
      `      <span className="w-20 text-right text-sm font-semibold text-zinc-200">\${e.amount.toFixed(2)}</span>`,
      `      <div className="flex shrink-0 gap-0.5 opacity-0 transition-opacity group-hover:opacity-100 max-sm:opacity-100">`,
      `        <button onClick={ev => { ev.stopPropagation(); startEdit(); }} title="Edit expense"`,
      `          className="rounded p-1 text-zinc-600 hover:bg-zinc-800 hover:text-blue-400 active:scale-90 transition-all">`,
      `          <Pencil className="h-3.5 w-3.5" />`,
      `        </button>`,
      `        <button onClick={ev => { ev.stopPropagation(); onDelete(e.id); }} title="Delete expense"`,
      `          className="rounded p-1 text-zinc-600 hover:bg-zinc-800 hover:text-red-400 active:scale-90 transition-all">`,
      `          <Trash2 className="h-3.5 w-3.5" />`,
      `        </button>`,
      `      </div>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
      `export function App() {`,
      `  const [expenses, setExpenses] = useState<Expense[]>([]);`,
      `  const [summary, setSummary] = useState<Summary>({ total: 0, count: 0, byCategory: {} });`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) });`,
      `  const [loading, setLoading] = useState(true);`,
      ``,
      `  const load = async () => {`,
      `    const [list, sum] = await Promise.all([`,
      `      trpc<Expense[]>('expense.list'),`,
      `      trpc<Summary>('expense.summary'),`,
      `    ]);`,
      `    setExpenses(list);`,
      `    setSummary(sum);`,
      `    setLoading(false);`,
      `  };`,
      ``,
      `  useEffect(() => { load(); }, []);`,
      ``,
      `  const addExpense = async () => {`,
      `    if (!form.description.trim() || !form.amount) return;`,
      `    await trpc<Expense>('expense.create', {`,
      `      description: form.description, amount: parseFloat(form.amount),`,
      `      category: form.category, date: form.date,`,
      `    });`,
      `    setForm({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const updateExpense = async (id: number, data: Partial<Expense>) => {`,
      `    setExpenses(prev => prev.map(e => e.id === id ? { ...e, ...data } : e));`,
      `    await trpc<Expense>('expense.update', { id, ...data });`,
      `    load(); // Refresh summary`,
      `  };`,
      ``,
      `  const deleteExpense = async (id: number) => {`,
      `    setExpenses(prev => prev.filter(e => e.id !== id));`,
      `    await trpc<{ ok: boolean }>('expense.delete', { id });`,
      `    load(); // Refresh summary`,
      `  };`,
      ``,
      `  const topCategory = Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1])[0];`,
      `  const maxCategoryAmount = Math.max(...Object.values(summary.byCategory), 1);`,
      ``,
      `  return (`,
      `    <div className="mx-auto min-h-dvh max-w-4xl px-4 py-8 font-sans sm:px-6 sm:py-10">`,
      `      <div className="mb-8">`,
      `        <h1 className="text-2xl font-bold tracking-tight">Expenses</h1>`,
      `        <p className="mt-1 text-sm text-zinc-500">Track spending with end-to-end type safety</p>`,
      `      </div>`,
      ``,
      `      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-1.5 text-xs text-zinc-500"><DollarSign className="h-3.5 w-3.5" /> Total</div>`,
      `          <p className="mt-1 text-xl font-bold text-purple-400">\${summary.total.toFixed(2)}</p>`,
      `        </div>`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-1.5 text-xs text-zinc-500"><Receipt className="h-3.5 w-3.5" /> Count</div>`,
      `          <p className="mt-1 text-xl font-bold text-emerald-400">{summary.count}</p>`,
      `        </div>`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-1.5 text-xs text-zinc-500"><TrendingUp className="h-3.5 w-3.5" /> Top</div>`,
      `          <p className="mt-1 truncate text-xl font-bold text-amber-400">{topCategory?.[0] ?? '\u2014'}</p>`,
      `        </div>`,
      `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <div className="flex items-center gap-1.5 text-xs text-zinc-500"><Calendar className="h-3.5 w-3.5" /> Average</div>`,
      `          <p className="mt-1 text-xl font-bold text-blue-400">\${summary.count ? (summary.total / summary.count).toFixed(2) : '0.00'}</p>`,
      `        </div>`,
      `      </div>`,
      ``,
      `      {Object.keys(summary.byCategory).length > 0 && (`,
      `        <div className="mb-6 rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
      `          <h3 className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-500">Category Breakdown</h3>`,
      `          <div className="space-y-2">`,
      `            {Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1]).map(([cat, amount]) => (`,
      `              <div key={cat} className="flex items-center gap-3">`,
      `                <span className="w-24 truncate text-xs text-zinc-400">{cat}</span>`,
      `                <div className="relative h-2 flex-1 overflow-hidden rounded-full bg-zinc-800">`,
      `                  <div className={clsx('h-full rounded-full transition-all duration-500', barColors[cat] ?? 'bg-zinc-600')}`,
      `                    style={{ width: \`\${(amount / maxCategoryAmount) * 100}%\` }} />`,
      `                </div>`,
      `                <span className="w-16 text-right text-xs font-medium text-zinc-300">\${amount.toFixed(2)}</span>`,
      `              </div>`,
      `            ))}`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      ``,
      `      <div className="mb-4 flex items-center justify-between">`,
      `        <h2 className="text-sm font-medium text-zinc-400">Recent Expenses</h2>`,
      `        <button onClick={() => setShowAdd(!showAdd)} title={showAdd ? 'Cancel' : 'Add expense'}`,
      `          className={clsx('flex items-center gap-1.5 rounded-lg px-4 py-2 text-sm font-medium transition-colors',`,
      `            showAdd ? 'bg-zinc-800 text-zinc-300' : 'bg-purple-600 text-white hover:bg-purple-500')}>`,
      `          {showAdd ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}`,
      `          <span className="hidden sm:inline">{showAdd ? 'Cancel' : 'Add'}</span>`,
      `        </button>`,
      `      </div>`,
      ``,
      `      {showAdd && (`,
      `        <div className="mb-4 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">`,
      `          <div className="grid gap-3 sm:grid-cols-2">`,
      `            <input value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="Description"`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-purple-500/50" />`,
      `            <input type="number" step="0.01" value={form.amount} onChange={e => setForm(f => ({ ...f, amount: e.target.value }))} placeholder="Amount"`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-purple-500/50" />`,
      `            <select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))}`,
      `              className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none">`,
      `              {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}`,
      `            </select>`,
      `            <div className="flex gap-2">`,
      `              <input type="date" value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))}`,
      `                className="flex-1 rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none" />`,
      `              <button onClick={addExpense} title="Save expense"`,
      `                className="rounded-md bg-purple-600 px-4 py-2 text-sm font-medium text-white hover:bg-purple-500 active:scale-[0.97]">Save</button>`,
      `            </div>`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      ``,
      `      {loading ? (`,
      `        <div className="space-y-2">`,
      `          {[...Array(5)].map((_, i) => <div key={i} className="h-14 animate-pulse rounded-xl bg-zinc-900" />)}`,
      `        </div>`,
      `      ) : expenses.length === 0 ? (`,
      `        <div className="flex flex-col items-center justify-center py-20">`,
      `          <Sparkles className="mb-3 h-12 w-12 text-zinc-800" />`,
      `          <p className="text-sm text-zinc-500">No expenses yet — add one to start tracking!</p>`,
      `        </div>`,
      `      ) : (`,
      `        <div className="space-y-1.5">`,
      `          <AnimatePresence mode="popLayout">`,
      `            {expenses.map(e => (`,
      `              <motion.div key={e.id} layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}`,
      `                exit={{ opacity: 0, x: -80 }} transition={{ type: 'spring', stiffness: 400, damping: 30 }}>`,
      `                <ExpenseRow expense={e} onDelete={deleteExpense} onUpdate={updateExpense} />`,
      `              </motion.div>`,
      `            ))}`,
      `          </AnimatePresence>`,
      `        </div>`,
      `      )}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `@import "tailwindcss";`,
      ``,
      `@font-face {`,
      `  font-family: "Geist";`,
      `  src: url("https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-sans/Geist-Variable.woff2") format("woff2");`,
      `  font-weight: 100 900;`,
      `  font-display: swap;`,
      `}`,
      `@font-face {`,
      `  font-family: "Geist Mono";`,
      `  src: url("https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-mono/GeistMono-Variable.woff2") format("woff2");`,
      `  font-weight: 100 900;`,
      `  font-display: swap;`,
      `}`,
      ``,
      `@theme inline {`,
      `  --font-sans: "Geist", "Inter", system-ui, -apple-system, sans-serif;`,
      `  --font-mono: "Geist Mono", "Fira Code", ui-monospace, monospace;`,
      `  --color-background: oklch(0.145 0 0);`,
      `  --color-foreground: oklch(0.985 0 0);`,
      `  --color-muted: oklch(0.269 0 0);`,
      `  --color-muted-foreground: oklch(0.708 0 0);`,
      `  --color-border: oklch(0.27 0.006 286);`,
      `  --color-accent: oklch(0.627 0.265 303.9);`,
      `  --color-accent-foreground: oklch(0.985 0 0);`,
      `  --color-destructive: oklch(0.577 0.245 27.3);`,
      `  --animate-fade-in: fade-in 0.3s ease-out;`,
      `  --animate-slide-up: slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1);`,
      `}`,
      ``,
      `@keyframes fade-in { from { opacity: 0 } to { opacity: 1 } }`,
      `@keyframes slide-up { from { opacity: 0; transform: translateY(8px) } to { opacity: 1; transform: translateY(0) } }`,
      ``,
      `body { font-family: var(--font-sans); background: var(--color-background); color: var(--color-foreground); }`,
      ``,
      `::-webkit-scrollbar { width: 6px; height: 6px; }`,
      `::-webkit-scrollbar-track { background: transparent; }`,
      `::-webkit-scrollbar-thumb { background: var(--color-border); border-radius: 3px; }`,
      `::-webkit-scrollbar-thumb:hover { background: var(--color-muted-foreground); }`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/lib/utils.ts',
    content: [
      `import { type ClassValue, clsx } from 'clsx';`,
      `import { twMerge } from 'tailwind-merge';`,
      ``,
      `export function cn(...inputs: ClassValue[]) {`,
      `  return twMerge(clsx(inputs));`,
      `}`,
      ``,
      `export function formatRelativeTime(date: Date | number): string {`,
      `  const now = new Date();`,
      `  const d = typeof date === 'number' ? new Date(date) : date;`,
      `  const diff = now.getTime() - d.getTime();`,
      `  const seconds = Math.floor(diff / 1000);`,
      `  const minutes = Math.floor(seconds / 60);`,
      `  const hours = Math.floor(minutes / 60);`,
      `  const days = Math.floor(hours / 24);`,
      `  if (days > 30) return d.toLocaleDateString();`,
      `  if (days > 0) return \`\${days}d ago\`;`,
      `  if (hours > 0) return \`\${hours}h ago\`;`,
      `  if (minutes > 0) return \`\${minutes}m ago\`;`,
      `  return 'Just now';`,
      `}`,
      ``,
      `export function formatBytes(bytes: number): string {`,
      `  if (bytes === 0) return '0 B';`,
      `  const k = 1024;`,
      `  const sizes = ['B', 'KB', 'MB', 'GB'];`,
      `  const i = Math.floor(Math.log(bytes) / Math.log(k));`,
      `  return \`\${parseFloat((bytes / Math.pow(k, i)).toFixed(1))} \${sizes[i]}\`;`,
      `}`,
      ``,
    ].join('\n'),
  },
];

/* ── Basic tier: CLI setup + demo ── */
basicFiles.push(
  { path: 'scripts/setup.mjs', content: buildSetupScript('t3', 'basic', getT3EnvVars()) },
  { path: 'demo.sequence.json', content: JSON.stringify(generateT3DemoSequence('basic'), null, 2) },
);

const t3Basic: StackTemplate = {
  id: 't3-basic',
  stackId: 't3',
  tier: 'basic',
  name: 'T3 Basic',
  description: 'Expense tracker — inline editing, tRPC procedures, category breakdown',
  features: [
    'Inline edit (pencil icon + long-press 500ms + haptic vibration)',
    'Hover tooltips on all interactive buttons',
    'tRPC-style typed procedures (6 endpoints incl. update)',
    'Zod schema validation',
    'Category breakdown chart with color-coded bars',
    'Dashboard stats cards (total/count/top/average)',
    'Framer Motion spring animations (AnimatePresence)',
    'CLI setup wizard (node scripts/setup.mjs)',
    'Demo-as-validation sequence',
    'Mobile-first (always-visible actions, h-dvh, touch-manipulation)',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   DOMAIN COMPONENT — ExpenseTracker (extracted for tier shells)
   ================================================================ */

const T3_DOMAIN: DomainShellConfig = {
  componentName: 'ExpenseTracker',
  componentImport: './components/ExpenseTracker',
  tabId: 'expenses',
  tabLabel: 'Expenses',
  tabIcon: 'DollarSign',
  tabIconJsx: 'DollarSign',
  fullBleed: false,
};

function generateExpenseTracker(): string {
  return [
    `import { useState, useEffect, useRef, useCallback } from 'react';`,
    `import { AnimatePresence, motion } from 'framer-motion';`,
    `import { DollarSign, Plus, Trash2, X, TrendingUp, Receipt, Tag, Calendar, Sparkles, Pencil, Check } from 'lucide-react';`,
    `import clsx from 'clsx';`,
    `import { trpc } from '../trpc';`,
    ``,
    `interface Expense { id: number; description: string; amount: number; category: string; date: string; }`,
    `interface Summary { total: number; count: number; byCategory: Record<string, number>; }`,
    ``,
    `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
    `const categoryColors: Record<string, string> = {`,
    `  Food: 'bg-orange-500/15 text-orange-400 border-orange-500/20', Transport: 'bg-blue-500/15 text-blue-400 border-blue-500/20',`,
    `  Entertainment: 'bg-pink-500/15 text-pink-400 border-pink-500/20', Bills: 'bg-red-500/15 text-red-400 border-red-500/20',`,
    `  Shopping: 'bg-emerald-500/15 text-emerald-400 border-emerald-500/20', Health: 'bg-cyan-500/15 text-cyan-400 border-cyan-500/20',`,
    `  Other: 'bg-zinc-500/15 text-zinc-400 border-zinc-500/20',`,
    `};`,
    `const barColors: Record<string, string> = {`,
    `  Food: 'bg-orange-500', Transport: 'bg-blue-500', Entertainment: 'bg-pink-500',`,
    `  Bills: 'bg-red-500', Shopping: 'bg-emerald-500', Health: 'bg-cyan-500', Other: 'bg-zinc-500',`,
    `};`,
    ``,
    `function ExpenseRow({ expense: e, onDelete, onUpdate }: {`,
    `  expense: Expense; onDelete: (id: number) => void; onUpdate: (id: number, data: Partial<Expense>) => void;`,
    `}) {`,
    `  const [editing, setEditing] = useState(false);`,
    `  const [desc, setDesc] = useState(e.description);`,
    `  const [amount, setAmount] = useState(String(e.amount));`,
    `  const inputRef = useRef<HTMLInputElement>(null);`,
    `  const longPressRef = useRef<ReturnType<typeof setTimeout> | null>(null);`,
    `  const didLongPress = useRef(false);`,
    `  const startPos = useRef({ x: 0, y: 0 });`,
    ``,
    `  useEffect(() => { setDesc(e.description); setAmount(String(e.amount)); }, [e.description, e.amount]);`,
    `  useEffect(() => { if (editing) inputRef.current?.focus(); }, [editing]);`,
    `  const startEdit = useCallback(() => { setDesc(e.description); setAmount(String(e.amount)); setEditing(true); }, [e.description, e.amount]);`,
    `  const save = () => { const d = desc.trim(), a = parseFloat(amount); if (d && !isNaN(a) && a > 0 && (d !== e.description || a !== e.amount)) onUpdate(e.id, { description: d, amount: a }); setEditing(false); };`,
    `  const cancel = () => { setDesc(e.description); setAmount(String(e.amount)); setEditing(false); };`,
    `  const onDown = (ev: React.PointerEvent) => { startPos.current = { x: ev.clientX, y: ev.clientY }; didLongPress.current = false; longPressRef.current = setTimeout(() => { didLongPress.current = true; try { navigator.vibrate?.(50); } catch {} startEdit(); }, 500); };`,
    `  const onMove = (ev: React.PointerEvent) => { if (!longPressRef.current) return; if (Math.abs(ev.clientX - startPos.current.x) > 5 || Math.abs(ev.clientY - startPos.current.y) > 5) { clearTimeout(longPressRef.current); longPressRef.current = null; } };`,
    `  const onCancel = () => { if (longPressRef.current) clearTimeout(longPressRef.current); didLongPress.current = false; };`,
    ``,
    `  if (editing) return (`,
    `    <div className="flex flex-wrap items-center gap-2 rounded-xl border border-purple-500/30 bg-zinc-900/80 px-4 py-2.5 backdrop-blur-sm">`,
    `      <input ref={inputRef} value={desc} onChange={ev => setDesc(ev.target.value)} placeholder="Description"`,
    `        onKeyDown={ev => { if (ev.key === 'Enter') save(); if (ev.key === 'Escape') cancel(); }}`,
    `        className="min-w-0 flex-1 bg-transparent text-sm text-zinc-200 outline-none" />`,
    `      <input type="number" step="0.01" value={amount} onChange={ev => setAmount(ev.target.value)}`,
    `        onKeyDown={ev => { if (ev.key === 'Enter') save(); if (ev.key === 'Escape') cancel(); }}`,
    `        className="w-24 bg-transparent text-right text-sm font-semibold text-zinc-200 outline-none" />`,
    `      <button onClick={save} className="rounded-md p-1.5 text-green-400 hover:bg-zinc-800 active:scale-95"><Check className="h-4 w-4" /></button>`,
    `      <button onClick={cancel} className="rounded-md p-1.5 text-zinc-500 hover:bg-zinc-800 active:scale-95"><X className="h-4 w-4" /></button>`,
    `    </div>`,
    `  );`,
    `  return (`,
    `    <div className="group flex items-center gap-3 rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-3 transition-colors hover:border-zinc-700"`,
    `      onPointerDown={onDown} onPointerMove={onMove} onPointerUp={onCancel} onPointerLeave={onCancel}>`,
    `      <span className={clsx('shrink-0 rounded-md border px-2 py-0.5 text-[10px] font-medium', categoryColors[e.category] ?? 'bg-zinc-800 text-zinc-400 border-zinc-700')}>{e.category}</span>`,
    `      <span className="flex-1 truncate text-sm select-none touch-manipulation">{e.description}</span>`,
    `      <span className="text-xs text-zinc-500 hidden sm:inline">{e.date}</span>`,
    `      <span className="w-20 text-right text-sm font-semibold text-zinc-200">\${e.amount.toFixed(2)}</span>`,
    `      <div className="flex shrink-0 gap-0.5 opacity-0 transition-opacity group-hover:opacity-100 max-sm:opacity-100">`,
    `        <button onClick={ev => { ev.stopPropagation(); startEdit(); }} className="rounded p-1 text-zinc-600 hover:bg-zinc-800 hover:text-blue-400 active:scale-90 transition-all"><Pencil className="h-3.5 w-3.5" /></button>`,
    `        <button onClick={ev => { ev.stopPropagation(); onDelete(e.id); }} className="rounded p-1 text-zinc-600 hover:bg-zinc-800 hover:text-red-400 active:scale-90 transition-all"><Trash2 className="h-3.5 w-3.5" /></button>`,
    `      </div>`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
    `export function ExpenseTracker() {`,
    `  const [expenses, setExpenses] = useState<Expense[]>([]);`,
    `  const [summary, setSummary] = useState<Summary>({ total: 0, count: 0, byCategory: {} });`,
    `  const [showAdd, setShowAdd] = useState(false);`,
    `  const [form, setForm] = useState({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) });`,
    `  const [loading, setLoading] = useState(true);`,
    ``,
    `  const load = async () => {`,
    `    const [list, sum] = await Promise.all([trpc<Expense[]>('expense.list'), trpc<Summary>('expense.summary')]);`,
    `    setExpenses(list); setSummary(sum); setLoading(false);`,
    `  };`,
    `  useEffect(() => { load(); }, []);`,
    ``,
    `  const addExpense = async () => {`,
    `    if (!form.description.trim() || !form.amount) return;`,
    `    await trpc<Expense>('expense.create', { description: form.description, amount: parseFloat(form.amount), category: form.category, date: form.date });`,
    `    setForm({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) }); setShowAdd(false); load();`,
    `  };`,
    `  const updateExpense = async (id: number, data: Partial<Expense>) => {`,
    `    setExpenses(prev => prev.map(e => e.id === id ? { ...e, ...data } : e));`,
    `    await trpc<Expense>('expense.update', { id, ...data }); load();`,
    `  };`,
    `  const deleteExpense = async (id: number) => {`,
    `    setExpenses(prev => prev.filter(e => e.id !== id));`,
    `    await trpc<{ ok: boolean }>('expense.delete', { id }); load();`,
    `  };`,
    ``,
    `  const topCategory = Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1])[0];`,
    `  const maxCategoryAmount = Math.max(...Object.values(summary.byCategory), 1);`,
    ``,
    `  return (`,
    `    <div className="mx-auto max-w-4xl px-4 py-8 font-sans sm:px-6 sm:py-10">`,
    `      <div className="mb-8"><h1 className="text-2xl font-bold tracking-tight">Expenses</h1><p className="mt-1 text-sm text-zinc-500">Track spending with end-to-end type safety</p></div>`,
    `      <div className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-4">`,
    `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center gap-1.5 text-xs text-zinc-500"><DollarSign className="h-3.5 w-3.5" /> Total</div><p className="mt-1 text-xl font-bold text-purple-400">\${summary.total.toFixed(2)}</p></div>`,
    `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center gap-1.5 text-xs text-zinc-500"><Receipt className="h-3.5 w-3.5" /> Count</div><p className="mt-1 text-xl font-bold text-emerald-400">{summary.count}</p></div>`,
    `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center gap-1.5 text-xs text-zinc-500"><TrendingUp className="h-3.5 w-3.5" /> Top</div><p className="mt-1 truncate text-xl font-bold text-amber-400">{topCategory?.[0] ?? '\u2014'}</p></div>`,
    `        <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex items-center gap-1.5 text-xs text-zinc-500"><Calendar className="h-3.5 w-3.5" /> Average</div><p className="mt-1 text-xl font-bold text-blue-400">\${summary.count ? (summary.total / summary.count).toFixed(2) : '0.00'}</p></div>`,
    `      </div>`,
    `      {Object.keys(summary.byCategory).length > 0 && (`,
    `        <div className="mb-6 rounded-xl border border-zinc-800 bg-zinc-900 p-4">`,
    `          <h3 className="mb-3 text-xs font-medium uppercase tracking-wider text-zinc-500">Category Breakdown</h3>`,
    `          <div className="space-y-2">`,
    `            {Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1]).map(([cat, amount]) => (`,
    `              <div key={cat} className="flex items-center gap-3">`,
    `                <span className="w-24 truncate text-xs text-zinc-400">{cat}</span>`,
    `                <div className="relative h-2 flex-1 overflow-hidden rounded-full bg-zinc-800">`,
    `                  <div className={clsx('h-full rounded-full transition-all duration-500', barColors[cat] ?? 'bg-zinc-600')} style={{ width: \`\${(amount / maxCategoryAmount) * 100}%\` }} />`,
    `                </div>`,
    `                <span className="w-16 text-right text-xs font-medium text-zinc-300">\${amount.toFixed(2)}</span>`,
    `              </div>`,
    `            ))}`,
    `          </div>`,
    `        </div>`,
    `      )}`,
    `      <div className="mb-4 flex items-center justify-between">`,
    `        <h2 className="text-sm font-medium text-zinc-400">Recent Expenses</h2>`,
    `        <button onClick={() => setShowAdd(!showAdd)} className={clsx('flex items-center gap-1.5 rounded-lg px-4 py-2 text-sm font-medium transition-colors', showAdd ? 'bg-zinc-800 text-zinc-300' : 'bg-purple-600 text-white hover:bg-purple-500')}>`,
    `          {showAdd ? <X className="h-4 w-4" /> : <Plus className="h-4 w-4" />}<span className="hidden sm:inline">{showAdd ? 'Cancel' : 'Add'}</span>`,
    `        </button>`,
    `      </div>`,
    `      {showAdd && (`,
    `        <div className="mb-4 rounded-xl border border-zinc-800 bg-zinc-900/50 p-4">`,
    `          <div className="grid gap-3 sm:grid-cols-2">`,
    `            <input value={form.description} onChange={e => setForm(f => ({ ...f, description: e.target.value }))} placeholder="Description" className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-purple-500/50" />`,
    `            <input type="number" step="0.01" value={form.amount} onChange={e => setForm(f => ({ ...f, amount: e.target.value }))} placeholder="Amount" className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-purple-500/50" />`,
    `            <select value={form.category} onChange={e => setForm(f => ({ ...f, category: e.target.value }))} className="rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none">{CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}</select>`,
    `            <div className="flex gap-2">`,
    `              <input type="date" value={form.date} onChange={e => setForm(f => ({ ...f, date: e.target.value }))} className="flex-1 rounded-md border border-zinc-800 bg-zinc-900 px-3 py-2 text-sm text-zinc-200 outline-none" />`,
    `              <button onClick={addExpense} className="rounded-md bg-purple-600 px-4 py-2 text-sm font-medium text-white hover:bg-purple-500 active:scale-[0.97]">Save</button>`,
    `            </div>`,
    `          </div>`,
    `        </div>`,
    `      )}`,
    `      {loading ? (`,
    `        <div className="space-y-2">{[...Array(5)].map((_, i) => <div key={i} className="h-14 animate-pulse rounded-xl bg-zinc-900" />)}</div>`,
    `      ) : expenses.length === 0 ? (`,
    `        <div className="flex flex-col items-center justify-center py-20"><Sparkles className="mb-3 h-12 w-12 text-zinc-800" /><p className="text-sm text-zinc-500">No expenses yet — add one to start tracking!</p></div>`,
    `      ) : (`,
    `        <div className="space-y-1.5">`,
    `          <AnimatePresence mode="popLayout">`,
    `            {expenses.map(e => (<motion.div key={e.id} layout initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, x: -80 }} transition={{ type: 'spring', stiffness: 400, damping: 30 }}><ExpenseRow expense={e} onDelete={deleteExpense} onUpdate={updateExpense} /></motion.div>))}`,
    `          </AnimatePresence>`,
    `        </div>`,
    `      )}`,
    `    </div>`,
    `  );`,
    `}`,
    ``,
  ].join('\n');
}

/* ================================================================
   SOLID TIER — Prisma + enhanced tRPC patterns
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-solid',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          postinstall: 'npx prisma generate',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0',
          '@prisma/client': '^6.6.0', 'framer-motion': '^12.34.0', 'lucide-react': '^0.513.0', clsx: '^2.1.1', 'tailwind-merge': '^3.2.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0', '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0', prisma: '^6.6.0',
          typescript: '^5.9.0', vite: '^7.3.0',
          '@tailwindcss/vite': '^4.1.0', tailwindcss: '^4.1.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client {`,
      `  provider = "prisma-client-js"`,
      `}`,
      `datasource db {`,
      `  provider = "sqlite"`,
      `  url      = "file:./dev.db"`,
      `}`,
      ``,
      `model Expense {`,
      `  id          Int      @id @default(autoincrement())`,
      `  description String`,
      `  amount      Float`,
      `  category    String   @default("Other")`,
      `  date        String`,
      `  createdAt   DateTime @default(now())`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      `import { PrismaClient } from '@prisma/client';`,
      `import { handleAuthRoute } from './auth';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      ``,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive().max(999999),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      ``,
      `const procedures: Record<string, (input: unknown) => Promise<unknown>> = {`,
      `  'expense.list': async () => prisma.expense.findMany({ orderBy: { date: 'desc' } }),`,
      `  'expense.create': async (input) => {`,
      `    const data = CreateExpense.parse(input);`,
      `    return prisma.expense.create({ data });`,
      `  },`,
      `  'expense.delete': async (input) => {`,
      `    const { id } = z.object({ id: z.number() }).parse(input);`,
      `    await prisma.expense.delete({ where: { id } });`,
      `    return { ok: true };`,
      `  },`,
      `  'expense.summary': async () => {`,
      `    const all = await prisma.expense.findMany();`,
      `    const total = all.reduce((s, e) => s + e.amount, 0);`,
      `    const byCategory: Record<string, number> = {};`,
      `    all.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    return { total, count: all.length, byCategory, categories: CATEGORIES };`,
      `  },`,
      `};`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 't3-api',`,
      `    apply: 'serve',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        const url = new URL(req.url || '', 'http://localhost');`,
      `        if (handleAuthRoute(req, res, url.pathname)) return;`,
      `        if (req.url === '/api/health') return json(res, { status: 'ok' });`,
      `        const m = req.url?.match(/^\\/api\\/trpc\\/(.+)$/);`,
      `        if (!m) return next();`,
      `        const proc = procedures[m[1]];`,
      `        if (!proc) return json(res, { error: 'Procedure not found' }, 404);`,
      `        try {`,
      `          const input = req.method === 'POST' ? await parseBody(req) : {};`,
      `          return json(res, { result: await proc(input) });`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', issues: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# Switch to PostgreSQL for production\nDATABASE_URL="file:./prisma/dev.db"\n`,
  },
];

/* ── Solid tier: web setup wizard ── */
solidOverrides.push(
  { path: 'scripts/setup.mjs', content: buildSetupScript('t3', 'solid', getT3EnvVars()) },
  { path: 'demo.sequence.json', content: JSON.stringify(generateT3DemoSequence('solid'), null, 2) },
);

/* ── Solid tier: JWT auth system ── */
solidOverrides.push(
  { path: 'src/context/AuthContext.tsx', content: generateAuthContext() },
  { path: 'src/pages/AuthPage.tsx', content: generateAuthPage() },
  { path: 'src/components/UserMenu.tsx', content: generateUserMenu() },
  { path: 'server/auth.ts', content: generateAuthApiRoutes() },
  { path: 'server/setup-plugin.ts', content: generateSetupApiRoutes() },
);

/* ── Solid tier: domain component + app shell + vite config ── */
solidOverrides.push(
  { path: 'src/components/ExpenseTracker.tsx', content: generateExpenseTracker() },
  { path: 'src/App.tsx', content: generateGenericSolidShell(T3_DOMAIN) },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import tailwindcss from '@tailwindcss/vite';`,
      `import { apiPlugin } from './server/plugin';`,
      `import { setupPlugin } from './server/setup-plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), tailwindcss(), apiPlugin(), setupPlugin()] });`,
      ``,
    ].join('\n'),
  },
);

const t3Solid: StackTemplate = {
  id: 't3-solid',
  stackId: 't3',
  tier: 'solid',
  name: 'T3 Solid',
  description: 'With Auth — JWT login/register, Prisma ORM, tRPC, setup wizard',
  features: [
    'JWT authentication (register, login, logout)',
    'Login & register pages with form validation',
    'User menu with avatar & sign out',
    'Auth context provider with token persistence',
    'Prisma ORM with auto-migration',
    'Type-safe tRPC procedures backed by DB',
    'Zod validation on all inputs',
    'CLI setup (node scripts/setup.mjs)',
    'Demo sequence for Vai validation',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client {`,
      `  provider = "prisma-client-js"`,
      `}`,
      `datasource db {`,
      `  provider = "postgresql"`,
      `  url      = env("DATABASE_URL")`,
      `}`,
      ``,
      `model Expense {`,
      `  id          Int      @id @default(autoincrement())`,
      `  description String`,
      `  amount      Float`,
      `  category    String   @default("Other")`,
      `  date        String`,
      `  createdAt   DateTime @default(now())`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# PostgreSQL (used by docker-compose)\nDATABASE_URL="postgresql://t3:t3_secret@localhost:5432/t3_app"\n`,
  },
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate',
          'docker:build': 'docker build -t t3-app .',
          'docker:up': 'docker compose up -d',
        },
        dependencies: {
          react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0',
          '@prisma/client': '^6.6.0',
          'framer-motion': '^12.34.0', 'lucide-react': '^0.513.0', clsx: '^2.1.1', 'tailwind-merge': '^3.2.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0', '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0', prisma: '^6.6.0',
          '@tailwindcss/vite': '^4.1.0', tailwindcss: '^4.1.0',
          typescript: '^5.9.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: t3_app`,
      `      POSTGRES_USER: t3`,
      `      POSTGRES_PASSWORD: t3_secret`,
      `    ports: ['5432:5432']`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U t3']`,
      `      interval: 5s`,
      `  app:`,
      `    build: .`,
      `    ports: ['3000:3000']`,
      `    depends_on:`,
      `      db: { condition: service_healthy }`,
      `    environment:`,
      `      DATABASE_URL: postgresql://t3:t3_secret@db:5432/t3_app`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: `import { defineConfig } from 'vitest/config';\nexport default defineConfig({ test: { globals: true, include: ['__tests__/**/*.test.ts'] } });\n`,
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive(),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      ``,
      `describe('T3 Expense API', () => {`,
      `  it('validates expense creation', () => {`,
      `    expect(() => CreateExpense.parse({ description: '', amount: 0, category: 'Bad', date: 'x' })).toThrow();`,
      `    expect(CreateExpense.parse({ description: 'Lunch', amount: 12.5, category: 'Food', date: '2025-01-15' })).toBeDefined();`,
      `  });`,
      `  it('rejects negative amounts', () => {`,
      `    expect(() => CreateExpense.parse({ description: 'Refund', amount: -5, category: 'Other', date: '2025-01-15' })).toThrow();`,
      `  });`,
      `  it('calculates summary', () => {`,
      `    const exps = [{ amount: 10, category: 'Food' }, { amount: 20, category: 'Transport' }, { amount: 5, category: 'Food' }];`,
      `    const total = exps.reduce((s, e) => s + e.amount, 0);`,
      `    expect(total).toBe(35);`,
      `    const byCategory: Record<string, number> = {};`,
      `    exps.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    expect(byCategory['Food']).toBe(15);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# T3 Expenses — Battle-Tested`,
      ``,
      `Production-ready expense tracker with tRPC, Prisma, and Docker.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

/* ── Battle-Tested: OAuth + demo ── */
battleTestedOverrides.push(
  { path: 'scripts/setup.mjs', content: buildSetupScript('t3', 'battle-tested', getT3EnvVars()) },
  { path: 'demo.sequence.json', content: JSON.stringify(generateT3DemoSequence('battle-tested'), null, 2) },
);

/* ── Battle-Tested: social platform features ── */
battleTestedOverrides.push(
  { path: 'src/components/MessagePanel.tsx', content: generateMessagePanel() },
  { path: 'src/components/ProfileCard.tsx', content: generateProfileCard() },
  { path: 'src/components/SocialFeed.tsx', content: generateSocialFeed() },
  { path: 'src/components/NotificationPanel.tsx', content: generateNotificationPanel() },
);

/* ── Battle-Tested: domain component + admin + app shell ── */
battleTestedOverrides.push(
  { path: 'src/components/ExpenseTracker.tsx', content: generateExpenseTracker() },
  { path: 'src/components/AdminDashboard.tsx', content: generateAdminDashboard() },
  { path: 'src/App.tsx', content: generateGenericBattleTestedShell(T3_DOMAIN) },
);

const t3BattleTested: StackTemplate = {
  id: 't3-battle-tested',
  stackId: 't3',
  tier: 'battle-tested',
  name: 'T3 Battle-Tested',
  description: 'Social Platform — messaging, profiles, feed, notifications + Docker + CI/CD',
  features: [
    'Real-time messaging with conversation threads',
    'User profiles with followers/following',
    'Social feed with posts, likes, comments, shares',
    'Notification center (likes, comments, follows, mentions)',
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite',
    'GitHub Actions CI',
    'OAuth setup via wizard (Google, GitHub)',
    'Demo sequence for validation',
    'Everything from Solid tier',
  ],
  files: mergeFiles(t3Solid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate',
          'docker:build': 'docker build -t t3-vai .',
          'docker:up': 'docker compose up -d',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          react: '^19.2.0', 'react-dom': '^19.2.0', zod: '^4.3.0',
          '@prisma/client': '^6.6.0',
          'framer-motion': '^12.34.0', 'lucide-react': '^0.513.0', clsx: '^2.1.1', 'tailwind-merge': '^3.2.0',
        },
        devDependencies: {
          '@types/react': '^19.2.0', '@types/react-dom': '^19.2.0',
          '@vitejs/plugin-react': '^5.1.0', prisma: '^6.6.0',
          '@tailwindcss/vite': '^4.1.0', tailwindcss: '^4.1.0',
          typescript: '^5.9.0', vite: '^7.3.0', vitest: '^4.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci && npx prisma generate`,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build && npm prune --production`,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 't3-vai', version: '1.0.0', stack: 't3', tier: 'vai',`,
      `  features: { trpc: true, prisma: true, monitoring: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 T3 Expenses — Vai Premium`,
      ``,
      `> VeggaAI's curated T3 expense tracker.`,
      ``,
      `## Features`,
      `- 🔷 End-to-end type-safe tRPC procedures`,
      `- 💰 Category breakdown with visual chart`,
      `- 🗄️ Prisma ORM + Zod validation`,
      `- 🐳 Optimized Docker (non-root, healthcheck)`,
      `- 🧪 Vitest + CI/CD`,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

/* ── Vai Premium: domain component + admin + app shell ── */
vaiOverrides.push(
  { path: 'src/components/ExpenseTracker.tsx', content: generateExpenseTracker() },
  { path: 'src/components/AdminDashboard.tsx', content: generateAdminDashboard() },
  { path: 'src/App.tsx', content: generateGenericVaiShell(T3_DOMAIN) },
);

/* ── Vai Premium: full setup wizard, BYOK, glass UI, metrics ── */
vaiOverrides.push(
  { path: 'scripts/setup.mjs', content: buildSetupScript('t3', 'vai', getT3EnvVars()) },
  { path: 'demo.sequence.json', content: JSON.stringify(generateT3DemoSequence('vai'), null, 2) },
  {
    path: 'src/components/ErrorBoundary.tsx',
    content: [
      `import { Component, type ReactNode, type ErrorInfo } from 'react';`,
      ``,
      `interface Props { children: ReactNode; fallback?: ReactNode; }`,
      `interface State { hasError: boolean; error: Error | null; }`,
      ``,
      `export class ErrorBoundary extends Component<Props, State> {`,
      `  state: State = { hasError: false, error: null };`,
      `  static getDerivedStateFromError(error: Error): State { return { hasError: true, error }; }`,
      `  componentDidCatch(error: Error, info: ErrorInfo) { console.error('[Vai ErrorBoundary]', error, info.componentStack); }`,
      `  render() {`,
      `    if (this.state.hasError) {`,
      `      return this.props.fallback ?? (`,
      `        <div style={{ padding: 40, textAlign: 'center', color: '#ef4444' }}>`,
      `          <h2>Something went wrong</h2>`,
      `          <pre style={{ fontSize: '0.8rem', color: '#71717a', marginTop: 8 }}>{this.state.error?.message}</pre>`,
      `          <button onClick={() => this.setState({ hasError: false, error: null })}`,
      `            style={{ marginTop: 16, padding: '8px 16px', borderRadius: 8, background: '#27272a', color: '#e4e4e7', border: 'none', cursor: 'pointer' }}>`,
      `            Try Again`,
      `          </button>`,
      `        </div>`,
      `      );`,
      `    }`,
      `    return this.props.children;`,
      `  }`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/hooks/useApi.ts',
    content: [
      `import { useState, useCallback } from 'react';`,
      ``,
      `interface UseApiOptions<T> { onSuccess?: (data: T) => void; onError?: (error: Error) => void; }`,
      ``,
      `export function useApi<T>(url: string, options?: UseApiOptions<T>) {`,
      `  const [data, setData] = useState<T | null>(null);`,
      `  const [loading, setLoading] = useState(false);`,
      `  const [error, setError] = useState<Error | null>(null);`,
      ``,
      `  const execute = useCallback(async (init?: RequestInit) => {`,
      `    setLoading(true); setError(null);`,
      `    try {`,
      `      const res = await fetch(url, init);`,
      `      if (!res.ok) throw new Error(\`HTTP \${res.status}\`);`,
      `      const json = await res.json();`,
      `      setData(json); options?.onSuccess?.(json);`,
      `      return json as T;`,
      `    } catch (err) {`,
      `      const e = err instanceof Error ? err : new Error(String(err));`,
      `      setError(e); options?.onError?.(e); throw e;`,
      `    } finally { setLoading(false); }`,
      `  }, [url]);`,
      ``,
      `  return { data, loading, error, execute };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/monitor.ts',
    content: [
      `/** VeggaAI Performance Monitor — lightweight request tracing. */`,
      `interface RequestMetric { path: string; method: string; status: number; duration: number; timestamp: number; }`,
      `const metrics: RequestMetric[] = [];`,
      `const MAX_METRICS = 1000;`,
      ``,
      `export function recordMetric(metric: RequestMetric) {`,
      `  metrics.push(metric);`,
      `  if (metrics.length > MAX_METRICS) metrics.shift();`,
      `}`,
      ``,
      `export function getMetricsSummary() {`,
      `  const last5m = metrics.filter(m => m.timestamp > Date.now() - 5 * 60 * 1000);`,
      `  const avgDuration = last5m.length ? last5m.reduce((s, m) => s + m.duration, 0) / last5m.length : 0;`,
      `  const errorRate = last5m.length ? last5m.filter(m => m.status >= 400).length / last5m.length : 0;`,
      `  return {`,
      `    totalRequests: metrics.length,`,
      `    last5min: last5m.length,`,
      `    avgResponseMs: Math.round(avgDuration * 100) / 100,`,
      `    errorRate: Math.round(errorRate * 10000) / 100,`,
      `    uptime: process.uptime(),`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/ByokPanel.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { Key, Eye, EyeOff, Trash2, ExternalLink, CheckCircle2, AlertCircle } from 'lucide-react';`,
      ``,
      `interface SavedKey { id: string; provider: string; maskedKey: string; createdAt: string; }`,
      ``,
      `const PROVIDERS = [`,
      `  { id: 'openai', name: 'OpenAI', prefix: 'sk-', url: 'https://platform.openai.com/api-keys', icon: '🟢' },`,
      `  { id: 'anthropic', name: 'Anthropic', prefix: 'sk-ant-', url: 'https://console.anthropic.com/settings/keys', icon: '🟠' },`,
      `  { id: 'google', name: 'Google AI', prefix: 'AIza', url: 'https://aistudio.google.com/app/apikey', icon: '🔵' },`,
      `  { id: 'groq', name: 'Groq', prefix: 'gsk_', url: 'https://console.groq.com/keys', icon: '⚡' },`,
      `  { id: 'xai', name: 'Grok (xAI)', prefix: 'xai-', url: 'https://console.x.ai/team/default/api-keys', icon: '🤖' },`,
      `  { id: 'openrouter', name: 'OpenRouter', prefix: 'sk-or-', url: 'https://openrouter.ai/keys', icon: '🌐' },`,
      `];`,
      ``,
      `function detectProvider(key: string) {`,
      `  if (key.startsWith('sk-ant-')) return 'anthropic';`,
      `  if (key.startsWith('sk-or-')) return 'openrouter';`,
      `  if (key.startsWith('sk-')) return 'openai';`,
      `  if (key.startsWith('gsk_')) return 'groq';`,
      `  if (key.startsWith('xai-')) return 'xai';`,
      `  if (key.startsWith('AIza')) return 'google';`,
      `  return null;`,
      `}`,
      ``,
      `export function ByokPanel() {`,
      `  const [expanded, setExpanded] = useState(false);`,
      `  const [keyInput, setKeyInput] = useState('');`,
      `  const [detected, setDetected] = useState<string | null>(null);`,
      `  const [savedKeys, setSavedKeys] = useState<SavedKey[]>([]);`,
      `  const [remember, setRemember] = useState(true);`,
      `  const [saving, setSaving] = useState(false);`,
      `  const [showKey, setShowKey] = useState(false);`,
      ``,
      `  useEffect(() => { setDetected(detectProvider(keyInput)); }, [keyInput]);`,
      `  useEffect(() => { fetch('/api/ai-keys').then(r => r.json()).then(setSavedKeys).catch(() => {}); }, []);`,
      ``,
      `  const saveKey = async () => {`,
      `    if (!detected || !keyInput.trim()) return;`,
      `    setSaving(true);`,
      `    try {`,
      `      const res = await fetch('/api/ai-keys', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: keyInput, provider: detected, remember }) });`,
      `      if (res.ok) { const saved = await res.json(); setSavedKeys(prev => [...prev, saved]); setKeyInput(''); }`,
      `    } finally { setSaving(false); }`,
      `  };`,
      `  const deleteKey = async (id: string) => { setSavedKeys(prev => prev.filter(k => k.id !== id)); await fetch(\`/api/ai-keys/\${id}\`, { method: 'DELETE' }); };`,
      `  const detectedProvider = detected ? PROVIDERS.find(p => p.id === detected) : null;`,
      ``,
      `  return (`,
      `    <div data-testid="byok-panel" className="rounded-xl border border-zinc-800 bg-zinc-900/50 backdrop-blur-sm">`,
      `      <button onClick={() => setExpanded(!expanded)} className="flex w-full items-center justify-between px-4 py-3 text-sm">`,
      `        <span className="flex items-center gap-2"><Key className="h-4 w-4 text-amber-400" /><span className="font-medium">Use your own API key</span>`,
      `          {savedKeys.length > 0 && <span className="rounded-full bg-green-500/10 px-2 py-0.5 text-xs text-green-400">{savedKeys.length} saved</span>}`,
      `        </span>`,
      `        <span className={\`text-xs text-zinc-500 transition-transform \${expanded ? 'rotate-180' : ''}\`}>▾</span>`,
      `      </button>`,
      `      {expanded && (`,
      `        <div className="border-t border-zinc-800 p-4 space-y-3">`,
      `          <div className="relative">`,
      `            <input type={showKey ? 'text' : 'password'} value={keyInput} onChange={e => setKeyInput(e.target.value)}`,
      `              placeholder="Paste API key..." className="w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2.5 pr-20 text-sm text-zinc-200 placeholder-zinc-600 outline-none focus:border-blue-500/50" />`,
      `            <button onClick={() => setShowKey(!showKey)} className="absolute right-2 top-1/2 -translate-y-1/2 p-1 text-zinc-500 hover:text-zinc-300">`,
      `              {showKey ? <EyeOff className="h-3.5 w-3.5" /> : <Eye className="h-3.5 w-3.5" />}`,
      `            </button>`,
      `          </div>`,
      `          {detected && detectedProvider && (`,
      `            <div className="flex items-center gap-2 rounded-lg bg-green-500/5 border border-green-500/20 px-3 py-2">`,
      `              <span>{detectedProvider.icon}</span><span className="text-xs text-green-400">Detected: {detectedProvider.name}</span>`,
      `              <CheckCircle2 className="ml-auto h-3.5 w-3.5 text-green-400" />`,
      `            </div>`,
      `          )}`,
      `          {keyInput.length > 2 && !detected && (`,
      `            <div className="flex items-center gap-2 rounded-lg bg-amber-500/5 border border-amber-500/20 px-3 py-2">`,
      `              <AlertCircle className="h-3.5 w-3.5 text-amber-400" /><span className="text-xs text-amber-400">Unrecognized key format</span>`,
      `            </div>`,
      `          )}`,
      `          <div className="flex items-center justify-between">`,
      `            <label className="flex items-center gap-2 text-xs text-zinc-500">`,
      `              <input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} className="rounded border-zinc-700" /> Remember (encrypted)`,
      `            </label>`,
      `            <button onClick={saveKey} disabled={!detected || saving} className="rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-medium text-white disabled:opacity-40 hover:bg-blue-500 active:scale-[0.97]">`,
      `              {saving ? 'Saving...' : 'Save Key'}`,
      `            </button>`,
      `          </div>`,
      `          {savedKeys.length > 0 && (`,
      `            <div className="space-y-1.5"><p className="text-xs font-medium text-zinc-500">Saved keys:</p>`,
      `              {savedKeys.map(k => { const p = PROVIDERS.find(x => x.id === k.provider); return (`,
      `                <div key={k.id} className="flex items-center gap-2 rounded-lg border border-zinc-800 bg-zinc-950 px-3 py-2">`,
      `                  <span className="text-sm">{p?.icon || '🔑'}</span><span className="text-xs text-zinc-300">{p?.name || k.provider}</span>`,
      `                  <code className="text-xs text-zinc-600">{k.maskedKey}</code>`,
      `                  <button onClick={() => deleteKey(k.id)} className="ml-auto p-1 text-zinc-600 hover:text-red-400"><Trash2 className="h-3 w-3" /></button>`,
      `                </div>`,
      `              ); })}`,
      `            </div>`,
      `          )}`,
      `          <div className="pt-2 border-t border-zinc-800"><p className="mb-1.5 text-xs text-zinc-600">Get keys:</p>`,
      `            <div className="flex flex-wrap gap-1.5">`,
      `              {PROVIDERS.map(p => (<a key={p.id} href={p.url} target="_blank" rel="noopener"`,
      `                className="inline-flex items-center gap-1 rounded-md border border-zinc-800 px-2 py-1 text-xs text-zinc-400 hover:border-zinc-600 hover:text-zinc-200">`,
      `                {p.icon} {p.name} <ExternalLink className="h-2.5 w-2.5" /></a>))}`,
      `            </div>`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/GlassPanel.tsx',
    content: [
      `import type { ReactNode, CSSProperties } from 'react';`,
      `import clsx from 'clsx';`,
      ``,
      `interface GlassPanelProps { children: ReactNode; className?: string; style?: CSSProperties; variant?: 'default' | 'elevated' | 'subtle'; }`,
      `const variants = {`,
      `  default: 'bg-zinc-900/80 backdrop-blur-xl border-zinc-700/50 shadow-lg shadow-black/20',`,
      `  elevated: 'bg-zinc-800/90 backdrop-blur-2xl border-zinc-600/50 shadow-xl shadow-black/30',`,
      `  subtle: 'bg-zinc-950/60 backdrop-blur-md border-zinc-800/30',`,
      `};`,
      `export function GlassPanel({ children, className, style, variant = 'default' }: GlassPanelProps) {`,
      `  return <div className={clsx('rounded-xl border', variants[variant], className)} style={style}>{children}</div>;`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/KeySharingConsent.tsx',
    content: [
      `import { useState } from 'react';`,
      `import { Shield, Key, Check } from 'lucide-react';`,
      ``,
      `interface KeySharingConsentProps { onAccept: () => void; onDecline: () => void; platformName?: string; }`,
      ``,
      `export function KeySharingConsent({ onAccept, onDecline, platformName = 'VeggaAI' }: KeySharingConsentProps) {`,
      `  const [agreed, setAgreed] = useState(false);`,
      `  return (`,
      `    <div data-testid="key-consent" className="mx-auto max-w-md rounded-2xl border border-zinc-800 bg-zinc-900/90 backdrop-blur-xl p-6">`,
      `      <div className="mb-4 flex items-center gap-3">`,
      `        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10"><Shield className="h-5 w-5 text-blue-400" /></div>`,
      `        <div><h3 className="text-sm font-semibold">Platform Key Access</h3><p className="text-xs text-zinc-500">Use {platformName}'s AI keys</p></div>`,
      `      </div>`,
      `      <div className="mb-4 space-y-2 text-xs text-zinc-400">`,
      `        <p>By using platform-provided API keys, you agree to:</p>`,
      `        <ul className="space-y-1.5 pl-4">`,
      `          <li className="flex items-start gap-2"><Check className="mt-0.5 h-3 w-3 shrink-0 text-green-400" /><span>Rate limits apply (fair usage)</span></li>`,
      `          <li className="flex items-start gap-2"><Check className="mt-0.5 h-3 w-3 shrink-0 text-green-400" /><span>You can switch to BYOK anytime</span></li>`,
      `          <li className="flex items-start gap-2"><Key className="mt-0.5 h-3 w-3 shrink-0 text-amber-400" /><span>BYOK keys are encrypted at rest</span></li>`,
      `        </ul>`,
      `      </div>`,
      `      <label className="mb-4 flex items-center gap-2 text-xs text-zinc-400">`,
      `        <input type="checkbox" checked={agreed} onChange={e => setAgreed(e.target.checked)} className="rounded border-zinc-700" /> I agree to the terms`,
      `      </label>`,
      `      <div className="flex gap-2">`,
      `        <button onClick={onDecline} className="flex-1 rounded-lg border border-zinc-700 px-4 py-2.5 text-xs text-zinc-400 hover:bg-zinc-800">Use BYOK</button>`,
      `        <button onClick={onAccept} disabled={!agreed} className="flex-1 rounded-lg bg-blue-600 px-4 py-2.5 text-xs font-medium text-white disabled:opacity-40 hover:bg-blue-500 active:scale-[0.97]">Accept</button>`,
      `      </div>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/MetricsPanel.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { Activity, Clock, AlertTriangle, Zap, TrendingUp } from 'lucide-react';`,
      ``,
      `interface Metrics { totalRequests: number; last5min: number; avgResponseMs: number; errorRate: number; uptime: number; }`,
      ``,
      `export function MetricsPanel() {`,
      `  const [metrics, setMetrics] = useState<Metrics | null>(null);`,
      `  useEffect(() => {`,
      `    const refresh = () => fetch('/api/metrics').then(r => r.json()).then(setMetrics).catch(() => {});`,
      `    refresh(); const iv = setInterval(refresh, 5000); return () => clearInterval(iv);`,
      `  }, []);`,
      ``,
      `  if (!metrics) return <div className="space-y-2 p-4">{[...Array(4)].map((_, i) => <div key={i} className="h-16 animate-pulse rounded-xl bg-zinc-900" />)}</div>;`,
      ``,
      `  const fmt = (s: number) => { const h = Math.floor(s/3600); const m = Math.floor((s%3600)/60); return h > 0 ? \`\${h}h \${m}m\` : m > 0 ? \`\${m}m \${Math.floor(s%60)}s\` : \`\${Math.floor(s)}s\`; };`,
      `  const stats = [`,
      `    { icon: Activity, label: 'Requests (5m)', value: metrics.last5min, color: 'text-blue-400', bg: 'bg-blue-500/10' },`,
      `    { icon: Clock, label: 'Avg Response', value: metrics.avgResponseMs + 'ms', color: 'text-green-400', bg: 'bg-green-500/10' },`,
      `    { icon: AlertTriangle, label: 'Error Rate', value: metrics.errorRate + '%', color: metrics.errorRate > 5 ? 'text-red-400' : 'text-zinc-400', bg: metrics.errorRate > 5 ? 'bg-red-500/10' : 'bg-zinc-500/10' },`,
      `    { icon: Zap, label: 'Uptime', value: fmt(metrics.uptime), color: 'text-amber-400', bg: 'bg-amber-500/10' },`,
      `  ];`,
      ``,
      `  return (`,
      `    <div data-testid="metrics-panel" className="space-y-3 p-4">`,
      `      <div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-green-400" /><h3 className="text-sm font-semibold">Performance</h3></div>`,
      `      <div className="grid gap-2 sm:grid-cols-2">`,
      `        {stats.map(s => (`,
      `          <div key={s.label} className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-3 backdrop-blur-sm">`,
      `            <div className="flex items-center gap-2">`,
      `              <div className={\`flex h-7 w-7 items-center justify-center rounded-lg \${s.bg}\`}><s.icon className={\`h-3.5 w-3.5 \${s.color}\`} /></div>`,
      `              <div><p className="text-xs text-zinc-500">{s.label}</p><p className={\`text-sm font-bold \${s.color}\`}>{s.value}</p></div>`,
      `            </div>`,
      `          </div>`,
      `        ))}`,
      `      </div>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/components/Toast.tsx',
    content: [
      `import { useState, useCallback, createContext, useContext, type ReactNode } from 'react';`,
      `import { AnimatePresence, motion } from 'framer-motion';`,
      `import { CheckCircle2, AlertCircle, Info, X } from 'lucide-react';`,
      ``,
      `type ToastType = 'success' | 'error' | 'info';`,
      `interface Toast { id: string; type: ToastType; message: string; }`,
      `interface ToastContextType { toast: (type: ToastType, message: string) => void; }`,
      ``,
      `const ToastContext = createContext<ToastContextType>({ toast: () => {} });`,
      `export const useToast = () => useContext(ToastContext);`,
      ``,
      `const icons = { success: CheckCircle2, error: AlertCircle, info: Info };`,
      `const colors = { success: 'border-green-500/30 bg-green-500/10 text-green-400', error: 'border-red-500/30 bg-red-500/10 text-red-400', info: 'border-blue-500/30 bg-blue-500/10 text-blue-400' };`,
      ``,
      `export function ToastProvider({ children }: { children: ReactNode }) {`,
      `  const [toasts, setToasts] = useState<Toast[]>([]);`,
      `  const addToast = useCallback((type: ToastType, message: string) => {`,
      `    const id = crypto.randomUUID();`,
      `    setToasts(prev => [...prev, { id, type, message }]);`,
      `    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 3000);`,
      `  }, []);`,
      `  const dismiss = (id: string) => setToasts(prev => prev.filter(t => t.id !== id));`,
      ``,
      `  return (`,
      `    <ToastContext.Provider value={{ toast: addToast }}>`,
      `      {children}`,
      `      <div className="fixed bottom-4 right-4 z-[100] flex flex-col gap-2">`,
      `        <AnimatePresence>`,
      `          {toasts.map(t => {`,
      `            const Icon = icons[t.type];`,
      `            return (`,
      `              <motion.div key={t.id} initial={{ opacity: 0, y: 20, scale: 0.95 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -10, scale: 0.95 }}`,
      `                className={\`flex items-center gap-2 rounded-xl border px-4 py-3 backdrop-blur-xl \${colors[t.type]}\`}>`,
      `                <Icon className="h-4 w-4 shrink-0" /><span className="text-sm">{t.message}</span>`,
      `                <button onClick={() => dismiss(t.id)} className="ml-2 p-0.5 opacity-60 hover:opacity-100"><X className="h-3 w-3" /></button>`,
      `              </motion.div>`,
      `            );`,
      `          })}`,
      `        </AnimatePresence>`,
      `      </div>`,
      `    </ToastContext.Provider>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `@import "tailwindcss";`,
      ``,
      `@font-face { font-family: "Geist"; src: url("https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-sans/Geist-Variable.woff2") format("woff2"); font-weight: 100 900; font-display: swap; }`,
      `@font-face { font-family: "Geist Mono"; src: url("https://cdn.jsdelivr.net/npm/geist@1.3.1/dist/fonts/geist-mono/GeistMono-Variable.woff2") format("woff2"); font-weight: 100 900; font-display: swap; }`,
      ``,
      `@theme inline {`,
      `  --font-sans: "Geist", "Inter", system-ui, -apple-system, sans-serif;`,
      `  --font-mono: "Geist Mono", "JetBrains Mono", ui-monospace, monospace;`,
      `  --color-background: oklch(0.13 0 0);`,
      `  --color-foreground: oklch(0.93 0 0);`,
      `  --color-muted: oklch(0.16 0 0);`,
      `  --color-muted-foreground: oklch(0.60 0 0);`,
      `  --color-border: oklch(0.25 0 0);`,
      `  --color-border-active: oklch(0.45 0.14 250);`,
      `  --color-accent: oklch(0.65 0.20 250);`,
      `  --color-accent-foreground: oklch(0.985 0 0);`,
      `  --color-success: oklch(0.65 0.18 155);`,
      `  --color-warning: oklch(0.75 0.15 80);`,
      `  --color-destructive: oklch(0.60 0.22 25);`,
      `  --color-bg-elevated: oklch(0.19 0.005 250);`,
      `  --animate-shimmer: shimmer 1.5s infinite ease-in-out;`,
      `}`,
      ``,
      `@keyframes shimmer { 0% { background-position: 200% 0 } 100% { background-position: -200% 0 } }`,
      `.glass-panel { background: oklch(0.16 0.005 250 / 0.80); backdrop-filter: blur(16px) saturate(1.2); border: 1px solid oklch(0.30 0 0 / 0.50); border-radius: 12px; box-shadow: 0 4px 24px oklch(0 0 0 / 0.30); }`,
      `.skeleton { background: linear-gradient(90deg, oklch(0.19 0 0) 25%, oklch(0.23 0 0) 50%, oklch(0.19 0 0) 75%); background-size: 200% 100%; animation: shimmer 1.5s infinite ease-in-out; border-radius: 6px; }`,
      `.click-feedback:active { transform: scale(0.97); } .click-feedback { transition: transform 100ms cubic-bezier(0.16, 1, 0.3, 1); }`,
      `body { font-family: var(--font-sans); background: var(--color-background); color: var(--color-foreground); }`,
      `::-webkit-scrollbar { width: 6px; height: 6px; } ::-webkit-scrollbar-track { background: transparent; } ::-webkit-scrollbar-thumb { background: var(--color-border); border-radius: 3px; }`,
      `:focus-visible { outline: 2px solid oklch(0.45 0.14 250); outline-offset: 2px; }`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: [
      `import { createRoot } from 'react-dom/client';`,
      `import { App } from './App';`,
      `import { ErrorBoundary } from './components/ErrorBoundary';`,
      `import { ToastProvider } from './components/Toast';`,
      `import './index.css';`,
      ``,
      `createRoot(document.getElementById('root')!).render(`,
      `  <ErrorBoundary>`,
      `    <ToastProvider>`,
      `      <App />`,
      `    </ToastProvider>`,
      `  </ErrorBoundary>,`,
      `);`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: [
      `# ═══════════════════════════════════════════`,
      `# T3 Vai Premium — Environment Variables`,
      `# Run "node scripts/setup.mjs" for guided setup`,
      `# ═══════════════════════════════════════════`,
      `DATABASE_URL="file:./prisma/dev.db"`,
      `PORT=3000`,
      `JWT_SECRET=""`,
      `SESSION_SECRET=""`,
      `GOOGLE_CLIENT_ID=""`,
      `GOOGLE_CLIENT_SECRET=""`,
      `GITHUB_CLIENT_ID=""`,
      `GITHUB_CLIENT_SECRET=""`,
      `OPENAI_API_KEY=""`,
      `ANTHROPIC_API_KEY=""`,
      `AI_ENCRYPTION_KEY=""`,
      ``,
    ].join('\n'),
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const ExpenseSchema = z.object({ description: z.string().min(1).max(200), amount: z.number().positive(), category: z.string() });`,
      ``,
      `describe('T3 Vai — Validation', () => {`,
      `  it('validates expense creation', () => {`,
      `    expect(() => ExpenseSchema.parse({ description: '', amount: 10, category: 'Food' })).toThrow();`,
      `    expect(ExpenseSchema.parse({ description: 'Lunch', amount: 12.50, category: 'Food' })).toEqual({ description: 'Lunch', amount: 12.50, category: 'Food' });`,
      `  });`,
      `  it('rejects negative amounts', () => {`,
      `    expect(() => ExpenseSchema.parse({ description: 'Test', amount: -5, category: 'Other' })).toThrow();`,
      `  });`,
      `});`,
      ``,
      `describe('T3 — Category Aggregation', () => {`,
      `  it('groups expenses by category', () => {`,
      `    const expenses = [{ cat: 'Food', amount: 10 }, { cat: 'Food', amount: 20 }, { cat: 'Bills', amount: 50 }];`,
      `    const totals = expenses.reduce((acc, e) => { acc[e.cat] = (acc[e.cat] || 0) + e.amount; return acc; }, {} as Record<string, number>);`,
      `    expect(totals).toEqual({ Food: 30, Bills: 50 });`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
);

const t3Vai: StackTemplate = {
  id: 't3-vai',
  stackId: 't3',
  tier: 'vai',
  name: 'T3 Vai',
  description: "VeggaAI's premium T3 — BYOK, glass UI, monitoring, full setup wizard",
  features: [
    'Optimized Docker (non-root, healthcheck)',
    'BYOK panel — auto-detect provider, save encrypted',
    'Key sharing consent gate',
    'Glass panel components (OKLCH)',
    'Performance monitoring',
    'Full setup wizard (CLI + web) with all providers',
    'Demo sequence validates ALL features',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(t3BattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const t3Stack: StackDefinition = {
  id: 't3',
  name: 'T3 Stack',
  tagline: 'Type-safety everywhere',
  description: 'tRPC + Zod + React + TypeScript — end-to-end type-safe stack',
  techStack: ['tRPC', 'Zod', 'React', 'TypeScript'],
  icon: '🔷',
  color: 'purple',
  templates: [t3Basic, t3Solid, t3BattleTested, t3Vai],
};
