/**
 * T3 Stack — tRPC + Zod + React + TypeScript
 * All four tiers: Basic expense tracker → Vai premium.
 *
 * Showcases end-to-end type safety with tRPC-like procedure system.
 */

import type { StackDefinition, StackTemplate } from './types.js';
import { mergeFiles } from './types.js';

/* ================================================================
   BASIC TIER — Expense Tracker with tRPC-like Procedures
   End-to-end type-safe, Zod-validated, category-grouped expenses.
   ================================================================ */

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: { react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0' },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', typescript: '^5.7.0', vite: '^6.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head>`,
      `  <meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" />`,
      `  <title>T3 Expenses</title>`,
      `  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />`,
      `</head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      ``,
      `/* ── Data ── */`,
      `interface Expense { id: number; description: string; amount: number; category: string; date: string; }`,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      `let nextId = 8;`,
      `const expenses: Expense[] = [`,
      `  { id: 1, description: 'Grocery run', amount: 67.42, category: 'Food', date: '2025-01-15' },`,
      `  { id: 2, description: 'Uber to office', amount: 12.50, category: 'Transport', date: '2025-01-15' },`,
      `  { id: 3, description: 'Netflix subscription', amount: 15.99, category: 'Entertainment', date: '2025-01-14' },`,
      `  { id: 4, description: 'Electric bill', amount: 89.00, category: 'Bills', date: '2025-01-13' },`,
      `  { id: 5, description: 'Coffee beans', amount: 18.50, category: 'Food', date: '2025-01-13' },`,
      `  { id: 6, description: 'New headphones', amount: 79.99, category: 'Shopping', date: '2025-01-12' },`,
      `  { id: 7, description: 'Gym membership', amount: 45.00, category: 'Health', date: '2025-01-10' },`,
      `];`,
      ``,
      `/* ── Zod Schemas ── */`,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive().max(999999),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      `const UpdateExpense = z.object({`,
      `  description: z.string().min(1).max(200).optional(),`,
      `  amount: z.number().positive().optional(),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]).optional(),`,
      `}).partial();`,
      ``,
      `/* ── tRPC-like Type-Safe Procedures ── */`,
      `const procedures: Record<string, (input: unknown) => Promise<unknown>> = {`,
      `  'expense.list': async () => expenses.sort((a, b) => b.date.localeCompare(a.date)),`,
      `  'expense.create': async (input) => {`,
      `    const data = CreateExpense.parse(input);`,
      `    const exp: Expense = { id: nextId++, ...data };`,
      `    expenses.push(exp);`,
      `    return exp;`,
      `  },`,
      `  'expense.update': async (input) => {`,
      `    const { id, ...updates } = z.object({ id: z.number() }).merge(UpdateExpense).parse(input);`,
      `    const exp = expenses.find(e => e.id === id);`,
      `    if (exp) Object.assign(exp, updates);`,
      `    return exp;`,
      `  },`,
      `  'expense.delete': async (input) => {`,
      `    const { id } = z.object({ id: z.number() }).parse(input);`,
      `    const idx = expenses.findIndex(e => e.id === id);`,
      `    if (idx !== -1) expenses.splice(idx, 1);`,
      `    return { ok: true };`,
      `  },`,
      `  'expense.summary': async () => {`,
      `    const total = expenses.reduce((s, e) => s + e.amount, 0);`,
      `    const byCategory: Record<string, number> = {};`,
      `    expenses.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    return { total, count: expenses.length, byCategory, categories: CATEGORIES };`,
      `  },`,
      `};`,
      ``,
      `/* ── Plugin ── */`,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 't3-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        if (req.url === '/api/health') return json(res, { status: 'ok' });`,
      `        const m = req.url?.match(/^\\/api\\/trpc\\/(.+)$/);`,
      `        if (!m) return next();`,
      `        const proc = procedures[m[1]];`,
      `        if (!proc) return json(res, { error: 'Procedure not found' }, 404);`,
      `        try {`,
      `          const input = req.method === 'POST' ? await parseBody(req) : {};`,
      `          return json(res, { result: await proc(input) });`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', issues: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/trpc.ts',
    content: [
      `// Type-safe tRPC-like client`,
      `export async function trpc<T>(procedure: string, input?: unknown): Promise<T> {`,
      `  const res = await fetch(\`/api/trpc/\${procedure}\`, input !== undefined`,
      `    ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }`,
      `    : {});`,
      `  const data = await res.json();`,
      `  if (data.error) throw new Error(typeof data.error === 'string' ? data.error : 'Procedure failed');`,
      `  return data.result;`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useState, useEffect } from 'react';`,
      `import { trpc } from './trpc';`,
      ``,
      `interface Expense { id: number; description: string; amount: number; category: string; date: string; }`,
      `interface Summary { total: number; count: number; byCategory: Record<string, number>; categories: string[]; }`,
      ``,
      `export function App() {`,
      `  const [expenses, setExpenses] = useState<Expense[]>([]);`,
      `  const [summary, setSummary] = useState<Summary | null>(null);`,
      `  const [showAdd, setShowAdd] = useState(false);`,
      `  const [form, setForm] = useState({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) });`,
      ``,
      `  const load = async () => {`,
      `    const [exps, sum] = await Promise.all([`,
      `      trpc<Expense[]>('expense.list'),`,
      `      trpc<Summary>('expense.summary'),`,
      `    ]);`,
      `    setExpenses(exps);`,
      `    setSummary(sum);`,
      `  };`,
      ``,
      `  useEffect(() => { load(); }, []);`,
      ``,
      `  const addExpense = async () => {`,
      `    if (!form.description || !form.amount) return;`,
      `    await trpc('expense.create', { ...form, amount: parseFloat(form.amount) });`,
      `    setForm({ description: '', amount: '', category: 'Food', date: new Date().toISOString().slice(0, 10) });`,
      `    setShowAdd(false);`,
      `    load();`,
      `  };`,
      ``,
      `  const remove = async (id: number) => {`,
      `    await trpc('expense.delete', { id });`,
      `    load();`,
      `  };`,
      ``,
      `  const topCat = summary ? Object.entries(summary.byCategory).sort((a, b) => b[1] - a[1]) : [];`,
      ``,
      `  return (`,
      `    <div className="dashboard">`,
      `      <header className="header">`,
      `        <h1>🔷 Expense Tracker</h1>`,
      `        <p>tRPC · Zod · React · TypeScript — End-to-end type safety</p>`,
      `      </header>`,
      ``,
      `      {summary && (`,
      `        <div className="stats">`,
      `          <div className="stat-card">`,
      `            <span className="label">Total Spent</span>`,
      `            <div className="value purple">$\{summary.total.toFixed(2)}</div>`,
      `          </div>`,
      `          <div className="stat-card">`,
      `            <span className="label">Transactions</span>`,
      `            <div className="value blue">{summary.count}</div>`,
      `          </div>`,
      `          <div className="stat-card">`,
      `            <span className="label">Top Category</span>`,
      `            <div className="value amber">{topCat[0]?.[0] || '—'}</div>`,
      `          </div>`,
      `        </div>`,
      `      )}`,
      ``,
      `      {/* Category breakdown bar */}`,
      `      {summary && topCat.length > 0 && (`,
      `        <div className="bar-chart">`,
      `          {topCat.map(([cat, amt]) => (`,
      `            <div key={cat} className="bar-row">`,
      `              <span className="bar-label">{cat}</span>`,
      `              <div className="bar-track">`,
      `                <div className="bar-fill" style={{ width: \`\${(amt / summary.total) * 100}%\` }} />`,
      `              </div>`,
      `              <span className="bar-amount">$\{amt.toFixed(0)}</span>`,
      `            </div>`,
      `          ))}`,
      `        </div>`,
      `      )}`,
      ``,
      `      <div className="toolbar">`,
      `        <span className="toolbar-title">Recent Expenses</span>`,
      `        <button className={\`btn \${showAdd ? '' : 'btn-primary'}\`} onClick={() => setShowAdd(!showAdd)}>`,
      `          {showAdd ? 'Cancel' : '+ Add Expense'}`,
      `        </button>`,
      `      </div>`,
      ``,
      `      {showAdd && (`,
      `        <div className="add-form">`,
      `          <input placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} />`,
      `          <input placeholder="Amount" type="number" step="0.01" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} />`,
      `          <select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}>`,
      `            {(summary?.categories || []).map(c => <option key={c}>{c}</option>)}`,
      `          </select>`,
      `          <input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })} />`,
      `          <button className="btn btn-primary" onClick={addExpense}>Save</button>`,
      `        </div>`,
      `      )}`,
      ``,
      `      <div className="expense-list">`,
      `        {expenses.map(e => (`,
      `          <div key={e.id} className="expense-row">`,
      `            <div className="exp-main">`,
      `              <span className="exp-desc">{e.description}</span>`,
      `              <span className="exp-cat">{e.category}</span>`,
      `            </div>`,
      `            <div className="exp-right">`,
      `              <span className="exp-amount">$\{e.amount.toFixed(2)}</span>`,
      `              <span className="exp-date">{e.date}</span>`,
      `              <button className="del" onClick={() => remove(e.id)}>×</button>`,
      `            </div>`,
      `          </div>`,
      `        ))}`,
      `      </div>`,
      `      {expenses.length === 0 && <p className="empty">No expenses yet</p>}`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: 'Inter', system-ui, sans-serif; background: #09090b; color: #e4e4e7; -webkit-font-smoothing: antialiased; }`,
      ``,
      `.dashboard { max-width: 800px; margin: 0 auto; padding: 40px 24px; }`,
      `.header { margin-bottom: 28px; }`,
      `.header h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 4px; }`,
      `.header p { color: #71717a; font-size: 0.85rem; }`,
      ``,
      `/* Stats */`,
      `.stats { display: flex; gap: 12px; margin-bottom: 20px; }`,
      `.stat-card { flex: 1; background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; }`,
      `.stat-card .label { font-size: 0.7rem; color: #71717a; text-transform: uppercase; letter-spacing: 0.05em; }`,
      `.stat-card .value { font-size: 1.4rem; font-weight: 700; margin-top: 4px; }`,
      `.stat-card .value.purple { color: #a78bfa; }`,
      `.stat-card .value.blue { color: #60a5fa; }`,
      `.stat-card .value.amber { color: #fbbf24; }`,
      ``,
      `/* Bar chart */`,
      `.bar-chart { background: #111115; border: 1px solid #1c1c22; border-radius: 10px; padding: 16px; margin-bottom: 20px; }`,
      `.bar-row { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }`,
      `.bar-row:last-child { margin-bottom: 0; }`,
      `.bar-label { width: 100px; font-size: 0.8rem; color: #a1a1aa; text-align: right; }`,
      `.bar-track { flex: 1; height: 8px; background: #1c1c22; border-radius: 4px; overflow: hidden; }`,
      `.bar-fill { height: 100%; background: #7c3aed; border-radius: 4px; transition: width 0.3s ease; }`,
      `.bar-amount { width: 50px; font-size: 0.8rem; color: #71717a; }`,
      ``,
      `/* Toolbar */`,
      `.toolbar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }`,
      `.toolbar-title { font-size: 0.9rem; font-weight: 600; }`,
      `.btn { padding: 8px 16px; border-radius: 8px; background: #18181b; color: #e4e4e7; border: 1px solid #27272a; font-size: 0.85rem; font-weight: 500; cursor: pointer; transition: all 0.15s; }`,
      `.btn:hover { background: #27272a; }`,
      `.btn-primary { background: #7c3aed; border-color: #7c3aed; color: #fff; }`,
      `.btn-primary:hover { background: #6d28d9; }`,
      ``,
      `/* Add form */`,
      `.add-form { display: flex; gap: 8px; padding: 12px; background: #111115; border: 1px solid #1c1c22; border-radius: 10px; margin-bottom: 12px; flex-wrap: wrap; }`,
      `.add-form input, .add-form select { padding: 8px 12px; border-radius: 6px; border: 1px solid #27272a; background: #141418; color: #e4e4e7; font-size: 0.85rem; outline: none; flex: 1; min-width: 120px; }`,
      `.add-form select { cursor: pointer; }`,
      `.add-form input:focus, .add-form select:focus { border-color: #7c3aed; }`,
      ``,
      `/* Expense list */`,
      `.expense-list { display: flex; flex-direction: column; gap: 4px; }`,
      `.expense-row { display: flex; align-items: center; justify-content: space-between; padding: 12px 14px; background: #111115; border: 1px solid #1c1c22; border-radius: 8px; transition: border-color 0.15s; }`,
      `.expense-row:hover { border-color: #27272a; }`,
      `.exp-main { display: flex; align-items: center; gap: 10px; flex: 1; min-width: 0; }`,
      `.exp-desc { font-size: 0.9rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }`,
      `.exp-cat { font-size: 0.7rem; padding: 2px 8px; border-radius: 10px; background: #1c1c22; color: #a1a1aa; white-space: nowrap; }`,
      `.exp-right { display: flex; align-items: center; gap: 12px; flex-shrink: 0; }`,
      `.exp-amount { font-size: 0.9rem; font-weight: 600; color: #a78bfa; }`,
      `.exp-date { font-size: 0.75rem; color: #52525b; }`,
      `.del { background: none; border: none; color: #52525b; cursor: pointer; font-size: 1.1rem; padding: 4px 8px; border-radius: 4px; opacity: 0; transition: all 0.15s; }`,
      `.expense-row:hover .del { opacity: 1; }`,
      `.del:hover { color: #ef4444; background: #1c1c22; }`,
      `.empty { color: #52525b; text-align: center; padding: 48px; }`,
      ``,
      `@media (max-width: 640px) { .stats { flex-direction: column; } .add-form { flex-direction: column; } .expense-row { flex-direction: column; align-items: flex-start; gap: 8px; } }`,
      ``,
    ].join('\n'),
  },
];

const t3Basic: StackTemplate = {
  id: 't3-basic',
  stackId: 't3',
  tier: 'basic',
  name: 'T3 Basic',
  description: 'Expense tracker — tRPC procedures, Zod validation, category breakdown',
  features: [
    'tRPC-style typed procedures (5 endpoints)',
    'Zod schema validation',
    'Category breakdown chart',
    'Dashboard stats cards',
    'Type-safe client helper',
    'React 19 + TypeScript',
  ],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   SOLID TIER — Prisma + enhanced tRPC patterns
   ================================================================ */

const solidOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-solid',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          postinstall: 'npx prisma generate & npx prisma db push',
          'db:studio': 'prisma studio',
        },
        dependencies: {
          react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0',
          '@prisma/client': '^6.0.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', prisma: '^6.0.0',
          typescript: '^5.7.0', vite: '^6.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'prisma/schema.prisma',
    content: [
      `generator client { provider = "prisma-client-js" }`,
      `datasource db { provider = "sqlite"; url = "file:./dev.db" }`,
      ``,
      `model Expense {`,
      `  id          Int      @id @default(autoincrement())`,
      `  description String`,
      `  amount      Float`,
      `  category    String   @default("Other")`,
      `  date        String`,
      `  createdAt   DateTime @default(now())`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      `import { PrismaClient } from '@prisma/client';`,
      ``,
      `const prisma = new PrismaClient();`,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      ``,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive().max(999999),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      ``,
      `const procedures: Record<string, (input: unknown) => Promise<unknown>> = {`,
      `  'expense.list': async () => prisma.expense.findMany({ orderBy: { date: 'desc' } }),`,
      `  'expense.create': async (input) => {`,
      `    const data = CreateExpense.parse(input);`,
      `    return prisma.expense.create({ data });`,
      `  },`,
      `  'expense.delete': async (input) => {`,
      `    const { id } = z.object({ id: z.number() }).parse(input);`,
      `    await prisma.expense.delete({ where: { id } });`,
      `    return { ok: true };`,
      `  },`,
      `  'expense.summary': async () => {`,
      `    const all = await prisma.expense.findMany();`,
      `    const total = all.reduce((s, e) => s + e.amount, 0);`,
      `    const byCategory: Record<string, number> = {};`,
      `    all.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    return { total, count: all.length, byCategory, categories: CATEGORIES };`,
      `  },`,
      `};`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 't3-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        if (req.url === '/api/health') return json(res, { status: 'ok' });`,
      `        const m = req.url?.match(/^\\/api\\/trpc\\/(.+)$/);`,
      `        if (!m) return next();`,
      `        const proc = procedures[m[1]];`,
      `        if (!proc) return json(res, { error: 'Procedure not found' }, 404);`,
      `        try {`,
      `          const input = req.method === 'POST' ? await parseBody(req) : {};`,
      `          return json(res, { result: await proc(input) });`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', issues: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: '.env.example',
    content: `# Switch to PostgreSQL for production\nDATABASE_URL="file:./prisma/dev.db"\n`,
  },
];

const t3Solid: StackTemplate = {
  id: 't3-solid',
  stackId: 't3',
  tier: 'solid',
  name: 'T3 Solid',
  description: 'Prisma ORM + enhanced tRPC procedures',
  features: [
    'Prisma ORM with auto-migration',
    'Type-safe tRPC procedures backed by DB',
    'Zod validation on all inputs',
    'Everything from Basic tier',
  ],
  files: mergeFiles(basicFiles, solidOverrides),
  hasDocker: false,
  hasTests: false,
};

/* ================================================================
   BATTLE-TESTED TIER
   ================================================================ */

const battleTestedOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-battle-tested',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t t3-app .',
          'docker:up': 'docker compose up -d',
        },
        dependencies: {
          react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0',
          '@prisma/client': '^6.0.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', prisma: '^6.0.0',
          typescript: '^5.7.0', vite: '^6.0.0', vitest: '^3.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci`,
      `COPY . .`,
      `RUN npm run build`,
      `FROM node:22-alpine`,
      `WORKDIR /app`,
      `COPY --from=builder /app/dist ./dist`,
      `COPY --from=builder /app/node_modules ./node_modules`,
      `COPY --from=builder /app/package*.json ./`,
      `COPY --from=builder /app/prisma ./prisma`,
      `EXPOSE 3000`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'docker-compose.yml',
    content: [
      `version: '3.9'`,
      `services:`,
      `  db:`,
      `    image: postgres:16-alpine`,
      `    environment:`,
      `      POSTGRES_DB: t3_app`,
      `      POSTGRES_USER: t3`,
      `      POSTGRES_PASSWORD: t3_secret`,
      `    ports: ['5432:5432']`,
      `    healthcheck:`,
      `      test: ['CMD-SHELL', 'pg_isready -U t3']`,
      `      interval: 5s`,
      `  app:`,
      `    build: .`,
      `    ports: ['3000:3000']`,
      `    depends_on:`,
      `      db: { condition: service_healthy }`,
      `    environment:`,
      `      DATABASE_URL: postgresql://t3:t3_secret@db:5432/t3_app`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vitest.config.ts',
    content: `import { defineConfig } from 'vitest/config';\nexport default defineConfig({ test: { globals: true, include: ['__tests__/**/*.test.ts'] } });\n`,
  },
  {
    path: '__tests__/api.test.ts',
    content: [
      `import { describe, it, expect } from 'vitest';`,
      `import { z } from 'zod';`,
      ``,
      `const CATEGORIES = ['Food', 'Transport', 'Entertainment', 'Bills', 'Shopping', 'Health', 'Other'];`,
      `const CreateExpense = z.object({`,
      `  description: z.string().min(1).max(200),`,
      `  amount: z.number().positive(),`,
      `  category: z.enum(CATEGORIES as [string, ...string[]]),`,
      `  date: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/),`,
      `});`,
      ``,
      `describe('T3 Expense API', () => {`,
      `  it('validates expense creation', () => {`,
      `    expect(() => CreateExpense.parse({ description: '', amount: 0, category: 'Bad', date: 'x' })).toThrow();`,
      `    expect(CreateExpense.parse({ description: 'Lunch', amount: 12.5, category: 'Food', date: '2025-01-15' })).toBeDefined();`,
      `  });`,
      `  it('rejects negative amounts', () => {`,
      `    expect(() => CreateExpense.parse({ description: 'Refund', amount: -5, category: 'Other', date: '2025-01-15' })).toThrow();`,
      `  });`,
      `  it('calculates summary', () => {`,
      `    const exps = [{ amount: 10, category: 'Food' }, { amount: 20, category: 'Transport' }, { amount: 5, category: 'Food' }];`,
      `    const total = exps.reduce((s, e) => s + e.amount, 0);`,
      `    expect(total).toBe(35);`,
      `    const byCategory: Record<string, number> = {};`,
      `    exps.forEach(e => { byCategory[e.category] = (byCategory[e.category] || 0) + e.amount; });`,
      `    expect(byCategory['Food']).toBe(15);`,
      `  });`,
      `});`,
      ``,
    ].join('\n'),
  },
  {
    path: '.github/workflows/ci.yml',
    content: [
      `name: CI`,
      `on: [push, pull_request]`,
      `jobs:`,
      `  test:`,
      `    runs-on: ubuntu-latest`,
      `    steps:`,
      `      - uses: actions/checkout@v4`,
      `      - uses: actions/setup-node@v4`,
      `        with: { node-version: 22, cache: npm }`,
      `      - run: npm ci`,
      `      - run: npm test`,
      `      - run: npm run build`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# T3 Expenses — Battle-Tested`,
      ``,
      `Production-ready expense tracker with tRPC, Prisma, and Docker.`,
      ``,
      `## Quick Start`,
      `\`\`\`bash`,
      `npm install && npm run dev`,
      `\`\`\``,
      ``,
      `## Docker`,
      `\`\`\`bash`,
      `docker compose up -d`,
      `\`\`\``,
      ``,
    ].join('\n'),
  },
];

const t3BattleTested: StackTemplate = {
  id: 't3-battle-tested',
  stackId: 't3',
  tier: 'battle-tested',
  name: 'T3 Battle-Tested',
  description: 'Deployment ready — Docker, tests, CI/CD',
  features: [
    'Docker + Docker Compose with PostgreSQL',
    'Vitest test suite',
    'GitHub Actions CI',
    'Everything from Solid tier',
  ],
  files: mergeFiles(t3Solid.files, battleTestedOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   VAI TIER
   ================================================================ */

const vaiOverrides: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-vai',
        private: true,
        type: 'module',
        scripts: {
          dev: 'vite', build: 'vite build', preview: 'vite preview',
          test: 'vitest run', 'test:watch': 'vitest',
          postinstall: 'npx prisma generate & npx prisma db push',
          'docker:build': 'docker build -t t3-vai .',
          'docker:up': 'docker compose up -d',
          lint: 'tsc --noEmit',
        },
        dependencies: {
          react: '^19.0.0', 'react-dom': '^19.0.0', zod: '^3.23.0',
          '@prisma/client': '^6.0.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0', '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0', prisma: '^6.0.0',
          typescript: '^5.7.0', vite: '^6.0.0', vitest: '^3.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'Dockerfile',
    content: [
      `FROM node:22-alpine AS deps`,
      `WORKDIR /app`,
      `COPY package*.json prisma/ ./`,
      `RUN npm ci && npx prisma generate`,
      `FROM node:22-alpine AS builder`,
      `WORKDIR /app`,
      `COPY --from=deps /app/node_modules ./node_modules`,
      `COPY . .`,
      `RUN npm run build && npm prune --production`,
      `FROM node:22-alpine`,
      `RUN addgroup --system app && adduser --system --ingroup app app`,
      `WORKDIR /app`,
      `COPY --from=builder --chown=app:app /app/dist ./dist`,
      `COPY --from=builder --chown=app:app /app/node_modules ./node_modules`,
      `COPY --from=builder --chown=app:app /app/package.json ./`,
      `COPY --from=builder --chown=app:app /app/prisma ./prisma`,
      `USER app`,
      `EXPOSE 3000`,
      `HEALTHCHECK --interval=30s --timeout=3s CMD wget -qO- http://localhost:3000/api/health || exit 1`,
      `CMD ["node", "dist/server/index.js"]`,
      ``,
    ].join('\n'),
  },
  {
    path: 'vai.config.ts',
    content: [
      `export default {`,
      `  name: 't3-vai', version: '1.0.0', stack: 't3', tier: 'vai',`,
      `  features: { trpc: true, prisma: true, monitoring: true },`,
      `  database: { provider: 'postgresql', devProvider: 'sqlite' },`,
      `};`,
      ``,
    ].join('\n'),
  },
  {
    path: 'README.md',
    content: [
      `# 🤖 T3 Expenses — Vai Premium`,
      ``,
      `> VeggaAI's curated T3 expense tracker.`,
      ``,
      `## Features`,
      `- 🔷 End-to-end type-safe tRPC procedures`,
      `- 💰 Category breakdown with visual chart`,
      `- 🗄️ Prisma ORM + Zod validation`,
      `- 🐳 Optimized Docker (non-root, healthcheck)`,
      `- 🧪 Vitest + CI/CD`,
      ``,
      `---`,
      `*Built with VeggaAI*`,
      ``,
    ].join('\n'),
  },
];

const t3Vai: StackTemplate = {
  id: 't3-vai',
  stackId: 't3',
  tier: 'vai',
  name: 'T3 Vai',
  description: "VeggaAI's premium T3 — optimized Docker, monitoring",
  features: [
    'Optimized Docker (non-root, healthcheck)',
    'Vai project config',
    'Everything from Battle-Tested tier',
  ],
  files: mergeFiles(t3BattleTested.files, vaiOverrides),
  hasDocker: true,
  hasTests: true,
};

/* ================================================================
   EXPORT
   ================================================================ */

export const t3Stack: StackDefinition = {
  id: 't3',
  name: 'T3 Stack',
  tagline: 'Type-safety everywhere',
  description: 'tRPC + Zod + React + TypeScript — end-to-end type-safe stack',
  techStack: ['tRPC', 'Zod', 'React', 'TypeScript'],
  icon: '🔷',
  color: 'purple',
  templates: [t3Basic, t3Solid, t3BattleTested, t3Vai],
};
