/**
 * T3 Stack — Next.js + tRPC + Tailwind + TypeScript
 * Basic tier with simplified tRPC-like patterns, higher tiers coming soon.
 */

import type { StackDefinition, StackTemplate } from './types.js';

const basicFiles: { path: string; content: string }[] = [
  {
    path: 'package.json',
    content: JSON.stringify(
      {
        name: 't3-basic',
        private: true,
        type: 'module',
        scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
        dependencies: {
          react: '^19.0.0',
          'react-dom': '^19.0.0',
          zod: '^3.23.0',
        },
        devDependencies: {
          '@types/react': '^19.0.0',
          '@types/react-dom': '^19.0.0',
          '@vitejs/plugin-react': '^4.3.0',
          typescript: '^5.7.0',
          vite: '^6.0.0',
        },
      },
      null,
      2,
    ),
  },
  {
    path: 'vite.config.ts',
    content: [
      `import { defineConfig } from 'vite';`,
      `import react from '@vitejs/plugin-react';`,
      `import { apiPlugin } from './server/plugin';`,
      ``,
      `export default defineConfig({ plugins: [react(), apiPlugin()] });`,
      ``,
    ].join('\n'),
  },
  {
    path: 'tsconfig.json',
    content: JSON.stringify(
      {
        compilerOptions: {
          target: 'ES2022', module: 'ESNext', moduleResolution: 'bundler',
          jsx: 'react-jsx', strict: true, esModuleInterop: true, skipLibCheck: true,
        },
        include: ['src', 'server'],
      },
      null,
      2,
    ),
  },
  {
    path: 'index.html',
    content: [
      `<!DOCTYPE html>`,
      `<html lang="en">`,
      `<head><meta charset="UTF-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>T3 Stack</title></head>`,
      `<body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body>`,
      `</html>`,
      ``,
    ].join('\n'),
  },
  {
    path: 'server/plugin.ts',
    content: [
      `import type { Plugin, Connect } from 'vite';`,
      `import { z } from 'zod';`,
      ``,
      `// Simplified tRPC-like pattern — type-safe procedures`,
      `interface Todo { id: number; text: string; done: boolean; }`,
      `const todos: Todo[] = [`,
      `  { id: 1, text: 'Learn tRPC patterns', done: true },`,
      `  { id: 2, text: 'Add Prisma ORM', done: false },`,
      `];`,
      `let nextId = 3;`,
      ``,
      `const CreateInput = z.object({ text: z.string().min(1) });`,
      `const UpdateInput = z.object({ id: z.number(), done: z.boolean().optional(), text: z.string().optional() });`,
      ``,
      `// Type-safe procedures (tRPC-like)`,
      `const procedures = {`,
      `  'todo.list': async () => todos,`,
      `  'todo.create': async (input: unknown) => {`,
      `    const { text } = CreateInput.parse(input);`,
      `    const todo = { id: nextId++, text, done: false };`,
      `    todos.push(todo);`,
      `    return todo;`,
      `  },`,
      `  'todo.update': async (input: unknown) => {`,
      `    const { id, ...updates } = UpdateInput.parse(input);`,
      `    const todo = todos.find(t => t.id === id);`,
      `    if (todo) Object.assign(todo, updates);`,
      `    return todo;`,
      `  },`,
      `  'todo.delete': async (input: unknown) => {`,
      `    const { id } = z.object({ id: z.number() }).parse(input);`,
      `    const idx = todos.findIndex(t => t.id === id);`,
      `    if (idx !== -1) todos.splice(idx, 1);`,
      `    return { ok: true };`,
      `  },`,
      `} as Record<string, (input: unknown) => Promise<unknown>>;`,
      ``,
      `function json(res: Connect.ServerResponse, data: unknown, status = 200) {`,
      `  res.statusCode = status; res.setHeader('Content-Type', 'application/json'); res.end(JSON.stringify(data));`,
      `}`,
      `function parseBody(req: Connect.IncomingMessage): Promise<any> {`,
      `  return new Promise(r => { let b = ''; req.on('data', c => b += c); req.on('end', () => r(b ? JSON.parse(b) : {})); });`,
      `}`,
      ``,
      `export function apiPlugin(): Plugin {`,
      `  return {`,
      `    name: 't3-api',`,
      `    configureServer(server) {`,
      `      server.middlewares.use(async (req, res, next) => {`,
      `        if (req.url === '/api/health') return json(res, { status: 'ok' });`,
      `        const m = req.url?.match(/^\\/api\\/trpc\\/(.+)$/);`,
      `        if (!m) return next();`,
      `        const proc = procedures[m[1]];`,
      `        if (!proc) return json(res, { error: 'Procedure not found' }, 404);`,
      `        try {`,
      `          const input = req.method === 'POST' ? await parseBody(req) : {};`,
      `          const result = await proc(input);`,
      `          return json(res, { result });`,
      `        } catch (err) {`,
      `          if (err instanceof z.ZodError) return json(res, { error: 'Validation failed', issues: err.issues }, 400);`,
      `          return json(res, { error: (err as Error).message }, 500);`,
      `        }`,
      `      });`,
      `    },`,
      `  };`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/main.tsx',
    content: `import { createRoot } from 'react-dom/client';\nimport { App } from './App';\nimport './index.css';\ncreateRoot(document.getElementById('root')!).render(<App />);\n`,
  },
  {
    path: 'src/App.tsx',
    content: [
      `import { useEffect, useState } from 'react';`,
      ``,
      `interface Todo { id: number; text: string; done: boolean; }`,
      ``,
      `// Type-safe tRPC-like client`,
      `async function trpc<T>(procedure: string, input?: unknown): Promise<T> {`,
      `  const res = await fetch(\`/api/trpc/\${procedure}\`, input !== undefined`,
      `    ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) }`,
      `    : {});`,
      `  const data = await res.json();`,
      `  if (data.error) throw new Error(data.error);`,
      `  return data.result;`,
      `}`,
      ``,
      `export function App() {`,
      `  const [todos, setTodos] = useState<Todo[]>([]);`,
      `  const [text, setText] = useState('');`,
      `  useEffect(() => { trpc<Todo[]>('todo.list').then(setTodos); }, []);`,
      ``,
      `  const add = async () => {`,
      `    if (!text.trim()) return;`,
      `    const todo = await trpc<Todo>('todo.create', { text });`,
      `    setTodos([...todos, todo]); setText('');`,
      `  };`,
      ``,
      `  return (`,
      `    <div className="app">`,
      `      <h1>🔷 T3 Stack Todos</h1>`,
      `      <p className="sub">tRPC · Zod · React · TypeScript</p>`,
      `      <div className="input-row">`,
      `        <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} placeholder="Add via tRPC..." />`,
      `        <button onClick={add}>Add</button>`,
      `      </div>`,
      `      <ul>{todos.map(t => (`,
      `        <li key={t.id}>`,
      `          <input type="checkbox" checked={t.done} onChange={async () => {`,
      `            await trpc('todo.update', { id: t.id, done: !t.done });`,
      `            setTodos(todos.map(x => x.id === t.id ? { ...x, done: !x.done } : x));`,
      `          }} />`,
      `          <span style={{ textDecoration: t.done ? 'line-through' : 'none' }}>{t.text}</span>`,
      `        </li>`,
      `      ))}</ul>`,
      `    </div>`,
      `  );`,
      `}`,
      ``,
    ].join('\n'),
  },
  {
    path: 'src/index.css',
    content: [
      `*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }`,
      `body { font-family: system-ui, sans-serif; background: #09090b; color: #e4e4e7; }`,
      `.app { max-width: 600px; margin: 60px auto; padding: 0 20px; }`,
      `h1 { font-size: 2rem; margin-bottom: 4px; }`,
      `.sub { color: #71717a; font-size: 0.875rem; margin-bottom: 32px; }`,
      `.input-row { display: flex; gap: 8px; margin-bottom: 24px; }`,
      `.input-row input { flex: 1; padding: 10px 14px; border-radius: 8px; border: 1px solid #27272a; background: #18181b; color: #e4e4e7; font-size: 0.9rem; }`,
      `.input-row button { padding: 10px 20px; border-radius: 8px; background: #7c3aed; color: #fff; border: none; font-weight: 600; cursor: pointer; }`,
      `ul { list-style: none; } li { display: flex; align-items: center; gap: 12px; padding: 10px 0; border-bottom: 1px solid #27272a; }`,
      `li input[type="checkbox"] { width: 18px; height: 18px; accent-color: #7c3aed; }`,
      `li span { flex: 1; font-size: 0.9rem; }`,
      ``,
    ].join('\n'),
  },
];

const t3Basic: StackTemplate = {
  id: 't3-basic',
  stackId: 't3',
  tier: 'basic',
  name: 'T3 Basic',
  description: 'Type-safe full-stack with tRPC-like patterns and Zod',
  features: ['tRPC-style typed procedures', 'Zod validation', 'React 19 + TypeScript', 'Type-safe client'],
  files: basicFiles,
  hasDocker: false,
  hasTests: false,
};

const comingSoon = (tier: 'solid' | 'battle-tested' | 'vai'): StackTemplate => ({
  id: `t3-${tier}`,
  stackId: 't3',
  tier,
  name: `T3 ${tier === 'battle-tested' ? 'Battle-Tested' : tier === 'vai' ? 'Vai' : 'Solid'}`,
  description: 'Coming soon',
  features: ['Coming soon — check back for updates'],
  files: [],
  hasDocker: tier === 'battle-tested' || tier === 'vai',
  hasTests: tier === 'battle-tested' || tier === 'vai',
  comingSoon: true,
});

export const t3Stack: StackDefinition = {
  id: 't3',
  name: 'T3 Stack',
  tagline: 'Type-safety everywhere',
  description: 'tRPC + Zod + React + TypeScript — end-to-end type-safe stack',
  techStack: ['tRPC', 'Zod', 'React', 'TypeScript'],
  icon: '🔷',
  color: 'purple',
  templates: [t3Basic, comingSoon('solid'), comingSoon('battle-tested'), comingSoon('vai')],
};
