/**
 * MessageBubble — Claude-inspired message rendering.
 *
 * User messages: right-aligned pill with subtle tinted bg, max-width ~80%.
 * Assistant messages: left-aligned, full width, no bubble — flowing markdown.
 * Action buttons: always visible on latest, hover-reveal on older messages.
 * Deploy markers, nudge/clarify pickers preserved from previous version.
 */

import { useState, useCallback } from 'react';
import { MarkdownRenderer } from '@vai/ui';
import { API_BASE } from '../lib/api.js';
import {
  Copy, Check, FileText, Rocket, HelpCircle, X as XIcon,
  ChevronRight, CornerDownRight, User, Bot, ThumbsUp, ThumbsDown,
  Wrench, Sparkles,
} from 'lucide-react';
import { useSandboxStore } from '../stores/sandboxStore.js';
import { useLayoutStore } from '../stores/layoutStore.js';
import { extractDeployActions, extractTemplateActions, stripSandboxActionMarkers } from '../lib/sandbox-actions.js';
import { extractFilesFromMarkdown, stripFileBlocksFromMarkdown } from '../lib/file-extractor.js';
import {
  buildGroundedBuildBriefExecutionPrompt,
  getGroundedBuildBriefActionLabel,
} from '../lib/grounded-build-brief-actions.js';
import { extractProjectUpdateArtifact, parseProjectUpdateBody, stripProjectArtifactMarkup } from '../lib/project-artifact.js';
import type { SearchSourceUI, GroundedBuildBriefUI, MessageSender, IDE_AGENT_COLORS as _Colors } from '../stores/chatStore.js';
import type { DeployIntent, RecoveryPattern } from '../lib/intent-detector.js';
import { ProjectArtifactCard } from './ProjectArtifactCard.js';
import { SourceCards } from './SourceCards.js';

interface FileAttachment {
  name: string;
  content: string;
  language: string;
}

interface MessageBubbleProps {
  role: 'user' | 'assistant' | 'system' | 'tool';
  content: string;
  imageId?: string | null;
  imagePreview?: string;
  files?: FileAttachment[];
  fallbackDeploy?: DeployIntent | null;
  recoveryPattern?: RecoveryPattern;
  allIntents?: DeployIntent[];
  onIntentAction?: (accepted: boolean) => void;
  /** Whether this is the newest message in the thread */
  isLatest?: boolean;
  /** Whether this message is currently being streamed */
  isStreaming?: boolean;
  /** Search sources for Perplexity-style citation cards */
  sources?: SearchSourceUI[];
  /** Follow-up questions the user can click */
  followUps?: string[];
  /** Confidence score (0-1) from search pipeline */
  confidence?: number;
  /** Structured research-to-build handoff */
  groundedBuildBrief?: GroundedBuildBriefUI;
  /** Feedback state: true=helpful, false=not helpful, undefined=no feedback */
  feedback?: boolean;
  /** Called when user gives thumbs up/down */
  onFeedback?: (helpful: boolean) => void;
  /** Called when user clicks a follow-up question */
  onFollowUp?: (question: string) => void;
  /** Called when user explicitly turns a grounded brief into an execution turn */
  onGroundedExecute?: (prompt: string) => void;
  /** Group chat sender identity */
  sender?: MessageSender;
  /** Set when message was auto-generated by the repair loop */
  isAutoRepair?: boolean;
  /** Which repair attempt this is (1-based) */
  repairAttempt?: number;
  /** Quieter research layout used in deeper multi-turn threads */
  compactResearchChrome?: boolean;
  /** True when this is the latest source-backed research answer in the thread */
  isLatestResearchMessage?: boolean;
  /** Route source exploration into the right-side research rail instead of inline cards */
  sourceRailHandlesSources?: boolean;
  /** Whether the research rail is currently open for this answer */
  sourceRailOpen?: boolean;
  /** Opens the right-side research rail */
  onOpenSources?: () => void;
  /** Light “studio builder” message chrome (pairs with chat + preview split) */
  studioChrome?: boolean;
}

const INLINE_TOKEN_REGEX = /(\[[^\]]+\]\([^)]+\)|\[\d+\]|`[^`]+`|\*\*[^*]+\*\*|\*[^*]+\*)/g;

function renderInlineWithCitations({
  text,
  sources,
  hoveredCitationKey,
  onHoverCitation,
  keyPrefix,
}: {
  text: string;
  sources?: SearchSourceUI[];
  hoveredCitationKey: string | null;
  onHoverCitation: (key: string | null) => void;
  keyPrefix: string;
}) {
  const nodes: React.ReactNode[] = [];
  let lastIndex = 0;
  let tokenMatch: RegExpExecArray | null;

  INLINE_TOKEN_REGEX.lastIndex = 0;

  while ((tokenMatch = INLINE_TOKEN_REGEX.exec(text)) !== null) {
    if (tokenMatch.index > lastIndex) {
      nodes.push(
        <span key={`${keyPrefix}-text-${lastIndex}`}>
          {text.slice(lastIndex, tokenMatch.index)}
        </span>,
      );
    }

    const token = tokenMatch[0];
    const citationMatch = token.match(/^\[(\d+)\]$/);
    const linkMatch = token.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
    const codeMatch = token.match(/^`([^`]+)`$/);
    const boldMatch = token.match(/^\*\*([^*]+)\*\*$/);
    const italicMatch = token.match(/^\*([^*]+)\*$/);
    const tokenKey = `${keyPrefix}-token-${tokenMatch.index}`;

    if (citationMatch) {
      const sourceIndex = Number.parseInt(citationMatch[1], 10) - 1;
      const source = sources?.[sourceIndex];
      if (source) {
        const instanceKey = `${tokenKey}-cite-${sourceIndex}`;
        nodes.push(
          <CitationBadge
            key={instanceKey}
            index={sourceIndex + 1}
            source={source}
            isHovered={hoveredCitationKey === instanceKey}
            onEnter={() => onHoverCitation(instanceKey)}
            onLeave={() => onHoverCitation(null)}
          />,
        );
      } else {
        nodes.push(<span key={tokenKey}>{token}</span>);
      }
    } else if (linkMatch) {
      nodes.push(
        <a
          key={tokenKey}
          href={linkMatch[2]}
          target="_blank"
          rel="noopener noreferrer"
          className="font-medium text-sky-300 transition-colors hover:text-sky-200 hover:underline"
        >
          {linkMatch[1]}
        </a>,
      );
    } else if (codeMatch) {
      nodes.push(
        <code
          key={tokenKey}
          className="rounded-md border border-white/10 bg-black/20 px-1.5 py-0.5 font-mono text-[0.92em] text-zinc-100"
        >
          {codeMatch[1]}
        </code>,
      );
    } else if (boldMatch) {
      nodes.push(
        <strong key={tokenKey} className="font-semibold text-zinc-50">
          {boldMatch[1]}
        </strong>,
      );
    } else if (italicMatch) {
      nodes.push(
        <em key={tokenKey} className="italic text-zinc-100/90">
          {italicMatch[1]}
        </em>,
      );
    } else {
      nodes.push(<span key={tokenKey}>{token}</span>);
    }

    lastIndex = tokenMatch.index + token.length;
  }

  if (lastIndex < text.length) {
    nodes.push(
      <span key={`${keyPrefix}-tail`}>
        {text.slice(lastIndex)}
      </span>,
    );
  }

  return nodes;
}

// ── Inline Citation Badge ──

function CitationBadge({
  index,
  source,
  isHovered,
  onEnter,
  onLeave,
}: {
  index: number;
  source: SearchSourceUI;
  isHovered: boolean;
  onEnter: () => void;
  onLeave: () => void;
}) {
  return (
    <span className="relative inline-flex align-middle">
      <button
        type="button"
        data-citation-badge={index}
        className="ml-1 inline-flex h-5 min-w-5 cursor-pointer items-center justify-center rounded-full border border-violet-500/30 bg-violet-500/14 px-1.5 text-[10px] font-semibold text-violet-200 shadow-[0_0_0_1px_rgba(124,58,237,0.14)] transition-all hover:-translate-y-px hover:border-violet-400/45 hover:bg-violet-500/22 hover:text-white"
        onMouseEnter={onEnter}
        onMouseLeave={onLeave}
        onFocus={onEnter}
        onBlur={onLeave}
        aria-label={`View source ${index}: ${source.title || source.domain}`}
      >
        {index}
      </button>
      {isHovered && (
        <span className="absolute left-0 top-full z-50 mt-2.5 w-72 animate-in fade-in slide-in-from-top-1 duration-100">
          <span className="block rounded-2xl border border-zinc-700/70 bg-zinc-950/96 p-3 shadow-[0_18px_48px_rgba(0,0,0,0.42)] backdrop-blur-xl">
            <span className="mb-2 flex items-center gap-2">
              {source.favicon && (
                <img src={source.favicon} alt="" className="h-4 w-4 rounded-sm" onError={(e) => { (e.target as HTMLImageElement).style.display = 'none'; }} />
              )}
              <span className="truncate text-[11px] font-semibold text-zinc-100">{source.title || source.domain}</span>
            </span>
            {source.snippet && (
              <span className="block text-[11px] leading-5 text-zinc-400 line-clamp-3">{source.snippet}</span>
            )}
            <span className="mt-2 inline-flex rounded-full border border-white/6 bg-white/4 px-2 py-1 text-[10px] uppercase tracking-[0.18em] text-zinc-500">
              {source.domain}
            </span>
          </span>
        </span>
      )}
    </span>
  );
}

// ── Cited Markdown: renders markdown with inline [N] citation badges ──

function CitedMarkdown({
  content,
  sources,
  hoveredCitationKey,
  onHoverCitation,
}: {
  content: string;
  sources?: SearchSourceUI[];
  hoveredCitationKey: string | null;
  onHoverCitation: (key: string | null) => void;
}) {
  // If no sources or no citation markers, render plain markdown
  if (!sources || sources.length === 0 || !/\[\d+\]/.test(content)) {
    return <MarkdownRenderer content={content} />;
  }

  const blocks = content
    .trim()
    .split(/\n{2,}/)
    .map((block) => block.trim())
    .filter(Boolean);

  return (
    <div className="space-y-3.5">
      {blocks.map((block, blockIndex) => {
        const headingMatch = block.match(/^(#{1,3})\s+(.+)$/);
        if (headingMatch) {
          const headingLevel = headingMatch[1].length;
          const headingClassName = headingLevel === 1
            ? 'text-lg font-semibold text-zinc-50'
            : headingLevel === 2
              ? 'text-base font-semibold text-zinc-100'
              : 'text-sm font-semibold uppercase tracking-[0.14em] text-zinc-400';
          return (
            <div key={`block-${blockIndex}`} className={headingClassName}>
              {renderInlineWithCitations({
                text: headingMatch[2],
                sources,
                hoveredCitationKey,
                onHoverCitation,
                keyPrefix: `heading-${blockIndex}`,
              })}
            </div>
          );
        }

        const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);
        const isBulletList = lines.length > 0 && lines.every((line) => /^[-*]\s+/.test(line));
        const isNumberedList = lines.length > 0 && lines.every((line) => /^\d+\.\s+/.test(line));

        if (isBulletList) {
          return (
            <ul key={`block-${blockIndex}`} className="space-y-2">
              {lines.map((line, lineIndex) => (
                <li key={`bullet-${blockIndex}-${lineIndex}`} className="flex items-start gap-2.5 text-[15px] leading-7 text-zinc-200">
                  <span className="mt-[0.8rem] h-1.5 w-1.5 rounded-full bg-violet-300/85" />
                  <span className="min-w-0 flex-1 text-zinc-300">
                    {renderInlineWithCitations({
                      text: line.replace(/^[-*]\s+/, ''),
                      sources,
                      hoveredCitationKey,
                      onHoverCitation,
                      keyPrefix: `bullet-${blockIndex}-${lineIndex}`,
                    })}
                  </span>
                </li>
              ))}
            </ul>
          );
        }

        if (isNumberedList) {
          return (
            <ol key={`block-${blockIndex}`} className="space-y-2">
              {lines.map((line, lineIndex) => {
                const itemMatch = line.match(/^(\d+)\.\s+(.+)$/);
                if (!itemMatch) return null;
                return (
                  <li key={`ordered-${blockIndex}-${lineIndex}`} className="flex items-start gap-3 text-[15px] leading-7 text-zinc-300">
                    <span className="mt-[0.2rem] inline-flex h-6 min-w-6 items-center justify-center rounded-full border border-white/8 bg-white/4 px-1.5 text-[11px] font-semibold text-zinc-200">
                      {itemMatch[1]}
                    </span>
                    <span className="min-w-0 flex-1">
                      {renderInlineWithCitations({
                        text: itemMatch[2],
                        sources,
                        hoveredCitationKey,
                        onHoverCitation,
                        keyPrefix: `ordered-${blockIndex}-${lineIndex}`,
                      })}
                    </span>
                  </li>
                );
              })}
            </ol>
          );
        }

        const paragraphLines = block.split('\n');
        return (
          <p key={`block-${blockIndex}`} className="text-[15px] leading-7 text-zinc-300">
            {paragraphLines.map((line, lineIndex) => (
              <span key={`paragraph-${blockIndex}-${lineIndex}`}>
                {renderInlineWithCitations({
                  text: line,
                  sources,
                  hoveredCitationKey,
                  onHoverCitation,
                  keyPrefix: `paragraph-${blockIndex}-${lineIndex}`,
                })}
                {lineIndex < paragraphLines.length - 1 && <br />}
              </span>
            ))}
          </p>
        );
      })}
    </div>
  );
}

function stripStructuredSections(
  content: string,
  {
    hasSources,
    hasFollowUps,
  }: {
    hasSources: boolean;
    hasFollowUps: boolean;
  },
): string {
  let next = content.trim();

  if (hasSources) {
    next = next
      .replace(/\n{2,}(?:#{1,6}\s*)?sources:?\s*[\s\S]*$/i, '')
      .replace(/\s*\[sources:[^\]]+\]\s*$/i, '')
      .trim();
  }

  if (hasFollowUps) {
    next = next
      .replace(/\n{2,}(?:#{1,6}\s*)?related:?\s*[\s\S]*$/i, '')
      .trim();
  }

  return next;
}

function isProjectUpdateMessage(content: string): boolean {
  return /^\s*Project update:?/i.test(content);
}

function stripProjectUpdatePrefix(content: string): string {
  return content.replace(/^\s*Project update:?\s*/i, '').trim();
}

function GroundedBuildBriefCard({
  brief,
  onExecute,
}: {
  brief: GroundedBuildBriefUI;
  onExecute?: (prompt: string) => void;
}) {
  const confidenceLabel = `${Math.round(brief.confidence * 100)}% confidence`;
  const actionLabel = getGroundedBuildBriefActionLabel(brief);

  return (
    <div className="mb-4 rounded-[1.35rem] border border-violet-500/18 bg-[linear-gradient(180deg,rgba(76,29,149,0.18),rgba(17,17,22,0.92))] px-4 py-4 shadow-[0_16px_48px_rgba(0,0,0,0.18)]">
      <div className="flex flex-wrap items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-200/80">
        <span className="rounded-full border border-violet-400/20 bg-violet-500/12 px-2 py-1 text-violet-100">
          Grounded build brief
        </span>
        <span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-zinc-300">
          {brief.intent}
        </span>
        <span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-zinc-400">
          {confidenceLabel}
        </span>
      </div>

      <div className="mt-3 flex flex-wrap items-center gap-2">
        <span className="rounded-full border border-zinc-700/70 bg-zinc-900/70 px-2.5 py-1 text-[11px] font-medium text-zinc-200">
          {brief.focusLabel}
        </span>
        {brief.sourceDomains.slice(0, 3).map((domain) => (
          <span
            key={domain}
            className="rounded-full border border-zinc-800/80 bg-zinc-900/40 px-2 py-1 text-[10px] text-zinc-500"
          >
            {domain}
          </span>
        ))}
      </div>

      <p className="mt-3 text-[14px] leading-6 text-zinc-200">{brief.summary}</p>

      <div className="mt-3 rounded-2xl border border-zinc-800/80 bg-zinc-950/55 px-3.5 py-3">
        <div className="text-[10px] font-semibold uppercase tracking-[0.2em] text-zinc-500">Recommendation</div>
        <p className="mt-1.5 text-[13px] leading-6 text-zinc-200">{brief.recommendation}</p>
      </div>

      <div className="mt-3 rounded-2xl border border-zinc-800/80 bg-zinc-950/40 px-3.5 py-3 text-[12px] leading-6 text-zinc-300">
        <span className="font-semibold text-zinc-100">Next step:</span> {brief.nextStep}
      </div>

      {onExecute && (
        <div className="mt-3 flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => onExecute(buildGroundedBuildBriefExecutionPrompt(brief))}
            data-grounded-build-action="button"
            data-grounded-build-intent={brief.intent}
            className="inline-flex items-center gap-2 rounded-xl border border-violet-400/20 bg-violet-500/14 px-3.5 py-2 text-[12px] font-medium text-violet-100 transition-colors hover:border-violet-300/30 hover:bg-violet-500/20 hover:text-white"
          >
            <Rocket className="h-3.5 w-3.5" />
            {actionLabel}
          </button>
        </div>
      )}

      {brief.reasons.length > 0 && (
        <div className="mt-3 space-y-2">
          {brief.reasons.map((reason, index) => (
            <div key={`${brief.focusLabel}-${index}`} className="flex items-start gap-2 text-[12px] leading-6 text-zinc-400">
              <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-violet-300/80" />
              <span>{reason}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export function MessageBubble({
  role, content, imageId, imagePreview, files,
  fallbackDeploy, recoveryPattern = 'silent', allIntents, onIntentAction,
  isLatest = false, isStreaming = false,
  sources, followUps, confidence, groundedBuildBrief, feedback, onFeedback, onFollowUp, onGroundedExecute, sender,
  isAutoRepair = false, repairAttempt,
  compactResearchChrome = false,
  isLatestResearchMessage = false,
  sourceRailHandlesSources = false,
  sourceRailOpen = false,
  onOpenSources,
  studioChrome = false,
}: MessageBubbleProps) {
  const isUser = role === 'user';
  const isProjectUpdate = !isUser && isProjectUpdateMessage(content);
  const [copied, setCopied] = useState(false);
  const [nudgeDismissed, setNudgeDismissed] = useState(false);
  const [clarifyDismissed, setClarifyDismissed] = useState(false);
  const [hoveredCitationKey, setHoveredCitationKey] = useState<string | null>(null);
  const deployStack = useSandboxStore((s) => s.deployStack);
  const deployPhase = useSandboxStore((s) => s.deployPhase);
  const deployStackName = useSandboxStore((s) => s.deployStackName);
  const projectName = useSandboxStore((s) => s.projectName);
  const devPort = useSandboxStore((s) => s.devPort);
  const toggleBuilderPanel = useLayoutStore((s) => s.toggleBuilderPanel);
  const showBuilderPanel = useLayoutStore((s) => s.showBuilderPanel);

  const artifactFreeContent = stripProjectArtifactMarkup(content);
  const projectUpdateArtifact = !isUser && isProjectUpdate ? extractProjectUpdateArtifact(content) : null;
  const handleCopyAll = useCallback(() => {
    const copyText = isProjectUpdate ? stripProjectUpdatePrefix(artifactFreeContent) : artifactFreeContent;
    navigator.clipboard.writeText(copyText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [artifactFreeContent, isProjectUpdate]);

  const deployActions = extractDeployActions(content);
  const templateActions = extractTemplateActions(content);
  const hasSandboxAction = deployActions.length > 0 || templateActions.length > 0;
  const normalizedContent = isProjectUpdate ? stripProjectUpdatePrefix(artifactFreeContent) : artifactFreeContent;
  const extractedFiles = isUser ? [] : extractFilesFromMarkdown(normalizedContent);
  const hasAppliedFileBlocks = extractedFiles.length > 0;
  const projectUpdateBody = isProjectUpdate ? parseProjectUpdateBody(normalizedContent) : null;

  const useSilentFallback = !hasSandboxAction
    && fallbackDeploy
    && recoveryPattern === 'silent'
    && !isUser;

  if (useSilentFallback && fallbackDeploy) {
    deployActions.push({
      stackId: fallbackDeploy.stackId,
      tier: fallbackDeploy.tier,
      name: fallbackDeploy.displayName,
    });
  }

  const displayContent = stripSandboxActionMarkers(normalizedContent);
  const summarizedContent = hasAppliedFileBlocks
    ? stripFileBlocksFromMarkdown(displayContent)
    : displayContent;
  const hasStructuredSources = !isUser && Boolean(sources?.length);
  const hasStructuredFollowUps = !isUser && Boolean(followUps?.length);
  const visibleFollowUps = hasStructuredFollowUps ? (followUps ?? []).slice(0, 2) : [];
  const isResearchMessage = !isUser && (hasStructuredSources || Boolean(groundedBuildBrief));
  const compactResearchMode = compactResearchChrome && isResearchMessage;
  const cleanedContent = isUser
    ? summarizedContent
    : stripStructuredSections(summarizedContent, {
        hasSources: hasStructuredSources,
        hasFollowUps: hasStructuredFollowUps,
      });

  // Inject inline source citations: append [N] markers at paragraph boundaries
  // when sources exist. Each citation links to a source by index.
  const citedContent = (() => {
    if (isUser || !sources || sources.length === 0) return cleanedContent;
    // If content already has citation markers [1], [2], use as-is
    if (/\[\d+\]/.test(cleanedContent)) return cleanedContent;
    // Inject citations at the end of the first N paragraphs matching source keywords
    const paragraphs = cleanedContent.split('\n\n');
    const used = new Set<number>();
    for (let pi = 0; pi < paragraphs.length && used.size < sources.length; pi++) {
      const pLower = paragraphs[pi].toLowerCase();
      for (let si = 0; si < sources.length; si++) {
        if (used.has(si)) continue;
        const src = sources[si];
        // Check if paragraph contains keywords from source title or domain
        const keywords = (src.title + ' ' + src.domain).toLowerCase().split(/\s+/).filter(w => w.length > 3);
        const hasOverlap = keywords.some(kw => pLower.includes(kw));
        if (hasOverlap || (pi === 0 && used.size === 0)) {
          paragraphs[pi] = paragraphs[pi].replace(/(\S)(\s*)$/, `$1 [${si + 1}]$2`);
          used.add(si);
          break;
        }
      }
    }
    // Append any remaining source citations to the last paragraph
    for (let si = 0; si < sources.length; si++) {
      if (!used.has(si)) {
        const lastIdx = paragraphs.length - 1;
        paragraphs[lastIdx] += ` [${si + 1}]`;
        used.add(si);
      }
    }
    return paragraphs.join('\n\n');
  })();
  const compactSummary = cleanedContent.trim();
  const visibleFiles = extractedFiles.slice(0, 6);
  const remainingFileCount = Math.max(0, extractedFiles.length - visibleFiles.length);
  const isActionLive = useCallback((action: { name: string }) => (
    action.name === deployStackName
    && (deployPhase === 'deploying' || deployPhase === 'ready' || (projectName === action.name && devPort !== null))
  ), [deployPhase, deployStackName, devPort, projectName]);

  const handleDeploy = (action: { stackId: string; tier: string; name: string }) => {
    if (!showBuilderPanel) toggleBuilderPanel();
    if (isActionLive(action)) {
      onIntentAction?.(true);
      return;
    }
    deployStack(action.stackId, action.tier, action.name, action.tier);
    onIntentAction?.(true);
  };

  const handleNudgeDismiss = () => { setNudgeDismissed(true); onIntentAction?.(false); };
  const handleClarifyDismiss = () => { setClarifyDismissed(true); onIntentAction?.(false); };

  const showNudge = !isUser && !hasSandboxAction && fallbackDeploy && recoveryPattern === 'nudge' && !nudgeDismissed;
  const showClarify = !isUser && !hasSandboxAction && !fallbackDeploy && allIntents && allIntents.length > 0 && recoveryPattern === 'clarify' && !clarifyDismissed;

  const imageSrc = imagePreview || (imageId ? `${API_BASE}/api/images/${imageId}/raw` : null);

  /* ── Action buttons visibility: always on latest, hover on older ── */
  const actionVisibility = isLatest && !isStreaming
    ? 'opacity-100'
    : 'opacity-0 group-hover/msg:opacity-100';
  const showHeaderConfidence = !isUser && !isProjectUpdate && confidence !== undefined && hasStructuredSources && !compactResearchMode && confidence < 1;
  const sourceRailDomains = sources
    ? Array.from(new Set(sources.map((source) => source.domain.replace(/^www\./, '')))).slice(0, 2)
    : [];
  const sourceRailConfidenceLabel = confidence !== undefined ? `${Math.round(confidence * 100)}% confidence` : null;
  const showCompactResearchMeta = (compactResearchMode || sourceRailHandlesSources) && hasStructuredSources && Boolean(sources?.length);
  const showExpandedSources = hasStructuredSources && sources && !compactResearchMode && !sourceRailHandlesSources;
  const showResearchFollowUps = visibleFollowUps.length > 0
    && !isStreaming
    && (!compactResearchMode || isLatestResearchMessage || !hasStructuredSources);
  const showPlainFollowUps = visibleFollowUps.length > 0 && !isStreaming && (hasAppliedFileBlocks || !isResearchMessage);
  const plainFollowUpsSection = showPlainFollowUps ? (
    <div className={`border-t pt-3 ${studioChrome ? 'border-zinc-200' : 'border-zinc-800/60'}`}>
      <div className={`mb-2 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.22em] ${studioChrome ? 'text-zinc-500' : 'text-zinc-600'}`}>
        <Sparkles className="h-3 w-3" />
        Related
      </div>
      <div className="flex flex-wrap gap-1.5">
        {visibleFollowUps.map((q, i) => (
          <button
            key={i}
            onClick={() => onFollowUp?.(q)}
            data-follow-up-button="button"
            className={`group/chip flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[12px] transition-all ${
              studioChrome
                ? 'border-zinc-200 bg-zinc-50 text-zinc-700 hover:border-orange-200 hover:bg-orange-50/80 hover:text-zinc-900'
                : 'border-zinc-700/60 bg-zinc-900/50 text-zinc-300 hover:border-violet-500/30 hover:bg-zinc-800/70 hover:text-zinc-100'
            }`}
          >
            {q}
            <CornerDownRight className={`h-3 w-3 flex-shrink-0 transition-colors group-hover/chip:text-violet-400 ${studioChrome ? 'text-zinc-400' : 'text-zinc-700'}`} />
          </button>
        ))}
      </div>
    </div>
  ) : null;

  return (
    <div
      className={`group/msg mb-6 flex w-full ${isUser ? 'justify-end' : 'justify-start'}`}
      data-chat-message-role={role}
      data-message-latest={isLatest ? 'true' : 'false'}
      data-research-message={isResearchMessage ? 'true' : 'false'}
      data-streaming={isStreaming ? 'true' : 'false'}
    >
      <div className={`flex w-full gap-3 ${isUser ? 'max-w-[72%] flex-row-reverse 2xl:max-w-[48rem]' : isResearchMessage ? (compactResearchMode ? 'max-w-[50rem] flex-row items-start' : 'max-w-[56rem] flex-row items-start xl:max-w-[58rem]') : 'max-w-[64rem] flex-row items-start'}`}>
        {/* ── Avatar ── */}
        <div
          className={`flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full mt-0.5 ${
            isUser
              ? studioChrome ? 'bg-sky-100' : 'bg-violet-500/12'
              : isProjectUpdate
                ? 'bg-emerald-500/10'
              : sender?.type === 'ide-agent'
                ? studioChrome ? 'ring-1 ring-zinc-200' : 'ring-1 ring-white/8'
                : studioChrome ? 'bg-zinc-200/80' : 'bg-zinc-800/60'
          }`}
          style={sender?.type === 'ide-agent' && sender.color ? { backgroundColor: `${sender.color}20` } : undefined}
        >
          {isUser
            ? <User className={`h-3.5 w-3.5 ${studioChrome ? 'text-sky-700' : 'text-violet-400'}`} />
            : isProjectUpdate
              ? <Wrench className="h-3.5 w-3.5 text-emerald-300" />
            : sender?.type === 'ide-agent'
              ? <span className="text-[10px] font-bold" style={{ color: sender.color || '#a1a1aa' }}>{sender.name.charAt(0).toUpperCase()}</span>
              : <Bot className={`h-3.5 w-3.5 ${studioChrome ? 'text-zinc-600' : 'text-zinc-500'}`} />
          }
        </div>

        {/* ── Content column ── */}
        <div className={`min-w-0 ${isUser ? 'flex-1' : 'w-full flex-1'}`}>
          {/* Auto-repair badge — shown above user messages that were injected by the repair loop */}
          {isUser && isAutoRepair && (
            <div className="mb-1 flex justify-end">
              <span className="inline-flex items-center gap-1 rounded-full bg-amber-500/10 px-2 py-0.5 text-[9px] font-semibold text-amber-400/80 ring-1 ring-amber-500/20">
                <Wrench className="h-2.5 w-2.5" />
                Auto-repair{repairAttempt !== undefined ? ` · attempt ${repairAttempt}` : ''}
              </span>
            </div>
          )}

          {/* Role label + confidence indicator */}
          <div className={`mb-1.5 flex items-center gap-1.5 text-[11px] font-medium ${
            isUser
              ? `justify-end ${studioChrome ? 'text-zinc-500' : 'text-zinc-500'}`
              : isProjectUpdate
                ? 'text-emerald-400/70'
                : studioChrome
                  ? 'text-zinc-500'
                  : 'text-zinc-500'
          }`}>
            <span>{isUser ? 'You' : isProjectUpdate ? 'Project update' : sender?.name || 'Vai'}</span>
            {sender?.model && !isUser && (
              <span className={`text-[10px] font-normal ${studioChrome ? 'text-zinc-400' : 'text-zinc-700'}`}>· {sender.model}</span>
            )}
            {showHeaderConfidence && (
              <span
                className={`inline-flex items-center gap-0.5 rounded-full px-1.5 py-px text-[9px] font-semibold tabular-nums ${
                  confidence >= 0.7
                    ? 'bg-emerald-500/10 text-emerald-500/70'
                    : confidence >= 0.4
                      ? 'bg-amber-500/10 text-amber-500/70'
                      : 'bg-red-500/10 text-red-500/60'
                }`}
                title={`Search confidence: ${Math.round(confidence * 100)}%`}
              >
                <span className={`inline-block h-1 w-1 rounded-full ${
                  confidence >= 0.7 ? 'bg-emerald-400' : confidence >= 0.4 ? 'bg-amber-400' : 'bg-red-400'
                }`} />
                {Math.round(confidence * 100)}%
              </span>
            )}
          </div>

          {/* Message body */}
          <div
            className={`relative transition-all duration-200 ${
              isUser
                ? studioChrome
                  ? 'rounded-2xl rounded-br-md border border-sky-200/80 bg-sky-50 px-4 py-3 text-zinc-900 shadow-sm'
                  : 'rounded-2xl rounded-br-md bg-zinc-800/50 px-4 py-3 text-zinc-100'
                : isProjectUpdate
                  ? 'w-full overflow-visible rounded-2xl border border-emerald-500/12 bg-emerald-500/[0.04] px-5 py-4 text-zinc-100'
                : compactResearchMode
                  ? `w-full overflow-visible px-0 py-0 ${studioChrome ? 'text-zinc-800' : 'text-zinc-200'}`
                : isResearchMessage
                  ? studioChrome
                    ? 'w-full overflow-visible rounded-2xl border border-zinc-200 bg-white px-5 py-4 text-zinc-800 shadow-sm'
                    : 'w-full overflow-visible rounded-2xl border border-white/[0.05] bg-white/[0.02] px-5 py-4 text-zinc-200'
                  : `w-full overflow-visible px-1 py-0.5 ${studioChrome ? 'text-zinc-800' : 'text-zinc-200'}`
            }`}
          >
            {/* Image */}
            {imageSrc && (
              <div className={`mb-2 ${isUser ? '' : 'pl-0'}`}>
                <img
                  src={imageSrc}
                  alt="Attached screenshot"
                  className="max-h-56 w-auto rounded-lg border border-white/10"
                  loading="lazy"
                />
              </div>
            )}

            {/* File attachments */}
            {files && files.length > 0 && (
              <div className="mb-2 space-y-1">
                {files.map((f, i) => (
                  <div key={i} className="flex items-center gap-2 rounded-lg border border-zinc-700/30 bg-zinc-800/40 px-3 py-1.5 transition-colors hover:border-zinc-600/40">
                    <FileText className="h-3.5 w-3.5 shrink-0 text-zinc-400" />
                    <span className="truncate text-xs font-medium text-zinc-300">{f.name}</span>
                    <span className="text-[10px] text-zinc-600">{f.language}</span>
                  </div>
                ))}
              </div>
            )}

            {/* Source chip row — Perplexity-style, rendered ABOVE the answer for research messages */}
            {!isUser && isResearchMessage && hasStructuredSources && sources && sources.length > 0 && (
              <SourceCards variant="chips" sources={sources} confidence={confidence} />
            )}

            {!isUser && groundedBuildBrief && (
              <GroundedBuildBriefCard brief={groundedBuildBrief} onExecute={onGroundedExecute} />
            )}

            {/* Text — low confidence responses get subtle visual decay */}
            {isProjectUpdate && projectUpdateArtifact ? (
              <ProjectArtifactCard
                artifact={projectUpdateArtifact}
                summary={projectUpdateBody?.summary || compactSummary}
                details={projectUpdateBody?.details ?? []}
                onPrompt={onFollowUp}
              />
            ) : isUser ? (
              <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{content}</p>
            ) : hasAppliedFileBlocks ? (
              <div className="space-y-2">
                {compactSummary ? (
                  <div className="text-sm leading-relaxed transition-opacity duration-300">
                    <CitedMarkdown
                      content={citedContent}
                      sources={sources}
                      hoveredCitationKey={hoveredCitationKey}
                      onHoverCitation={setHoveredCitationKey}
                    />
                  </div>
                ) : (
                  <p className="text-sm leading-relaxed text-zinc-300">
                    Updated the current project in sandbox. Open Preview or Code to inspect the result directly.
                  </p>
                )}

                <div className="space-y-1 text-xs text-zinc-500">
                  <div>
                    Updated {extractedFiles.length} file{extractedFiles.length === 1 ? '' : 's'} in the current project.
                  </div>
                  <div className="space-y-0.5">
                    {visibleFiles.map((file) => (
                      <div key={file.path} className="truncate">
                        {file.path}
                      </div>
                    ))}
                    {remainingFileCount > 0 && (
                      <div>
                        +{remainingFileCount} more file{remainingFileCount === 1 ? '' : 's'}
                      </div>
                    )}
                  </div>
                </div>

                {plainFollowUpsSection}
              </div>
            ) : (
              <div className="space-y-3">
                <div className={isResearchMessage ? 'space-y-3' : ''}>
                  <div>
                    <div
                      className={`transition-opacity duration-300 ${
                        confidence !== undefined && confidence < 0.3 ? 'opacity-75' : ''
                      }`}
                    >
                      <CitedMarkdown
                        content={citedContent}
                        sources={sources}
                        hoveredCitationKey={hoveredCitationKey}
                        onHoverCitation={setHoveredCitationKey}
                      />
                      {/* Streaming cursor */}
                      {isStreaming && content.length > 0 && (
                        <span className="streaming-cursor" />
                      )}
                    </div>
                  </div>

                  {showExpandedSources && (
                    <div className="border-t border-zinc-800/70 pt-3">
                      <SourceCards sources={sources} confidence={confidence} />
                    </div>
                  )}

                  {showCompactResearchMeta && sources && (
                    sourceRailHandlesSources ? (
                      <div className="border-t border-zinc-900/80 pt-3">
                        <button
                          type="button"
                          onClick={() => onOpenSources?.()}
                          data-research-source-summary="button"
                          data-state={sourceRailOpen ? 'open' : 'closed'}
                          className="group/source-summary flex w-full items-center justify-between rounded-2xl border border-zinc-800/80 bg-zinc-950/55 px-3.5 py-3 text-left transition-colors hover:border-zinc-700 hover:bg-zinc-900/70"
                        >
                          <div className="min-w-0">
                            <div className="flex flex-wrap items-center gap-1.5">
                              <span className="rounded-full border border-zinc-800/80 bg-zinc-900/60 px-2 py-0.5 text-[10px] font-medium text-zinc-200">
                                {sources.length} source{sources.length === 1 ? '' : 's'}
                              </span>
                              {sourceRailDomains.map((domain) => (
                                <span
                                  key={domain}
                                  className="rounded-full border border-zinc-800/80 bg-zinc-900/40 px-2 py-0.5 text-[10px] text-zinc-500"
                                >
                                  {domain}
                                </span>
                              ))}
                            </div>
                            <div className="mt-2 text-[11px] leading-5 text-zinc-500">
                              {sourceRailOpen
                                ? 'Sources are open in the sidebar for this answer.'
                                : 'Open the right-side source rail for the cleaner evidence view.'}
                            </div>
                          </div>

                          <span className="ml-4 inline-flex items-center gap-1 text-[11px] font-medium text-zinc-300 transition-colors group-hover/source-summary:text-white">
                            {sourceRailConfidenceLabel ?? 'Open sources'}
                            <ChevronRight className="h-3.5 w-3.5" />
                          </span>
                        </button>
                      </div>
                    ) : (
                      <div className="flex items-center gap-2 border-t border-zinc-900/80 pt-3 text-[11px] text-zinc-500">
                        <span className="rounded-full border border-zinc-800/80 bg-zinc-900/50 px-2 py-0.5 text-[10px] text-zinc-300">
                          {sources.length} source{sources.length === 1 ? '' : 's'}
                        </span>
                        {confidence !== undefined && (
                          <span>{Math.round(confidence * 100)}% confidence</span>
                        )}
                      </div>
                    )
                  )}

                  {showResearchFollowUps && (
                    <div className="border-t border-zinc-800/60 pt-3">
                      <div className="mb-2 flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.22em] text-zinc-600">
                        <Sparkles className="h-3 w-3" />
                        Related
                      </div>
                      <div className="space-y-1">
                        {visibleFollowUps.map((q, i) => (
                          <button
                            key={i}
                            onClick={() => onFollowUp?.(q)}
                            data-follow-up-button="button"
                            className="group/follow flex w-full items-center justify-between rounded-xl border border-zinc-800/50 bg-zinc-900/30 px-3 py-2.5 text-left text-[13px] text-zinc-300 transition-all hover:border-zinc-700/60 hover:bg-zinc-900/60 hover:text-zinc-100"
                          >
                            <span className="pr-3 leading-5">{q}</span>
                            <CornerDownRight className="h-3.5 w-3.5 flex-shrink-0 text-zinc-700 transition-colors group-hover/follow:text-violet-400" />
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>

                {hasStructuredSources && sources && !isResearchMessage && (
                  <div className="border-t border-zinc-800/70 pt-3">
                    <SourceCards sources={sources} confidence={confidence} />
                  </div>
                )}

                {plainFollowUpsSection}
              </div>
            )}

            {/* Deploy actions */}
            {deployActions.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-2 border-t border-zinc-700/20 pt-3">
                {deployActions.map((action, i) => {
                  const actionLive = isActionLive(action);
                  const actionLabel = actionLive
                    ? (devPort ? 'Preview live' : 'Opening preview')
                    : 'Open preview';
                  return (
                  <button
                    key={i}
                    onClick={() => handleDeploy(action)}
                    className="group/deploy flex items-center gap-1.5 rounded-lg bg-violet-600/80 px-3 py-1.5 text-xs font-medium text-white transition-all hover:bg-violet-500 hover:shadow-md hover:shadow-violet-500/20"
                  >
                    <Rocket className="h-3.5 w-3.5 transition-transform group-hover/deploy:translate-x-0.5" />
                    {actionLabel}
                  </button>
                  );
                })}
              </div>
            )}

            {/* Nudge */}
            {showNudge && fallbackDeploy && (
              <div className="mt-3 border-t border-zinc-700/20 pt-3">
                <div className="flex items-start gap-2">
                  <CornerDownRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-amber-400/70" />
                  <div className="flex-1">
                    <p className="text-xs text-zinc-400">
                      Create a runnable <span className="font-semibold text-zinc-200">{fallbackDeploy.displayName}</span> baseline now?
                    </p>
                    <div className="mt-2 flex gap-2">
                      <button
                        onClick={() => handleDeploy({ stackId: fallbackDeploy.stackId, tier: fallbackDeploy.tier, name: fallbackDeploy.displayName })}
                        className="flex items-center gap-1.5 rounded-lg bg-violet-600/80 px-3 py-1.5 text-xs font-medium text-white transition-all hover:bg-violet-500"
                      >
                        <Rocket className="h-3 w-3" />
                        Create baseline
                      </button>
                      <button onClick={handleNudgeDismiss} className="rounded-lg border border-zinc-700/50 px-3 py-1.5 text-xs text-zinc-500 transition-colors hover:border-zinc-600 hover:text-zinc-300">
                        Skip
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Clarify Picker */}
            {showClarify && allIntents && (
              <div className="mt-3 border-t border-zinc-700/20 pt-3">
                <div className="flex items-start gap-2">
                  <HelpCircle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-zinc-500" />
                  <div className="flex-1">
                    <p className="mb-2 text-xs text-zinc-500">Which stack would you like?</p>
                    <div className="grid grid-cols-2 gap-1.5">
                      {allIntents.slice(0, 4).map((intent, i) => (
                        <button
                          key={i}
                          onClick={() => handleDeploy({ stackId: intent.stackId, tier: intent.tier, name: intent.displayName })}
                          className="flex items-center gap-1.5 rounded-lg border border-zinc-700/40 bg-zinc-800/40 px-2.5 py-2 text-left text-xs text-zinc-300 transition-all hover:border-zinc-500/50 hover:bg-zinc-800/80"
                        >
                          <Rocket className="h-3 w-3 shrink-0 text-zinc-600" />
                          <span className="font-medium">{intent.displayName}</span>
                        </button>
                      ))}
                    </div>
                    <button onClick={handleClarifyDismiss} className="mt-2 flex items-center gap-1 text-[10px] text-zinc-700 transition-colors hover:text-zinc-400">
                      <XIcon className="h-2.5 w-2.5" />
                      Dismiss
                    </button>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* ── Action buttons row (below the message) ── */}
          {!isUser && content.length > 0 && !isStreaming && (
            <div className={`mt-3 flex items-center gap-0.5 pt-1 transition-opacity duration-200 ${actionVisibility}`}>
              <button
                onClick={handleCopyAll}
                className="flex items-center gap-1 rounded-lg px-2 py-1.5 text-[11px] text-zinc-600 transition-colors hover:bg-white/[0.04] hover:text-zinc-400"
                title="Copy response"
              >
                {copied
                  ? <><Check className="h-3 w-3 text-emerald-400" /> Copied</>
                  : <><Copy className="h-3 w-3" /> Copy</>
                }
              </button>
              <button
                onClick={() => onFeedback?.(true)}
                className={`flex items-center gap-1 rounded-lg px-2 py-1.5 text-[11px] transition-colors ${
                  feedback === true
                    ? 'bg-emerald-500/10 text-emerald-400'
                    : 'text-zinc-600 hover:bg-white/[0.04] hover:text-zinc-400'
                }`}
                title="Helpful"
              >
                <ThumbsUp className="h-3 w-3" />
              </button>
              <button
                onClick={() => onFeedback?.(false)}
                className={`flex items-center gap-1 rounded-lg px-2 py-1.5 text-[11px] transition-colors ${
                  feedback === false
                    ? 'bg-red-500/10 text-red-400'
                    : 'text-zinc-600 hover:bg-white/[0.04] hover:text-zinc-400'
                }`}
                title="Not helpful"
              >
                <ThumbsDown className="h-3 w-3" />
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
