import { isProductEngineeringPlanningPrompt } from './product-engineering-intent.js';

export function tryEmitProductEngineeringMemo(input: { content: string }): string | null {
  const content = input.content.trim();
  if (!isProductEngineeringPlanningPrompt(content)) return null;

  const sensorLike = /\b(?:temperature|humidity|sensor|esp32|wall|enclosure|casing)\b/i.test(content);
  if (!sensorLike) {
    return [
      'This is a product-engineering planning question, not a codegen request. Start by separating the physical product, firmware, cloud platform, and business validation before building any UI.',
      '',
      '## Executive Takeaway',
      'Build a small proof-of-concept first: one working device, one reliable data path, one dashboard view, and one clear user problem. Do not start with a full SaaS or custom manufacturing run.',
      '',
      '## What To Plan First',
      '- Hardware/BOM: identify the core sensor, controller, power path, enclosure, and connectivity.',
      '- Firmware: define sampling interval, calibration, offline storage, OTA/update path, and failure behavior.',
      '- Cloud/SaaS: define ingestion, storage, alert rules, user/project ownership, and dashboards.',
      '- Business: validate who pays, why they need it, and what failure would make them stop trusting it.',
      '',
      '## Verify Next',
      '- Build or buy one prototype and prove the measurement is stable for 7 days.',
      '- Get two supplier quotes before treating any cost estimate as real.',
      '- Test whether users care more about alerts, graphs, or historical comparisons.',
    ].join('\n');
  }

  return [
    'Yes — this is buildable, but treat it as a hardware + firmware + SaaS product, not just a web dashboard. The fastest path is one reliable wall unit first, then the cloud/admin layer once the readings are trustworthy.',
    '',
    '## Executive Takeaway',
    'Start with an ESP32-S3 touchscreen module plus a good Sensirion humidity sensor, then validate accuracy, enclosure airflow, and installation safety before you think about selling it. The biggest assumption is that homeowners or building owners will pay for alerts and history, not just current temperature.',
    '',
    '## Product Shape',
    '- Per-home wall unit: local screen, temperature, humidity, trends, alerts, Wi-Fi setup, offline logging.',
    '- Admin/SaaS layer: owner accounts, buildings/homes, device health, historical graphs, leak/anomaly alerts, exports.',
    '- Service model: hardware sale plus monthly monitoring, or installation/service subscription.',
    '',
    '## Hardware/BOM Sketch',
    '- Main module: ESP32-S3 3.5 inch capacitive touchscreen module, ideally 320x480 or 480x480 with PSRAM. Likely good for LVGL UI and graphs.',
    '- Sensor: SHT40/SHT45 I2C breakout. Prefer this over DHT22/AHT20 for a product because stability and accuracy matter.',
    '- Storage: microSD if included on the module, or flash ring-buffer if you only need recent history.',
    '- Power: 5V USB-C for prototype; 12-24V to 5V buck converter only if you know the wall wiring and safety constraints.',
    '- Extras: JST connectors, mounting screws, optional buzzer, reset/setup button, status LED.',
    '',
    '## Enclosure And Mechanical Constraints',
    '- Put sensor airflow vents away from the ESP32 heat source and display backlight; otherwise the readings will drift warm.',
    '- Prototype with PETG/ASA 3D print. Avoid PLA if mounted near heat or sunlight.',
    '- Plan for wall screw holes, cable relief, service access, and a clean screen bezel.',
    '- If you want this to look commercial, design around one exact display module and do not switch modules casually.',
    '',
    '## Firmware And Device UI',
    '- Firmware stack: ESP32-S3, LVGL for screen UI, SHT sensor over I2C, Wi-Fi provisioning, MQTT or HTTPS telemetry.',
    '- Local screens: current temp/RH, 24h graph, 7-day graph, date comparison, alert log, Wi-Fi/settings, calibration offset.',
    '- Reliability: offline queue, watchdog, time sync, sensor error state, and a clear “cloud disconnected but local readings still work” state.',
    '',
    '## SaaS/Admin Architecture',
    '- Device sends JSON telemetry every 1-5 minutes.',
    '- Backend stores time-series readings; InfluxDB/TimescaleDB is a better fit than plain rows if history becomes large.',
    '- Admin dashboard needs homes/devices, current status, historical charts, anomaly/leak rules, notification settings, and owner contact flow.',
    '- Alerts should start simple: humidity spike, humidity above threshold for N minutes, device offline, abnormal temperature drop/rise.',
    '',
    '## Risks And Unknowns',
    '- Needs current sourcing quote: exact module price, availability, display variant, and enclosure cost.',
    '- Unknown: certification path if sold commercially. Wi-Fi modules can reduce risk, but CE/FCC and electrical safety still matter.',
    '- Risk: enclosure heat/airflow can ruin sensor accuracy.',
    '- Risk: wall wiring is not universal; prototype with safe low-voltage/USB power first.',
    '- Risk: users may not pay monthly unless leak/anomaly alerts are clearly valuable.',
    '',
    '## Roadmap',
    '1. Prototype: order 2-3 ESP32-S3 touch modules, 3-5 SHT40/SHT45 breakouts, microSD cards, wiring, and a basic enclosure prototype.',
    '2. Bench test: run readings beside a trusted reference sensor for 7 days; log drift, Wi-Fi reliability, and heat offset.',
    '3. Field pilot: install 2-3 units in real homes; test alert thresholds and whether people understand the screen.',
    '4. SaaS MVP: one admin dashboard with device list, graphs, alert log, and notification rules.',
    '5. Production path: custom PCB/enclosure, assembly process, calibration jig, certification review, support/update process.',
    '',
    '## Next Deeper Options',
    '- Ask for a prototype shopping list with exact search terms.',
    '- Ask for ESP32 + SHT45 firmware architecture.',
    '- Ask for LVGL screen layout for the wall unit.',
    '- Ask for SaaS/backend architecture for telemetry and alerts.',
    '- Ask for enclosure dimensions and airflow rules.',
  ].join('\n');
}
